# Generated by Django 5.2.6 on 2026-04-02 00:00

import apps.contabilidad.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AsientoContable",
            fields=[
                (
                    "id_asiento",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID Asiento"
                    ),
                ),
                (
                    "numero_asiento",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Número de Asiento",
                    ),
                ),
                (
                    "fecha_contable",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Fecha Contable"
                    ),
                ),
                (
                    "descripcion_general",
                    models.CharField(
                        max_length=255, verbose_name="Descripción General"
                    ),
                ),
                (
                    "tipo_asiento",
                    models.CharField(
                        choices=[
                            ("DIA", "Diario"),
                            ("COM", "Compras"),
                            ("VEN", "Ventas"),
                            ("NOM", "Nómina"),
                            ("APE", "Apertura"),
                            ("CIE", "Cierre"),
                            ("AJU", "Ajuste"),
                        ],
                        default="DIA",
                        max_length=3,
                        verbose_name="Tipo de Asiento",
                    ),
                ),
                (
                    "referencia_documento",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Factura #, Reserva #",
                        max_length=100,
                        null=True,
                        verbose_name="Referencia Documento",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BOR", "Borrador"),
                            ("CON", "Contabilizado"),
                            ("ANU", "Anulado"),
                        ],
                        default="BOR",
                        max_length=3,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "tasa_cambio_aplicada",
                    models.DecimalField(
                        decimal_places=8,
                        default=1.0,
                        help_text="Respecto a la moneda local, si aplica.",
                        max_digits=18,
                        verbose_name="Tasa de Cambio Aplicada",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "total_debe",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=15,
                        verbose_name="Total Debe",
                    ),
                ),
                (
                    "total_haber",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=15,
                        verbose_name="Total Haber",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asiento Contable",
                "verbose_name_plural": "Asientos Contables",
                "ordering": ["-fecha_contable", "-numero_asiento"],
            },
        ),
        migrations.CreateModel(
            name="DetalleAsiento",
            fields=[
                (
                    "id_detalle_asiento",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Detalle Asiento",
                    ),
                ),
                (
                    "linea",
                    models.PositiveSmallIntegerField(
                        help_text="Número de línea dentro del asiento.",
                        verbose_name="Línea",
                    ),
                ),
                (
                    "debe",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Debe USD",
                    ),
                ),
                (
                    "haber",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Haber USD",
                    ),
                ),
                (
                    "debe_bsd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Monto en bolívares para presentación legal",
                        max_digits=18,
                        verbose_name="Debe BSD",
                    ),
                ),
                (
                    "haber_bsd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Monto en bolívares para presentación legal",
                        max_digits=18,
                        verbose_name="Haber BSD",
                    ),
                ),
                (
                    "descripcion_linea",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Descripción de la Línea",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Asiento",
                "verbose_name_plural": "Detalles de Asientos",
                "ordering": ["asiento", "linea"],
            },
        ),
        migrations.CreateModel(
            name="PlanContable",
            fields=[
                (
                    "id_cuenta",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID Cuenta"
                    ),
                ),
                (
                    "codigo_cuenta",
                    models.CharField(
                        max_length=30,
                        unique=True,
                        validators=[apps.contabilidad.models.validar_no_vacio_o_espacios],
                        verbose_name="Código de Cuenta",
                    ),
                ),
                (
                    "nombre_cuenta",
                    models.CharField(
                        max_length=100,
                        validators=[apps.contabilidad.models.validar_no_vacio_o_espacios],
                        verbose_name="Nombre de la Cuenta",
                    ),
                ),
                (
                    "tipo_cuenta",
                    models.CharField(
                        choices=[
                            ("AC", "Activo"),
                            ("PA", "Pasivo"),
                            ("PT", "Patrimonio"),
                            ("IN", "Ingreso"),
                            ("GA", "Gasto/Costo"),
                            ("CO", "Cuenta de Orden"),
                        ],
                        max_length=2,
                        verbose_name="Tipo de Cuenta",
                    ),
                ),
                (
                    "nivel",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Nivel Jerárquico"
                    ),
                ),
                (
                    "permite_movimientos",
                    models.BooleanField(
                        default=True,
                        help_text="Si es False, es una cuenta de agrupación.",
                        verbose_name="Permite Movimientos",
                    ),
                ),
                (
                    "naturaleza",
                    models.CharField(
                        choices=[("D", "Deudora"), ("H", "Acreedora")],
                        max_length=1,
                        verbose_name="Naturaleza",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
            ],
            options={
                "verbose_name": "Cuenta Contable",
                "verbose_name_plural": "Plan de Cuentas",
                "ordering": ["codigo_cuenta"],
            },
        ),
        migrations.CreateModel(
            name="TasaCambioBCV",
            fields=[
                (
                    "id_tasa",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID Tasa"
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        db_index=True,
                        help_text="Fecha de vigencia de la tasa",
                        unique=True,
                        verbose_name="Fecha",
                    ),
                ),
                (
                    "tasa_bsd_por_usd",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Bolívares por cada dólar estadounidense",
                        max_digits=12,
                        verbose_name="Tasa BSD/USD",
                    ),
                ),
                (
                    "fuente",
                    models.CharField(
                        default="BCV",
                        help_text="Origen de la tasa (BCV, API, Manual)",
                        max_length=100,
                        verbose_name="Fuente",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "actualizado",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
            ],
            options={
                "verbose_name": "Tasa de Cambio BCV",
                "verbose_name_plural": "Tasas de Cambio BCV",
                "ordering": ["-fecha"],
            },
        ),
    ]
