# Generated by Django 5.2.6 on 2026-04-02 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contabilidad", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asientocontable",
            name="moneda",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contabilidad_asientos_contables",
                to="core.moneda",
                verbose_name="Moneda del Asiento",
            ),
        ),
        migrations.AddField(
            model_name="detalleasiento",
            name="asiento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles_asiento",
                to="contabilidad.asientocontable",
                verbose_name="Asiento Contable",
            ),
        ),
        migrations.AddField(
            model_name="plancontable",
            name="cuenta_padre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subcuentas",
                to="contabilidad.plancontable",
                verbose_name="Cuenta Padre",
            ),
        ),
        migrations.AddField(
            model_name="detalleasiento",
            name="cuenta_contable",
            field=models.ForeignKey(
                limit_choices_to={"permite_movimientos": True},
                on_delete=django.db.models.deletion.PROTECT,
                to="contabilidad.plancontable",
                verbose_name="Cuenta Contable",
            ),
        ),
        migrations.AddIndex(
            model_name="tasacambiobcv",
            index=models.Index(fields=["-fecha"], name="contabilida_fecha_7481be_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="detalleasiento",
            unique_together={("asiento", "linea")},
        ),
    ]
