# Generated by Django 5.2.6 on 2026-05-04 00:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0008_amenity_comisionoverrideaerolinea_cruceroreserva_and_more"),
        ("contabilidad", "0002_initial"),
        ("core", "0007_hoteltarifario_agencia_tarifarioproveedor_agencia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asientocontable",
            name="moneda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contabilidad_asientos_contables",
                to="core.moneda",
                verbose_name="Moneda del Asiento",
            ),
        ),
        migrations.AlterField(
            model_name="detalleasiento",
            name="asiento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles_asiento",
                to="contabilidad.asientocontable",
                verbose_name="Asiento Contable",
            ),
        ),
        migrations.AlterField(
            model_name="detalleasiento",
            name="cuenta_contable",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"permite_movimientos": True},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="contabilidad.plancontable",
                verbose_name="Cuenta Contable",
            ),
        ),
        migrations.CreateModel(
            name="LiquidacionProveedor",
            fields=[
                ("id_liquidacion", models.AutoField(primary_key=True, serialize=False)),
                (
                    "fecha_emision",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Emisión",
                    ),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(blank=True, null=True, verbose_name="Fecha de Vencimiento"),
                ),
                (
                    "monto_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Monto Total a Pagar",
                    ),
                ),
                (
                    "monto_pagado",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Monto Pagado",
                    ),
                ),
                (
                    "saldo_pendiente",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=12,
                        verbose_name="Saldo Pendiente",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PEN", "Pendiente"),
                            ("PAR", "Pagada Parcialmente"),
                            ("PAG", "Pagada"),
                            ("ANU", "Anulada"),
                        ],
                        default="PEN",
                        max_length=3,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "notas",
                    models.TextField(blank=True, null=True, verbose_name="Notas Internas"),
                ),
                (
                    "archivo_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="liquidaciones_proveedor/%Y/%m/",
                        verbose_name="PDF de Liquidación",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.proveedor",
                        verbose_name="Proveedor",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bookings.venta",
                        verbose_name="Venta Asociada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liquidación a Proveedor",
                "verbose_name_plural": "Liquidaciones a Proveedores",
                "ordering": ["-fecha_emision"],
            },
        ),
        migrations.CreateModel(
            name="ItemLiquidacion",
            fields=[
                (
                    "id_item_liquidacion",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=500, verbose_name="Descripción"),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto a Pagar"
                    ),
                ),
                (
                    "item_venta",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bookings.itemventa",
                        verbose_name="Item de Venta Original",
                    ),
                ),
                (
                    "liquidacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="contabilidad.liquidacionproveedor",
                        verbose_name="Liquidación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Liquidación",
                "verbose_name_plural": "Items de Liquidación",
            },
        ),
    ]
