# Generated by Django 5.2.6 on 2026-05-04 13:42

"""Migración de base de datos para contabilidad.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        (
            "bookings",
            "0010_comisionproveedorservicio_productoservicio_proveedor_and_more",
        ),
        ("contabilidad", "0003_alter_asientocontable_moneda_and_more"),
        ("finance", "0004_moneda_alter_reporteproveedor_proveedor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asientocontable",
            name="moneda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contabilidad_asientos_contables",
                to="finance.moneda",
                verbose_name="Moneda del Asiento",
            ),
        ),
        migrations.AlterField(
            model_name="liquidacionproveedor",
            name="proveedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="bookings.proveedor",
                verbose_name="Proveedor",
            ),
        ),
    ]
