# Generated by Django 5.2.6 on 2026-06-03 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_moneda"),
        ("contabilidad", "0007_alter_asientocontable_agencia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asientocontable",
            name="moneda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contabilidad_asientos_contables",
                to="common.moneda",
                verbose_name="Moneda del Asiento",
            ),
        ),
    ]
