# Generated by Django 5.2.14 on 2026-06-24 17:56

"""Migración de base de datos para contabilidad.
"""

from django.db import migrations, models

import core.validators


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("contabilidad", "0008_alter_asientocontable_moneda"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liquidacionproveedor",
            name="archivo_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="liquidaciones_proveedor/%Y/%m/",
                validators=[core.validators.antivirus_hook],
                verbose_name="PDF de Liquidación",
            ),
        ),
    ]
