# Generated by Django 5.2.14 on 2026-06-30 14:45

"""Migración de base de datos para contabilidad.
"""

from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("contabilidad", "0009_alter_liquidacionproveedor_archivo_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liquidacionproveedor",
            name="archivo_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="liquidaciones_proveedor/%Y/%m/",
                verbose_name="PDF de Liquidación",
            ),
        ),
    ]
