# Generated by Django 5.2.14 on 2026-07-14 17:49

"""Migración de base de datos para contabilidad.
"""

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("contabilidad", "0010_alter_liquidacionproveedor_archivo_pdf"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0050_delete_numberingsequence"),
    ]

    operations = [
        migrations.CreateModel(
            name="CuentaContable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=30)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("PASIVO", "Pasivo"),
                            ("PATRIMONIO", "Patrimonio"),
                            ("INGRESO", "Ingreso"),
                            ("GASTO", "Gasto"),
                        ],
                        max_length=10,
                    ),
                ),
                ("acepta_movimientos", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Cuenta Contable",
                "verbose_name_plural": "Cuentas Contables",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="MovimientoContable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("DEBITO", "Débito"), ("CREDITO", "Crédito")],
                        max_length=7,
                    ),
                ),
                ("monto_ves", models.DecimalField(decimal_places=4, max_digits=15)),
                ("monto_usd", models.DecimalField(decimal_places=4, max_digits=15)),
            ],
            options={
                "verbose_name": "Movimiento Contable",
                "verbose_name_plural": "Movimientos Contables",
                "ordering": ["asiento", "pk"],
            },
        ),
        migrations.DeleteModel(
            name="TasaCambioBCV",
        ),
        migrations.AlterModelOptions(
            name="asientocontable",
            options={
                "ordering": ["-fecha_contable"],
                "verbose_name": "Asiento Contable",
                "verbose_name_plural": "Asientos Contables",
            },
        ),
        migrations.AlterModelOptions(
            name="detalleasiento",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="itemliquidacion",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="liquidacionproveedor",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="plancontable",
            options={"managed": False},
        ),
        migrations.RemoveField(
            model_name="asientocontable",
            name="descripcion_general",
        ),
        migrations.RemoveField(
            model_name="asientocontable",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="asientocontable",
            name="fecha_creacion",
        ),
        migrations.RemoveField(
            model_name="asientocontable",
            name="id_asiento",
        ),
        migrations.RemoveField(
            model_name="asientocontable",
            name="moneda",
        ),
        migrations.RemoveField(
            model_name="asientocontable",
            name="numero_asiento",
        ),
        migrations.RemoveField(
            model_name="asientocontable",
            name="referencia_documento",
        ),
        migrations.RemoveField(
            model_name="asientocontable",
            name="tasa_cambio_aplicada",
        ),
        migrations.RemoveField(
            model_name="asientocontable",
            name="tipo_asiento",
        ),
        migrations.RemoveField(
            model_name="asientocontable",
            name="total_debe",
        ),
        migrations.RemoveField(
            model_name="asientocontable",
            name="total_haber",
        ),
        migrations.AddField(
            model_name="asientocontable",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="asientocontable",
            name="glosa",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="asientocontable",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="asientocontable",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="asientocontable",
            name="fecha_contable",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddIndex(
            model_name="asientocontable",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="contabilida_content_8d3510_idx",
            ),
        ),
        migrations.AddField(
            model_name="cuentacontable",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
        migrations.AddField(
            model_name="cuentacontable",
            name="cuenta_padre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subcuentas",
                to="contabilidad.cuentacontable",
            ),
        ),
        migrations.AddField(
            model_name="movimientocontable",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
        migrations.AddField(
            model_name="movimientocontable",
            name="asiento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movimientos",
                to="contabilidad.asientocontable",
            ),
        ),
        migrations.AddField(
            model_name="movimientocontable",
            name="cuenta",
            field=models.ForeignKey(
                limit_choices_to={"acepta_movimientos": True},
                on_delete=django.db.models.deletion.PROTECT,
                to="contabilidad.cuentacontable",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cuentacontable",
            unique_together={("agencia", "codigo")},
        ),
    ]
