# Generated by Django 5.2.14 on 2026-07-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contabilidad", "0011_cuentacontable_movimientocontable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asientocontable",
            name="estado",
            field=models.CharField(
                choices=[
                    ("BORRADOR", "Borrador"),
                    ("CONTABILIZADO", "Contabilizado"),
                    ("ANULADO", "Anulado"),
                ],
                default="BORRADOR",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="asientocontable",
            name="tipo_asiento",
            field=models.CharField(
                choices=[
                    ("DIARIO", "Diario"),
                    ("VENTAS", "Ventas"),
                    ("AJUSTE", "Ajuste"),
                    ("CIERRE", "Cierre"),
                ],
                default="DIARIO",
                max_length=7,
            ),
        ),
    ]
