version: '3.9'
services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-travelhub}
      POSTGRES_USER: ${POSTGRES_USER:-travelhub}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-travelhub}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-travelhub}"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db_data:
