# Generated by Django 5.2.6 on 2026-04-02 00:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("core", "0002_initial"),
        ("crm", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cotizacion",
            fields=[
                (
                    "id_cotizacion",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID Cotización"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "numero_cotizacion",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Número de Cotización",
                    ),
                ),
                (
                    "nombre_cliente_manual",
                    models.CharField(
                        blank=True,
                        help_text="Usar si el cliente no está registrado aún.",
                        max_length=150,
                        null=True,
                        verbose_name="Nombre Cliente (Prospecto)",
                    ),
                ),
                (
                    "descripcion_general",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descripción General"
                    ),
                ),
                (
                    "destino",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Destino del Viaje",
                    ),
                ),
                (
                    "numero_pasajeros",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Número de Pasajeros"
                    ),
                ),
                (
                    "fecha_emision",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Emisión",
                    ),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Vencimiento"
                    ),
                ),
                (
                    "total_cotizado",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=12,
                        verbose_name="Total Cotizado",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=12
                    ),
                ),
                (
                    "impuestos",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=12
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BOR", "Borrador"),
                            ("ENV", "Enviada al Cliente"),
                            ("VIS", "Vista por Cliente"),
                            ("ACE", "Aceptada"),
                            ("REC", "Rechazada"),
                            ("VEN", "Vencida"),
                            ("CON", "Convertida a Venta"),
                        ],
                        default="BOR",
                        max_length=3,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "terminos_pago",
                    models.TextField(
                        blank=True, null=True, verbose_name="Términos de Pago"
                    ),
                ),
                (
                    "terminos_cancelacion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Términos de Cancelación"
                    ),
                ),
                (
                    "condiciones_comerciales",
                    models.TextField(
                        blank=True, null=True, verbose_name="Condiciones Comerciales"
                    ),
                ),
                (
                    "notas_internas",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notas Internas"
                    ),
                ),
                (
                    "fecha_validez",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Validez"
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notas Internas"
                    ),
                ),
                (
                    "archivo_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="cotizaciones_pdf/",
                        verbose_name="Archivo PDF",
                    ),
                ),
                (
                    "gds_raw_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Texto Crudo GDS"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Imagen de Destino (Unsplash)",
                    ),
                ),
                (
                    "metadata_ia",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Metadatos IA (Gemini)"
                    ),
                ),
                (
                    "agency_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Fee de Agencia (Markup)",
                    ),
                ),
                (
                    "fecha_envio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Envío"
                    ),
                ),
                (
                    "fecha_vista",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Vista por Cliente"
                    ),
                ),
                (
                    "fecha_respuesta",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Respuesta"
                    ),
                ),
                (
                    "email_enviado",
                    models.BooleanField(default=False, verbose_name="Email Enviado"),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="crm.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "consultor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Consultor",
                    ),
                ),
                (
                    "moneda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.moneda",
                        verbose_name="Moneda",
                    ),
                ),
                (
                    "venta_generada",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bookings.venta",
                        verbose_name="Venta Generada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cotización",
                "verbose_name_plural": "Cotizaciones",
                "db_table": "core_cotizacion",
                "ordering": ["-fecha_emision"],
            },
        ),
        migrations.CreateModel(
            name="ItemCotizacion",
            fields=[
                (
                    "id_item_cotizacion",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Item Cotización",
                    ),
                ),
                (
                    "tipo_item",
                    models.CharField(
                        choices=[
                            ("VUE", "Vuelo"),
                            ("ALO", "Alojamiento"),
                            ("ACT", "Actividad"),
                            ("SEG", "Seguro de Viaje"),
                            ("OTR", "Otro"),
                        ],
                        default="OTR",
                        max_length=3,
                        verbose_name="Tipo de Item",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        default="", max_length=255, verbose_name="Descripción Principal"
                    ),
                ),
                (
                    "descripcion_personalizada",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Descripción Personalizada",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Precio Unitario",
                    ),
                ),
                (
                    "subtotal_item",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "total_item",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="Total"
                    ),
                ),
                (
                    "impuestos_item",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Impuestos",
                    ),
                ),
                (
                    "detalles_json",
                    models.JSONField(
                        blank=True,
                        help_text="Estructura de datos específica para el tipo de item",
                        null=True,
                        verbose_name="Detalles (JSON)",
                    ),
                ),
                (
                    "costo",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Costo Total del Item",
                    ),
                ),
                (
                    "cotizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cotizaciones.cotizacion",
                        verbose_name="Cotización",
                    ),
                ),
                (
                    "producto_servicio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.productoservicio",
                        verbose_name="Producto/Servicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Cotización",
                "verbose_name_plural": "Items de Cotización",
                "db_table": "core_itemcotizacion",
                "ordering": ["id_item_cotizacion"],
            },
        ),
    ]
