# Generated by Django 5.2.6 on 2026-05-04 13:42

"""Migración de base de datos para cotizaciones.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        (
            "bookings",
            "0010_comisionproveedorservicio_productoservicio_proveedor_and_more",
        ),
        ("cotizaciones", "0001_initial"),
        ("finance", "0004_moneda_alter_reporteproveedor_proveedor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacion",
            name="moneda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.moneda",
                verbose_name="Moneda",
            ),
        ),
        migrations.AlterField(
            model_name="itemcotizacion",
            name="producto_servicio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bookings.productoservicio",
                verbose_name="Producto/Servicio",
            ),
        ),
    ]
