# Generated by Django 5.2.6 on 2026-05-09 22:43

"""Migración de base de datos para cotizaciones.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("core", "0022_remove_agencia_bi_insights_and_more"),
        ("cotizaciones", "0002_alter_cotizacion_moneda_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
        migrations.AddField(
            model_name="itemcotizacion",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
    ]
