# Generated by Django 5.2.6 on 2026-05-10 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0003_cotizacion_agencia_itemcotizacion_agencia"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="cotizacion",
            table=None,
        ),
        migrations.AlterModelTable(
            name="itemcotizacion",
            table=None,
        ),
    ]
