# Generated by Django 5.2.6 on 2026-05-10 19:18
# Edited 2026-06-06: removed AlterModelTable(table=None) so state keeps
# db_table='core_xxx' for the renamed models.

"""Migración de base de datos para cotizaciones.
"""

from django.db import migrations


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("cotizaciones", "0003_cotizacion_agencia_itemcotizacion_agencia"),
    ]

    operations = []
