# Generated by Django 5.2.6 on 2026-05-14 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_alter_anulacionboleto_agencia_and_more"),
        ("cotizaciones", "0004_alter_cotizacion_table_alter_itemcotizacion_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacion",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
        migrations.AlterField(
            model_name="itemcotizacion",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
    ]
