# Generated by Django 5.2.6 on 2026-06-03 17:27

"""Migración de base de datos para cotizaciones.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("common", "0003_moneda"),
        ("cotizaciones", "0006_alter_cotizacion_agencia_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="cotizacion",
                    name="moneda",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.moneda",
                        verbose_name="Moneda",
                    ),
                ),
            ],
        ),
    ]
