# Generated by Django 5.2.14 on 2026-06-06 20:37

from django.db import migrations


class Migration(migrations.Migration):
    # Edited 2026-06-07: wrap in SeparateDatabaseAndState with
    # database_operations=[] because the tables named in the original
    # AlterModelTable(table=None) operations were already renamed
    # manually (or via pg_dump --schema-only + migrate --fake) in
    # dev/prod. State-only update is safe and idempotent in fresh-DB.

    dependencies = [
        ("cotizaciones", "0007_alter_cotizacion_moneda"),
        ("core", "0037_rename_remaining_core_tables"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelTable(
                    name="cotizacion",
                    table=None,
                ),
                migrations.AlterModelTable(
                    name="itemcotizacion",
                    table=None,
                ),
            ],
        ),
    ]
