# Generated by Django 5.2.14 on 2026-06-11 03:43

"""Migración de base de datos para cotizaciones.
"""

import django.utils.timezone
from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("cotizaciones", "0009_add_soft_delete_and_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="cotizacion",
            name="idx_cotizacion_agencia_estado",
        ),
        migrations.RemoveIndex(
            model_name="cotizacion",
            name="idx_cotizacion_agencia_fecha_emision",
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="condiciones_comerciales",
            field=models.TextField(blank=True, verbose_name="Condiciones Comerciales"),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="descripcion_general",
            field=models.TextField(blank=True, verbose_name="Descripción General"),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="destino",
            field=models.CharField(blank=True, max_length=200, verbose_name="Destino del Viaje"),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("BOR", "Borrador"),
                    ("ENV", "Enviada al Cliente"),
                    ("VIS", "Vista por Cliente"),
                    ("ACE", "Aceptada"),
                    ("REC", "Rechazada"),
                    ("VEN", "Vencida"),
                    ("CON", "Convertida a Venta"),
                ],
                default="BOR",
                max_length=3,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="fecha_emision",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Fecha de Emisión"
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="gds_raw_text",
            field=models.TextField(blank=True, verbose_name="Texto Crudo GDS"),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="nombre_cliente_manual",
            field=models.CharField(
                blank=True,
                help_text="Usar si el cliente no está registrado aún.",
                max_length=150,
                verbose_name="Nombre Cliente (Prospecto)",
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="notas",
            field=models.TextField(blank=True, verbose_name="Notas Internas"),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="notas_internas",
            field=models.TextField(blank=True, verbose_name="Notas Internas"),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="terminos_cancelacion",
            field=models.TextField(blank=True, verbose_name="Términos de Cancelación"),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="terminos_pago",
            field=models.TextField(blank=True, verbose_name="Términos de Pago"),
        ),
        migrations.AlterField(
            model_name="itemcotizacion",
            name="descripcion_personalizada",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Descripción Personalizada"
            ),
        ),
    ]
