# Generated by Django 5.2.14 on 2026-06-12 11:17

"""Migración de base de datos para cotizaciones.
"""

from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        (
            "cotizaciones",
            "0010_remove_cotizacion_idx_cotizacion_agencia_estado_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacion",
            name="condiciones_comerciales",
            field=models.TextField(blank=True, null=True, verbose_name="Condiciones Comerciales"),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="descripcion_general",
            field=models.TextField(blank=True, null=True, verbose_name="Descripción General"),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="destino",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Destino del Viaje"
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="gds_raw_text",
            field=models.TextField(blank=True, null=True, verbose_name="Texto Crudo GDS"),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="nombre_cliente_manual",
            field=models.CharField(
                blank=True,
                help_text="Usar si el cliente no está registrado aún.",
                max_length=150,
                null=True,
                verbose_name="Nombre Cliente (Prospecto)",
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="notas",
            field=models.TextField(blank=True, null=True, verbose_name="Notas Internas"),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="notas_internas",
            field=models.TextField(blank=True, null=True, verbose_name="Notas Internas"),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="terminos_cancelacion",
            field=models.TextField(blank=True, null=True, verbose_name="Términos de Cancelación"),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="terminos_pago",
            field=models.TextField(blank=True, null=True, verbose_name="Términos de Pago"),
        ),
        migrations.AlterField(
            model_name="itemcotizacion",
            name="descripcion_personalizada",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Descripción Personalizada",
            ),
        ),
    ]
