# Generated by Django 5.2.14 on 2026-06-24 17:56

from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("cotizaciones", "0011_alter_cotizacion_condiciones_comerciales_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacion",
            name="archivo_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="cotizaciones_pdf/",
                validators=[core.validators.antivirus_hook],
                verbose_name="Archivo PDF",
            ),
        ),
    ]
