# Generated by Django 5.2.14 on 2026-06-30 14:45

"""Migración de base de datos para cotizaciones.
"""

from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("cotizaciones", "0012_alter_cotizacion_archivo_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacion",
            name="archivo_pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="cotizaciones_pdf/", verbose_name="Archivo PDF"
            ),
        ),
    ]
