# Generated by Django 5.2.14 on 2026-07-11 22:00

from django.db import migrations


def clean_null_charfields(apps, schema_editor):
    """Replace NULL with empty string in CharField/TextField."""
    model_fields = {
        "Cotizacion": [
            "destino",
            "notas",
            "terminos_condiciones",
            "nombre_cliente_manual",
            "email_cliente_manual",
            "telefono_cliente_manual",
        ],
        "ItemCotizacion": [
            "descripcion_personalizada",
            "categoria_auto",
        ],
    }

    for model_name, fields in model_fields.items():
        try:
            Modelo = apps.get_model("cotizaciones", model_name)
            for obj in Modelo.objects.all():
                changed = False
                for field in fields:
                    value = getattr(obj, field, None)
                    if value is None:
                        setattr(obj, field, "")
                        changed = True
                if changed:
                    obj.save(update_fields=fields)
        except LookupError:
            pass


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("cotizaciones", "0013_alter_cotizacion_archivo_pdf"),
    ]

    operations = [
        migrations.RunPython(
            clean_null_charfields,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
