# Generated by Django 5.2.6 on 2025-09-18 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("cotizaciones", "__first__"),
        ("personas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="personas.cliente",
                verbose_name="Cliente (Pagador)",
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="cotizacion_origen",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cotizaciones.cotizacion",
                verbose_name="Cotización de Origen",
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ventas_creadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado Por",
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="factura",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ventas",
                to="core.factura",
                verbose_name="Factura Asociada",
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="moneda",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="core.moneda",
                verbose_name="Moneda",
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="pasajeros",
            field=models.ManyToManyField(
                related_name="ventas", to="personas.pasajero", verbose_name="Pasajeros"
            ),
        ),
        migrations.AddField(
            model_name="trasladoservicio",
            name="venta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="traslados",
                to="core.venta",
                verbose_name="Venta",
            ),
        ),
        migrations.AddField(
            model_name="servicioadicionaldetalle",
            name="venta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="servicios_adicionales",
                to="core.venta",
                verbose_name="Venta",
            ),
        ),
        migrations.AddField(
            model_name="segmentovuelo",
            name="venta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="segmentos_vuelo",
                to="core.venta",
                verbose_name="Venta",
            ),
        ),
        migrations.AddField(
            model_name="paqueteaereo",
            name="venta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paquetes_aereos",
                to="core.venta",
                verbose_name="Venta",
            ),
        ),
        migrations.AddField(
            model_name="pagoventa",
            name="venta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pagos_venta",
                to="core.venta",
                verbose_name="Venta",
            ),
        ),
        migrations.AddField(
            model_name="itemventa",
            name="venta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items_venta",
                to="core.venta",
                verbose_name="Venta",
            ),
        ),
        migrations.AddField(
            model_name="feeventa",
            name="venta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fees_venta",
                to="core.venta",
                verbose_name="Venta",
            ),
        ),
        migrations.AddField(
            model_name="eventoservicio",
            name="venta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventos_servicios",
                to="core.venta",
                verbose_name="Venta",
            ),
        ),
        migrations.AddField(
            model_name="circuitoturistico",
            name="venta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="circuitos_turisticos",
                to="core.venta",
                verbose_name="Venta",
            ),
        ),
        migrations.AddField(
            model_name="boletoimportado",
            name="venta_asociada",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="boleto_importado",
                to="core.venta",
                verbose_name="Venta/Reserva Asociada",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="venta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="core.venta",
                verbose_name="Venta Asociada",
            ),
        ),
        migrations.AddField(
            model_name="alquilerautoreserva",
            name="venta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alquileres_autos",
                to="core.venta",
                verbose_name="Venta",
            ),
        ),
        migrations.AddField(
            model_name="alojamientoreserva",
            name="venta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alojamientos",
                to="core.venta",
                verbose_name="Venta",
            ),
        ),
        migrations.AddField(
            model_name="actividadservicio",
            name="venta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actividades",
                to="core.venta",
                verbose_name="Venta",
            ),
        ),
        migrations.AddField(
            model_name="ventaparsemetadata",
            name="venta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metadata_parseo",
                to="core.venta",
                verbose_name="Venta",
            ),
        ),
        migrations.AddIndex(
            model_name="circuitodia",
            index=models.Index(
                fields=["dia_numero"], name="core_circui_dia_num_5ab3a8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="circuitodia",
            unique_together={("circuito", "dia_numero")},
        ),
        migrations.AlterUniqueTogether(
            name="ciudad",
            unique_together={("nombre", "pais", "region_estado")},
        ),
        migrations.AlterUniqueTogether(
            name="pasajero",
            unique_together={("nombres", "apellidos", "fecha_nacimiento")},
        ),
        migrations.AlterUniqueTogether(
            name="detalleasiento",
            unique_together={("asiento", "linea")},
        ),
        migrations.AlterUniqueTogether(
            name="productoservicio",
            unique_together={("nombre", "tipo_producto", "proveedor_principal")},
        ),
        migrations.AlterUniqueTogether(
            name="tipocambio",
            unique_together={("moneda_origen", "moneda_destino", "fecha_efectiva")},
        ),
        migrations.AddIndex(
            model_name="servicioadicionaldetalle",
            index=models.Index(
                fields=["tipo_servicio"], name="core_servic_tipo_se_1f3d42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paqueteaereo",
            index=models.Index(
                fields=["incluye_vuelos", "incluye_hotel"],
                name="core_paquet_incluye_d13cca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="eventoservicio",
            index=models.Index(
                fields=["fecha_evento"], name="core_evento_fecha_e_4cbc1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventoservicio",
            index=models.Index(
                fields=["nombre_evento"], name="core_evento_nombre__c306a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="circuitoturistico",
            index=models.Index(
                fields=["fecha_inicio"], name="core_circui_fecha_i_c9ac23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alquilerautoreserva",
            index=models.Index(
                fields=["fecha_hora_retiro"], name="core_alquil_fecha_h_9424c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alquilerautoreserva",
            index=models.Index(
                fields=["fecha_hora_devolucion"], name="core_alquil_fecha_h_19d2b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alquilerautoreserva",
            index=models.Index(
                fields=["compania_rentadora"], name="core_alquil_compani_88d6b6_idx"
            ),
        ),
    ]
