# Generated by Django 5.2.4 on 2025-07-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletoimportado',
            name='archivo_pdf_generado',
            field=models.FileField(blank=True, help_text='El archivo PDF del boleto unificado, generado automáticamente.', null=True, upload_to='boletos_generados/%Y/%m/', verbose_name='PDF Unificado Generado'),
        ),
    ]
