# Generated by Django 5.2.6 on 2025-09-19 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
        ("personas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venta",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="personas.cliente",
                verbose_name="Cliente (Pagador)",
            ),
        ),
    ]
