# Generated by Django 5.2.4 on 2025-07-28 20:52

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_boletoimportado_archivo_pdf_generado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='venta_asociada',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='numero_venta',
        ),
        migrations.AddField(
            model_name='venta',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='core.factura', verbose_name='Factura Asociada'),
        ),
        migrations.AddField(
            model_name='venta',
            name='localizador',
            field=models.CharField(blank=True, help_text='Código único de la reserva o localizador.', max_length=20, unique=True, verbose_name='Localizador/PNR'),
        ),
        migrations.AlterField(
            model_name='boletoimportado',
            name='venta_asociada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boleto_importado', to='core.venta', verbose_name='Venta/Reserva Asociada'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Monto Total'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Saldo Pendiente'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cliente', verbose_name='Cliente (Pagador)'),
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id_pasajero', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Pasajero')),
                ('nombres', models.CharField(max_length=100, validators=[core.models.validar_no_vacio_o_espacios], verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, validators=[core.models.validar_no_vacio_o_espacios], verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('tipo_documento', models.CharField(choices=[('PASS', 'Pasaporte'), ('CI', 'Cédula de Identidad'), ('OTRO', 'Otro')], default='PASS', max_length=4, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(max_length=50, unique=True, validators=[core.models.validar_numero_pasaporte], verbose_name='Número de Documento/Pasaporte')),
                ('fecha_vencimiento_documento', models.DateField(blank=True, null=True, verbose_name='Fecha Vencimiento Documento')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas sobre el Pasajero')),
                ('nacionalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasajeros_nacionalidad', to='core.pais', verbose_name='Nacionalidad')),
                ('pais_emision_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pais', verbose_name='País Emisión Documento')),
            ],
            options={
                'verbose_name': 'Pasajero',
                'verbose_name_plural': 'Pasajeros',
                'ordering': ['apellidos', 'nombres'],
                'unique_together': {('nombres', 'apellidos', 'fecha_nacimiento')},
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='pasajeros',
            field=models.ManyToManyField(related_name='ventas', to='core.pasajero', verbose_name='Pasajeros'),
        ),
    ]
