# Generated by Django 5.2.6 on 2026-04-29 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_asientocontable_moneda_ciudad_pais_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ciudad",
            name="codigo_iata",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Código IATA de 3 letras de la ciudad o aeropuerto.",
                max_length=3,
                null=True,
                verbose_name="Código IATA",
            ),
        ),
        migrations.CreateModel(
            name="ComisionOverrideAerolinea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comision_porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Comisión Especial %",
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas Internas")),
                (
                    "aerolinea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.aerolinea",
                        verbose_name="Aerolínea",
                    ),
                ),
                (
                    "tarifario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides_aerolinea",
                        to="core.tarifarioproveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comisión Especial por Aerolínea",
                "verbose_name_plural": "Comisiones Especiales (Overrides)",
                "unique_together": {("tarifario", "aerolinea")},
            },
        ),
    ]
