# Generated by Django 5.2.6 on 2025-09-19 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_venta_cliente"),
        ("personas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factura",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="personas.cliente",
                verbose_name="Cliente",
            ),
        ),
    ]
