# Generated by Django 5.2.5 on 2025-08-28 19:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_boletoimportado_campos_financieros'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='canal_origen',
            field=models.CharField(choices=[('ADM', 'Admin'), ('IMP', 'Importación'), ('API', 'API'), ('WEB', 'Formulario Web'), ('MIG', 'Migración'), ('OTR', 'Otro')], db_index=True, default='ADM', max_length=3, verbose_name='Canal de Origen'),
        ),
        migrations.AddField(
            model_name='venta',
            name='co2_estimado_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimación agregada de la huella de carbono.', max_digits=12, null=True, verbose_name='Emisiones CO₂ Estimadas (kg)'),
        ),
        migrations.AddField(
            model_name='venta',
            name='margen_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio venta - costo neto estimado (informativo).', max_digits=12, null=True, verbose_name='Margen Estimado'),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_venta',
            field=models.CharField(choices=[('B2C', 'B2C (Ocio)'), ('B2B', 'B2B (Corporativo)'), ('MICE', 'MICE / Eventos'), ('PKG', 'Paquete'), ('CIR', 'Circuito'), ('TLD', 'Viaje a Medida'), ('SEG', 'Solo Seguro'), ('OTR', 'Otro')], db_index=True, default='B2C', max_length=4, verbose_name='Tipo de Venta'),
        ),
        migrations.CreateModel(
            name='ActividadServicio',
            fields=[
                ('id_actividad_servicio', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Actividad')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Actividad')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('duracion_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Duración (horas)')),
                ('incluye', models.TextField(blank=True, null=True, verbose_name='Incluye')),
                ('no_incluye', models.TextField(blank=True, null=True, verbose_name='No Incluye')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.proveedor', verbose_name='Proveedor')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='core.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Actividad / Excursión',
                'verbose_name_plural': 'Actividades / Excursiones',
                'ordering': ['fecha', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AlojamientoReserva',
            fields=[
                ('id_alojamiento_reserva', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Alojamiento')),
                ('nombre_establecimiento', models.CharField(max_length=150, verbose_name='Nombre Establecimiento')),
                ('check_in', models.DateField(blank=True, null=True, verbose_name='Check In')),
                ('check_out', models.DateField(blank=True, null=True, verbose_name='Check Out')),
                ('regimen_alimentacion', models.CharField(blank=True, help_text='Ej: Desayuno, Media Pensión, Todo Incluido', max_length=30, null=True, verbose_name='Régimen Alimentación')),
                ('habitaciones', models.PositiveSmallIntegerField(default=1, verbose_name='Habitaciones')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ciudad', verbose_name='Ciudad')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.proveedor', verbose_name='Proveedor')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alojamientos', to='core.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Alojamiento (Reserva)',
                'verbose_name_plural': 'Alojamientos (Reservas)',
                'ordering': ['check_in'],
            },
        ),
        migrations.CreateModel(
            name='FeeVenta',
            fields=[
                ('id_fee_venta', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Fee')),
                ('tipo_fee', models.CharField(choices=[('EMI', 'Emisión'), ('CAM', 'Cambio / Exchange'), ('GST', 'Gestión'), ('URG', 'Urgente'), ('OTR', 'Otro')], default='GST', max_length=3, verbose_name='Tipo Fee')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('es_comision_agencia', models.BooleanField(default=True, verbose_name='Es Comisión Agencia')),
                ('taxable', models.BooleanField(default=False, verbose_name='Sujeto a Impuestos')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.moneda', verbose_name='Moneda')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_venta', to='core.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Fee de Venta',
                'verbose_name_plural': 'Fees de Venta',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='PagoVenta',
            fields=[
                ('id_pago_venta', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Pago')),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('metodo', models.CharField(choices=[('EFE', 'Efectivo'), ('TAR', 'Tarjeta'), ('TRF', 'Transferencia'), ('ZEL', 'Zelle'), ('PPL', 'PayPal'), ('OTR', 'Otro')], default='TRF', max_length=3, verbose_name='Método')),
                ('referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia')),
                ('confirmado', models.BooleanField(default=True, verbose_name='Confirmado')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.moneda', verbose_name='Moneda')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_venta', to='core.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Pago de Venta',
                'verbose_name_plural': 'Pagos de Venta',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='SegmentoVuelo',
            fields=[
                ('id_segmento_vuelo', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Segmento Vuelo')),
                ('aerolinea', models.CharField(blank=True, max_length=80, null=True, verbose_name='Aerolínea')),
                ('numero_vuelo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Vuelo')),
                ('fecha_salida', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora Salida')),
                ('fecha_llegada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora Llegada')),
                ('clase_reserva', models.CharField(blank=True, max_length=5, null=True, verbose_name='Clase')),
                ('cabina', models.CharField(blank=True, help_text='Ej: Economy, Business, First', max_length=20, null=True, verbose_name='Cabina')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='segmentos_llegada', to='core.ciudad', verbose_name='Ciudad Destino')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='segmentos_salida', to='core.ciudad', verbose_name='Ciudad Origen')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentos_vuelo', to='core.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Segmento de Vuelo',
                'verbose_name_plural': 'Segmentos de Vuelo',
                'ordering': ['fecha_salida'],
            },
        ),
        migrations.CreateModel(
            name='TrasladoServicio',
            fields=[
                ('id_traslado_servicio', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Traslado')),
                ('tipo_traslado', models.CharField(choices=[('ARR', 'Arribo / Llegada'), ('DEP', 'Salida'), ('INT', 'Interno')], default='ARR', max_length=3, verbose_name='Tipo Traslado')),
                ('origen', models.CharField(blank=True, max_length=150, null=True, verbose_name='Origen')),
                ('destino', models.CharField(blank=True, max_length=150, null=True, verbose_name='Destino')),
                ('fecha_hora', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora')),
                ('pasajeros', models.PositiveSmallIntegerField(default=1, verbose_name='Pasajeros')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.proveedor', verbose_name='Proveedor')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traslados', to='core.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Traslado',
                'verbose_name_plural': 'Traslados',
                'ordering': ['fecha_hora'],
            },
        ),
    ]
