# Generated by Django 5.2.6 on 2025-09-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_factura_cliente"),
    ]

    operations = [
        migrations.AddField(
            model_name="factura",
            name="archivo_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="facturas/%Y/%m/",
                verbose_name="Archivo PDF",
            ),
        ),
    ]
