# Generated by Django 5.2.5 on 2025-08-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_venta_canal_origen_venta_co2_estimado_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='puntos_fidelidad_asignados',
            field=models.BooleanField(default=False, editable=False, help_text='Evita otorgar puntos duplicados cuando la venta pasa a completada/pagada.', verbose_name='Puntos Fidelidad Asignados'),
        ),
    ]
