# Generated by Django 5.2.6 on 2025-09-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_factura_archivo_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemventa",
            name="comision_agencia_monto",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Comisión Agencia (Monto)",
            ),
        ),
        migrations.AddField(
            model_name="itemventa",
            name="costo_neto_proveedor",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Costo Neto Proveedor",
            ),
        ),
        migrations.AddField(
            model_name="itemventa",
            name="fee_agencia_interno",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Fee Interno Agencia",
            ),
        ),
        migrations.AddField(
            model_name="itemventa",
            name="fee_proveedor",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Fee Emisión Proveedor",
            ),
        ),
    ]
