# Generated by Django 5.2.6 on 2026-05-03 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_comisionproveedorservicio_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        choices=[
                            ("gemini-1.5-pro", "Gemini 1.5 Pro"),
                            ("gemini-1.5-flash", "Gemini 1.5 Flash"),
                            ("gemini-1.5-flash-8b", "Gemini 1.5 Flash 8B"),
                            ("imagen-3", "Imagen 3"),
                        ],
                        max_length=50,
                    ),
                ),
                ("feature", models.CharField(max_length=100)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="SUCCESS", max_length=20)),
                (
                    "agencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_logs",
                        to="core.agencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Uso de IA",
                "verbose_name_plural": "Logs de Uso de IA",
                "ordering": ["-timestamp"],
            },
        ),
    ]
