# Generated by Django 5.2.6 on 2026-05-03 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_aiusagelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="hoteltarifario",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
        migrations.AddField(
            model_name="tarifarioproveedor",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
        migrations.AlterField(
            model_name="hoteltarifario",
            name="slug",
            field=models.SlugField(blank=True, help_text="URL amigable", max_length=250, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="hoteltarifario",
            unique_together={("agencia", "slug")},
        ),
    ]
