# Generated by Django 5.2.6 on 2025-09-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_liquidacionproveedor_itemliquidacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicioadicionaldetalle",
            name="contacto_emergencia",
            field=models.TextField(
                blank=True, null=True, verbose_name="Contacto Emergencia"
            ),
        ),
        migrations.AddField(
            model_name="servicioadicionaldetalle",
            name="detalles_cobertura",
            field=models.TextField(
                blank=True, null=True, verbose_name="Detalles Cobertura"
            ),
        ),
        migrations.AddField(
            model_name="servicioadicionaldetalle",
            name="duracion_estimada",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Duración Estimada"
            ),
        ),
        migrations.AddField(
            model_name="servicioadicionaldetalle",
            name="hora_lugar_encuentro",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Hora y Lugar de Encuentro",
            ),
        ),
        migrations.AddField(
            model_name="servicioadicionaldetalle",
            name="inclusiones_servicio",
            field=models.TextField(
                blank=True, null=True, verbose_name="Inclusiones Servicio"
            ),
        ),
        migrations.AddField(
            model_name="servicioadicionaldetalle",
            name="nombre_pasajero",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Nombre Pasajero"
            ),
        ),
        migrations.AddField(
            model_name="servicioadicionaldetalle",
            name="operado_por",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Operado Por"
            ),
        ),
        migrations.AddField(
            model_name="servicioadicionaldetalle",
            name="participantes",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Participantes"
            ),
        ),
        migrations.AddField(
            model_name="servicioadicionaldetalle",
            name="pasaporte_pasajero",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Pasaporte Pasajero"
            ),
        ),
        migrations.AddField(
            model_name="servicioadicionaldetalle",
            name="recomendaciones",
            field=models.TextField(
                blank=True, null=True, verbose_name="Recomendaciones"
            ),
        ),
    ]
