# Generated by Django 5.2.6 on 2025-09-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_servicioadicionaldetalle_contacto_emergencia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicioadicionaldetalle",
            name="descripcion",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Descripción"
            ),
        ),
    ]
