# Generated by Django 5.2.6 on 2026-05-04 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0009_alter_venta_factura_consolidada_and_more"),
        ("core", "0008_remove_hoteltarifario_amenidades_and_more"),
        ("finance", "0003_alter_factura_asiento_contable_factura_and_more"),
        ("marketing", "0002_alter_activomarketing_hotel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AsientoContable",
        ),
        migrations.DeleteModel(
            name="ComisionOverrideAerolinea",
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="CruceroReserva",
                ),
            ],
            database_operations=[],
        ),
        migrations.DeleteModel(
            name="DetalleAsiento",
        ),
        migrations.DeleteModel(
            name="DocumentoExportacionConsolidado",
        ),
        migrations.DeleteModel(
            name="ItemFacturaConsolidada",
        ),
        migrations.DeleteModel(
            name="FacturaConsolidada",
        ),
        migrations.DeleteModel(
            name="HotelTarifario",
        ),
        migrations.DeleteModel(
            name="ImagenHotel",
        ),
        migrations.DeleteModel(
            name="ItemLiquidacion",
        ),
        migrations.DeleteModel(
            name="LiquidacionProveedor",
        ),
        migrations.DeleteModel(
            name="NotificacionAgente",
        ),
        migrations.DeleteModel(
            name="NotificacionInteligente",
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="PasaporteEscaneado",
                ),
            ],
            database_operations=[],
        ),
        migrations.DeleteModel(
            name="PlanContable",
        ),
        migrations.DeleteModel(
            name="ProductoTerrestre",
        ),
        migrations.DeleteModel(
            name="RetencionISLR",
        ),
        migrations.DeleteModel(
            name="TarifaHabitacion",
        ),
        migrations.DeleteModel(
            name="TipoHabitacion",
        ),
        migrations.DeleteModel(
            name="TarifarioProveedor",
        ),
    ]
