# Generated by Django 5.2.6 on 2025-09-23 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_servicioadicionaldetalle_descripcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="factura",
            name="venta_asociada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="facturas",
                to="core.venta",
                verbose_name="Venta Asociada",
            ),
        ),
    ]
