# Generated by Django 5.2.6 on 2026-05-04 13:42

from django.db import migrations


class Migration:
    """Migración de base de datos generada por Django."""
    dependencies = [
        ("bookings", "0011_alter_cruceroreserva_moneda_alter_feeventa_moneda_and_more"),
        ("core", "0009_delete_asientocontable_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Aerolinea",
                ),
                migrations.AlterUniqueTogether(
                    name="ciudad",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="ciudad",
                    name="pais",
                ),
                migrations.RemoveField(
                    model_name="proveedor",
                    name="ciudad",
                ),
                migrations.AlterUniqueTogether(
                    name="comisionproveedorservicio",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="comisionproveedorservicio",
                    name="agencia",
                ),
                migrations.RemoveField(
                    model_name="comisionproveedorservicio",
                    name="moneda",
                ),
                migrations.RemoveField(
                    model_name="comisionproveedorservicio",
                    name="proveedor",
                ),
                # migrations.RemoveField(
                #     model_name="productoservicio",
                #     name="moneda_referencial",
                # ),
                # migrations.RemoveField(
                #     model_name="tipocambio",
                #     name="moneda_destino",
                # ),
                # migrations.RemoveField(
                #     model_name="tipocambio",
                #     name="moneda_origen",
                # ),
                migrations.AlterUniqueTogether(
                    name="productoservicio",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="productoservicio",
                    name="agencia",
                ),
                migrations.RemoveField(
                    model_name="productoservicio",
                    name="proveedor_principal",
                ),
                migrations.RemoveField(
                    model_name="proveedor",
                    name="agencia",
                ),
                migrations.DeleteModel(
                    name="TasaCambio",
                ),
                migrations.AlterUniqueTogether(
                    name="tipocambio",
                    unique_together=None,
                ),
            ],
            database_operations=[],
        ),
    ]
