# Generated by Django 5.2.6 on 2025-09-27 01:02

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_factura_venta_asociada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boletoimportado",
            name="archivo_boleto",
            field=models.FileField(
                blank=True,
                help_text="Suba el archivo del boleto en formato PDF, TXT o EML (máx 5MB).",
                null=True,
                upload_to="boletos_importados/%Y/%m/",
                validators=[
                    core.validators.validate_file_size,
                    core.validators.validate_file_extension,
                    core.validators.antivirus_hook,
                ],
                verbose_name="Archivo del Boleto (.pdf, .txt, .eml)",
            ),
        ),
    ]
