# Generated by Django 5.2.6 on 2026-05-04 13:42

from django.db import migrations


class Migration:
    """Migración de base de datos generada por Django."""
    dependencies = [
        ("bookings", "0011_alter_cruceroreserva_moneda_alter_feeventa_moneda_and_more"),
        ("contabilidad", "0004_alter_asientocontable_moneda_and_more"),
        ("core", "0010_delete_aerolinea_alter_ciudad_unique_together_and_more"),
        ("cotizaciones", "0002_alter_cotizacion_moneda_and_more"),
        ("crm", "0009_alter_cliente_ciudad_alter_cliente_nacionalidad_and_more"),
        ("finance", "0004_moneda_alter_reporteproveedor_proveedor_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Pais",
                ),
                migrations.DeleteModel(
                    name="Ciudad",
                ),
                migrations.DeleteModel(
                    name="ComisionProveedorServicio",
                ),
                migrations.DeleteModel(
                    name="Moneda",
                ),
                migrations.DeleteModel(
                    name="TipoCambio",
                ),
                migrations.DeleteModel(
                    name="ProductoServicio",
                ),
                migrations.DeleteModel(
                    name="Proveedor",
                ),
            ],
            database_operations=[],
        ),
    ]
