# Generated by Django 5.2.6 on 2026-05-04 19:17

from django.db import migrations

import core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_delete_pais_delete_ciudad_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agencia",
            name="email_monitor_password",
            field=core.fields.EncryptedCharField(
                blank=True,
                help_text="Contraseña de Aplicación de Google (o Token)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="agencia",
            name="password_app_correo",
            field=core.fields.EncryptedCharField(
                blank=True,
                help_text="Contraseña de Aplicación (Ej. Google App Password) para lectura IMAP",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="agencia",
            name="telegram_bot_token",
            field=core.fields.EncryptedCharField(
                blank=True,
                help_text="Token del Bot de Telegram exclusivo de esta agencia (Opcional)",
                max_length=255,
                null=True,
            ),
        ),
    ]
