# Generated by Django 5.2.6 on 2025-09-30 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_boletoimportado_archivo_boleto"),
    ]

    operations = [
        migrations.AddField(
            model_name="alojamientoreserva",
            name="item_venta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alojamientos_reserva",
                to="core.itemventa",
                verbose_name="Item de Venta Asociado",
            ),
        ),
    ]
