# Generated by Django 5.2.6 on 2026-05-04 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_agencia_email_monitor_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="core.agencia",
                verbose_name="Agencia",
            ),
        ),
    ]
