# Generated by Django 5.2.6 on 2025-10-01 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alojamientoreserva_item_venta"),
        ("personas", "0002_cliente_cedula_identidad"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PasaporteEscaneado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagen_original", models.ImageField(upload_to="pasaportes/%Y/%m/")),
                (
                    "imagen_procesada",
                    models.ImageField(
                        blank=True, null=True, upload_to="pasaportes/processed/%Y/%m/"
                    ),
                ),
                ("numero_pasaporte", models.CharField(blank=True, max_length=20)),
                ("nombres", models.CharField(blank=True, max_length=100)),
                ("apellidos", models.CharField(blank=True, max_length=100)),
                ("nacionalidad", models.CharField(blank=True, max_length=3)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("fecha_vencimiento", models.DateField(blank=True, null=True)),
                (
                    "sexo",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculino"), ("F", "Femenino")],
                        max_length=1,
                    ),
                ),
                ("lugar_nacimiento", models.CharField(blank=True, max_length=100)),
                (
                    "confianza_ocr",
                    models.CharField(
                        choices=[
                            ("HIGH", "Alta"),
                            ("MEDIUM", "Media"),
                            ("LOW", "Baja"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("datos_ocr_completos", models.JSONField(default=dict)),
                ("texto_mrz", models.TextField(blank=True)),
                ("errores_detectados", models.JSONField(default=list)),
                ("fecha_procesamiento", models.DateTimeField(auto_now_add=True)),
                ("verificado_manualmente", models.BooleanField(default=False)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personas.cliente",
                    ),
                ),
                (
                    "procesado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pasaporte Escaneado",
                "verbose_name_plural": "Pasaportes Escaneados",
                "db_table": "core_pasaporte_escaneado",
                "ordering": ["-fecha_procesamiento"],
            },
        ),
    ]
