# Generated by Django 5.2.6 on 2026-05-05 02:52

from django.db import migrations, models


class Migration:
    """Migración de base de datos generada por Django."""
    dependencies = [
        ("core", "0013_auditlog_agencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiusagelog",
            name="status",
            field=models.CharField(default="SUCCESS", max_length=100),
        ),
    ]
