# Generated by Django 5.2.6 on 2025-10-06 22:52

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_add_facturacion_venezuela"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aerolinea",
            fields=[
                (
                    "id_aerolinea",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID Aerolínea"
                    ),
                ),
                (
                    "codigo_iata",
                    models.CharField(
                        help_text="Código IATA de 2 letras de la aerolínea (ej. AA, AV, LA).",
                        max_length=2,
                        unique=True,
                        verbose_name="Código IATA",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=150,
                        validators=[core.validators.validar_no_vacio_o_espacios],
                        verbose_name="Nombre de la Aerolínea",
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si la aerolínea está actualmente operando.",
                        verbose_name="Activa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aerolínea",
                "verbose_name_plural": "Aerolíneas",
                "ordering": ["nombre"],
            },
        ),
    ]
