# Generated by Django 5.2.6 on 2026-05-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_aiusagelog_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="agencia",
            name="configuracion_contable",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Configuración contable: CUENTA_PROVEEDOR_USD, CUENTA_GASTO_DEFAULT, CUENTA_INGRESO_DEFAULT",
            ),
        ),
    ]
