# Generated by Django 5.2.6 on 2025-10-08 15:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_aerolinea"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotaDebitoVenezuela",
            fields=[
                (
                    "id_nota_debito",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID Nota Débito"
                    ),
                ),
                (
                    "numero_nota_debito",
                    models.CharField(
                        help_text="Número correlativo de la nota de débito",
                        max_length=50,
                        unique=True,
                        verbose_name="Número Nota Débito",
                    ),
                ),
                (
                    "fecha_emision",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha Emisión"
                    ),
                ),
                (
                    "ganancia_cambiaria_bsd",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monto de la ganancia cambiaria en bolívares",
                        max_digits=15,
                        verbose_name="Ganancia Cambiaria BSD",
                    ),
                ),
                (
                    "monto_iva_bsd",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="IVA sobre la ganancia cambiaria",
                        max_digits=15,
                        verbose_name="IVA 16% BSD",
                    ),
                ),
                (
                    "tasa_factura",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Tasa BCV al momento de la factura",
                        max_digits=12,
                        verbose_name="Tasa Factura",
                    ),
                ),
                (
                    "tasa_pago",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Tasa BCV al momento del pago",
                        max_digits=12,
                        verbose_name="Tasa Pago",
                    ),
                ),
                (
                    "referencia_pago",
                    models.CharField(
                        blank=True,
                        help_text="Referencia del pago que originó la ganancia",
                        max_length=100,
                        verbose_name="Referencia Pago",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("EMI", "Emitida"),
                            ("COB", "Cobrada"),
                            ("ANU", "Anulada"),
                        ],
                        default="EMI",
                        max_length=3,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "factura_origen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notas_debito",
                        to="core.facturavenezuela",
                        verbose_name="Factura Origen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota de Débito Venezuela",
                "verbose_name_plural": "Notas de Débito Venezuela",
                "ordering": ["-fecha_emision"],
            },
        ),
    ]
