# Generated by Django 5.2.6 on 2026-05-09 01:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0016_add_critical_indexes"),
        ("core", "0015_agencia_configuracion_contable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["modelo", "object_id"], name="idx_audit_modelo_object"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["agencia", "creado"], name="idx_audit_agencia_creado"),
        ),
    ]
