# Generated by Django 5.2.6 on 2025-10-19 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_add_nota_debito_venezuela"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, unique=True)),
                ("nombre_comercial", models.CharField(blank=True, max_length=200)),
                (
                    "rif",
                    models.CharField(
                        blank=True,
                        help_text="RIF o identificación fiscal",
                        max_length=20,
                    ),
                ),
                (
                    "iata",
                    models.CharField(
                        blank=True, help_text="Código IATA", max_length=20
                    ),
                ),
                ("telefono_principal", models.CharField(blank=True, max_length=20)),
                ("telefono_secundario", models.CharField(blank=True, max_length=20)),
                ("email_principal", models.EmailField(max_length=254)),
                ("email_soporte", models.EmailField(blank=True, max_length=254)),
                ("email_ventas", models.EmailField(blank=True, max_length=254)),
                ("direccion", models.TextField(blank=True)),
                ("ciudad", models.CharField(blank=True, max_length=100)),
                ("estado", models.CharField(blank=True, max_length=100)),
                ("pais", models.CharField(default="Venezuela", max_length=100)),
                ("codigo_postal", models.CharField(blank=True, max_length=10)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="agencias/logos/"
                    ),
                ),
                (
                    "logo_secundario",
                    models.ImageField(
                        blank=True,
                        help_text="Logo alternativo para documentos",
                        null=True,
                        upload_to="agencias/logos/",
                    ),
                ),
                (
                    "color_primario",
                    models.CharField(
                        default="#1976d2",
                        help_text="Color hex (ej: #1976d2)",
                        max_length=7,
                    ),
                ),
                (
                    "color_secundario",
                    models.CharField(
                        default="#dc004e",
                        help_text="Color hex (ej: #dc004e)",
                        max_length=7,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("facebook", models.URLField(blank=True)),
                ("instagram", models.URLField(blank=True)),
                ("twitter", models.URLField(blank=True)),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True, help_text="Número con código de país", max_length=20
                    ),
                ),
                (
                    "moneda_principal",
                    models.CharField(
                        default="USD", help_text="Código ISO de moneda", max_length=3
                    ),
                ),
                (
                    "timezone",
                    models.CharField(default="America/Caracas", max_length=50),
                ),
                (
                    "idioma",
                    models.CharField(
                        default="es", help_text="Código ISO de idioma", max_length=5
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "propietario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agencias_propias",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agencia",
                "verbose_name_plural": "Agencias",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="UsuarioAgencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("admin", "Administrador"),
                            ("gerente", "Gerente"),
                            ("vendedor", "Vendedor"),
                            ("contador", "Contador"),
                            ("operador", "Operador"),
                            ("consulta", "Solo Consulta"),
                        ],
                        default="vendedor",
                        max_length=20,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_asignacion", models.DateTimeField(auto_now_add=True)),
                (
                    "agencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuarios",
                        to="core.agencia",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agencias",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario de Agencia",
                "verbose_name_plural": "Usuarios de Agencias",
                "ordering": ["agencia", "usuario__username"],
                "unique_together": {("usuario", "agencia")},
            },
        ),
    ]
