# Generated by Django 5.2.6 on 2025-10-20 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_agencia_usuarioagencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="proveedor",
            name="fee_internacional",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Fee por servicios internacionales",
                max_digits=10,
                null=True,
                verbose_name="Fee Internacional",
            ),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="fee_nacional",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Fee por servicios nacionales",
                max_digits=10,
                null=True,
                verbose_name="Fee Nacional",
            ),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="rif",
            field=models.CharField(
                blank=True,
                help_text="Registro de Información Fiscal",
                max_length=20,
                null=True,
                verbose_name="RIF",
            ),
        ),
        migrations.CreateModel(
            name="ComisionProveedorServicio",
            fields=[
                (
                    "id_comision",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID Comisión"
                    ),
                ),
                (
                    "tipo_servicio",
                    models.CharField(
                        choices=[
                            ("AIR", "Boleto Aéreo"),
                            ("HTL", "Alojamiento (Hotel)"),
                            ("PKG", "Paquete Turístico"),
                            ("TOU", "Tour o Actividad"),
                            ("TRF", "Traslado"),
                            ("INS", "Seguro de Viaje"),
                            ("CRU", "Crucero"),
                            ("CAR", "Alquiler de Auto"),
                            ("SVC", "Servicio Adicional"),
                            ("OTR", "Otro"),
                        ],
                        max_length=3,
                        verbose_name="Tipo de Servicio",
                    ),
                ),
                (
                    "comision_porcentaje",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Porcentaje de comisión",
                        max_digits=5,
                        null=True,
                        verbose_name="Comisión (%)",
                    ),
                ),
                (
                    "comision_monto_fijo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monto fijo de comisión",
                        max_digits=10,
                        null=True,
                        verbose_name="Comisión Monto Fijo",
                    ),
                ),
                (
                    "notas",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "moneda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.moneda",
                        verbose_name="Moneda",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comisiones",
                        to="core.proveedor",
                        verbose_name="Proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comisión de Proveedor por Servicio",
                "verbose_name_plural": "Comisiones de Proveedores por Servicios",
                "ordering": ["proveedor__nombre", "tipo_servicio"],
                "unique_together": {("proveedor", "tipo_servicio")},
            },
        ),
    ]
