# Generated by Django 5.2.6 on 2026-05-09 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration:
    """Migración de base de datos generada por Django."""
    dependencies = [
        ("bookings", "0016_add_critical_indexes"),
        ("core", "0017_row_level_security"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnulacionBoleto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_anulacion",
                    models.CharField(
                        choices=[("VOL", "Voluntaria"), ("INV", "Involutaria")],
                        default="VOL",
                        max_length=3,
                    ),
                ),
                ("motivo", models.TextField(blank=True)),
                (
                    "monto_original",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "penalidad_aerolinea",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "fee_agencia",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "monto_reembolso",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("SOL", "Solicitada"),
                            ("APR", "Aprobada"),
                            ("REC", "Rechazada"),
                            ("REE", "Reembolsada"),
                        ],
                        default="SOL",
                        max_length=3,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                ("fecha_solicitud", models.DateTimeField(auto_now_add=True)),
                ("fecha_aprobacion", models.DateTimeField(blank=True, null=True)),
                ("fecha_reembolso", models.DateTimeField(blank=True, null=True)),
                (
                    "agencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="core.agencia",
                    ),
                ),
                (
                    "aprobado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anulaciones_aprobadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "boleto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anulaciones",
                        to="bookings.boletoimportado",
                    ),
                ),
                (
                    "solicitado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anulaciones_solicitadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Anulación",
                "verbose_name_plural": "Anulaciones",
                "ordering": ["-fecha_solicitud"],
            },
        ),
        migrations.CreateModel(
            name="HistorialCambioBoleto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_cambio",
                    models.CharField(
                        choices=[
                            ("PRE", "Precio cambiado"),
                            ("EST", "Estado cambiado"),
                            ("RUT", "Ruta cambiada"),
                            ("FEC", "Fecha cambiada"),
                            ("PAX", "Pasajero cambiado"),
                            ("OTR", "Otro"),
                        ],
                        max_length=3,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("valor_anterior", models.CharField(blank=True, max_length=255)),
                ("valor_nuevo", models.CharField(blank=True, max_length=255)),
                ("fecha_cambio", models.DateTimeField(auto_now_add=True)),
                (
                    "agencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="core.agencia",
                    ),
                ),
                (
                    "boleto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_cambios",
                        to="bookings.boletoimportado",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Cambio",
                "verbose_name_plural": "Historial de Cambios",
                "ordering": ["-fecha_cambio"],
            },
        ),
    ]
