# Generated by Django 5.2.6 on 2025-10-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_proveedor_fee_internacional_proveedor_fee_nacional_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proveedor",
            name="alias",
            field=models.CharField(
                blank=True,
                help_text="Nombre con el que es conocido en el mercado",
                max_length=150,
                null=True,
                verbose_name="Alias/Nombre Comercial",
            ),
        ),
    ]
