# Generated by Django 5.2.6 on 2026-05-09 19:39

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_anulacionboleto_historialcambioboleto"),
    ]

    operations = [
        migrations.CreateModel(
            name="MagicLinkToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "redirect_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("is_onboarding", models.BooleanField(default=False)),
                ("onboarding_data", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Magic Link Token",
                "verbose_name_plural": "Magic Link Tokens",
                "db_table": "core_magiclinktoken",
                "ordering": ["-created_at"],
            },
        ),
    ]
