# Generated by Django 5.2.6 on 2026-05-09 21:33

import core.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_magic_link_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgenciaBranding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="agencias/logos/"
                    ),
                ),
                (
                    "logo_light",
                    models.ImageField(
                        blank=True, null=True, upload_to="agencias/logos/"
                    ),
                ),
                (
                    "logo_dark",
                    models.ImageField(
                        blank=True, null=True, upload_to="agencias/logos/"
                    ),
                ),
                (
                    "logo_secundario",
                    models.ImageField(
                        blank=True, null=True, upload_to="agencias/logos/"
                    ),
                ),
                ("logo_base64", models.TextField(blank=True, null=True)),
                ("logo_pdf_base64", models.TextField(blank=True, null=True)),
                ("logo_pdf_dark_base64", models.TextField(blank=True, null=True)),
                ("color_primario", models.CharField(default="#1976d2", max_length=7)),
                ("color_secundario", models.CharField(default="#88081f", max_length=7)),
                ("color_amadeus", models.CharField(default="#0c66e1", max_length=7)),
                ("color_kiu", models.CharField(default="#0d1e40", max_length=7)),
                ("color_copa", models.CharField(default="#0032a0", max_length=7)),
                ("color_tk_connect", models.CharField(default="#232b38", max_length=7)),
                ("color_wingo", models.CharField(default="#6633cb", max_length=7)),
                ("color_travelport", models.CharField(default="#111827", max_length=7)),
                (
                    "logo_telegram_id",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "logo_telegram_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("eslogan", models.CharField(blank=True, max_length=255)),
                ("pie_pagina", models.TextField(blank=True)),
                ("terminos_condiciones", models.TextField(blank=True)),
                ("ui_theme", models.CharField(default="obsidian", max_length=20)),
                ("plantilla_boletos", models.CharField(default="m1", max_length=2)),
                ("plantilla_vouchers", models.CharField(default="m1", max_length=2)),
                ("plantilla_facturas", models.CharField(default="m1", max_length=2)),
                (
                    "agencia",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branding_v2",
                        to="core.agencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agencia - Branding",
                "verbose_name_plural": "Agencias - Branding",
            },
        ),
        migrations.AddField(
            model_name="agencia",
            name="branding",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agencia_master",
                to="core.agenciabranding",
            ),
        ),
        migrations.CreateModel(
            name="AgenciaConfiguracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("moneda_principal", models.CharField(default="USD", max_length=3)),
                (
                    "zona_horaria",
                    models.CharField(default="America/Caracas", max_length=50),
                ),
                ("idioma", models.CharField(default="es", max_length=5)),
                ("configuracion_correo", models.JSONField(blank=True, default=dict)),
                ("configuracion_api", models.JSONField(blank=True, default=dict)),
                ("configuracion_contable", models.JSONField(blank=True, default=dict)),
                (
                    "correo_emisiones",
                    models.EmailField(blank=True, max_length=255, null=True),
                ),
                (
                    "password_app_correo",
                    core.fields.EncryptedCharField(
                        blank=True, max_length=255, null=True
                    ),
                ),
                (
                    "telegram_bot_token",
                    core.fields.EncryptedCharField(
                        blank=True, max_length=255, null=True
                    ),
                ),
                (
                    "telegram_chat_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "email_monitor_user",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "email_monitor_password",
                    core.fields.EncryptedCharField(
                        blank=True, max_length=255, null=True
                    ),
                ),
                ("email_monitor_active", models.BooleanField(default=False)),
                (
                    "email_monitor_last_check",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "imprenta_digital_nombre",
                    models.CharField(blank=True, max_length=200),
                ),
                ("imprenta_digital_rif", models.CharField(blank=True, max_length=20)),
                (
                    "imprenta_digital_providencia",
                    models.CharField(blank=True, max_length=50),
                ),
                ("es_sujeto_pasivo_especial", models.BooleanField(default=False)),
                ("esta_inscrita_rtn", models.BooleanField(default=False)),
                ("plan", models.CharField(default="FREE", max_length=20)),
                ("limite_mensual_boletos", models.PositiveIntegerField(default=100)),
                ("limite_usuarios", models.IntegerField(default=1)),
                ("limite_ventas_mes", models.IntegerField(default=50)),
                ("ventas_mes_actual", models.IntegerField(default=0)),
                ("plan_status", models.CharField(default="active", max_length=20)),
                ("subscription_end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "fecha_inicio_plan",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("fecha_fin_trial", models.DateField(blank=True, null=True)),
                ("stripe_customer_id", models.CharField(blank=True, max_length=100)),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "subdominio_slug",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("es_demo", models.BooleanField(default=False)),
                ("bi_insights", models.JSONField(blank=True, default=dict)),
                (
                    "agencia",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracion_v2",
                        to="core.agencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agencia - Configuración",
                "verbose_name_plural": "Agencias - Configuraciones",
            },
        ),
        migrations.AddField(
            model_name="agencia",
            name="configuracion",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agencia_master",
                to="core.agenciaconfiguracion",
            ),
        ),
    ]
