# Generated by Django 5.2.6 on 2025-10-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_proveedor_alias"),
    ]

    operations = [
        migrations.AddField(
            model_name="actividadservicio",
            name="localizador_proveedor",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Localizador Proveedor"
            ),
        ),
        migrations.AddField(
            model_name="actividadservicio",
            name="nombre_pasajero",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Nombre Pasajero"
            ),
        ),
        migrations.AddField(
            model_name="alojamientoreserva",
            name="localizador_proveedor",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Localizador Proveedor"
            ),
        ),
        migrations.AddField(
            model_name="alojamientoreserva",
            name="nombre_pasajero",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Nombre Pasajero"
            ),
        ),
        migrations.AddField(
            model_name="alquilerautoreserva",
            name="nombre_conductor",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Nombre Conductor"
            ),
        ),
    ]
