# Generated by Django 5.2.6 on 2025-10-22 17:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_add_passenger_localizador_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agencia",
            old_name="timezone",
            new_name="zona_horaria",
        ),
        migrations.AddField(
            model_name="agencia",
            name="es_demo",
            field=models.BooleanField(
                default=False, help_text="Agencia de demostración"
            ),
        ),
        migrations.AddField(
            model_name="agencia",
            name="fecha_fin_trial",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agencia",
            name="fecha_inicio_plan",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="agencia",
            name="limite_usuarios",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="agencia",
            name="limite_ventas_mes",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="agencia",
            name="plan",
            field=models.CharField(
                choices=[
                    ("FREE", "Gratuito (Trial 30 días)"),
                    ("BASIC", "Básico - $29/mes"),
                    ("PRO", "Profesional - $99/mes"),
                    ("ENTERPRISE", "Enterprise - Personalizado"),
                ],
                default="FREE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="agencia",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="agencia",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="agencia",
            name="ventas_mes_actual",
            field=models.IntegerField(default=0),
        ),
    ]
