# Generated by Django 5.2.6 on 2026-05-10 19:18

from django.db import migrations


class Migration:
    """Migración de base de datos generada por Django."""
    # Edited 2026-06-07: wrap in SeparateDatabaseAndState with
    # database_operations=[] because the tables named in the original
    # AlterModelTable(table=None) operations were already renamed
    # manually (or via pg_dump --schema-only + migrate --fake) in
    # dev/prod. State-only update is safe and idempotent in fresh-DB.

    dependencies = [
        ("core", "0022_remove_agencia_bi_insights_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelTable(
                    name="auditlog",
                    table=None,
                ),
            ],
        ),
    ]
