# Generated by Django 5.2.6 on 2025-10-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_add_facturacion_consolidada"),
    ]

    operations = [
        migrations.AddField(
            model_name="agencia",
            name="es_sujeto_pasivo_especial",
            field=models.BooleanField(
                default=False, help_text="Contribuyente Especial SENIAT"
            ),
        ),
        migrations.AddField(
            model_name="agencia",
            name="esta_inscrita_rtn",
            field=models.BooleanField(
                default=False, help_text="Inscrita en Registro Turístico Nacional"
            ),
        ),
        migrations.AddField(
            model_name="agencia",
            name="imprenta_digital_nombre",
            field=models.CharField(
                blank=True,
                help_text="Razón Social de la Imprenta Digital Autorizada",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="agencia",
            name="imprenta_digital_providencia",
            field=models.CharField(
                blank=True,
                help_text="Número de Providencia SENIAT (ej: SNAT/2024/XXXXX)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="agencia",
            name="imprenta_digital_rif",
            field=models.CharField(
                blank=True, help_text="RIF de la Imprenta Digital", max_length=20
            ),
        ),
    ]
