# Generated by Django 5.2.6 on 2026-05-10 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_remove_agencia_bi_insights_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="auditlog",
            table=None,
        ),
    ]
