# Generated by Django 5.2.6 on 2026-05-10 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_auditlog_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="magiclinktoken",
            table=None,
        ),
    ]
