# Generated by Django 5.2.6 on 2025-10-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_add_retenciones_islr"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="retencionislr",
            new_name="core_retenc_periodo_2fe1fa_idx",
            old_name="core_retenc_periodo_idx",
        ),
        migrations.RenameIndex(
            model_name="retencionislr",
            new_name="core_retenc_estado_4007e3_idx",
            old_name="core_retenc_estado_idx",
        ),
        migrations.RenameIndex(
            model_name="retencionislr",
            new_name="core_retenc_cliente_fe6c85_idx",
            old_name="core_retenc_cliente_idx",
        ),
        migrations.AddField(
            model_name="aerolinea",
            name="codigo_icao",
            field=models.CharField(
                blank=True,
                help_text="Código ICAO de 3 letras",
                max_length=3,
                verbose_name="Código ICAO",
            ),
        ),
        migrations.AddField(
            model_name="aerolinea",
            name="pais_origen",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="País de Origen"
            ),
        ),
        migrations.AddField(
            model_name="aerolinea",
            name="rif",
            field=models.CharField(
                blank=True,
                help_text="RIF venezolano o E-99999999-X para internacionales",
                max_length=20,
                verbose_name="RIF",
            ),
        ),
        migrations.AlterField(
            model_name="aerolinea",
            name="codigo_iata",
            field=models.CharField(
                blank=True,
                help_text="Código IATA de 2 letras de la aerolínea (ej. AA, AV, LA).",
                max_length=3,
                verbose_name="Código IATA",
            ),
        ),
    ]
