# Generated by Django 5.2.6 on 2026-05-11 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration:
    """Migración de base de datos generada por Django."""
    dependencies = [
        ("core", "0024_alter_magiclinktoken_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="CronApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(editable=False, max_length=128, unique=True),
                ),
                (
                    "name",
                    models.CharField(help_text="Ej: cron-job.org BCV sync", max_length=100),
                ),
                (
                    "prefix",
                    models.CharField(
                        editable=False, help_text="Primeros 8 chars para identificar", max_length=12
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "agencia",
                    models.ForeignKey(
                        blank=True,
                        help_text="Si es null, es una key global de plataforma",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.agencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cron API Key",
                "verbose_name_plural": "Cron API Keys",
            },
        ),
    ]
