# Generated by Django 5.2.6 on 2025-10-24 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_add_aerolinea_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="factura_consolidada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ventas_facturadas",
                to="core.facturaconsolidada",
                verbose_name="Factura Consolidada",
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="factura",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ventas",
                to="core.factura",
                verbose_name="Factura Asociada (Legacy)",
            ),
        ),
    ]
