# Generated by Django 5.2.6 on 2026-05-11 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration:
    """Migración de base de datos generada por Django."""
    dependencies = [
        ("core", "0025_cron_api_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(db_index=True, max_length=100)),
                ("enabled", models.BooleanField(default=False)),
                (
                    "rollout_percentage",
                    models.IntegerField(
                        default=100,
                        help_text="0-100. Solo aplica si enabled=True y agencia=None.",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agencia",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null = flag global. Con agencia = flag por tenant.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.agencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Flag",
                "verbose_name_plural": "Feature Flags",
                "unique_together": {("nombre", "agencia")},
            },
        ),
    ]
