# Generated by Django 5.2.6 on 2025-10-24 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_add_venta_factura_consolidada"),
    ]

    operations = [
        migrations.CreateModel(
            name="CruceroReserva",
            fields=[
                (
                    "id_crucero",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID Crucero"
                    ),
                ),
                (
                    "nombre_crucero",
                    models.CharField(
                        help_text="Ej: Caribbean Explorer 7 Noches",
                        max_length=200,
                        verbose_name="Nombre del Crucero",
                    ),
                ),
                (
                    "naviera",
                    models.CharField(
                        help_text="Ej: Royal Caribbean, Carnival, MSC",
                        max_length=150,
                        verbose_name="Naviera/Compañía",
                    ),
                ),
                (
                    "nombre_barco",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Nombre del Barco"
                    ),
                ),
                ("fecha_embarque", models.DateField(verbose_name="Fecha de Embarque")),
                (
                    "fecha_desembarque",
                    models.DateField(verbose_name="Fecha de Desembarque"),
                ),
                (
                    "noches",
                    models.PositiveSmallIntegerField(
                        help_text="Número de noches a bordo", verbose_name="Noches"
                    ),
                ),
                (
                    "puerto_embarque",
                    models.CharField(max_length=150, verbose_name="Puerto de Embarque"),
                ),
                (
                    "puerto_desembarque",
                    models.CharField(
                        max_length=150, verbose_name="Puerto de Desembarque"
                    ),
                ),
                (
                    "puertos_escala",
                    models.JSONField(
                        blank=True,
                        help_text='Lista de puertos: [{"puerto": "Cozumel", "dia": 2, "actividades": "..."}]',
                        null=True,
                        verbose_name="Puertos de Escala",
                    ),
                ),
                (
                    "dias_navegacion",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Días en alta mar sin puerto",
                        verbose_name="Días de Navegación",
                    ),
                ),
                (
                    "tipo_cabina",
                    models.CharField(
                        choices=[
                            ("INT", "Interior (sin ventana)"),
                            ("VEN", "Vista al Mar (con ventana)"),
                            ("BAL", "Balcón Privado"),
                            ("SUI", "Suite"),
                            ("SUP", "Suite Premium"),
                        ],
                        default="BAL",
                        max_length=3,
                        verbose_name="Tipo de Cabina",
                    ),
                ),
                (
                    "numero_cabina",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Número de Cabina"
                    ),
                ),
                (
                    "ubicacion_cabina",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Deck 8, Proa, Popa",
                        max_length=100,
                        verbose_name="Ubicación en el Barco",
                    ),
                ),
                (
                    "clase_cabina",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Deluxe, Premium, Concierge",
                        max_length=50,
                        verbose_name="Clase de Cabina",
                    ),
                ),
                (
                    "numero_pasajeros",
                    models.PositiveSmallIntegerField(
                        default=2, verbose_name="Número de Pasajeros"
                    ),
                ),
                (
                    "nombres_pasajeros",
                    models.TextField(
                        help_text="Uno por línea o separados por coma",
                        verbose_name="Nombres de Pasajeros",
                    ),
                ),
                (
                    "paquete_bebidas",
                    models.BooleanField(
                        default=False, verbose_name="Paquete de Bebidas"
                    ),
                ),
                (
                    "tipo_paquete_bebidas",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Refrescos, Clásico, Premium, Deluxe",
                        max_length=100,
                        verbose_name="Tipo Paquete Bebidas",
                    ),
                ),
                (
                    "costo_paquete_bebidas",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Costo Paquete Bebidas",
                    ),
                ),
                (
                    "paquete_restaurantes",
                    models.BooleanField(
                        default=False, verbose_name="Paquete Restaurantes Especialidad"
                    ),
                ),
                (
                    "detalle_restaurantes",
                    models.TextField(
                        blank=True,
                        help_text="Restaurantes incluidos y menús",
                        verbose_name="Detalle Restaurantes",
                    ),
                ),
                (
                    "costo_paquete_restaurantes",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Costo Paquete Restaurantes",
                    ),
                ),
                (
                    "paquete_spa",
                    models.BooleanField(
                        default=False, verbose_name="Paquete Spa y Bienestar"
                    ),
                ),
                (
                    "detalle_spa",
                    models.TextField(
                        blank=True,
                        help_text="Tratamientos incluidos",
                        verbose_name="Detalle Spa",
                    ),
                ),
                (
                    "costo_paquete_spa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Costo Paquete Spa",
                    ),
                ),
                (
                    "paquete_wifi",
                    models.BooleanField(default=False, verbose_name="Paquete Wi-Fi"),
                ),
                (
                    "tipo_paquete_wifi",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Básico, Premium, Streaming",
                        max_length=100,
                        verbose_name="Tipo Paquete Wi-Fi",
                    ),
                ),
                (
                    "costo_paquete_wifi",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Costo Paquete Wi-Fi",
                    ),
                ),
                (
                    "excursiones_tierra",
                    models.JSONField(
                        blank=True,
                        help_text="Lista de excursiones contratadas por puerto",
                        null=True,
                        verbose_name="Excursiones en Tierra",
                    ),
                ),
                (
                    "pension_completa",
                    models.BooleanField(
                        default=True, verbose_name="Pensión Completa Incluida"
                    ),
                ),
                (
                    "servicios_incluidos",
                    models.TextField(
                        blank=True,
                        help_text="Detalle de lo que incluye la tarifa base",
                        verbose_name="Servicios Incluidos",
                    ),
                ),
                (
                    "servicios_no_incluidos",
                    models.TextField(
                        blank=True,
                        help_text="Ej: Propinas, bebidas alcohólicas, excursiones",
                        verbose_name="Servicios NO Incluidos",
                    ),
                ),
                (
                    "localizador_proveedor",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Localizador Proveedor"
                    ),
                ),
                (
                    "tarifa_base_cabina",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Costo base de la cabina",
                        max_digits=12,
                        null=True,
                        verbose_name="Tarifa Base Cabina",
                    ),
                ),
                (
                    "es_comisionable",
                    models.BooleanField(
                        default=True,
                        help_text="Si el proveedor paga comisión",
                        verbose_name="Es Comisionable",
                    ),
                ),
                (
                    "porcentaje_comision",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Porcentaje de comisión del proveedor",
                        max_digits=5,
                        null=True,
                        verbose_name="% Comisión",
                    ),
                ),
                (
                    "monto_comision",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        help_text="Calculado automáticamente",
                        max_digits=12,
                        null=True,
                        verbose_name="Monto Comisión",
                    ),
                ),
                (
                    "fee_servicio_agencia",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fee que cobra la agencia al cliente",
                        max_digits=12,
                        null=True,
                        verbose_name="Fee Servicio Agencia",
                    ),
                ),
                (
                    "costo_total_proveedor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total a pagar al proveedor",
                        max_digits=12,
                        null=True,
                        verbose_name="Costo Total Proveedor",
                    ),
                ),
                (
                    "precio_venta_cliente",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total que paga el cliente",
                        max_digits=12,
                        null=True,
                        verbose_name="Precio Venta Cliente",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Notas internas sobre la reserva",
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "recomendaciones_cliente",
                    models.TextField(
                        blank=True,
                        help_text="Consejos sobre roaming, propinas, etc.",
                        verbose_name="Recomendaciones al Cliente",
                    ),
                ),
                (
                    "moneda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.moneda",
                        verbose_name="Moneda",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.proveedor",
                        verbose_name="Proveedor/Consolidador",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cruceros",
                        to="core.venta",
                        verbose_name="Venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crucero",
                "verbose_name_plural": "Cruceros",
                "ordering": ["fecha_embarque"],
            },
        ),
    ]
