# Generated by Django 5.2.6 on 2026-05-14 18:48

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "bookings",
            "0023_remove_boletoimportado_bookings_bo_agencia_1abd71_idx_and_more",
        ),
        ("core", "0027_seed_feature_flags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),
        migrations.AlterField(
            model_name="agencia",
            name="activa",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="agenciabranding",
            name="plantilla_boletos",
            field=models.CharField(
                choices=[
                    ("m1", "Modelo Clásico"),
                    ("m2", "Editorial Plus"),
                    ("m3", "Executive Compact"),
                    ("m4", "Timeline Pro"),
                    ("m5", "Modern Digital"),
                ],
                default="m1",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="agenciabranding",
            name="plantilla_facturas",
            field=models.CharField(
                choices=[
                    ("m1", "Modelo Estándar"),
                    ("m2", "Modelo Moderno"),
                    ("m3", "Modelo Minimalista"),
                ],
                default="m1",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="agenciabranding",
            name="plantilla_vouchers",
            field=models.CharField(
                choices=[
                    ("m1", "Modelo Estándar"),
                    ("m2", "Modelo Moderno"),
                    ("m3", "Modelo Minimalista"),
                ],
                default="m1",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="agenciabranding",
            name="ui_theme",
            field=models.CharField(
                choices=[
                    ("obsidian", "Obsidian Emerald"),
                    ("swiss", "Vintage Cream"),
                    ("cyber", "Cyber Fuchsia"),
                    ("nordic", "Nordic Snow"),
                    ("midnight", "Midnight Gold"),
                    ("sunset", "Sunset Rose"),
                ],
                default="obsidian",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="venta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs_central",
                to="bookings.venta",
                verbose_name="Venta Asociada",
            ),
        ),
        migrations.AlterField(
            model_name="usuarioagencia",
            name="activo",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["descripcion"],
                name="idx_audit_desc_gin",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["descripcion"], name="idx_audit_desc_simple"),
        ),
    ]
