# Generated by Django 5.2.6 on 2025-10-24 19:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_add_crucero_reserva"),
    ]

    operations = [
        migrations.CreateModel(
            name="TarifarioProveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "archivo_pdf",
                    models.FileField(
                        blank=True,
                        upload_to="tarifarios/%Y/%m/",
                        verbose_name="Archivo PDF",
                    ),
                ),
                (
                    "fecha_vigencia_inicio",
                    models.DateField(verbose_name="Vigencia Inicio"),
                ),
                ("fecha_vigencia_fin", models.DateField(verbose_name="Vigencia Fin")),
                (
                    "comision_estandar",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("15.00"),
                        max_digits=5,
                        verbose_name="Comisión Estándar %",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "fecha_carga",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Carga"
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifarios",
                        to="core.proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarifario de Proveedor",
                "verbose_name_plural": "Tarifarios de Proveedores",
                "ordering": ["-fecha_carga"],
            },
        ),
        migrations.CreateModel(
            name="HotelTarifario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Nombre del Hotel"),
                ),
                ("destino", models.CharField(max_length=100, verbose_name="Destino")),
                (
                    "ubicacion_descripcion",
                    models.TextField(blank=True, verbose_name="Ubicación"),
                ),
                (
                    "regimen",
                    models.CharField(
                        choices=[
                            ("SO", "Solo Alojamiento"),
                            ("SD", "Solo Desayuno"),
                            ("MP", "Media Pensión"),
                            ("PC", "Pensión Completa"),
                            ("TI", "Todo Incluido"),
                        ],
                        max_length=2,
                        verbose_name="Régimen",
                    ),
                ),
                (
                    "comision",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Comisión %"
                    ),
                ),
                (
                    "politica_ninos",
                    models.TextField(blank=True, verbose_name="Política de Niños"),
                ),
                (
                    "check_in",
                    models.TimeField(default="15:00", verbose_name="Check-in"),
                ),
                (
                    "check_out",
                    models.TimeField(default="12:00", verbose_name="Check-out"),
                ),
                (
                    "minimo_noches_temporada_baja",
                    models.IntegerField(
                        default=1, verbose_name="Mínimo Noches (Temp. Baja)"
                    ),
                ),
                (
                    "minimo_noches_temporada_alta",
                    models.IntegerField(
                        default=2, verbose_name="Mínimo Noches (Temp. Alta)"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "tarifario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hoteles",
                        to="core.tarifarioproveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hotel en Tarifario",
                "verbose_name_plural": "Hoteles en Tarifario",
                "ordering": ["destino", "nombre"],
                "unique_together": {("tarifario", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="TipoHabitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Tipo de Habitación"),
                ),
                (
                    "capacidad_adultos",
                    models.IntegerField(verbose_name="Capacidad Adultos"),
                ),
                (
                    "capacidad_ninos",
                    models.IntegerField(default=0, verbose_name="Capacidad Niños"),
                ),
                (
                    "capacidad_total",
                    models.IntegerField(verbose_name="Capacidad Total"),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tipos_habitacion",
                        to="core.hoteltarifario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Habitación",
                "verbose_name_plural": "Tipos de Habitación",
                "ordering": ["hotel", "nombre"],
                "unique_together": {("hotel", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="TarifaHabitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha Inicio")),
                ("fecha_fin", models.DateField(verbose_name="Fecha Fin")),
                (
                    "nombre_temporada",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Temporada"
                    ),
                ),
                (
                    "tarifa_sgl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Tarifa SGL",
                    ),
                ),
                (
                    "tarifa_dbl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Tarifa DBL",
                    ),
                ),
                (
                    "tarifa_tpl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Tarifa TPL",
                    ),
                ),
                (
                    "tarifa_cdp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Tarifa CDP",
                    ),
                ),
                (
                    "tarifa_qpl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Tarifa QPL",
                    ),
                ),
                (
                    "tarifa_sex_pax",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Tarifa 6 PAX",
                    ),
                ),
                (
                    "tarifa_pax_adicional",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Tarifa PAX Adicional",
                    ),
                ),
                (
                    "tarifa_nino_4_10",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Tarifa Niño 4-10",
                    ),
                ),
                (
                    "tipo_habitacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifas",
                        to="core.tipohabitacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarifa de Habitación",
                "verbose_name_plural": "Tarifas de Habitaciones",
                "ordering": ["tipo_habitacion", "fecha_inicio"],
            },
        ),
    ]
