# Generated by Django 5.2.6 on 2025-10-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_add_tarifario_hoteles"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarifahabitacion",
            name="moneda",
            field=models.CharField(
                choices=[
                    ("USD", "Dólares USD"),
                    ("EUR", "Euros €"),
                    ("VES", "Bolívares Bs"),
                ],
                default="USD",
                max_length=3,
                verbose_name="Moneda",
            ),
        ),
    ]
