# Generated by Django 5.2.6 on 2026-05-14 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration:
    """Migración de base de datos generada por Django."""
    dependencies = [
        ("bookings", "0024_alter_actividadservicio_agencia_and_more"),
        ("core", "0028_alter_agencia_activa_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="anulacionboleto",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
        migrations.AlterField(
            model_name="historialcambioboleto",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["descripcion"], name="core_auditl_descrip_75ff59_idx"),
        ),
    ]
