# Generated by Django 5.2.6 on 2026-05-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_alter_anulacionboleto_agencia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenciaconfiguracion",
            name="email_monitor_host",
            field=models.CharField(default="imap.gmail.com", max_length=255),
        ),
        migrations.AddField(
            model_name="agenciaconfiguracion",
            name="email_monitor_port",
            field=models.PositiveIntegerField(default=993),
        ),
    ]
