# Generated by Django 5.2.6 on 2025-10-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_add_moneda_tarifas"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hoteltarifario",
            name="politica_ninos",
        ),
        migrations.RemoveField(
            model_name="tarifahabitacion",
            name="tarifa_cdp",
        ),
        migrations.RemoveField(
            model_name="tarifahabitacion",
            name="tarifa_nino_4_10",
        ),
        migrations.RemoveField(
            model_name="tarifahabitacion",
            name="tarifa_pax_adicional",
        ),
        migrations.RemoveField(
            model_name="tarifahabitacion",
            name="tarifa_qpl",
        ),
        migrations.RemoveField(
            model_name="tarifahabitacion",
            name="tarifa_sex_pax",
        ),
        migrations.AddField(
            model_name="hoteltarifario",
            name="politicas",
            field=models.TextField(blank=True, verbose_name="Políticas"),
        ),
        migrations.AddField(
            model_name="tarifahabitacion",
            name="tipo_tarifa",
            field=models.CharField(
                choices=[
                    ("POR_PERSONA", "Por Persona por Noche"),
                    ("POR_HABITACION", "Por Habitación por Noche"),
                ],
                default="POR_PERSONA",
                max_length=20,
                verbose_name="Tipo de Tarifa",
            ),
        ),
        migrations.AlterField(
            model_name="tarifahabitacion",
            name="moneda",
            field=models.CharField(
                choices=[("USD", "$ Dólares"), ("EUR", "€ Euros")],
                default="USD",
                max_length=3,
                verbose_name="Moneda",
            ),
        ),
        migrations.AlterField(
            model_name="tarifahabitacion",
            name="tarifa_dbl",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="DBL (Doble)",
            ),
        ),
        migrations.AlterField(
            model_name="tarifahabitacion",
            name="tarifa_sgl",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="SGL (Simple)",
            ),
        ),
        migrations.AlterField(
            model_name="tarifahabitacion",
            name="tarifa_tpl",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="TPL (Triple)",
            ),
        ),
    ]
