# Generated by Django 5.2.6 on 2026-05-16 17:07

from django.db import migrations, models

import core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_agenciaconfiguracion_email_monitor_host_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenciaconfiguracion",
            name="evolution_api_key",
            field=core.fields.EncryptedCharField(
                blank=True,
                help_text="API Key global de Evolution",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agenciaconfiguracion",
            name="evolution_api_url",
            field=models.URLField(
                blank=True,
                help_text="Base URL de Evolution API (ej: http://evolution:8080)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agenciaconfiguracion",
            name="evolution_instance_name",
            field=models.CharField(
                blank=True,
                help_text="Nombre de la instancia de WhatsApp",
                max_length=255,
                null=True,
            ),
        ),
    ]
