# Generated by Django 5.2.6 on 2025-11-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_remove_hoteltarifario_politica_ninos_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boletoimportado",
            name="localizador_pnr",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Localizador (PNR)"
            ),
        ),
    ]
