# Generated by Django 5.2.6 on 2025-11-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_alter_boletoimportado_localizador_pnr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boletoimportado",
            name="formato_detectado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PDF_KIU", "PDF (KIU)"),
                    ("PDF_SAB", "PDF (Sabre)"),
                    ("PDF_AMA", "PDF (Amadeus)"),
                    ("TXT_KIU", "TXT (KIU)"),
                    ("TXT_SAB", "TXT (Sabre)"),
                    ("TXT_AMA", "TXT (Amadeus)"),
                    ("EML_KIU", "EML (KIU)"),
                    ("EML_GEN", "EML (General)"),
                    ("OTR", "Otro/Desconocido"),
                    ("ERR", "Error de Formato"),
                ],
                default="OTR",
                max_length=20,
                verbose_name="Formato Detectado",
            ),
        ),
    ]
