# Generated by Django 5.2.6 on 2026-05-19 11:37

from django.db import migrations

import core.fields


class Migration:
    """Migración de base de datos generada por Django."""
    dependencies = [
        ("core", "0031_agenciaconfiguracion_evolution_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenciaconfiguracion",
            name="gemini_api_key",
            field=core.fields.EncryptedCharField(
                blank=True,
                help_text="Clave API de Gemini específica para esta agencia",
                max_length=255,
                null=True,
            ),
        ),
    ]
