# Generated by Django 5.2.6 on 2025-11-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_aumentar_formato_detectado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boletoimportado",
            name="aerolinea_emisora",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Aerolínea Emisora"
            ),
        ),
        migrations.AlterField(
            model_name="boletoimportado",
            name="agente_emisor",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Agente Emisor"
            ),
        ),
    ]
