# Generated by Django 5.2.6 on 2026-05-23 02:09

from django.db import migrations, models


class Migration:
    """Migración de base de datos generada por Django."""
    dependencies = [
        ("core", "0032_agenciaconfiguracion_gemini_api_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="agencia",
            name="dominio_personalizado",
            field=models.CharField(
                blank=True,
                help_text="Dominio corporativo personalizado (ej: viajes.humboldt.com)",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
