# Generated by Django 5.2.6 on 2026-05-28 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_agencia_dominio_personalizado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anulacionboleto",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
        migrations.AlterField(
            model_name="historialcambioboleto",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
    ]
