# Generated by Django 5.2.6 on 2025-11-11 22:47

import core.storage
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_aumentar_max_length_archivo_boleto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boletoimportado",
            name="archivo_boleto",
            field=models.FileField(
                blank=True,
                help_text="Suba el archivo del boleto en formato PDF, TXT o EML (máx 5MB).",
                max_length=255,
                null=True,
                storage=core.storage.RawFileStorage,
                upload_to="boletos_importados/%Y/%m/",
                validators=[
                    core.validators.validate_file_size,
                    core.validators.validate_file_extension,
                    core.validators.antivirus_hook,
                ],
                verbose_name="Archivo del Boleto (.pdf, .txt, .eml)",
            ),
        ),
        migrations.AlterField(
            model_name="boletoimportado",
            name="archivo_pdf_generado",
            field=models.FileField(
                blank=True,
                help_text="El archivo PDF del boleto unificado, generado automáticamente.",
                max_length=255,
                null=True,
                storage=core.storage.RawFileStorage,
                upload_to="boletos_generados/%Y/%m/",
                verbose_name="PDF Unificado Generado",
            ),
        ),
    ]
