# Generated by Django 5.2.6 on 2026-06-02 02:54

from django.db import migrations, models


class Migration:
    """Migración de base de datos generada por Django."""
    dependencies = [
        ("core", "0034_alter_anulacionboleto_agencia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agenciabranding",
            name="plantilla_facturas",
            field=models.CharField(
                choices=[
                    ("m1", "Modelo Clásico"),
                    ("m2", "Editorial Plus"),
                    ("m3", "Executive Compact"),
                    ("m4", "Timeline Pro"),
                    ("m5", "Modern Digital"),
                ],
                default="m1",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="agenciabranding",
            name="plantilla_vouchers",
            field=models.CharField(
                choices=[
                    ("m1", "Modelo Clásico"),
                    ("m2", "Editorial Plus"),
                    ("m3", "Executive Compact"),
                    ("m4", "Timeline Pro"),
                    ("m5", "Modern Digital"),
                ],
                default="m1",
                max_length=2,
            ),
        ),
    ]
