# Generated by Django 5.2.6 on 2025-11-15 01:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_alter_boletoimportado_archivo_boleto_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnulacionBoleto",
            fields=[
                ("id_anulacion", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo_anulacion",
                    models.CharField(
                        choices=[
                            ("VOL", "Voluntaria"),
                            ("INV", "Involuntaria"),
                            ("CAM", "Cambio de Itinerario"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("SOL", "Solicitada"),
                            ("PRO", "En Proceso"),
                            ("APR", "Aprobada"),
                            ("REC", "Rechazada"),
                            ("REE", "Reembolsada"),
                        ],
                        default="SOL",
                        max_length=3,
                    ),
                ),
                ("motivo", models.TextField(verbose_name="Motivo de Anulación")),
                (
                    "monto_original",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "penalidad_aerolinea",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "fee_agencia",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "monto_reembolso",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                ("fecha_solicitud", models.DateTimeField(auto_now_add=True)),
                ("fecha_aprobacion", models.DateTimeField(blank=True, null=True)),
                ("fecha_reembolso", models.DateTimeField(blank=True, null=True)),
                ("notas", models.TextField(blank=True)),
                (
                    "aprobado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anulaciones_aprobadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "boleto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anulaciones",
                        to="core.boletoimportado",
                    ),
                ),
                (
                    "solicitado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anulaciones_solicitadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Anulación de Boleto",
                "verbose_name_plural": "Anulaciones de Boletos",
                "ordering": ["-fecha_solicitud"],
            },
        ),
        migrations.CreateModel(
            name="HistorialCambioBoleto",
            fields=[
                ("id_historial", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo_cambio",
                    models.CharField(
                        choices=[
                            ("CF", "Cambio de Fecha"),
                            ("CP", "Cambio de Pasajero"),
                            ("RE", "Reemisión"),
                            ("CA", "Cancelación"),
                            ("CO", "Corrección"),
                            ("OT", "Otro"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(verbose_name="Descripción del Cambio"),
                ),
                ("datos_anteriores", models.JSONField(blank=True, null=True)),
                ("datos_nuevos", models.JSONField(blank=True, null=True)),
                (
                    "costo_cambio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Costo cobrado por el cambio",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "penalidad",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Penalidad aplicada",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("fecha_cambio", models.DateTimeField(auto_now_add=True)),
                (
                    "boleto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_cambios",
                        to="core.boletoimportado",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Cambio de Boleto",
                "verbose_name_plural": "Historial de Cambios de Boletos",
                "ordering": ["-fecha_cambio"],
            },
        ),
    ]
