# Generated by Django 5.2.14 on 2026-06-08 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration:
    """Migración de base de datos generada por Django."""
    dependencies = [
        ("core", "0035_agencia_mixin_finance_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agenciabranding",
            name="agencia",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="branding_v2",
                to="core.agencia",
            ),
        ),
        migrations.AlterField(
            model_name="agenciaconfiguracion",
            name="agencia",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="configuracion_v2",
                to="core.agencia",
            ),
        ),
    ]
