# Generated by Django 5.2.6 on 2025-11-25 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_boletoimportado_agencia"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitudAnulacion",
            fields=[
                (
                    "id_anulacion",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID Anulación"
                    ),
                ),
                (
                    "tipo_anulacion",
                    models.CharField(
                        choices=[
                            ("VOL", "Voluntaria"),
                            ("INV", "Involuntaria"),
                            ("CAM", "Cambio de Itinerario"),
                            ("OTR", "Otro"),
                        ],
                        default="VOL",
                        max_length=3,
                        verbose_name="Tipo Anulación",
                    ),
                ),
                ("motivo", models.TextField(verbose_name="Motivo")),
                (
                    "monto_original",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto Original"
                    ),
                ),
                (
                    "penalidad_aerolinea",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Penalidad Aerolínea",
                    ),
                ),
                (
                    "fee_agencia",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Fee Agencia",
                    ),
                ),
                (
                    "monto_reembolso",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Monto a Reembolsar",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PEN", "Pendiente"),
                            ("APR", "Aprobada"),
                            ("REC", "Rechazada"),
                            ("PRO", "Procesada"),
                        ],
                        default="PEN",
                        max_length=3,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_solicitud",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Solicitud"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Actualización"
                    ),
                ),
                (
                    "boleto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes_anulacion",
                        to="core.boletoimportado",
                        verbose_name="Boleto",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Solicitado Por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Anulación",
                "verbose_name_plural": "Solicitudes de Anulación",
                "ordering": ["-fecha_solicitud"],
            },
        ),
    ]
