# Generated by Django 5.2.6 on 2025-11-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_solicitudanulacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="AerolineaConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre Comercial"),
                ),
                (
                    "identificador_parser",
                    models.CharField(
                        help_text="Texto exacto que aparece en el boleto (ej: LASER, AVIOR)",
                        max_length=100,
                        verbose_name="Identificador en Parser",
                    ),
                ),
                (
                    "porcentaje_comision",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="% Comisión Estándar",
                    ),
                ),
                (
                    "porcentaje_retencion_iata",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Si aplica algún descuento automático",
                        max_digits=5,
                        verbose_name="% Retención IATA",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración Aerolínea",
                "verbose_name_plural": "Configuraciones Aerolíneas",
            },
        ),
    ]
