# Generated by Django 5.2.14 on 2026-06-12 11:17

from django.db import migrations, models


class Migration:
    """Migración de base de datos generada por Django."""
    dependencies = [
        ("core", "0039_merge_core_0037_0038"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aeropuerto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_iata",
                    models.CharField(
                        db_index=True,
                        max_length=3,
                        unique=True,
                        verbose_name="Código IATA",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=150, verbose_name="Nombre del Aeropuerto"),
                ),
                (
                    "ciudad",
                    models.CharField(db_index=True, max_length=150, verbose_name="Ciudad"),
                ),
                (
                    "pais",
                    models.CharField(db_index=True, max_length=100, verbose_name="País"),
                ),
                (
                    "pais_codigo",
                    models.CharField(db_index=True, max_length=2, verbose_name="Código de País"),
                ),
                ("latitud", models.FloatField(verbose_name="Latitud")),
                ("longitud", models.FloatField(verbose_name="Longitud")),
                (
                    "es_principal",
                    models.BooleanField(default=False, verbose_name="¿Es Aeropuerto Principal?"),
                ),
            ],
            options={
                "verbose_name": "Aeropuerto",
                "verbose_name_plural": "Aeropuertos",
                "ordering": ["pais", "ciudad", "nombre"],
            },
        ),
    ]
