# Generated by Django 5.2.6 on 2025-11-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_aerolineaconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="agencia",
            name="configuracion_api",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Claves de API: WHATSAPP_TOKEN, BCV_TOKEN, etc.",
            ),
        ),
        migrations.AddField(
            model_name="agencia",
            name="configuracion_correo",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Configuración SMTP: EMAIL_HOST, EMAIL_PORT, EMAIL_HOST_USER, EMAIL_HOST_PASSWORD",
            ),
        ),
    ]
