# Generated by Django 5.2.6 on 2025-12-17 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_agencia_configuracion_api_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boletoimportado",
            name="venta_asociada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="boletos_adjuntos",
                to="core.venta",
                verbose_name="Venta/Reserva Asociada",
            ),
        ),
    ]
