# Generated by Django 5.2.6 on 2025-12-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_alter_boletoimportado_venta_asociada"),
    ]

    operations = [
        migrations.AddField(
            model_name="boletoimportado",
            name="campo_fantasma_prueba",
            field=models.IntegerField(default=0, verbose_name="SI ME VES FUNCIONO"),
        ),
    ]
