# Generated by Django 5.2.14 on 2026-06-24 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration:
    """Migración de base de datos generada por Django."""
    dependencies = [
        ("core", "0042_agenciaconfiguracion_canal_notificaciones_mailbot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuarioagencia",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarios",
                to="core.agencia",
            ),
        ),
        migrations.AlterField(
            model_name="usuarioagencia",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agencias",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
