# Generated by Django 5.2.14 on 2026-06-30 14:45

from django.db import migrations, models


class Migration:
    """Migración de base de datos generada por Django."""
    dependencies = [
        ("core", "0043_alter_usuarioagencia_agencia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agenciaconfiguracion",
            name="evolution_api_url",
            field=models.CharField(
                blank=True,
                help_text="Base URL de Evolution API (ej: http://evolution:8080)",
                max_length=500,
                null=True,
            ),
        ),
    ]
