# Generated by Django 5.2.6 on 2025-12-17 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_boletoimportado_campo_fantasma_prueba"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boletoimportado",
            name="campo_fantasma_prueba",
        ),
    ]
