# Generated by Django 5.2.6 on 2025-12-19 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_remove_boletoimportado_campo_fantasma_prueba"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="nombre_cliente_manual",
            field=models.CharField(
                blank=True,
                help_text="Usar si el cliente no está registrado aún.",
                max_length=150,
                null=True,
                verbose_name="Nombre Cliente (Prospecto)",
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.cliente",
                verbose_name="Cliente",
            ),
        ),
    ]
