# Generated by Django 5.2.6 on 2025-12-19 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_cotizacion_nombre_cliente_manual_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="consultor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consultor_cotizaciones",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Consultor",
            ),
        ),
    ]
