# Generated by Django 5.2.6 on 2025-12-21 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_cotizacion_consultor"),
    ]

    operations = [
        migrations.AddField(
            model_name="boletoimportado",
            name="inatur_monto",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Monto Inatur (1%)",
            ),
        ),
        migrations.AddField(
            model_name="boletoimportado",
            name="iva_monto",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Monto IVA",
            ),
        ),
        migrations.AddField(
            model_name="boletoimportado",
            name="otros_impuestos_monto",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Otros Impuestos",
            ),
        ),
        migrations.AddField(
            model_name="boletoimportado",
            name="proveedor_emisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.proveedor",
                verbose_name="Proveedor Emisor (Consolidador/Aerolínea)",
            ),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="identificadores_gds",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Ej: {'IATA': ['12345678'], 'KIU_OFFICE_ID': ['CCS123']}",
                null=True,
                verbose_name="Identificadores GDS (IATA/OfficeID)",
            ),
        ),
    ]
