# Generated by Django 5.2.6 on 2025-12-21 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_boletoimportado_inatur_monto_and_more"),
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentoexportacion",
            name="factura",
        ),
        migrations.RemoveField(
            model_name="facturavenezuela",
            name="factura_ptr",
        ),
        migrations.RemoveField(
            model_name="notadebitovenezuela",
            name="factura_origen",
        ),
        migrations.RemoveField(
            model_name="itemfacturavenezuela",
            name="itemfactura_ptr",
        ),
        migrations.DeleteModel(
            name="DocumentoExportacion",
        ),
        migrations.DeleteModel(
            name="NotaDebitoVenezuela",
        ),
        migrations.DeleteModel(
            name="ItemFacturaVenezuela",
        ),
        migrations.DeleteModel(
            name="FacturaVenezuela",
        ),
        migrations.AddField(
            model_name="factura",
            name="base_exenta",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Base Exenta"
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="base_imponible",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Base Imponible (Gravada)",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="cliente_direccion",
            field=models.TextField(blank=True, verbose_name="Dirección Fiscal Cliente"),
        ),
        migrations.AddField(
            model_name="factura",
            name="cliente_nombre",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Nombre/Razón Social Cliente"
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="cliente_rif",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="RIF/Documento Cliente"
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="cliente_telefono",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Teléfono Cliente"
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="factura_asociada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documentos_relacionados",
                to="core.factura",
                verbose_name="Factura Asociada (Para ND/NC)",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="igtf_monto",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Impuesto a Grandes Transacciones Financieras (si aplica).",
                max_digits=12,
                verbose_name="Monto IGTF",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="igtf_porcentaje",
            field=models.DecimalField(
                decimal_places=2, default=3, max_digits=5, verbose_name="% IGTF"
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="inatur_monto",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Contribución parafiscal Turismo (1%).",
                max_digits=12,
                verbose_name="Monto INATUR",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="inatur_porcentaje",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=5, verbose_name="% INATUR"
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="iva_monto",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Monto IVA"
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="iva_porcentaje",
            field=models.DecimalField(
                decimal_places=2, default=16, max_digits=5, verbose_name="% IVA"
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="moneda_transaccion",
            field=models.CharField(
                default="USD",
                help_text="Moneda en la que se pagó",
                max_length=3,
                verbose_name="Moneda Transacción",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="numero_control",
            field=models.CharField(
                blank=True,
                help_text="Número de Control Fiscal obligatorio.",
                max_length=50,
                null=True,
                verbose_name="Número de Control",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="tasa_cambio",
            field=models.DecimalField(
                decimal_places=4,
                default=1,
                help_text="Tasa de cambio vigente a la fecha de emisión.",
                max_digits=12,
                verbose_name="Tasa de Cambio (BCV)",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="tipo_factura",
            field=models.CharField(
                choices=[
                    ("PRO", "Factura Propia (Comisión/Servicios)"),
                    ("TER", "Factura por Cuenta de Terceros (Boletos)"),
                    ("ND", "Nota de Débito"),
                    ("NC", "Nota de Crédito"),
                ],
                default="PRO",
                max_length=3,
                verbose_name="Tipo de Factura",
            ),
        ),
        migrations.AddField(
            model_name="itemfactura",
            name="tipo_impuesto",
            field=models.CharField(
                choices=[
                    ("16", "IVA General (16%)"),
                    ("08", "IVA Reducido (8%)"),
                    ("00", "Exento / No Sujeto"),
                ],
                default="16",
                max_length=2,
                verbose_name="Tipo Impuesto",
            ),
        ),
        migrations.AddIndex(
            model_name="factura",
            index=models.Index(
                fields=["numero_factura"], name="core_factur_numero__4980ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factura",
            index=models.Index(
                fields=["numero_control"], name="core_factur_numero__1af612_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factura",
            index=models.Index(
                fields=["fecha_emision"], name="core_factur_fecha_e_f7be26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factura",
            index=models.Index(
                fields=["tipo_factura"], name="core_factur_tipo_fa_26c852_idx"
            ),
        ),
    ]
