# Generated by Django 5.2.6 on 2025-12-30 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_remove_documentoexportacion_factura_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="destino",
            field=models.CharField(
                blank=True,
                help_text="Ciudad o lugar principal del viaje.",
                max_length=150,
                null=True,
                verbose_name="Destino Principal",
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.cliente",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="pasaporteescaneado",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="retencionislr",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="core.cliente",
                verbose_name="Cliente (Agente de Retención)",
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.cliente",
                verbose_name="Cliente (Pagador)",
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="cotizacion_origen",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.cotizacion",
                verbose_name="Cotización de Origen",
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="pasajeros",
            field=models.ManyToManyField(
                related_name="ventas", to="core.pasajero", verbose_name="Pasajeros"
            ),
        ),
    ]
