# Generated by Django 5.2.14 on 2026-07-14 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0049_remove_apikey_agencia_remove_apikey_user_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NumberingSequence",
        ),
    ]
