# Generated by Django 5.2.6 on 2025-12-31 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_cotizacion_destino_alter_factura_cliente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="tasa_cambio_bcv",
            field=models.DecimalField(
                decimal_places=4,
                default=1,
                help_text="Tasa oficial BCV para la fecha de venta.",
                max_digits=12,
                verbose_name="Tasa de Cambio (BCV)",
            ),
        ),
    ]
