# Generated by Django 5.2.6 on 2025-12-31 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_venta_tasa_cambio_bcv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facturaconsolidada",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="core.cliente",
                verbose_name="Cliente",
            ),
        ),
    ]
