# Generated by Django 5.2.14 on 2026-07-15 04:35

from django.db import migrations, models


class Migration:
    """Migración de base de datos generada por Django."""
    dependencies = [
        ("core", "0050_delete_numberingsequence"),
    ]

    operations = [
        migrations.AddField(
            model_name="cronapikey",
            name="salt",
            field=models.CharField(
                default="",
                editable=False,
                help_text="Salt aleatorio para PBKDF2 (hex). Vacío para keys legacy.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="cronapikey",
            name="key_hash",
            field=models.CharField(editable=False, max_length=256, unique=True),
        ),
        migrations.DeleteModel(
            name="SSOProvider",
        ),
    ]
