# Generated by Django 5.2.6 on 2025-12-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_alter_facturaconsolidada_cliente"),
    ]

    operations = [
        migrations.AddField(
            model_name="agencia",
            name="email_monitor_active",
            field=models.BooleanField(
                default=False, help_text="Activar monitoreo automático"
            ),
        ),
        migrations.AddField(
            model_name="agencia",
            name="email_monitor_last_check",
            field=models.DateTimeField(
                blank=True, help_text="Último chequeo realizado", null=True
            ),
        ),
        migrations.AddField(
            model_name="agencia",
            name="email_monitor_password",
            field=models.CharField(
                blank=True,
                help_text="Contraseña de Aplicación de Google (o Token)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agencia",
            name="email_monitor_user",
            field=models.EmailField(
                blank=True,
                help_text="Email a monitorear para boletos (Gmail)",
                max_length=254,
                null=True,
            ),
        ),
    ]
