# Generated by Django 5.2.6 on 2026-01-02 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_agencia_email_monitor_active_and_more"),
        (
            "cotizaciones",
            "0003_cotizacion_email_enviado_cotizacion_fecha_envio_and_more",
        ),
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factura",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="crm.cliente",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="pasaporteescaneado",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crm.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="retencionislr",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="crm.cliente",
                verbose_name="Cliente (Agente de Retención)",
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="crm.cliente",
                verbose_name="Cliente (Pagador)",
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="cotizacion_origen",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cotizaciones.cotizacion",
                verbose_name="Cotización de Origen",
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="pasajeros",
            field=models.ManyToManyField(
                related_name="ventas", to="crm.pasajero", verbose_name="Pasajeros"
            ),
        ),
    ]
