# Generated by Django 5.2.14 on 2026-07-15 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0052_cronapikey_lookup_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="SSOProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("azure_ad", "Azure AD (OIDC)"),
                            ("okta_oidc", "Okta (OIDC)"),
                            ("okta_saml", "Okta (SAML)"),
                            ("google_oidc", "Google Workspace (OIDC)"),
                            ("generic_oidc", "Generic OIDC"),
                            ("generic_saml", "Generic SAML 2.0"),
                        ],
                        help_text="Tipo de proveedor de identidad",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre descriptivo (ej: 'Okta TravelHub')",
                        max_length=100,
                    ),
                ),
                (
                    "client_id",
                    models.CharField(
                        blank=True,
                        help_text="Client ID (OIDC) / SAML Entity ID",
                        max_length=512,
                    ),
                ),
                (
                    "client_secret",
                    models.CharField(
                        blank=True,
                        help_text="Client Secret (OIDC solamente)",
                        max_length=512,
                    ),
                ),
                (
                    "oidc_config_url",
                    models.URLField(
                        blank=True,
                        help_text="OIDC Discovery URL (ej: https://login.microsoftonline.com/{tenant}/v2.0/.well-known/openid-configuration)",
                        max_length=512,
                    ),
                ),
                (
                    "saml_entity_id",
                    models.CharField(
                        blank=True, help_text="SAML Entity ID / Issuer", max_length=512
                    ),
                ),
                (
                    "saml_acs_url",
                    models.URLField(
                        blank=True,
                        help_text="SAML Assertion Consumer Service URL",
                        max_length=512,
                    ),
                ),
                (
                    "saml_x509_cert",
                    models.TextField(
                        blank=True, help_text="Certificado X.509 público del IdP (SAML)"
                    ),
                ),
                (
                    "email_attribute",
                    models.CharField(
                        default="email",
                        help_text="Atributo que contiene el email del usuario",
                        max_length=64,
                    ),
                ),
                (
                    "name_attribute",
                    models.CharField(
                        default="name",
                        help_text="Atributo que contiene el nombre completo",
                        max_length=64,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "auto_provision",
                    models.BooleanField(
                        default=True,
                        help_text="Crear usuario automáticamente si no existe",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sso_providers",
                        to="core.agencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proveedor SSO",
                "verbose_name_plural": "Proveedores SSO",
                "indexes": [
                    models.Index(
                        fields=["agencia", "is_active"],
                        name="core_ssopro_agencia_f135b4_idx",
                    )
                ],
                "unique_together": {("agencia", "provider_type", "client_id")},
            },
        ),
    ]
