# Generated by Django 5.2.6 on 2026-01-11 16:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_alter_factura_cliente_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "icono_lucide",
                    models.CharField(
                        default="check",
                        help_text="Nombre del icono de Lucide React",
                        max_length=50,
                        verbose_name="Icono Lucide",
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="hoteltarifario",
            options={
                "ordering": ["destino", "nombre"],
                "verbose_name": "Hotel",
                "verbose_name_plural": "Hoteles",
            },
        ),
        migrations.AlterUniqueTogether(
            name="hoteltarifario",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="hoteltarifario",
            name="categoria",
            field=models.IntegerField(
                choices=[
                    (1, "Eco / Posada"),
                    (2, "Estandar"),
                    (3, "Confort"),
                    (4, "Lujo"),
                    (5, "Gran Lujo / Premium"),
                ],
                default=3,
                verbose_name="Categoría",
            ),
        ),
        migrations.AddField(
            model_name="hoteltarifario",
            name="coordenadas_mapa",
            field=models.CharField(
                blank=True, help_text="Lat,Long para Google Maps", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="hoteltarifario",
            name="descripcion_corta",
            field=models.TextField(
                blank=True, help_text="Para listados", verbose_name="Descripción Corta"
            ),
        ),
        migrations.AddField(
            model_name="hoteltarifario",
            name="descripcion_larga",
            field=models.TextField(
                blank=True, verbose_name="Descripción Completa (IA)"
            ),
        ),
        migrations.AddField(
            model_name="hoteltarifario",
            name="destacado",
            field=models.BooleanField(default=False, verbose_name="Destacado (Home)"),
        ),
        migrations.AddField(
            model_name="hoteltarifario",
            name="direccion",
            field=models.TextField(blank=True, verbose_name="Dirección Completa"),
        ),
        migrations.AddField(
            model_name="hoteltarifario",
            name="imagen_principal",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="hoteles/portadas/",
                verbose_name="Imagen Portada",
            ),
        ),
        migrations.AddField(
            model_name="hoteltarifario",
            name="regimen_default",
            field=models.CharField(
                choices=[
                    ("SO", "Solo Alojamiento"),
                    ("SD", "Solo Desayuno"),
                    ("MP", "Media Pensión"),
                    ("PC", "Pensión Completa"),
                    ("TI", "Todo Incluido"),
                ],
                default="SD",
                max_length=2,
                verbose_name="Régimen Principal",
            ),
        ),
        migrations.AddField(
            model_name="hoteltarifario",
            name="slug",
            field=models.SlugField(
                blank=True, help_text="URL amigable", max_length=250, null=True
            ),
        ),
        migrations.AddField(
            model_name="pasajero",
            name="preferencias",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Preferencias"
            ),
        ),
        migrations.AddField(
            model_name="tarifahabitacion",
            name="tarifa_cpl",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="CPL (Cuadruple)",
            ),
        ),
        migrations.AddField(
            model_name="tarifahabitacion",
            name="tarifa_nino",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Tarifa Niño",
            ),
        ),
        migrations.AddField(
            model_name="tipohabitacion",
            name="foto_referencial",
            field=models.ImageField(
                blank=True, null=True, upload_to="hoteles/habitaciones/"
            ),
        ),
        migrations.AlterField(
            model_name="hoteltarifario",
            name="comision",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10.00"),
                max_digits=5,
                verbose_name="Comisión %",
            ),
        ),
        migrations.AlterField(
            model_name="hoteltarifario",
            name="tarifario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hoteles",
                to="core.tarifarioproveedor",
            ),
        ),
        migrations.AlterField(
            model_name="tipohabitacion",
            name="capacidad_adultos",
            field=models.IntegerField(default=2, verbose_name="Max Adultos"),
        ),
        migrations.AlterField(
            model_name="tipohabitacion",
            name="capacidad_ninos",
            field=models.IntegerField(default=1, verbose_name="Max Niños"),
        ),
        migrations.AlterField(
            model_name="tipohabitacion",
            name="capacidad_total",
            field=models.IntegerField(default=3, verbose_name="Max Total"),
        ),
        migrations.AddField(
            model_name="hoteltarifario",
            name="amenidades",
            field=models.ManyToManyField(
                blank=True, related_name="hoteles", to="core.amenity"
            ),
        ),
        migrations.CreateModel(
            name="ImagenHotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagen", models.ImageField(upload_to="hoteles/galeria/")),
                ("titulo", models.CharField(blank=True, max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General"),
                            ("HABITACION", "Habitación"),
                            ("COMIDA", "Restaurante/Comida"),
                            ("PLAYA", "Playa/Piscina"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                ("es_portada", models.BooleanField(default=False)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes",
                        to="core.hoteltarifario",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="hoteltarifario",
            name="minimo_noches_temporada_alta",
        ),
        migrations.RemoveField(
            model_name="hoteltarifario",
            name="minimo_noches_temporada_baja",
        ),
        migrations.RemoveField(
            model_name="hoteltarifario",
            name="regimen",
        ),
        migrations.RemoveField(
            model_name="hoteltarifario",
            name="ubicacion_descripcion",
        ),
    ]
