# Generated by Django 5.2.6 on 2026-01-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_amenity_alter_hoteltarifario_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hoteltarifario",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL amigable",
                max_length=250,
                null=True,
                unique=True,
            ),
        ),
    ]
