# Generated by Django 5.2.14 on 2026-07-22 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration:
    """Migración de base de datos generada por Django."""

    dependencies = [
        ('core', '0054_agencia_whitelabel_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL que recibirá las notificaciones POST', max_length=500)),
                ('events', models.JSONField(blank=True, default=list, help_text="Lista de eventos a escuchar (EJ: ['venta.creada', 'pago.confirmado'])")),
                ('secret', models.CharField(editable=False, help_text='Secret para firmar payloads (HMAC-SHA256)', max_length=64)),
                ('is_active', models.BooleanField(default=True, help_text='Pausar/reanudar sin eliminar')),
                ('description', models.CharField(blank=True, default='', help_text='Descripción del webhook', max_length=200)),
                ('last_triggered_at', models.DateTimeField(blank=True, help_text='Último intento de envío', null=True)),
                ('last_success_at', models.DateTimeField(blank=True, help_text='Último envío exitoso', null=True)),
                ('failure_count', models.PositiveIntegerField(default=0, help_text='Contador de fallos consecutivos')),
                ('total_deliveries', models.PositiveIntegerField(default=0, help_text='Total de entregas exitosas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agencia', models.ForeignKey(help_text='Agencia propietaria del webhook', on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='core.agencia')),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField(help_text='Payload enviado al webhook')),
                ('response_status', models.PositiveIntegerField(blank=True, help_text='HTTP status code de la respuesta', null=True)),
                ('response_body', models.TextField(blank=True, default='', help_text='Primeros 1000 chars de la respuesta', max_length=1000)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='Duración del request en milisegundos', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='core.webhook')),
            ],
            options={
                'verbose_name': 'Webhook Delivery',
                'verbose_name_plural': 'Webhook Deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='webhook',
            index=models.Index(fields=['agencia', 'is_active'], name='idx_webhook_agencia'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['webhook', 'success'], name='idx_webhook_del_success'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['created_at'], name='idx_webhook_del_date'),
        ),
    ]
