# Generated by Django 5.2.6 on 2026-01-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_alter_hoteltarifario_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="hoteltarifario",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="hoteles/logos/",
                verbose_name="Logo del Hotel",
            ),
        ),
        migrations.AddField(
            model_name="hoteltarifario",
            name="video_promocional",
            field=models.FileField(
                blank=True,
                help_text="Video corto para la ficha del hotel",
                null=True,
                upload_to="hoteles/videos/",
                verbose_name="Video Promocional",
            ),
        ),
    ]
