# Generated by Django 5.2.6 on 2026-01-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_hoteltarifario_logo_hoteltarifario_video_promocional"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagoventa",
            name="aplica_igtf",
            field=models.BooleanField(
                default=False,
                help_text="Impuesto a Grandes Transacciones Financieras (Divisas)",
                verbose_name="Aplica IGTF (3%)",
            ),
        ),
        migrations.AddField(
            model_name="pagoventa",
            name="monto_igtf",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Monto IGTF"
            ),
        ),
        migrations.AddField(
            model_name="pagoventa",
            name="tasa_igtf",
            field=models.DecimalField(
                decimal_places=2, default=3.0, max_digits=5, verbose_name="Tasa IGTF %"
            ),
        ),
    ]
