# Generated by Django 5.2.6 on 2026-01-13 23:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_pagoventa_aplica_igtf_pagoventa_monto_igtf_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                null=True,
                verbose_name="Token Público",
            ),
        ),
    ]
