# Generated by Django 5.2.14 on 2026-08-04
# Fix: AuditLog.creado auto_now_add → default=_tz.now
# El auto_now_add sobrescribía el timestamp DESPUÉS de calcular record_hash,
# dejando hashes anclados a un valor que nunca se guardaba → verify_audit_chain
# siempre fallaba en el primer registro.
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0058_add_telegram_storage_channel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="creado",
            field=models.DateTimeField(default=timezone.now, db_index=True, verbose_name="Creado"),
        ),
    ]
