# Generated by Django 5.2.6 on 2026-01-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_venta_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="WikiArticulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("contenido", models.TextField(help_text="Soporta HTML básico")),
                (
                    "tags",
                    models.JSONField(
                        default=list,
                        help_text="Lista de palabras clave que activan este artículo (ej: ['LASER', 'MIA'])",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("AEROLINEA", "Aerolínea"),
                            ("DESTINO", "Destino"),
                            ("GENERAL", "General"),
                            ("VISA", "Requisitos de Visa"),
                            ("HOTEL", "Tips de Hoteles"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Artículo de Wiki",
                "verbose_name_plural": "Wiki / Conocimiento",
                "ordering": ["titulo"],
            },
        ),
    ]
