# Generated by Django 5.2.6 on 2026-01-17 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_wikiarticulo"),
    ]

    operations = [
        migrations.AddField(
            model_name="boletoimportado",
            name="boleto_padre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="versiones_posteriores",
                to="core.boletoimportado",
                verbose_name="Boleto Padre (Versión Anterior)",
            ),
        ),
        migrations.AddField(
            model_name="boletoimportado",
            name="estado_emision",
            field=models.CharField(
                choices=[
                    ("ORI", "Original"),
                    ("REE", "Re-emisión"),
                    ("ANU", "Anulado / Void"),
                    ("REM", "Reembolso"),
                ],
                default="ORI",
                max_length=3,
                verbose_name="Estado de Emisión",
            ),
        ),
        migrations.AddField(
            model_name="boletoimportado",
            name="version",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Versión del boleto (1=Original, 2+=Re-emisión)",
                verbose_name="Versión",
            ),
        ),
    ]
