# Generated by Django 5.2.6 on 2026-01-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_boletoimportado_boleto_padre_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarifarioproveedor",
            name="archivo_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="tarifarios/%Y/%m/",
                verbose_name="Archivo PDF",
            ),
        ),
    ]
