# Generated by Django 5.2.6 on 2026-01-19 15:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_alter_tarifarioproveedor_archivo_pdf"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReporteProveedor",
            fields=[
                ("id_reporte", models.AutoField(primary_key=True, serialize=False)),
                (
                    "archivo_reporte",
                    models.FileField(
                        help_text="Archivo original (PDF, Excel, CSV)",
                        upload_to="reportes_proveedores/%Y/%m/",
                        verbose_name="Archivo de Reporte",
                    ),
                ),
                (
                    "fecha_carga",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Carga"
                    ),
                ),
                (
                    "fecha_reporte",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Fecha de corte o emisión del reporte",
                        verbose_name="Fecha del Reporte",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PEN", "Pendiente de Procesar"),
                            ("PRO", "Procesado"),
                            ("ERR", "Error al Procesar"),
                        ],
                        default="PEN",
                        max_length=3,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "log_proceso",
                    models.TextField(
                        blank=True, null=True, verbose_name="Log del Proceso"
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.proveedor",
                        verbose_name="Proveedor (Aerolínea/Consolidador)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte de Proveedor",
                "verbose_name_plural": "Reportes de Proveedores",
                "ordering": ["-fecha_reporte"],
            },
        ),
        migrations.CreateModel(
            name="ItemReporte",
            fields=[
                (
                    "id_item_reporte",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "numero_boleto",
                    models.CharField(max_length=50, verbose_name="Número de Boleto"),
                ),
                (
                    "pasajero",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Pasajero"
                    ),
                ),
                (
                    "monto_bruto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Monto Bruto",
                    ),
                ),
                (
                    "impuestos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Impuestos",
                    ),
                ),
                (
                    "comision",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Comisión",
                    ),
                ),
                (
                    "monto_neto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Monto Neto (A Pagar)",
                    ),
                ),
                (
                    "estado_conciliacion",
                    models.CharField(
                        choices=[
                            ("PEN", "Pendiente"),
                            ("CON", "Conciliado (Match)"),
                            ("DIS", "Discrepancia en Montos"),
                            ("NO_SYS", "No Encontrado en Sistema"),
                        ],
                        default="PEN",
                        max_length=10,
                        verbose_name="Estado Conciliación",
                    ),
                ),
                (
                    "notas_discrepancia",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notas de Discrepancia"
                    ),
                ),
                (
                    "boleto_sistema",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items_reporte_externo",
                        to="core.boletoimportado",
                        verbose_name="Boleto en Sistema",
                    ),
                ),
                (
                    "reporte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.reporteproveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Reporte",
                "verbose_name_plural": "Items de Reporte",
                "indexes": [
                    models.Index(
                        fields=["numero_boleto"], name="core_itemre_numero__c9fef4_idx"
                    ),
                    models.Index(
                        fields=["estado_conciliacion"],
                        name="core_itemre_estado__e410bd_idx",
                    ),
                ],
            },
        ),
    ]
