# Generated by Django 5.2.6 on 2026-01-21 00:51

import core.fields
import core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_reporteproveedor_itemreporte"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="numero_pasaporte",
            field=core.fields.EncryptedCharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[core.validators.validar_numero_pasaporte],
                verbose_name="Número de Pasaporte",
            ),
        ),
    ]
