# Generated by Django 5.2.6 on 2026-01-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_encrypt_passport_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="boletoimportado",
            name="telegram_file_id",
            field=models.CharField(
                blank=True,
                help_text="ID del archivo en la nube de Telegram (para almacenamiento gratuito).",
                max_length=255,
                null=True,
                verbose_name="Telegram File ID",
            ),
        ),
    ]
