# Generated by Django 5.2.6 on 2026-01-26 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_boletoimportado_telegram_file_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pasajero",
            name="fecha_emision_documento",
            field=models.DateField(
                blank=True,
                help_text="Fecha de emisión del pasaporte/documento",
                null=True,
                verbose_name="Fecha Emisión Documento",
            ),
        ),
        migrations.AddField(
            model_name="pasajero",
            name="fecha_vacuna_fiebre_amarilla",
            field=models.DateField(
                blank=True,
                help_text="Fecha de aplicación de la vacuna (válida por 10 años)",
                null=True,
                verbose_name="Fecha Vacuna Fiebre Amarilla",
            ),
        ),
        migrations.AddField(
            model_name="pasajero",
            name="tiene_fiebre_amarilla",
            field=models.BooleanField(
                default=False,
                help_text="¿El pasajero tiene la vacuna de fiebre amarilla?",
                verbose_name="Tiene Vacuna Fiebre Amarilla",
            ),
        ),
        migrations.CreateModel(
            name="MigrationCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        help_text="Código IATA del aeropuerto de origen (ej: CCS)",
                        max_length=3,
                    ),
                ),
                (
                    "destino",
                    models.CharField(
                        help_text="Código IATA del aeropuerto de destino (ej: MAD)",
                        max_length=3,
                    ),
                ),
                (
                    "transitos",
                    models.JSONField(
                        default=list,
                        help_text="Lista de códigos IATA de aeropuertos de tránsito (ej: ['PTY', 'MEX'])",
                    ),
                ),
                ("fecha_viaje", models.DateField(help_text="Fecha del primer vuelo")),
                (
                    "alert_level",
                    models.CharField(
                        choices=[
                            ("GREEN", "🟢 Todo en Orden"),
                            ("YELLOW", "🟡 Requiere Atención"),
                            ("RED", "🔴 Alerta Crítica"),
                        ],
                        help_text="Nivel de alerta resultante",
                        max_length=10,
                    ),
                ),
                (
                    "visa_required",
                    models.BooleanField(help_text="¿Requiere visa para el destino?"),
                ),
                (
                    "visa_type",
                    models.CharField(
                        blank=True,
                        help_text="Tipo de visa requerida (ej: 'Tourist', 'Transit', 'None')",
                        max_length=100,
                    ),
                ),
                (
                    "passport_validity_ok",
                    models.BooleanField(
                        help_text="¿El pasaporte tiene validez suficiente?"
                    ),
                ),
                (
                    "passport_min_months_required",
                    models.IntegerField(
                        default=6, help_text="Meses mínimos de validez requeridos"
                    ),
                ),
                (
                    "vaccination_required",
                    models.JSONField(
                        default=list,
                        help_text="Lista de vacunas requeridas (ej: ['Yellow Fever', 'COVID-19'])",
                    ),
                ),
                (
                    "summary",
                    models.TextField(help_text="Resumen legible de la validación"),
                ),
                (
                    "full_report",
                    models.JSONField(
                        default=dict, help_text="Reporte completo en formato JSON"
                    ),
                ),
                (
                    "checked_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha y hora de la validación"
                    ),
                ),
                (
                    "checked_by_ai",
                    models.BooleanField(
                        default=False,
                        help_text="¿Se usó IA (Gemini) para esta validación?",
                    ),
                ),
                (
                    "checked_by_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que solicitó la validación",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pasajero",
                    models.ForeignKey(
                        help_text="Pasajero validado",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="migration_checks",
                        to="core.pasajero",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        blank=True,
                        help_text="Venta asociada (opcional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="migration_checks",
                        to="core.venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Validación Migratoria",
                "verbose_name_plural": "Validaciones Migratorias",
                "ordering": ["-checked_at"],
                "indexes": [
                    models.Index(
                        fields=["pasajero", "-checked_at"],
                        name="core_migrat_pasajer_564768_idx",
                    ),
                    models.Index(
                        fields=["venta", "-checked_at"],
                        name="core_migrat_venta_i_786cde_idx",
                    ),
                    models.Index(
                        fields=["alert_level"], name="core_migrat_alert_l_ad7ef0_idx"
                    ),
                ],
            },
        ),
    ]
