# Generated by Django 5.2.6 on 2026-01-26 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0065_add_migration_check_model"),
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="migrationcheck",
            name="pasajero",
            field=models.ForeignKey(
                help_text="Pasajero validado",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="migration_checks",
                to="crm.pasajero",
                verbose_name="Pasajero",
            ),
        ),
    ]
