# Generated by Django 5.2.6 on 2026-01-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_alter_migrationcheck_pasajero"),
    ]

    operations = [
        migrations.AddField(
            model_name="agencia",
            name="plan_status",
            field=models.CharField(
                choices=[
                    ("active", "Activo"),
                    ("past_due", "Pago Pendiente"),
                    ("canceled", "Cancelado"),
                    ("incomplete", "Incompleto"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="agencia",
            name="subscription_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
