# Generated by Django 5.2.6 on 2026-01-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_agencia_plan_status_agencia_subscription_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuarioagencia",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True,
                help_text="ID de chat de Telegram para notificaciones",
                max_length=50,
                null=True,
            ),
        ),
    ]
