# Generated by Django 5.2.6 on 2026-01-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0068_usuarioagencia_telegram_chat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boletoimportado",
            name="estado_parseo",
            field=models.CharField(
                choices=[
                    ("PEN", "Pendiente de Parseo"),
                    ("PRO", "En Proceso"),
                    ("COM", "Parseo Completado"),
                    ("REV", "Revisión Requerida"),
                    ("ERR", "Error en Parseo"),
                    ("NAP", "No Aplica Parseo"),
                ],
                default="PEN",
                max_length=3,
                verbose_name="Estado del Parseo",
            ),
        ),
    ]
