# Generated by Django 5.2.6 on 2026-02-04 13:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0069_alter_boletoimportado_estado_parseo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GastoOperativo",
            fields=[
                ("id_gasto", models.AutoField(primary_key=True, serialize=False)),
                (
                    "fecha",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha del Gasto",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        help_text="Ej: Pago Internet, Compra Café",
                        max_length=255,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto Total"
                    ),
                ),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[
                            ("EFE", "Efectivo / Caja Chica"),
                            ("TRA", "Transferencia Bancaria"),
                            ("TDC", "Tarjeta Débito/Crédito"),
                            ("ZEL", "Zelle / Digital"),
                        ],
                        default="EFE",
                        max_length=3,
                        verbose_name="Método de Pago",
                    ),
                ),
                (
                    "comprobante",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="gastos/%Y/%m/",
                        verbose_name="Comprobante / Recibo",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "asiento_contable",
                    models.OneToOneField(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.asientocontable",
                        verbose_name="Asiento Contable Generado",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        help_text="Selecciona la cuenta contable asociada (ej: Servicios, Oficina).",
                        limit_choices_to={"tipo_cuenta": "GA"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.plancontable",
                        verbose_name="Categoría (Cuenta Contable)",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "moneda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.moneda",
                        verbose_name="Moneda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gasto Operativo",
                "verbose_name_plural": "Libro de Gastos",
                "ordering": ["-fecha", "-id_gasto"],
            },
        ),
    ]
