# Generated by Django 5.2.6 on 2026-02-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_gastooperativo"),
    ]

    operations = [
        migrations.AddField(
            model_name="aerolinea",
            name="codigo_numerico",
            field=models.CharField(
                blank=True,
                help_text="Código numérico de 3 dígitos asignado por IATA (ej. 134, 052)",
                max_length=3,
                null=True,
                verbose_name="Código Numérico/Placa",
            ),
        ),
        migrations.AddField(
            model_name="aerolinea",
            name="orden_prioridad",
            field=models.IntegerField(
                default=100,
                help_text="Para mostrar al principio en listas.",
                verbose_name="Orden de Prioridad",
            ),
        ),
    ]
