# Generated by Django 5.2.6 on 2026-02-09 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_aerolinea_codigo_numerico_aerolinea_orden_prioridad"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="actividadservicio",
                    name="proveedor",
                ),
                migrations.RemoveField(
                    model_name="actividadservicio",
                    name="venta",
                ),
                migrations.RemoveField(
                    model_name="alojamientoreserva",
                    name="ciudad",
                ),
                migrations.RemoveField(
                    model_name="alojamientoreserva",
                    name="item_venta",
                ),
                migrations.RemoveField(
                    model_name="alojamientoreserva",
                    name="proveedor",
                ),
                migrations.RemoveField(
                    model_name="alojamientoreserva",
                    name="venta",
                ),
                migrations.RemoveField(
                    model_name="alquilerautoreserva",
                    name="ciudad_devolucion",
                ),
                migrations.RemoveField(
                    model_name="alquilerautoreserva",
                    name="ciudad_retiro",
                ),
                migrations.RemoveField(
                    model_name="alquilerautoreserva",
                    name="proveedor",
                ),
                migrations.RemoveField(
                    model_name="alquilerautoreserva",
                    name="venta",
                ),
                migrations.RemoveField(
                    model_name="auditlog",
                    name="venta",
                ),
                migrations.AlterUniqueTogether(
                    name="circuitodia",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="circuitodia",
                    name="circuito",
                ),
                migrations.RemoveField(
                    model_name="circuitodia",
                    name="ciudad",
                ),
                migrations.RemoveField(
                    model_name="circuitoturistico",
                    name="venta",
                ),
                migrations.RemoveField(
                    model_name="cliente",
                    name="ciudad",
                ),
                migrations.RemoveField(
                    model_name="cliente",
                    name="nacionalidad",
                ),
                migrations.RemoveField(
                    model_name="cliente",
                    name="pais_emision_pasaporte",
                ),
                migrations.RemoveField(
                    model_name="cotizacion",
                    name="cliente",
                ),
            ],
            database_operations=[],
        ),
    ]
