# Generated by Django 5.2.6 on 2026-02-09 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_initial"),
        ("core", "0072_remove_actividadservicio_proveedor_and_more"),
        ("cotizaciones", "0004_cotizacion_condiciones_comerciales_and_more"),
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="facturaconsolidada",
                    name="cliente",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="crm.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                migrations.RemoveField(
                    model_name="cotizacion",
                    name="consultor",
                ),
                migrations.RemoveField(
                    model_name="cotizacion",
                    name="moneda",
                ),
                migrations.RemoveField(
                    model_name="itemcotizacion",
                    name="cotizacion",
                ),
                migrations.RemoveField(
                    model_name="eventoservicio",
                    name="proveedor",
                ),
                migrations.RemoveField(
                    model_name="eventoservicio",
                    name="venta",
                ),
                migrations.RemoveField(
                    model_name="factura",
                    name="asiento_contable_factura",
                ),
                migrations.RemoveField(
                    model_name="factura",
                    name="cliente",
                ),
                migrations.RemoveField(
                    model_name="factura",
                    name="factura_asociada",
                ),
                migrations.RemoveField(
                    model_name="factura",
                    name="moneda",
                ),
                migrations.RemoveField(
                    model_name="factura",
                    name="venta_asociada",
                ),
                migrations.RemoveField(
                    model_name="itemfactura",
                    name="factura",
                ),
                migrations.RemoveField(
                    model_name="venta",
                    name="factura",
                ),
                migrations.RemoveField(
                    model_name="feeventa",
                    name="moneda",
                ),
                migrations.RemoveField(
                    model_name="feeventa",
                    name="venta",
                ),
                migrations.RemoveField(
                    model_name="itemcotizacion",
                    name="producto_servicio",
                ),
                migrations.RemoveField(
                    model_name="itemventa",
                    name="producto_servicio",
                ),
                migrations.RemoveField(
                    model_name="itemventa",
                    name="proveedor_servicio",
                ),
                migrations.RemoveField(
                    model_name="itemventa",
                    name="venta",
                ),
                migrations.RemoveField(
                    model_name="pagoventa",
                    name="moneda",
                ),
                migrations.RemoveField(
                    model_name="pagoventa",
                    name="venta",
                ),
                migrations.RemoveField(
                    model_name="paqueteaereo",
                    name="venta",
                ),
                migrations.AlterUniqueTogether(
                    name="pasajero",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="pasajero",
                    name="nacionalidad",
                ),
                migrations.RemoveField(
                    model_name="pasajero",
                    name="pais_emision_documento",
                ),
                migrations.RemoveField(
                    model_name="segmentovuelo",
                    name="destino",
                ),
                migrations.RemoveField(
                    model_name="segmentovuelo",
                    name="origen",
                ),
                migrations.RemoveField(
                    model_name="segmentovuelo",
                    name="venta",
                ),
                migrations.RemoveField(
                    model_name="servicioadicionaldetalle",
                    name="proveedor",
                ),
                migrations.RemoveField(
                    model_name="servicioadicionaldetalle",
                    name="venta",
                ),
                migrations.RemoveField(
                    model_name="trasladoservicio",
                    name="proveedor",
                ),
                migrations.RemoveField(
                    model_name="trasladoservicio",
                    name="venta",
                ),
                migrations.RemoveField(
                    model_name="venta",
                    name="agencia",
                ),
                migrations.RemoveField(
                    model_name="venta",
                    name="asiento_contable_venta",
                ),
                migrations.RemoveField(
                    model_name="venta",
                    name="cliente",
                ),
                migrations.RemoveField(
                    model_name="venta",
                    name="cotizacion_origen",
                ),
                migrations.RemoveField(
                    model_name="venta",
                    name="creado_por",
                ),
                migrations.RemoveField(
                    model_name="venta",
                    name="factura_consolidada",
                ),
                migrations.RemoveField(
                    model_name="venta",
                    name="moneda",
                ),
                migrations.RemoveField(
                    model_name="venta",
                    name="pasajeros",
                ),
                migrations.RemoveField(
                    model_name="ventaparsemetadata",
                    name="venta",
                ),
                migrations.DeleteModel(
                    name="ActividadServicio",
                ),
                migrations.DeleteModel(
                    name="AlojamientoReserva",
                ),
                migrations.DeleteModel(
                    name="AlquilerAutoReserva",
                ),
                migrations.DeleteModel(
                    name="AuditLog",
                ),
                migrations.DeleteModel(
                    name="CircuitoDia",
                ),
                migrations.DeleteModel(
                    name="CircuitoTuristico",
                ),
                migrations.DeleteModel(
                    name="Cliente",
                ),
                migrations.DeleteModel(
                    name="Cotizacion",
                ),
                migrations.DeleteModel(
                    name="EventoServicio",
                ),
                migrations.DeleteModel(
                    name="ItemFactura",
                ),
                migrations.DeleteModel(
                    name="Factura",
                ),
                migrations.DeleteModel(
                    name="FeeVenta",
                ),
                migrations.DeleteModel(
                    name="ItemCotizacion",
                ),
                migrations.DeleteModel(
                    name="ItemVenta",
                ),
                migrations.DeleteModel(
                    name="PagoVenta",
                ),
                migrations.DeleteModel(
                    name="PaqueteAereo",
                ),
                migrations.DeleteModel(
                    name="Pasajero",
                ),
                migrations.DeleteModel(
                    name="SegmentoVuelo",
                ),
                migrations.DeleteModel(
                    name="ServicioAdicionalDetalle",
                ),
                migrations.DeleteModel(
                    name="TrasladoServicio",
                ),
                migrations.DeleteModel(
                    name="Venta",
                ),
                migrations.DeleteModel(
                    name="VentaParseMetadata",
                ),
                migrations.CreateModel(
                    name="ActividadServicio",
                    fields=[],
                    options={
                        "proxy": True,
                        "indexes": [],
                        "constraints": [],
                    },
                    bases=("bookings.actividadservicio",),
                ),
                migrations.CreateModel(
                    name="AlojamientoReserva",
                    fields=[],
                    options={
                        "proxy": True,
                        "indexes": [],
                        "constraints": [],
                    },
                    bases=("bookings.alojamientoreserva",),
                ),
                migrations.CreateModel(
                    name="AlquilerAutoReserva",
                    fields=[],
                    options={
                        "proxy": True,
                        "indexes": [],
                        "constraints": [],
                    },
                    bases=("bookings.alquilerautoreserva",),
                ),
                migrations.CreateModel(
                    name="AuditLog",
                    fields=[],
                    options={
                        "proxy": True,
                        "indexes": [],
                        "constraints": [],
                    },
                    bases=("bookings.auditlog",),
                ),
                migrations.CreateModel(
                    name="CircuitoDia",
                    fields=[],
                    options={
                        "proxy": True,
                        "indexes": [],
                        "constraints": [],
                    },
                    bases=("bookings.circuitodia",),
                ),
                migrations.CreateModel(
                    name="CircuitoTuristico",
                    fields=[],
                    options={
                        "proxy": True,
                        "indexes": [],
                        "constraints": [],
                    },
                    bases=("bookings.circuitoturistico",),
                ),
                migrations.CreateModel(
                    name="Cotizacion",
                    fields=[],
                    options={
                        "verbose_name": "Cotización",
                        "verbose_name_plural": "Cotizaciones",
                        "proxy": True,
                        "indexes": [],
                        "constraints": [],
                    },
                    bases=("cotizaciones.cotizacion",),
                ),
                migrations.CreateModel(
                    name="EventoServicio",
                    fields=[],
                    options={
                        "proxy": True,
                        "indexes": [],
                        "constraints": [],
                    },
                    bases=("bookings.eventoservicio",),
                ),
                migrations.CreateModel(
                    name="FeeVenta",
                    fields=[],
                    options={
                        "proxy": True,
                        "indexes": [],
                        "constraints": [],
                    },
                    bases=("bookings.feeventa",),
                ),
                migrations.CreateModel(
                    name="ItemCotizacion",
                    fields=[],
                    options={
                        "verbose_name": "Item de Cotización",
                        "verbose_name_plural": "Items de Cotización",
                        "proxy": True,
                        "indexes": [],
                        "constraints": [],
                    },
                    bases=("cotizaciones.itemcotizacion",),
                ),
                migrations.CreateModel(
                    name="ItemVenta",
                    fields=[],
                    options={
                        "proxy": True,
                        "indexes": [],
                        "constraints": [],
                    },
                    bases=("bookings.itemventa",),
                ),
                migrations.CreateModel(
                    name="PagoVenta",
                    fields=[],
                    options={
                        "proxy": True,
                        "indexes": [],
                        "constraints": [],
                    },
                    bases=("bookings.pagoventa",),
                ),
                migrations.CreateModel(
                    name="PaqueteAereo",
                    fields=[],
                    options={
                        "proxy": True,
                        "indexes": [],
                        "constraints": [],
                    },
                    bases=("bookings.paqueteaereo",),
                ),
                migrations.CreateModel(
                    name="SegmentoVuelo",
                    fields=[],
                    options={
                        "proxy": True,
                        "indexes": [],
                        "constraints": [],
                    },
                    bases=("bookings.segmentovuelo",),
                ),
                migrations.CreateModel(
                    name="ServicioAdicionalDetalle",
                    fields=[],
                    options={
                        "proxy": True,
                        "indexes": [],
                        "constraints": [],
                    },
                    bases=("bookings.servicioadicionaldetalle",),
                ),
                migrations.CreateModel(
                    name="TrasladoServicio",
                    fields=[],
                    options={
                        "proxy": True,
                        "indexes": [],
                        "constraints": [],
                    },
                    bases=("bookings.trasladoservicio",),
                ),
                migrations.CreateModel(
                    name="Venta",
                    fields=[],
                    options={
                        "proxy": True,
                        "indexes": [],
                        "constraints": [],
                    },
                    bases=("bookings.venta",),
                ),
                migrations.CreateModel(
                    name="VentaParseMetadata",
                    fields=[],
                    options={
                        "proxy": True,
                        "indexes": [],
                        "constraints": [],
                    },
                    bases=("bookings.ventaparsemetadata",),
                ),
            ],
            database_operations=[],
        ),
    ]
