# Generated by Django 5.2.6 on 2026-02-16 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0074_delete_aerolineaconfig_and_more"),
        ("finance", "0003_alter_itemreporte_boleto_interno_gastooperativo_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BoletoImportado",
        ),
        migrations.DeleteModel(
            name="DestinoCMS",
        ),
        migrations.DeleteModel(
            name="GastoOperativo",
        ),
        migrations.DeleteModel(
            name="HistorialCambioBoleto",
        ),
        migrations.DeleteModel(
            name="ItemReporte",
        ),
        migrations.DeleteModel(
            name="PaginaCMS",
        ),
        migrations.DeleteModel(
            name="MenuItemCMS",
        ),
        migrations.DeleteModel(
            name="PaqueteTuristicoCMS",
        ),
        migrations.DeleteModel(
            name="ReporteProveedor",
        ),
        migrations.DeleteModel(
            name="SolicitudAnulacion",
        ),
    ]
