# Generated by Django 5.2.6 on 2026-02-19 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0075_delete_boletoimportado_delete_destinocms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facturaconsolidada",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.agencia",
                verbose_name="Agencia",
            ),
        ),
    ]
