# Generated by Django 5.2.6 on 2026-04-02 00:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("contabilidad", "0001_initial"),
        ("core", "0001_initial"),
        ("crm", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id_factura",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID Factura"
                    ),
                ),
                (
                    "numero_factura",
                    models.CharField(
                        blank=True,
                        help_text="Puede ser un correlativo fiscal o interno.",
                        max_length=50,
                        unique=True,
                        verbose_name="Número de Factura",
                    ),
                ),
                (
                    "fecha_emision",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Emisión",
                    ),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Vencimiento"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "monto_impuestos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Monto Impuestos",
                    ),
                ),
                (
                    "monto_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=12,
                        verbose_name="Monto Total",
                    ),
                ),
                (
                    "saldo_pendiente",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=12,
                        verbose_name="Saldo Pendiente",
                    ),
                ),
                (
                    "tipo_factura",
                    models.CharField(
                        choices=[
                            ("PRO", "Factura Propia (Comisión/Servicios)"),
                            ("TER", "Factura por Cuenta de Terceros (Boletos)"),
                            ("ND", "Nota de Débito"),
                            ("NC", "Nota de Crédito"),
                        ],
                        default="PRO",
                        max_length=3,
                        verbose_name="Tipo de Factura",
                    ),
                ),
                (
                    "numero_control",
                    models.CharField(
                        blank=True,
                        help_text="Número de Control Fiscal obligatorio.",
                        max_length=50,
                        null=True,
                        verbose_name="Número de Control",
                    ),
                ),
                (
                    "cliente_nombre",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Nombre/Razón Social Cliente",
                    ),
                ),
                (
                    "cliente_rif",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="RIF/Documento Cliente"
                    ),
                ),
                (
                    "cliente_direccion",
                    models.TextField(
                        blank=True, verbose_name="Dirección Fiscal Cliente"
                    ),
                ),
                (
                    "cliente_telefono",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Teléfono Cliente"
                    ),
                ),
                (
                    "tasa_cambio",
                    models.DecimalField(
                        decimal_places=4,
                        default=1,
                        help_text="Tasa de cambio vigente a la fecha de emisión.",
                        max_digits=12,
                        verbose_name="Tasa de Cambio (BCV)",
                    ),
                ),
                (
                    "moneda_transaccion",
                    models.CharField(
                        default="USD",
                        help_text="Moneda en la que se pagó",
                        max_length=3,
                        verbose_name="Moneda Transacción",
                    ),
                ),
                (
                    "base_imponible",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Base Imponible (Gravada)",
                    ),
                ),
                (
                    "base_exenta",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Base Exenta",
                    ),
                ),
                (
                    "iva_porcentaje",
                    models.DecimalField(
                        decimal_places=2, default=16, max_digits=5, verbose_name="% IVA"
                    ),
                ),
                (
                    "iva_monto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Monto IVA",
                    ),
                ),
                (
                    "igtf_porcentaje",
                    models.DecimalField(
                        decimal_places=2, default=3, max_digits=5, verbose_name="% IGTF"
                    ),
                ),
                (
                    "igtf_monto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Impuesto a Grandes Transacciones Financieras (si aplica).",
                        max_digits=12,
                        verbose_name="Monto IGTF",
                    ),
                ),
                (
                    "inatur_porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=5,
                        verbose_name="% INATUR",
                    ),
                ),
                (
                    "inatur_monto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Contribución parafiscal Turismo (1%).",
                        max_digits=12,
                        verbose_name="Monto INATUR",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BOR", "Borrador"),
                            ("EMI", "Emitida (Pendiente de Pago)"),
                            ("PAR", "Pagada Parcialmente"),
                            ("PAG", "Pagada Totalmente"),
                            ("VEN", "Vencida"),
                            ("ANU", "Anulada"),
                        ],
                        default="BOR",
                        max_length=3,
                        verbose_name="Estado de la Factura",
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notas de la Factura"
                    ),
                ),
                (
                    "archivo_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="facturas/%Y/%m/",
                        verbose_name="Archivo PDF",
                    ),
                ),
                (
                    "agencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.agencia",
                        verbose_name="Agencia",
                    ),
                ),
                (
                    "asiento_contable_factura",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finance_facturas_asociadas",
                        to="core.asientocontable",
                        verbose_name="Asiento Contable de Factura",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="crm.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "factura_asociada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_relacionados",
                        to="finance.factura",
                        verbose_name="Factura Asociada (Para ND/NC)",
                    ),
                ),
                (
                    "moneda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.moneda",
                        verbose_name="Moneda",
                    ),
                ),
                (
                    "venta_asociada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="facturas",
                        to="bookings.venta",
                        verbose_name="Venta Asociada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura de Cliente",
                "verbose_name_plural": "Facturas de Clientes",
                "db_table": "core_factura",
                "ordering": ["-fecha_emision", "-numero_factura"],
            },
        ),
        migrations.CreateModel(
            name="GastoOperativo",
            fields=[
                (
                    "id_gasto",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID Gasto"
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto"
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Fecha"
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Categoría"
                    ),
                ),
                (
                    "comprobante",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="gastos/%Y/%m/",
                        verbose_name="Comprobante/Factura",
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "agencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.agencia",
                        verbose_name="Agencia",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
                (
                    "moneda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.moneda",
                        verbose_name="Moneda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gasto Operativo",
                "verbose_name_plural": "Gastos Operativos",
                "db_table": "core_gastooperativo",
                "ordering": ["-fecha", "-fecha_registro"],
            },
        ),
        migrations.CreateModel(
            name="ItemFactura",
            fields=[
                (
                    "id_item_factura",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Item Factura",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        max_length=500, verbose_name="Descripción del Item"
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Precio Unitario"
                    ),
                ),
                (
                    "subtotal_item",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=12,
                        verbose_name="Subtotal Item",
                    ),
                ),
                (
                    "tipo_impuesto",
                    models.CharField(
                        choices=[
                            ("16", "IVA General (16%)"),
                            ("08", "IVA Reducido (8%)"),
                            ("00", "Exento / No Sujeto"),
                        ],
                        default="16",
                        max_length=2,
                        verbose_name="Tipo Impuesto",
                    ),
                ),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items_factura",
                        to="finance.factura",
                        verbose_name="Factura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Factura",
                "verbose_name_plural": "Items de Factura",
                "db_table": "core_itemfactura",
            },
        ),
        migrations.CreateModel(
            name="ItemReporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_boleto",
                    models.CharField(max_length=50, verbose_name="Número de Boleto"),
                ),
                (
                    "pnr",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="PNR"
                    ),
                ),
                (
                    "pasajero",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Pasajero"
                    ),
                ),
                (
                    "fecha_emision",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Emisión"
                    ),
                ),
                (
                    "monto_total_proveedor",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "monto_sistema",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tax_proveedor",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "comision_proveedor",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("MAT", "Conciliado (OK)"),
                            ("DIS", "Discrepancia detectada"),
                            ("MIN", "Falta en sistema (Solo en reporte)"),
                            ("MPR", "Falta en reporte (Solo en sistema)"),
                        ],
                        default="MAT",
                        max_length=3,
                    ),
                ),
                ("fecha_conciliacion", models.DateTimeField(blank=True, null=True)),
                (
                    "boleto_interno",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items_reconciliacion",
                        to="bookings.boletoimportado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiferenciaFinanciera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campo_discrepancia", models.CharField(max_length=50)),
                ("valor_sistema", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "valor_proveedor",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("diferencia", models.DecimalField(decimal_places=2, max_digits=12)),
                ("resuelto", models.BooleanField(default=False)),
                ("fecha_resolucion", models.DateTimeField(blank=True, null=True)),
                (
                    "item_reporte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diferencias",
                        to="finance.itemreporte",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LinkDePago",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("monto_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("moneda", models.CharField(default="USD", max_length=3)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PEN", "Pendiente"),
                            ("REV", "En Revisión (Zelle/Transf)"),
                            ("PAG", "Pagado Exitosamente"),
                            ("EXP", "Expirado"),
                        ],
                        default="PEN",
                        max_length=3,
                    ),
                ),
                (
                    "referencia_pago",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "comprobante_imagen",
                    models.ImageField(
                        blank=True, null=True, upload_to="comprobantes_pago/"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("expira_en", models.DateTimeField()),
                (
                    "venta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link_pago",
                        to="bookings.venta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PagoBinance",
            fields=[
                (
                    "id_pago_binance",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "prepay_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Binance Prepay ID",
                    ),
                ),
                (
                    "merchant_trade_no",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Internal Trade Number"
                    ),
                ),
                (
                    "checkout_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Checkout URL",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto"
                    ),
                ),
                (
                    "moneda",
                    models.CharField(
                        default="USDT", max_length=5, verbose_name="Moneda"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("INI", "Inicial / Pendiente"),
                            ("PRO", "Procesando"),
                            ("EXI", "Exitoso"),
                            ("FAL", "Fallido"),
                            ("EXP", "Expirado"),
                        ],
                        default="INI",
                        max_length=3,
                        verbose_name="Estado",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Respuesta API Binance"
                    ),
                ),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos_binance",
                        to="finance.factura",
                        verbose_name="Factura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago Binance Pay",
                "verbose_name_plural": "Pagos Binance Pay",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="ReporteProveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to="finanzas/reportes/%Y/%m/",
                        verbose_name="Archivo de Reporte",
                    ),
                ),
                ("fecha_carga", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PEN", "Pendiente por Procesar"),
                            ("PRO", "Procesado"),
                            ("ERR", "Error en Procesamiento"),
                        ],
                        default="PEN",
                        max_length=3,
                        verbose_name="Estado",
                    ),
                ),
                ("total_registros", models.IntegerField(default=0)),
                ("total_con_diferencia", models.IntegerField(default=0)),
                ("notas", models.TextField(blank=True)),
                (
                    "agencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.agencia",
                        verbose_name="Agencia",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes_finance",
                        to="core.proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte de Proveedor",
                "verbose_name_plural": "Reportes de Proveedores",
            },
        ),
        migrations.AddField(
            model_name="itemreporte",
            name="reporte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="finance.reporteproveedor",
            ),
        ),
        migrations.CreateModel(
            name="ReporteReconciliacion",
            fields=[
                (
                    "id_reporte",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("archivo", models.FileField(upload_to="finance/reportes/%Y/%m/")),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                (
                    "proveedor",
                    models.CharField(
                        help_text="Ej: BSP, KIU, SABRE, AMADEUS", max_length=50
                    ),
                ),
                ("periodo_inicio", models.DateField(blank=True, null=True)),
                ("periodo_fin", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente de Procesamiento"),
                            ("PROCESANDO", "Procesando con IA"),
                            ("PROCESADO", "Procesado Exitosamente"),
                            ("ERROR", "Error en Procesamiento"),
                            ("CON_DISCREPANCIAS", "Con Discrepancias Detectadas"),
                            ("CONCILIADO", "Conciliado Totalmente"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                (
                    "datos_extraidos",
                    models.JSONField(
                        blank=True, help_text="Raw data extraída por la IA", null=True
                    ),
                ),
                (
                    "resumen_conciliacion",
                    models.JSONField(
                        blank=True, help_text="Resumen de match/mismatch", null=True
                    ),
                ),
                ("error_log", models.TextField(blank=True, null=True)),
                (
                    "agencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes_reconciliacion",
                        to="core.agencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte de Reconciliación",
                "verbose_name_plural": "Reportes de Reconciliación",
                "ordering": ["-fecha_subida"],
            },
        ),
        migrations.CreateModel(
            name="LineaReporteReconciliacion",
            fields=[
                ("id_linea", models.AutoField(primary_key=True, serialize=False)),
                (
                    "numero_boleto_reportado",
                    models.CharField(
                        db_index=True,
                        max_length=150,
                        verbose_name="Número de Boleto (Proveedor)",
                    ),
                ),
                (
                    "tarifa_base_cobrada",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Tarifa Base Cobrada",
                    ),
                ),
                (
                    "impuestos_cobrados",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Impuestos Cobrados",
                    ),
                ),
                (
                    "comision_cedida",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Comisión Cedida (-/+)",
                    ),
                ),
                (
                    "total_cobrado",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total Cobrado/Liquidado",
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Fila Cruda Original"
                    ),
                ),
                (
                    "reporte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineas",
                        to="finance.reportereconciliacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Linea de Reporte",
                "verbose_name_plural": "Líneas de Reporte",
            },
        ),
        migrations.CreateModel(
            name="ConciliacionBoleto",
            fields=[
                (
                    "id_conciliacion",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("OK", "Cuadrado Exacto"),
                            ("DISCREPANCIA", "Diferencia Matemática"),
                            ("HUERFANO_PROVEEDOR", "Cobrado, No existe en TravelHub"),
                            (
                                "HUERFANO_LOCAL",
                                "En TravelHub, No fue cobrado por el Proveedor",
                            ),
                            ("IGNORADO", "Ignorado Manualmente"),
                        ],
                        default="OK",
                        max_length=20,
                    ),
                ),
                (
                    "diferencia_tarifa",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "diferencia_impuestos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "diferencia_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "ia_razonamiento",
                    models.TextField(
                        blank=True,
                        help_text="Explicación de la IA sobre el match difuso o discrepancia",
                        null=True,
                    ),
                ),
                ("resolucion_notas", models.TextField(blank=True, null=True)),
                (
                    "boleto_local",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bookings.boletoimportado",
                    ),
                ),
                (
                    "sugerencia_asiento",
                    models.ForeignKey(
                        blank=True,
                        help_text="Asiento automático sugerido por IA",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contabilidad.asientocontable",
                    ),
                ),
                (
                    "linea_reporte",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.lineareportereconciliacion",
                    ),
                ),
                (
                    "reporte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conciliaciones",
                        to="finance.reportereconciliacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conciliación de Boleto",
                "verbose_name_plural": "Conciliaciones de Boletos",
            },
        ),
        migrations.CreateModel(
            name="TaxRefundOpportunity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "monto_estimado",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "monto_recuperado",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ELE", "Elegible (Dinero en la mesa)"),
                            ("TRA", "En Trámite (Global Blue / Partner)"),
                            ("COM", "Completado (Dinero Recuperado)"),
                            ("REC", "Rechazado"),
                        ],
                        default="ELE",
                        max_length=3,
                    ),
                ),
                (
                    "tracking_code_proveedor",
                    models.CharField(
                        blank=True,
                        help_text="Ej. Global Blue Tracking ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "agencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_refund_oo",
                        to="core.agencia",
                    ),
                ),
                (
                    "boleto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_refund_oo",
                        to="bookings.boletoimportado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransaccionPago",
            fields=[
                ("id_transaccion", models.AutoField(primary_key=True, serialize=False)),
                (
                    "proveedor",
                    models.CharField(
                        choices=[
                            ("BIN", "Binance Pay"),
                            ("STR", "Stripe"),
                            ("ZEL", "Zelle"),
                            ("OTR", "Otro"),
                        ],
                        max_length=3,
                        verbose_name="Proveedor",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto"
                    ),
                ),
                (
                    "moneda",
                    models.CharField(
                        default="USD", max_length=10, verbose_name="Moneda"
                    ),
                ),
                (
                    "webhook_transaction_id",
                    models.CharField(
                        db_index=True,
                        help_text="ID único de la pasarela (ej. TransactionID de Binance o pi_XXX de Stripe).",
                        max_length=255,
                        unique=True,
                        verbose_name="Webhook Transaction ID",
                    ),
                ),
                (
                    "data_raw",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Datos Raw del Webhook"
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Registro"
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transacciones_pago",
                        to="bookings.venta",
                        verbose_name="Venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transacción de Pago",
                "verbose_name_plural": "Transacciones de Pago",
                "ordering": ["-fecha_registro"],
            },
        ),
        migrations.AddIndex(
            model_name="factura",
            index=models.Index(
                fields=["numero_factura"], name="core_factur_numero__4980ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factura",
            index=models.Index(
                fields=["numero_control"], name="core_factur_numero__1af612_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factura",
            index=models.Index(
                fields=["fecha_emision"], name="core_factur_fecha_e_f7be26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factura",
            index=models.Index(
                fields=["tipo_factura"], name="core_factur_tipo_fa_26c852_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factura",
            index=models.Index(
                fields=["agencia", "fecha_emision"],
                name="core_factur_agencia_2438e6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="factura",
            index=models.Index(
                fields=["agencia", "estado"], name="core_factur_agencia_728849_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factura",
            index=models.Index(
                fields=["venta_asociada"], name="core_factur_venta_a_301d08_idx"
            ),
        ),
    ]
