# Generated by Django 5.2.6 on 2026-02-09 20:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("core", "0072_remove_actividadservicio_proveedor_and_more"),
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id_factura",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID Factura"
                    ),
                ),
                (
                    "numero_factura",
                    models.CharField(
                        blank=True,
                        help_text="Puede ser un correlativo fiscal o interno.",
                        max_length=50,
                        unique=True,
                        verbose_name="Número de Factura",
                    ),
                ),
                (
                    "fecha_emision",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Emisión",
                    ),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Vencimiento"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "monto_impuestos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Monto Impuestos",
                    ),
                ),
                (
                    "monto_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=12,
                        verbose_name="Monto Total",
                    ),
                ),
                (
                    "saldo_pendiente",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=12,
                        verbose_name="Saldo Pendiente",
                    ),
                ),
                (
                    "tipo_factura",
                    models.CharField(
                        choices=[
                            ("PRO", "Factura Propia (Comisión/Servicios)"),
                            ("TER", "Factura por Cuenta de Terceros (Boletos)"),
                            ("ND", "Nota de Débito"),
                            ("NC", "Nota de Crédito"),
                        ],
                        default="PRO",
                        max_length=3,
                        verbose_name="Tipo de Factura",
                    ),
                ),
                (
                    "numero_control",
                    models.CharField(
                        blank=True,
                        help_text="Número de Control Fiscal obligatorio.",
                        max_length=50,
                        null=True,
                        verbose_name="Número de Control",
                    ),
                ),
                (
                    "cliente_nombre",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Nombre/Razón Social Cliente",
                    ),
                ),
                (
                    "cliente_rif",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="RIF/Documento Cliente"
                    ),
                ),
                (
                    "cliente_direccion",
                    models.TextField(
                        blank=True, verbose_name="Dirección Fiscal Cliente"
                    ),
                ),
                (
                    "cliente_telefono",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Teléfono Cliente"
                    ),
                ),
                (
                    "tasa_cambio",
                    models.DecimalField(
                        decimal_places=4,
                        default=1,
                        help_text="Tasa de cambio vigente a la fecha de emisión.",
                        max_digits=12,
                        verbose_name="Tasa de Cambio (BCV)",
                    ),
                ),
                (
                    "moneda_transaccion",
                    models.CharField(
                        default="USD",
                        help_text="Moneda en la que se pagó",
                        max_length=3,
                        verbose_name="Moneda Transacción",
                    ),
                ),
                (
                    "base_imponible",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Base Imponible (Gravada)",
                    ),
                ),
                (
                    "base_exenta",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Base Exenta",
                    ),
                ),
                (
                    "iva_porcentaje",
                    models.DecimalField(
                        decimal_places=2, default=16, max_digits=5, verbose_name="% IVA"
                    ),
                ),
                (
                    "iva_monto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Monto IVA",
                    ),
                ),
                (
                    "igtf_porcentaje",
                    models.DecimalField(
                        decimal_places=2, default=3, max_digits=5, verbose_name="% IGTF"
                    ),
                ),
                (
                    "igtf_monto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Impuesto a Grandes Transacciones Financieras (si aplica).",
                        max_digits=12,
                        verbose_name="Monto IGTF",
                    ),
                ),
                (
                    "inatur_porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=5,
                        verbose_name="% INATUR",
                    ),
                ),
                (
                    "inatur_monto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Contribución parafiscal Turismo (1%).",
                        max_digits=12,
                        verbose_name="Monto INATUR",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BOR", "Borrador"),
                            ("EMI", "Emitida (Pendiente de Pago)"),
                            ("PAR", "Pagada Parcialmente"),
                            ("PAG", "Pagada Totalmente"),
                            ("VEN", "Vencida"),
                            ("ANU", "Anulada"),
                        ],
                        default="BOR",
                        max_length=3,
                        verbose_name="Estado de la Factura",
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notas de la Factura"
                    ),
                ),
                (
                    "archivo_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="facturas/%Y/%m/",
                        verbose_name="Archivo PDF",
                    ),
                ),
                (
                    "asiento_contable_factura",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finance_facturas_asociadas",
                        to="core.asientocontable",
                        verbose_name="Asiento Contable de Factura",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="crm.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "factura_asociada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_relacionados",
                        to="finance.factura",
                        verbose_name="Factura Asociada (Para ND/NC)",
                    ),
                ),
                (
                    "moneda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.moneda",
                        verbose_name="Moneda",
                    ),
                ),
                (
                    "venta_asociada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="facturas",
                        to="bookings.venta",
                        verbose_name="Venta Asociada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura de Cliente",
                "verbose_name_plural": "Facturas de Clientes",
                "db_table": "core_factura",
                "ordering": ["-fecha_emision", "-numero_factura"],
            },
        ),
        migrations.CreateModel(
            name="ItemFactura",
            fields=[
                (
                    "id_item_factura",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Item Factura",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        max_length=500, verbose_name="Descripción del Item"
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Precio Unitario"
                    ),
                ),
                (
                    "subtotal_item",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=12,
                        verbose_name="Subtotal Item",
                    ),
                ),
                (
                    "tipo_impuesto",
                    models.CharField(
                        choices=[
                            ("16", "IVA General (16%)"),
                            ("08", "IVA Reducido (8%)"),
                            ("00", "Exento / No Sujeto"),
                        ],
                        default="16",
                        max_length=2,
                        verbose_name="Tipo Impuesto",
                    ),
                ),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items_factura",
                        to="finance.factura",
                        verbose_name="Factura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Factura",
                "verbose_name_plural": "Items de Factura",
                "db_table": "core_itemfactura",
            },
        ),
        migrations.AddIndex(
            model_name="factura",
            index=models.Index(
                fields=["numero_factura"], name="core_factur_numero__4980ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factura",
            index=models.Index(
                fields=["numero_control"], name="core_factur_numero__1af612_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factura",
            index=models.Index(
                fields=["fecha_emision"], name="core_factur_fecha_e_f7be26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factura",
            index=models.Index(
                fields=["tipo_factura"], name="core_factur_tipo_fa_26c852_idx"
            ),
        ),
    ]
