# Generated by Django 5.2.6 on 2026-05-02 23:16

"""Migración de base de datos para finance.
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("bookings", "0006_alter_venta_localizador"),
        ("core", "0005_alter_comisionproveedorservicio_unique_together_and_more"),
        ("finance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conciliacionboleto",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
        migrations.AddField(
            model_name="conciliacionboleto",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fecha de Eliminación"),
        ),
        migrations.AddField(
            model_name="conciliacionboleto",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Eliminado"),
        ),
        migrations.AddField(
            model_name="factura",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fecha de Eliminación"),
        ),
        migrations.AddField(
            model_name="factura",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Eliminado"),
        ),
        migrations.AddField(
            model_name="gastooperativo",
            name="asiento_contable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.asientocontable",
                verbose_name="Asiento Contable Asociado",
            ),
        ),
        migrations.AddField(
            model_name="gastooperativo",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fecha de Eliminación"),
        ),
        migrations.AddField(
            model_name="gastooperativo",
            name="error_contable_msg",
            field=models.TextField(
                blank=True,
                help_text="Indica por qué no se pudo generar el asiento automático.",
                null=True,
                verbose_name="Mensaje de Error Contable",
            ),
        ),
        migrations.AddField(
            model_name="gastooperativo",
            name="estado_contable",
            field=models.CharField(
                choices=[
                    ("PEN", "Pendiente de Contabilizar"),
                    ("PRO", "Contabilizado Correctamente"),
                    ("ERR", "Error de Configuración Contable"),
                ],
                default="PEN",
                max_length=3,
                verbose_name="Estado Contable",
            ),
        ),
        migrations.AddField(
            model_name="gastooperativo",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Eliminado"),
        ),
        migrations.AddField(
            model_name="itemfactura",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fecha de Eliminación"),
        ),
        migrations.AddField(
            model_name="itemfactura",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Eliminado"),
        ),
        migrations.AddField(
            model_name="lineareportereconciliacion",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
        migrations.AddField(
            model_name="lineareportereconciliacion",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fecha de Eliminación"),
        ),
        migrations.AddField(
            model_name="lineareportereconciliacion",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Eliminado"),
        ),
        migrations.AddField(
            model_name="pagobinance",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
        migrations.AddField(
            model_name="pagobinance",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fecha de Eliminación"),
        ),
        migrations.AddField(
            model_name="pagobinance",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Eliminado"),
        ),
        migrations.AddField(
            model_name="reportereconciliacion",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fecha de Eliminación"),
        ),
        migrations.AddField(
            model_name="reportereconciliacion",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Eliminado"),
        ),
        migrations.AddField(
            model_name="transaccionpago",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
        migrations.AddField(
            model_name="transaccionpago",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fecha de Eliminación"),
        ),
        migrations.AddField(
            model_name="transaccionpago",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Eliminado"),
        ),
        migrations.AlterField(
            model_name="factura",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
        migrations.AlterField(
            model_name="gastooperativo",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
        migrations.AlterField(
            model_name="reportereconciliacion",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
        migrations.CreateModel(
            name="LiquidacionAgente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False, verbose_name="Eliminado"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Eliminación"
                    ),
                ),
                ("periodo_mes", models.IntegerField(help_text="1-12", verbose_name="Mes")),
                ("periodo_anio", models.IntegerField(help_text="YYYY", verbose_name="Año")),
                (
                    "total_comisiones",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="Total Comisiones"
                    ),
                ),
                ("cantidad_ventas", models.IntegerField(default=0, verbose_name="Cant. Ventas")),
                ("fecha_generacion", models.DateTimeField(auto_now_add=True)),
                ("pagado", models.BooleanField(default=False, verbose_name="Pagado/Transferido")),
                (
                    "referencia_pago",
                    models.CharField(blank=True, max_length=100, verbose_name="Referencia de Pago"),
                ),
                (
                    "agencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="core.agencia",
                    ),
                ),
                (
                    "agente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liquidaciones_mensuales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Liquidación de Agente",
                "verbose_name_plural": "Liquidaciones de Agentes",
                "unique_together": {("agente", "periodo_mes", "periodo_anio")},
            },
        ),
        migrations.CreateModel(
            name="ReglaComision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False, verbose_name="Eliminado"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Eliminación"
                    ),
                ),
                (
                    "tipo_calculo",
                    models.CharField(
                        choices=[
                            ("UTIL", "Porcentaje sobre Utilidad/Fee"),
                            ("VENTA", "Porcentaje sobre Total Venta"),
                            ("FIJO", "Monto Fijo por Boleto/Venta"),
                        ],
                        default="UTIL",
                        max_length=5,
                        verbose_name="Tipo de Cálculo",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monto en $ o % según el tipo.",
                        max_digits=12,
                        verbose_name="Valor (Propina/%)",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "agencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="core.agencia",
                    ),
                ),
                (
                    "agente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reglas_comision",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Agente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regla de Comisión",
                "verbose_name_plural": "Reglas de Comisiones",
                "unique_together": {("agencia", "agente")},
            },
        ),
        migrations.CreateModel(
            name="ComisionVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False, verbose_name="Eliminado"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Eliminación"
                    ),
                ),
                (
                    "monto_base_calculo",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total Venta o Utilidad usada para el cálculo.",
                        max_digits=12,
                        verbose_name="Monto Base",
                    ),
                ),
                (
                    "monto_comision",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto Comisión"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PEN", "Pendiente de Liquidar"),
                            ("LIQ", "Liquidado en Nómina"),
                            ("CAN", "Cancelado (Venta Anulada)"),
                        ],
                        default="PEN",
                        max_length=3,
                        verbose_name="Estado",
                    ),
                ),
                ("fecha_calculo", models.DateTimeField(auto_now_add=True)),
                (
                    "fecha_liquidacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Liquidación"
                    ),
                ),
                (
                    "agencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="core.agencia",
                    ),
                ),
                (
                    "agente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Agente",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comisiones_agente",
                        to="bookings.venta",
                        verbose_name="Venta",
                    ),
                ),
                (
                    "liquidacion_asociada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detalles_comisiones",
                        to="finance.liquidacionagente",
                    ),
                ),
                (
                    "regla_aplicada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.reglacomision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comisión por Venta",
                "verbose_name_plural": "Comisiones por Ventas",
                "ordering": ["-fecha_calculo"],
            },
        ),
    ]
