# Generated by Django 5.2.6 on 2026-02-12 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0073_alter_facturaconsolidada_cliente_and_more"),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemReporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_boleto",
                    models.CharField(max_length=50, verbose_name="Número de Boleto"),
                ),
                (
                    "monto_total_proveedor",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "tax_proveedor",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "comision_proveedor",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("MAT", "Conciliado (OK)"),
                            ("DIS", "Discrepancia detectada"),
                            ("MIN", "Falta en sistema (Solo en reporte)"),
                            ("MPR", "Falta en reporte (Solo en sistema)"),
                        ],
                        default="MAT",
                        max_length=3,
                    ),
                ),
                ("fecha_conciliacion", models.DateTimeField(blank=True, null=True)),
                (
                    "boleto_interno",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items_reconciliacion",
                        to="core.boletoimportado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiferenciaFinanciera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campo_discrepancia", models.CharField(max_length=50)),
                ("valor_sistema", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "valor_proveedor",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("diferencia", models.DecimalField(decimal_places=2, max_digits=12)),
                ("resuelto", models.BooleanField(default=False)),
                ("fecha_resolucion", models.DateTimeField(blank=True, null=True)),
                (
                    "item_reporte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diferencias",
                        to="finance.itemreporte",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReporteProveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to="finanzas/reportes/%Y/%m/",
                        verbose_name="Archivo de Reporte",
                    ),
                ),
                ("fecha_carga", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PEN", "Pendiente por Procesar"),
                            ("PRO", "Procesado"),
                            ("ERR", "Error en Procesamiento"),
                        ],
                        default="PEN",
                        max_length=3,
                        verbose_name="Estado",
                    ),
                ),
                ("total_registros", models.IntegerField(default=0)),
                ("total_con_diferencia", models.IntegerField(default=0)),
                ("notas", models.TextField(blank=True)),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes_finance",
                        to="core.proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte de Proveedor",
                "verbose_name_plural": "Reportes de Proveedores",
            },
        ),
        migrations.AddField(
            model_name="itemreporte",
            name="reporte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="finance.reporteproveedor",
            ),
        ),
    ]
