# Generated by Django 5.2.6 on 2026-02-16 14:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_boletoimportado_solicitudanulacion"),
        ("core", "0074_delete_aerolineaconfig_and_more"),
        ("finance", "0002_itemreporte_diferenciafinanciera_reporteproveedor_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemreporte",
            name="boleto_interno",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items_reconciliacion",
                to="bookings.boletoimportado",
            ),
        ),
        # migrations.CreateModel(
        #     name="GastoOperativo",
        #     fields=[
        #         (
        #             "id_gasto",
        #             models.AutoField(
        #                 primary_key=True, serialize=False, verbose_name="ID Gasto"
        #             ),
        #         ),
        #         (
        #             "descripcion",
        #             models.CharField(max_length=255, verbose_name="Descripción"),
        #         ),
        #         (
        #             "monto",
        #             models.DecimalField(
        #                 decimal_places=2, max_digits=12, verbose_name="Monto"
        #             ),
        #         ),
        #         (
        #             "fecha",
        #             models.DateField(
        #                 default=django.utils.timezone.now, verbose_name="Fecha"
        #             ),
        #         ),
        #         (
        #             "categoria",
        #             models.CharField(
        #                 blank=True, max_length=100, null=True, verbose_name="Categoría"
        #             ),
        #         ),
        #         (
        #             "comprobante",
        #             models.FileField(
        #                 blank=True,
        #                 null=True,
        #                 upload_to="gastos/%Y/%m/",
        #                 verbose_name="Comprobante/Factura",
        #             ),
        #         ),
        #         ("fecha_registro", models.DateTimeField(auto_now_add=True)),
        #         (
        #             "creado_por",
        #             models.ForeignKey(
        #                 blank=True,
        #                 null=True,
        #                 on_delete=django.db.models.deletion.SET_NULL,
        #                 to=settings.AUTH_USER_MODEL,
        #                 verbose_name="Registrado por",
        #             ),
        #         ),
        #         (
        #             "moneda",
        #             models.ForeignKey(
        #                 on_delete=django.db.models.deletion.PROTECT,
        #                 to="core.moneda",
        #                 verbose_name="Moneda",
        #             ),
        #         ),
        #     ],
        #     options={
        #         "verbose_name": "Gasto Operativo",
        #         "verbose_name_plural": "Gastos Operativos",
        #         "db_table": "core_gastooperativo",
        #         "ordering": ["-fecha", "-fecha_registro"],
        #     },
        # ),
        migrations.CreateModel(
            name="PagoBinance",
            fields=[
                (
                    "id_pago_binance",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "prepay_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Binance Prepay ID",
                    ),
                ),
                (
                    "merchant_trade_no",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Internal Trade Number"
                    ),
                ),
                (
                    "checkout_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Checkout URL",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto"
                    ),
                ),
                (
                    "moneda",
                    models.CharField(
                        default="USDT", max_length=5, verbose_name="Moneda"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("INI", "Inicial / Pendiente"),
                            ("PRO", "Procesando"),
                            ("EXI", "Exitoso"),
                            ("FAL", "Fallido"),
                            ("EXP", "Expirado"),
                        ],
                        default="INI",
                        max_length=3,
                        verbose_name="Estado",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Respuesta API Binance"
                    ),
                ),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos_binance",
                        to="finance.factura",
                        verbose_name="Factura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago Binance Pay",
                "verbose_name_plural": "Pagos Binance Pay",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
