# Generated by Django 5.2.6 on 2026-05-04 13:42

import core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookings",
            "0010_comisionproveedorservicio_productoservicio_proveedor_and_more",
        ),
        ("finance", "0003_alter_factura_asiento_contable_factura_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Moneda",
                    fields=[
                        (
                            "id_moneda",
                            models.AutoField(
                                primary_key=True, serialize=False, verbose_name="ID Moneda"
                            ),
                        ),
                        (
                            "codigo_iso",
                            models.CharField(
                                help_text="Código ISO 4217 de la moneda (ej. USD, EUR, VEF).",
                                max_length=3,
                                unique=True,
                                verbose_name="Código ISO",
                            ),
                        ),
                        (
                            "nombre",
                            models.CharField(
                                max_length=50,
                                unique=True,
                                validators=[core.validators.validar_no_vacio_o_espacios],
                                verbose_name="Nombre de la Moneda",
                            ),
                        ),
                        (
                            "simbolo",
                            models.CharField(
                                blank=True, max_length=5, null=True, verbose_name="Símbolo"
                            ),
                        ),
                        (
                            "es_moneda_local",
                            models.BooleanField(
                                default=False,
                                help_text="Marcar si esta es la moneda principal de la agencia.",
                                verbose_name="Es Moneda Local",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Moneda",
                        "verbose_name_plural": "Monedas",
                        "db_table": "core_moneda",
                        "ordering": ["nombre"],
                    },
                ),
            ],
        ),
        migrations.AlterField(
            model_name="reporteproveedor",
            name="proveedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reportes_finance",
                to="bookings.proveedor",
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="moneda",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.moneda",
                verbose_name="Moneda",
            ),
        ),
        migrations.AlterField(
            model_name="facturaconsolidada",
            name="moneda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.moneda",
                verbose_name="Moneda",
            ),
        ),
        migrations.AlterField(
            model_name="gastooperativo",
            name="moneda",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.moneda",
                verbose_name="Moneda",
            ),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="TasaCambio",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("fecha", models.DateField(db_index=True)),
                        (
                            "moneda",
                            models.CharField(
                                choices=[("USD", "Dólar"), ("EUR", "Euro")],
                                default="USD",
                                max_length=3,
                            ),
                        ),
                        (
                            "monto",
                            models.DecimalField(
                                decimal_places=4,
                                help_text="Tasa de cambio oficial",
                                max_digits=10,
                            ),
                        ),
                        ("ultima_actualizacion", models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        "verbose_name": "Tasa de Cambio",
                        "verbose_name_plural": "Tasas de Cambio",
                        "db_table": "core_tasacambio",
                        "ordering": ["-fecha"],
                        "unique_together": {("fecha", "moneda")},
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="TipoCambio",
                    fields=[
                        (
                            "id_tipo_cambio",
                            models.AutoField(
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID Tipo de Cambio",
                            ),
                        ),
                        (
                            "fecha_efectiva",
                            models.DateField(
                                default=django.utils.timezone.now,
                                help_text="Fecha en que esta tasa de cambio entra en vigor.",
                                verbose_name="Fecha Efectiva",
                            ),
                        ),
                        (
                            "tasa_conversion",
                            models.DecimalField(
                                decimal_places=8,
                                help_text="Cuánto de la moneda destino equivale a 1 unidad de la moneda origen.",
                                max_digits=18,
                                verbose_name="Tasa de Conversión",
                            ),
                        ),
                        (
                            "moneda_destino",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="tipos_cambio_destino",
                                to="finance.moneda",
                                verbose_name="Moneda Destino",
                            ),
                        ),
                        (
                            "moneda_origen",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="tipos_cambio_origen",
                                to="finance.moneda",
                                verbose_name="Moneda Origen",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Tipo de Cambio",
                        "verbose_name_plural": "Tipos de Cambio",
                        "db_table": "core_tipocambio",
                        "ordering": ["-fecha_efectiva", "moneda_origen__codigo_iso"],
                        "unique_together": {
                            ("moneda_origen", "moneda_destino", "fecha_efectiva")
                        },
                    },
                ),
            ],
        ),
    ]
