# Generated by Django 5.2.6 on 2026-02-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_alter_itemreporte_boleto_interno_gastooperativo_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="itemreporte",
                    name="fecha_emision",
                    field=models.DateField(blank=True, null=True, verbose_name="Fecha Emisión"),
                ),
                migrations.AddField(
                    model_name="itemreporte",
                    name="monto_sistema",
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                migrations.AddField(
                    model_name="itemreporte",
                    name="pasajero",
                    field=models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Pasajero"
                    ),
                ),
                migrations.AddField(
                    model_name="itemreporte",
                    name="pnr",
                    field=models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="PNR"
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
