# Generated by Django 5.2.6 on 2026-02-19 13:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0076_facturaconsolidada_agencia"),
        (
            "finance",
            "0004_itemreporte_fecha_emision_itemreporte_monto_sistema_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="factura",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.agencia",
                verbose_name="Agencia",
            ),
        ),
        migrations.AddField(
            model_name="reporteproveedor",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.agencia",
                verbose_name="Agencia",
            ),
        ),
        migrations.CreateModel(
            name="GastoOperativo",
            fields=[
                (
                    "id_gasto",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID Gasto"
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto"
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Fecha"
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Categoría"
                    ),
                ),
                (
                    "comprobante",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="gastos/%Y/%m/",
                        verbose_name="Comprobante/Factura",
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "agencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.agencia",
                        verbose_name="Agencia",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
                (
                    "moneda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.moneda",
                        verbose_name="Moneda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gasto Operativo",
                "verbose_name_plural": "Gastos Operativos",
                "db_table": "core_gastooperativo",
                "ordering": ["-fecha", "-fecha_registro"],
            },
        ),
    ]
