# Generated by Django 5.2.6 on 2026-02-19 20:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_venta_core_venta_agencia_08a6ff_idx_and_more"),
        ("core", "0076_facturaconsolidada_agencia"),
        ("crm", "0005_cliente_personas_cl_agencia_243194_idx_and_more"),
        ("finance", "0005_factura_agencia_reporteproveedor_agencia_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReporteReconciliacion",
            fields=[
                (
                    "id_reporte",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("archivo", models.FileField(upload_to="finance/reportes/%Y/%m/")),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                (
                    "proveedor",
                    models.CharField(
                        help_text="Ej: BSP, KIU, SABRE, AMADEUS", max_length=50
                    ),
                ),
                ("periodo_inicio", models.DateField(blank=True, null=True)),
                ("periodo_fin", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente de Procesamiento"),
                            ("PROCESANDO", "Procesando con IA"),
                            ("PROCESADO", "Procesado Exitosamente"),
                            ("ERROR", "Error en Procesamiento"),
                            ("CON_DISCREPANCIAS", "Con Discrepancias Detectadas"),
                            ("CONCILIADO", "Conciliado Totalmente"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                (
                    "datos_extraidos",
                    models.JSONField(
                        blank=True, help_text="Raw data extraída por la IA", null=True
                    ),
                ),
                (
                    "resumen_conciliacion",
                    models.JSONField(
                        blank=True, help_text="Resumen de match/mismatch", null=True
                    ),
                ),
                ("error_log", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Reporte de Reconciliación",
                "verbose_name_plural": "Reportes de Reconciliación",
                "ordering": ["-fecha_subida"],
            },
        ),
        migrations.AddIndex(
            model_name="factura",
            index=models.Index(
                fields=["agencia", "fecha_emision"],
                name="core_factur_agencia_2438e6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="factura",
            index=models.Index(
                fields=["agencia", "estado"], name="core_factur_agencia_728849_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factura",
            index=models.Index(
                fields=["venta_asociada"], name="core_factur_venta_a_301d08_idx"
            ),
        ),
        migrations.AddField(
            model_name="reportereconciliacion",
            name="agencia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reportes_reconciliacion",
                to="core.agencia",
            ),
        ),
    ]
