# Generated by Django 5.2.6 on 2026-05-10 19:18
# Edited 2026-06-06: removed AlterModelTable(table=None) so state keeps
# db_table='core_xxx' for the renamed models.

"""Migración de base de datos para finance.
"""

from django.db import migrations


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("finance", "0005_diferenciafinanciera_agencia_itemfactura_agencia_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="factura",
            new_name="finance_fac_numero__8f5d18_idx",
            old_name="core_factur_numero__4980ce_idx",
        ),
        migrations.RenameIndex(
            model_name="factura",
            new_name="finance_fac_numero__5c27f0_idx",
            old_name="core_factur_numero__1af612_idx",
        ),
        migrations.RenameIndex(
            model_name="factura",
            new_name="finance_fac_fecha_e_93b651_idx",
            old_name="core_factur_fecha_e_f7be26_idx",
        ),
        migrations.RenameIndex(
            model_name="factura",
            new_name="finance_fac_tipo_fa_a0840c_idx",
            old_name="core_factur_tipo_fa_26c852_idx",
        ),
        migrations.RenameIndex(
            model_name="factura",
            new_name="finance_fac_agencia_39b623_idx",
            old_name="core_factur_agencia_2438e6_idx",
        ),
        migrations.RenameIndex(
            model_name="factura",
            new_name="finance_fac_agencia_bb6d18_idx",
            old_name="core_factur_agencia_728849_idx",
        ),
        migrations.RenameIndex(
            model_name="factura",
            new_name="finance_fac_venta_a_295412_idx",
            old_name="core_factur_venta_a_301d08_idx",
        ),
    ]
