# Generated by Django 5.2.6 on 2026-05-14 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookings",
            "0023_remove_boletoimportado_bookings_bo_agencia_1abd71_idx_and_more",
        ),
        (
            "contabilidad",
            "0005_asientocontable_agencia_detalleasiento_agencia_and_more",
        ),
        ("core", "0028_alter_agencia_activa_and_more"),
        ("crm", "0014_alter_pasajero_options_and_more"),
        (
            "finance",
            "0006_rename_core_factur_numero__4980ce_idx_finance_fac_numero__8f5d18_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="factura",
            name="finance_fac_agencia_39b623_idx",
        ),
        migrations.RemoveIndex(
            model_name="factura",
            name="finance_fac_agencia_bb6d18_idx",
        ),
        migrations.AlterField(
            model_name="comisionventa",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="conciliacionboleto",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="factura",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="gastooperativo",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="itemfactura",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="lineareportereconciliacion",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="liquidacionagente",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="pagobinance",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="reglacomision",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="reportereconciliacion",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="transaccionpago",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="comisionventa",
            index=models.Index(
                fields=["is_deleted", "agencia"], name="idx_comisionvta_sd_saas"
            ),
        ),
        migrations.AddIndex(
            model_name="conciliacionboleto",
            index=models.Index(fields=["estado"], name="idx_concil_estado"),
        ),
        migrations.AddIndex(
            model_name="conciliacionboleto",
            index=models.Index(
                fields=["is_deleted", "agencia_id"], name="idx_concil_soft_delete_saas"
            ),
        ),
        migrations.AddIndex(
            model_name="factura",
            index=models.Index(
                fields=["agencia_id", "fecha_emision"],
                name="finance_fac_agencia_39b623_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="factura",
            index=models.Index(
                fields=["agencia_id", "estado"], name="finance_fac_agencia_bb6d18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factura",
            index=models.Index(
                fields=["is_deleted", "agencia_id"], name="idx_factura_soft_delete_saas"
            ),
        ),
        migrations.AddIndex(
            model_name="gastooperativo",
            index=models.Index(
                fields=["is_deleted", "agencia"], name="idx_gasto_soft_delete_saas"
            ),
        ),
        migrations.AddIndex(
            model_name="itemfactura",
            index=models.Index(
                fields=["is_deleted", "agencia_id"],
                name="idx_itemfact_soft_delete_saas",
            ),
        ),
        migrations.AddIndex(
            model_name="liquidacionagente",
            index=models.Index(
                fields=["is_deleted", "agencia"], name="idx_liqagente_sd_saas"
            ),
        ),
        migrations.AddIndex(
            model_name="reglacomision",
            index=models.Index(
                fields=["is_deleted", "agencia"], name="idx_reglacom_sd_saas"
            ),
        ),
    ]
