# Generated by Django 5.2.6 on 2026-05-18 15:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0025_boletoimportado_raw_hash"),
        ("core", "0031_agenciaconfiguracion_evolution_api_key_and_more"),
        ("finance", "0008_alter_comisionventa_agencia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="factura",
            name="cliente_es_residente",
            field=models.BooleanField(
                default=True,
                help_text="Determina si aplica exportación de servicios (alícuota 0%)",
                verbose_name="Cliente es Residente",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="cliente_identificacion",
            field=models.CharField(
                blank=True,
                help_text="Cédula, RIF o Pasaporte",
                max_length=50,
                verbose_name="Identificación Cliente",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="emisor_direccion_fiscal",
            field=models.TextField(blank=True, verbose_name="Dirección Fiscal Emisor"),
        ),
        migrations.AddField(
            model_name="factura",
            name="emisor_razon_social",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Razón Social Emisor"
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="emisor_rif",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="RIF Emisor"
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="es_sujeto_pasivo_especial",
            field=models.BooleanField(
                default=False,
                help_text="Determina obligaciones como agente de percepción IGTF",
                verbose_name="Es Sujeto Pasivo Especial",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="esta_inscrita_rtn",
            field=models.BooleanField(
                default=False,
                help_text="Registro Turístico Nacional",
                verbose_name="Inscrita en RTN",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="firma_digital",
            field=models.TextField(blank=True, null=True, verbose_name="Firma Digital"),
        ),
        migrations.AddField(
            model_name="factura",
            name="modalidad_emision",
            field=models.CharField(
                choices=[
                    ("DIGITAL", "Digital"),
                    ("CONTINGENCIA_FISICA", "Contingencia Física"),
                ],
                default="DIGITAL",
                max_length=20,
                verbose_name="Modalidad de Emisión",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="moneda_operacion",
            field=models.CharField(
                choices=[("BOLIVAR", "Bolívar"), ("DIVISA", "Divisa")],
                default="DIVISA",
                max_length=10,
                verbose_name="Moneda de Operación",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="monto_igtf",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="IGTF 3%"
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="monto_igtf_bs",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="IGTF Bs",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="monto_iva_16",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="IVA 16%"
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="monto_iva_16_bs",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="IVA 16% Bs",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="monto_iva_adicional",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="IVA Adicional Divisas",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="monto_total_bs",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="Total Bs",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="subtotal_base_gravada",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Base Gravada 16%",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="subtotal_base_gravada_bs",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="Base Gravada Bs",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="subtotal_exento",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Base Exenta"
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="subtotal_exento_bs",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="Base Exenta Bs",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="subtotal_exportacion",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Base Exportación 0%",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="tasa_cambio_bcv",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Tasa oficial BCV del día de la operación",
                max_digits=12,
                null=True,
                verbose_name="Tasa de Cambio BCV",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="tercero_razon_social",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Razón Social Tercero"
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="tercero_rif",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="RIF Tercero"
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="tipo_operacion",
            field=models.CharField(
                choices=[
                    ("VENTA_PROPIA", "Venta Propia"),
                    ("INTERMEDIACION", "Intermediación"),
                ],
                default="VENTA_PROPIA",
                max_length=20,
                verbose_name="Tipo de Operación",
            ),
        ),
        migrations.AddField(
            model_name="itemfactura",
            name="alicuota_iva",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("16.00"),
                max_digits=5,
                verbose_name="Alícuota IVA",
            ),
        ),
        migrations.AddField(
            model_name="itemfactura",
            name="codigo_aerolinea",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Código Aerolínea"
            ),
        ),
        migrations.AddField(
            model_name="itemfactura",
            name="es_gravado",
            field=models.BooleanField(default=True, verbose_name="Es Gravado"),
        ),
        migrations.AddField(
            model_name="itemfactura",
            name="itinerario",
            field=models.TextField(blank=True, verbose_name="Itinerario"),
        ),
        migrations.AddField(
            model_name="itemfactura",
            name="nombre_pasajero",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Nombre Pasajero"
            ),
        ),
        migrations.AddField(
            model_name="itemfactura",
            name="numero_boleto",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Número Boleto"
            ),
        ),
        migrations.AddField(
            model_name="itemfactura",
            name="tipo_servicio",
            field=models.CharField(
                choices=[
                    ("COMISION_INTERMEDIACION", "Comisión Intermediación"),
                    ("TRANSPORTE_AEREO_NACIONAL", "Transporte Aéreo Nacional"),
                    ("ALOJAMIENTO_Y_OTROS_GRAVADOS", "Alojamiento y Otros Gravados"),
                    ("SERVICIO_EXPORTACION", "Servicio Exportación"),
                ],
                default="ALOJAMIENTO_Y_OTROS_GRAVADOS",
                max_length=30,
                verbose_name="Tipo de Servicio",
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="cliente_direccion",
            field=models.TextField(blank=True, verbose_name="Dirección Cliente"),
        ),
        migrations.CreateModel(
            name="DocumentoExportacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("PASAPORTE", "Pasaporte"),
                            ("COMPROBANTE_PAGO", "Comprobante Pago Internacional"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo Documento",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(max_length=100, verbose_name="Número Documento"),
                ),
                (
                    "archivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documentos_exportacion/%Y/%m/",
                        verbose_name="Archivo",
                    ),
                ),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                (
                    "factura",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos_exportacion",
                        to="finance.factura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Exportación",
                "verbose_name_plural": "Documentos Exportación",
            },
        ),
        migrations.CreateModel(
            name="FacturaProveedor",
            fields=[
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id_factura_proveedor",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "proveedor_nombre",
                    models.CharField(max_length=255, verbose_name="Proveedor (Texto)"),
                ),
                (
                    "numero_factura",
                    models.CharField(max_length=100, verbose_name="Número de Factura"),
                ),
                (
                    "monto_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto Total"
                    ),
                ),
                ("fecha_emision", models.DateField(verbose_name="Fecha de Emisión")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PEN_CON", "Pendiente de Conciliación"),
                            ("CONCILIADA", "Conciliada"),
                            ("RECHAZADA", "Rechazada"),
                            ("REV_MAN", "Requiere Revisión Manual"),
                        ],
                        default="PEN_CON",
                        max_length=20,
                    ),
                ),
                (
                    "raw_hash",
                    models.CharField(
                        db_index=True,
                        help_text="Hash SHA-256 del contenido para evitar duplicidad",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "archivo_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="facturas_proveedores/%Y/%m/"
                    ),
                ),
                (
                    "datos_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Estructura completa extraída por IA",
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "agencia",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="core.agencia",
                    ),
                ),
                (
                    "moneda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance.moneda",
                        verbose_name="Moneda",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="facturas_proveedor_registradas",
                        to="bookings.proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura de Proveedor",
                "verbose_name_plural": "Facturas de Proveedores",
                "ordering": ["-fecha_registro"],
                "indexes": [
                    models.Index(
                        fields=["agencia", "estado"],
                        name="finance_fac_agencia_500cf7_idx",
                    ),
                    models.Index(
                        fields=["raw_hash"], name="finance_fac_raw_has_594055_idx"
                    ),
                ],
            },
        ),
    ]
