# Generated by Django 5.2.6 on 2026-05-18 15:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_factura_cliente_es_residente_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factura",
            name="iva_porcentaje",
            field=models.DecimalField(
                decimal_places=2, default=25, max_digits=5, verbose_name="% IVA"
            ),
        ),
        migrations.AlterField(
            model_name="itemfactura",
            name="alicuota_iva",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("25.00"),
                max_digits=5,
                verbose_name="Alícuota IVA",
            ),
        ),
        migrations.AlterField(
            model_name="itemfactura",
            name="tipo_impuesto",
            field=models.CharField(
                choices=[
                    ("25", "IVA General (25%)"),
                    ("16", "IVA General Legacy (16%)"),
                    ("08", "IVA Reducido (8%)"),
                    ("00", "Exento / No Sujeto"),
                ],
                default="25",
                max_length=2,
                verbose_name="Tipo Impuesto",
            ),
        ),
    ]
