# Generated by Django 5.2.6 on 2026-05-18 15:41

"""Migración de base de datos para finance.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("finance", "0010_alter_factura_iva_porcentaje_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retencionislr",
            name="factura",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="retenciones_islr",
                to="finance.factura",
                verbose_name="Factura",
            ),
        ),
    ]
