# Generated by Django 5.2.6 on 2026-05-18 19:01

"""Migración de base de datos para finance.
"""

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("core", "0031_agenciaconfiguracion_evolution_api_key_and_more"),
        ("finance", "0011_alter_retencionislr_factura"),
        ("bookings", "0033_alter_actividadservicio_managers_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facturaconsolidada",
            name="agencia",
        ),
        migrations.RemoveField(
            model_name="facturaconsolidada",
            name="asiento_contable_factura",
        ),
        migrations.RemoveField(
            model_name="facturaconsolidada",
            name="cliente",
        ),
        migrations.RemoveField(
            model_name="facturaconsolidada",
            name="moneda",
        ),
        migrations.RemoveField(
            model_name="facturaconsolidada",
            name="venta_asociada",
        ),
        migrations.RemoveField(
            model_name="itemfacturaconsolidada",
            name="factura",
        ),
        migrations.CreateModel(
            name="PropuestaTransaccionIA",
            fields=[
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id_propuesta",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "modulo_objetivo",
                    models.CharField(max_length=50, verbose_name="Módulo Objetivo"),
                ),
                (
                    "accion_tipo",
                    models.CharField(max_length=50, verbose_name="Tipo de Acción"),
                ),
                (
                    "payload_datos",
                    models.JSONField(
                        help_text="Datos exactos a procesar determinísticamente al aprobar",
                        verbose_name="Payload de Datos",
                    ),
                ),
                (
                    "ia_justificacion",
                    models.TextField(
                        help_text="Explicación y razonamiento en lenguaje natural de la IA",
                        verbose_name="Justificación de la IA",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PEN", "Pendiente de Aprobación"),
                            ("APR", "Aprobada y Procesada"),
                            ("REC", "Rechazada"),
                        ],
                        default="PEN",
                        max_length=3,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha Creación"),
                ),
                (
                    "fecha_resolucion",
                    models.DateTimeField(blank=True, null=True, verbose_name="Fecha Resolución"),
                ),
                (
                    "comentarios_resolucion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Comentarios de Resolución"
                    ),
                ),
                (
                    "agencia",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="core.agencia",
                    ),
                ),
                (
                    "usuario_resolutor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="propuestas_ia_resueltas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario Resolutor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Propuesta Transacción IA",
                "verbose_name_plural": "Propuestas Transacción IA",
                "db_table": "finance_propuesta_transaccion_ia",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.DeleteModel(
            name="DocumentoExportacionConsolidado",
        ),
        migrations.DeleteModel(
            name="FacturaConsolidada",
        ),
        migrations.DeleteModel(
            name="ItemFacturaConsolidada",
        ),
    ]
