# Generated by Django 5.2.6 on 2026-05-19 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_agenciaconfiguracion_evolution_api_key_and_more"),
        ("finance", "0013_staging_ledger_buffer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="propuestatransaccionia",
            options={
                "ordering": ["-fecha_creacion"],
                "verbose_name": "Propuesta Transacción IA",
                "verbose_name_plural": "Propuestas Transacción IA",
            },
        ),
        migrations.RemoveIndex(
            model_name="propuestatransaccionia",
            name="finance_pro_agencia_ea911b_idx",
        ),
        migrations.RenameField(
            model_name="propuestatransaccionia",
            old_name="id",
            new_name="id_propuesta",
        ),
        migrations.RemoveField(
            model_name="propuestatransaccionia",
            name="justificacion",
        ),
        migrations.AddField(
            model_name="propuestatransaccionia",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="propuestatransaccionia",
            name="ia_justificacion",
            field=models.TextField(
                default="",
                help_text="Explicación y razonamiento en lenguaje natural de la IA",
                verbose_name="Justificación de la IA",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="propuestatransaccionia",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="propuestatransaccionia",
            name="modulo_objetivo",
            field=models.CharField(default="", max_length=50, verbose_name="Módulo Objetivo"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="propuestatransaccionia",
            name="accion_tipo",
            field=models.CharField(max_length=50, verbose_name="Tipo de Acción"),
        ),
        migrations.AlterField(
            model_name="propuestatransaccionia",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
        migrations.AlterField(
            model_name="propuestatransaccionia",
            name="comentarios_resolucion",
            field=models.TextField(blank=True, null=True, verbose_name="Comentarios de Resolución"),
        ),
        migrations.AlterField(
            model_name="propuestatransaccionia",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PEN", "Pendiente de Aprobación"),
                    ("APR", "Aprobada y Procesada"),
                    ("REC", "Rechazada"),
                ],
                default="PEN",
                max_length=3,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="propuestatransaccionia",
            name="fecha_creacion",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Fecha Creación"),
        ),
        migrations.AlterField(
            model_name="propuestatransaccionia",
            name="fecha_resolucion",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fecha Resolución"),
        ),
        migrations.AlterField(
            model_name="propuestatransaccionia",
            name="payload_datos",
            field=models.JSONField(
                help_text="Datos exactos a procesar determinísticamente al aprobar",
                verbose_name="Payload de Datos",
            ),
        ),
        migrations.AlterField(
            model_name="propuestatransaccionia",
            name="usuario_resolutor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="propuestas_ia_resueltas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario Resolutor",
            ),
        ),
        migrations.AlterModelTable(
            name="propuestatransaccionia",
            table="finance_propuesta_transaccion_ia",
        ),
    ]
