# Generated by Django 5.2.6 on 2026-05-19 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_agenciaconfiguracion_evolution_api_key_and_more"),
        ("finance", "0013_staging_ledger_buffer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = []
