# Generated by Django 5.2.6 on 2026-05-19 01:49

"""Migración de base de datos para finance.
"""

from django.conf import settings
from django.db import migrations


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("core", "0031_agenciaconfiguracion_evolution_api_key_and_more"),
        ("finance", "0013_staging_ledger_buffer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = []
