# Generated by Django 5.2.6 on 2026-05-22 02:03

from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0027_boletoimportadotransito"),
        ("core", "0032_agenciaconfiguracion_gemini_api_key"),
        ("finance", "0014_alter_propuestatransaccionia_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CanalRecaudacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre del Canal"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CONSOLIDADOR", "Consolidador Internacional (IATA/BSP)"),
                            ("EFECTIVO", "Efectivo Cash USD"),
                            ("CUSTODIA", "Cuenta de Custodia Nacional"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Canal",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Descripción / Detalles Cuenta",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "agencia",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="core.agencia",
                    ),
                ),
                (
                    "moneda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance.moneda",
                        verbose_name="Moneda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Canal de Recaudación",
                "verbose_name_plural": "Canales de Recaudación",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id_pago", models.AutoField(primary_key=True, serialize=False)),
                (
                    "monto",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Monto Pago"),
                ),
                (
                    "tasa_cambio",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.0000"),
                        max_digits=12,
                        verbose_name="Tasa de Cambio",
                    ),
                ),
                (
                    "igtf_monto",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Monto IGTF (3%)",
                    ),
                ),
                (
                    "igtf_aplicado",
                    models.BooleanField(default=False, verbose_name="IGTF Aplicado"),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Referencia de Transacción",
                    ),
                ),
                (
                    "fecha_pago",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Fecha de Pago"
                    ),
                ),
                (
                    "confirmado",
                    models.BooleanField(default=True, verbose_name="Confirmado"),
                ),
                (
                    "comprobante",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="recaudaciones/comprobantes/%Y/%m/",
                        verbose_name="Comprobante de Pago",
                    ),
                ),
                (
                    "notas",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "agencia",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="core.agencia",
                    ),
                ),
                (
                    "canal_recaudacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos",
                        to="finance.canalrecaudacion",
                        verbose_name="Canal de Recaudación",
                    ),
                ),
                (
                    "moneda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance.moneda",
                        verbose_name="Moneda",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos_finanzas_recaudacion",
                        to="bookings.venta",
                        verbose_name="Venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago de Recaudación",
                "verbose_name_plural": "Pagos de Recaudación",
                "ordering": ["-fecha_pago", "-creado"],
            },
        ),
    ]
