# Generated by Django 5.2.6 on 2026-06-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0031_alter_actividadservicio_agencia_and_more"),
        ("finance", "0016_alter_canalrecaudacion_agencia_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="linkdepago",
            index=models.Index(fields=["estado"], name="idx_linkpago_estado"),
        ),
    ]
