# Generated by Django 5.2.6 on 2026-06-02 02:54

"""Modelos de base de datos para la aplicación finance.
"""

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("core", "0035_agencia_mixin_finance_models"),
        ("finance", "0017_add_missing_indexes"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="canalrecaudacion",
            managers=[
                ("with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="comisionventa",
            managers=[
                ("with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="conciliacionboleto",
            managers=[
                ("with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="factura",
            managers=[
                ("with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="facturaproveedor",
            managers=[
                ("with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="gastooperativo",
            managers=[
                ("with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="itemfactura",
            managers=[
                ("with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="lineareportereconciliacion",
            managers=[
                ("with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="liquidacionagente",
            managers=[
                ("with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pago",
            managers=[
                ("with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pagobinance",
            managers=[
                ("with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="propuestatransaccionia",
            managers=[
                ("with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="reglacomision",
            managers=[
                ("with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="reportereconciliacion",
            managers=[
                ("with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="transaccionpago",
            managers=[
                ("with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="linkdepago",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
        migrations.AddField(
            model_name="retencionislr",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
    ]
