# Generated by Django 5.2.6 on 2026-06-02 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0032_add_facturafiscal_agencia"),
        ("core", "0035_agencia_mixin_finance_models"),
        ("finance", "0018_agencia_mixin_finance_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacturaFiscal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_factura",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Número de Factura Fiscal",
                    ),
                ),
                (
                    "numero_control",
                    models.CharField(blank=True, max_length=50, verbose_name="Número de Control"),
                ),
                (
                    "cadena_firma_digital",
                    models.TextField(blank=True, verbose_name="Cadena de Firma Digital"),
                ),
                (
                    "xml_generado",
                    models.TextField(blank=True, verbose_name="XML Fiscal Generado"),
                ),
                (
                    "estado_fiscal",
                    models.CharField(
                        choices=[
                            ("PEN", "Pendiente de Envío"),
                            ("PRO", "En Procesamiento / Firmado"),
                            ("APR", "Aprobada / Autorizada"),
                            ("REC", "Rechazada por Error Fiscal"),
                        ],
                        default="PEN",
                        max_length=3,
                        verbose_name="Estado Fiscal",
                    ),
                ),
                (
                    "ultimo_mensaje_error",
                    models.TextField(blank=True, null=True, verbose_name="Último Error"),
                ),
                (
                    "fecha_emision_fiscal",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Emisión Fiscal"
                    ),
                ),
                (
                    "agencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="core.agencia",
                    ),
                ),
                (
                    "venta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factura_fiscal",
                        to="bookings.venta",
                        verbose_name="Venta Asociada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura Fiscal Electrónica",
                "verbose_name_plural": "Facturas Fiscales Electrónicas",
            },
        ),
    ]
