# Generated by Django 5.2.6 on 2026-06-02 03:03

from django.db import migrations


def backfill_agencia(apps, schema_editor):
    """
    Backfill agencia FK on RetencionISLR, LinkDePago, FacturaFiscal
    from their related objects (Factura, Venta).
    """
    apps.get_model("core", "Agencia")
    db_alias = schema_editor.connection.alias

    # RetencionISLR: agencia comes from factura.venta.agencia or factura.agencia
    RetencionISLR = apps.get_model("finance", "RetencionISLR")
    for ret in RetencionISLR.objects.using(db_alias).filter(agencia__isnull=True):
        if ret.factura_id:
            Factura = apps.get_model("finance", "Factura")
            try:
                factura = Factura.objects.using(db_alias).get(pk=ret.factura_id)
                if factura.agencia_id:
                    ret.agencia_id = factura.agencia_id
                    ret.save(update_fields=["agencia_id"])
                    continue
            except Factura.DoesNotExist:
                pass
            if factura.venta_asociada_id:
                Venta = apps.get_model("bookings", "Venta")
                try:
                    venta = Venta.objects.using(db_alias).get(pk=factura.venta_asociada_id)
                    if venta.agencia_id:
                        ret.agencia_id = venta.agencia_id
                        ret.save(update_fields=["agencia_id"])
                except Venta.DoesNotExist:
                    pass

    # LinkDePago: agencia comes from venta.agencia
    LinkDePago = apps.get_model("finance", "LinkDePago")
    Venta = apps.get_model("bookings", "Venta")
    for link in LinkDePago.objects.using(db_alias).filter(agencia__isnull=True):
        try:
            venta = Venta.objects.using(db_alias).get(pk=link.venta_id)
            if venta.agencia_id:
                link.agencia_id = venta.agencia_id
                link.save(update_fields=["agencia_id"])
        except Venta.DoesNotExist:
            pass

    # FacturaFiscal: agencia comes from venta.agencia
    FacturaFiscal = apps.get_model("finance", "FacturaFiscal")
    for ff in FacturaFiscal.objects.using(db_alias).filter(agencia__isnull=True):
        try:
            venta = Venta.objects.using(db_alias).get(pk=ff.venta_id)
            if venta.agencia_id:
                ff.agencia_id = venta.agencia_id
                ff.save(update_fields=["agencia_id"])
        except Venta.DoesNotExist:
            pass


def reverse_backfill(apps, schema_editor):
    # reverse_backfill: Reverse backfill. Args: según implementación. Returns: según implementación.
    pass


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("finance", "0019_add_facturafiscal_agencia"),
    ]

    operations = [
        migrations.RunPython(backfill_agencia, reverse_backfill),
    ]
