# Generated by Django 5.2.6 on 2026-06-03 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_moneda"),
        ("contabilidad", "0008_alter_asientocontable_moneda"),
        ("core", "0035_agencia_mixin_finance_models"),
        ("cotizaciones", "0007_alter_cotizacion_moneda"),
        ("crm", "0020_alter_cliente_managers_and_more"),
        ("finance", "0020_backfill_agencia_finance"),
    ]

    operations = [
        migrations.CreateModel(
            name="TasaCambioBCV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(db_index=True, unique=True)),
                (
                    "tasa_usd",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Tasa de cambio oficial USD",
                        max_digits=10,
                    ),
                ),
                (
                    "tasa_eur",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Tasa de cambio oficial EUR",
                        max_digits=10,
                    ),
                ),
                ("ultima_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tasa de Cambio BCV",
                "verbose_name_plural": "Tasas de Cambio BCV",
                "ordering": ["-fecha"],
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="pago",
                    name="moneda",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.moneda",
                        verbose_name="Moneda",
                    ),
                ),
                migrations.AlterField(
                    model_name="gastooperativo",
                    name="moneda",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.moneda",
                        verbose_name="Moneda",
                    ),
                ),
                migrations.AlterField(
                    model_name="facturaproveedor",
                    name="moneda",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.moneda",
                        verbose_name="Moneda",
                    ),
                ),
                migrations.AlterField(
                    model_name="canalrecaudacion",
                    name="moneda",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.moneda",
                        verbose_name="Moneda",
                    ),
                ),
                migrations.AlterField(
                    model_name="factura",
                    name="moneda",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.moneda",
                        verbose_name="Moneda",
                    ),
                ),
                migrations.AlterField(
                    model_name="tipocambio",
                    name="moneda_destino",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tipos_cambio_destino",
                        to="common.moneda",
                        verbose_name="Moneda Destino",
                    ),
                ),
                migrations.AlterField(
                    model_name="tipocambio",
                    name="moneda_origen",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tipos_cambio_origen",
                        to="common.moneda",
                        verbose_name="Moneda Origen",
                    ),
                ),
                migrations.AlterModelManagers(
                    name="canalrecaudacion",
                    managers=[],
                ),
                migrations.AlterModelManagers(
                    name="comisionventa",
                    managers=[],
                ),
                migrations.AlterModelManagers(
                    name="conciliacionboleto",
                    managers=[],
                ),
                migrations.AlterModelManagers(
                    name="factura",
                    managers=[],
                ),
                migrations.AlterModelManagers(
                    name="facturaproveedor",
                    managers=[],
                ),
                migrations.AlterModelManagers(
                    name="gastooperativo",
                    managers=[],
                ),
                migrations.AlterModelManagers(
                    name="itemfactura",
                    managers=[],
                ),
                migrations.AlterModelManagers(
                    name="lineareportereconciliacion",
                    managers=[],
                ),
                migrations.AlterModelManagers(
                    name="liquidacionagente",
                    managers=[],
                ),
                migrations.AlterModelManagers(
                    name="pago",
                    managers=[],
                ),
                migrations.AlterModelManagers(
                    name="pagobinance",
                    managers=[],
                ),
                migrations.AlterModelManagers(
                    name="propuestatransaccionia",
                    managers=[],
                ),
                migrations.AlterModelManagers(
                    name="reglacomision",
                    managers=[],
                ),
                migrations.AlterModelManagers(
                    name="reportereconciliacion",
                    managers=[],
                ),
                migrations.AlterModelManagers(
                    name="transaccionpago",
                    managers=[],
                ),
                migrations.RemoveIndex(
                    model_name="factura",
                    name="finance_fac_venta_a_295412_idx",
                ),
                migrations.RemoveField(
                    model_name="factura",
                    name="venta_asociada",
                ),
                migrations.AddField(
                    model_name="factura",
                    name="venta_asociada_id",
                    field=models.IntegerField(
                        blank=True, null=True, verbose_name="ID Venta Asociada"
                    ),
                ),
                migrations.AddIndex(
                    model_name="factura",
                    index=models.Index(
                        fields=["venta_asociada_id"], name="finance_fac_venta_a_295412_idx"
                    ),
                ),
                migrations.DeleteModel(
                    name="Moneda",
                ),
            ],
        ),
    ]
