# Generated by Django 5.2.6 on 2026-06-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0021_tasacambiobcv_alter_pago_moneda_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comisionventa",
            name="venta",
        ),
        migrations.RemoveField(
            model_name="linkdepago",
            name="venta",
        ),
        migrations.AddField(
            model_name="comisionventa",
            name="venta_id",
            field=models.IntegerField(default=1, verbose_name="ID Venta"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="linkdepago",
            name="venta_id",
            field=models.IntegerField(default=1, unique=True, verbose_name="ID Venta"),
            preserve_default=False,
        ),
    ]
