# Generated by Django 5.2.14 on 2026-06-06 20:37

"""Migración de base de datos para finance.
"""

from django.db import migrations


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    # Edited 2026-06-07: wrap in SeparateDatabaseAndState with
    # database_operations=[] because the tables named in the original
    # AlterModelTable(table=None) operations were already renamed
    # manually (or via pg_dump --schema-only + migrate --fake) in
    # dev/prod. State-only update is safe and idempotent in fresh-DB.

    dependencies = [
        ("finance", "0022_remove_comisionventa_venta_remove_linkdepago_venta_and_more"),
        ("core", "0037_rename_remaining_core_tables"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelTable(
                    name="factura",
                    table=None,
                ),
                migrations.AlterModelTable(
                    name="gastooperativo",
                    table=None,
                ),
                migrations.AlterModelTable(
                    name="itemfactura",
                    table=None,
                ),
                migrations.AlterModelTable(
                    name="tasacambio",
                    table=None,
                ),
                migrations.AlterModelTable(
                    name="tipocambio",
                    table=None,
                ),
            ],
        ),
    ]
