# Generated by Django 5.2.14 on 2026-06-08 00:27

"""Migración de base de datos para finance.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("bookings", "0035_alter_feeventa_venta_alter_pagoventa_venta"),
        ("finance", "0023_alter_factura_table_alter_gastooperativo_table_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentoexportacion",
            name="factura",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documentos_exportacion",
                to="finance.factura",
            ),
        ),
        migrations.AlterField(
            model_name="itemfactura",
            name="factura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items_factura",
                to="finance.factura",
                verbose_name="Factura",
            ),
        ),
        migrations.AlterField(
            model_name="pagobinance",
            name="factura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pagos_binance",
                to="finance.factura",
                verbose_name="Factura",
            ),
        ),
        migrations.AlterField(
            model_name="transaccionpago",
            name="venta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transacciones_pago",
                to="bookings.venta",
                verbose_name="Venta",
            ),
        ),
    ]
