# Generated by Django 5.2.14 on 2026-06-12 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0042_alter_actividadservicio_incluye_and_more"),
        ("core", "0040_aeropuerto"),
        ("finance", "0026_add_missing_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="factura",
            name="finance_fac_venta_a_295412_idx",
        ),
        migrations.RemoveField(
            model_name="comisionventa",
            name="venta_id",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="venta_asociada_id",
        ),
        migrations.RemoveField(
            model_name="linkdepago",
            name="venta_id",
        ),
        migrations.AddField(
            model_name="comisionventa",
            name="venta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bookings.venta",
                verbose_name="Venta",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="venta_asociada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bookings.venta",
                verbose_name="Venta Asociada",
            ),
        ),
        migrations.AddField(
            model_name="linkdepago",
            name="venta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bookings.venta",
                unique=True,
                verbose_name="Venta",
            ),
        ),
        migrations.AlterField(
            model_name="linkdepago",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
        migrations.AlterField(
            model_name="retencionislr",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
    ]
