# Generated by Django 5.2.14 on 2026-06-24 17:56

"""Migración de base de datos para finance.
"""

from django.db import migrations, models

import core.validators


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("finance", "0028_drop_orphaned_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factura",
            name="archivo_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="facturas/%Y/%m/",
                validators=[core.validators.antivirus_hook],
                verbose_name="Archivo PDF",
            ),
        ),
        migrations.AlterField(
            model_name="facturaproveedor",
            name="archivo_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="facturas_proveedores/%Y/%m/",
                validators=[core.validators.antivirus_hook],
            ),
        ),
        migrations.AlterField(
            model_name="gastooperativo",
            name="comprobante",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="gastos/%Y/%m/",
                validators=[core.validators.antivirus_hook],
                verbose_name="Comprobante/Factura",
            ),
        ),
        migrations.AlterField(
            model_name="linkdepago",
            name="comprobante_imagen",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="comprobantes_pago/",
                validators=[core.validators.antivirus_hook],
            ),
        ),
        migrations.AlterField(
            model_name="retencionislr",
            name="archivo_comprobante",
            field=models.FileField(
                blank=True,
                help_text="PDF del comprobante de retención",
                null=True,
                upload_to="retenciones_islr/%Y/%m/",
                validators=[core.validators.antivirus_hook],
                verbose_name="Archivo Comprobante",
            ),
        ),
    ]
