# Generated by Django 5.2.14 on 2026-06-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0029_alter_factura_archivo_pdf_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factura",
            name="archivo_pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="facturas/%Y/%m/", verbose_name="Archivo PDF"
            ),
        ),
        migrations.AlterField(
            model_name="facturaproveedor",
            name="archivo_pdf",
            field=models.FileField(blank=True, null=True, upload_to="facturas_proveedores/%Y/%m/"),
        ),
        migrations.AlterField(
            model_name="gastooperativo",
            name="comprobante",
            field=models.FileField(
                blank=True, null=True, upload_to="gastos/%Y/%m/", verbose_name="Comprobante/Factura"
            ),
        ),
        migrations.AlterField(
            model_name="linkdepago",
            name="comprobante_imagen",
            field=models.ImageField(blank=True, null=True, upload_to="comprobantes_pago/"),
        ),
        migrations.AlterField(
            model_name="retencionislr",
            name="archivo_comprobante",
            field=models.FileField(
                blank=True,
                help_text="PDF del comprobante de retención",
                null=True,
                upload_to="retenciones_islr/%Y/%m/",
                verbose_name="Archivo Comprobante",
            ),
        ),
    ]
