# Generated by Django 5.2.14 on 2026-07-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0030_alter_factura_archivo_pdf_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemfactura",
            name="tipo_servicio",
            field=models.CharField(
                choices=[
                    ("COMISION_INTERMEDIACION", "Comisión Intermediación"),
                    ("TRANSPORTE_AEREO_NACIONAL", "Transporte Aéreo Nacional"),
                    ("TRANSPORTE_AEREO_INTERNACIONAL", "Transporte Aéreo Internacional"),
                    ("ALOJAMIENTO_Y_OTROS_GRAVADOS", "Alojamiento y Otros Gravados"),
                    ("SERVICIO_EXPORTACION", "Servicio Exportación"),
                ],
                default="ALOJAMIENTO_Y_OTROS_GRAVADOS",
                max_length=30,
                verbose_name="Tipo de Servicio",
            ),
        ),
    ]
