# Generated by Django 5.2.14 on 2026-07-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0031_alter_itemfactura_tipo_servicio"),
    ]

    operations = [
        migrations.AddField(
            model_name="factura",
            name="tipo",
            field=models.CharField(
                choices=[("SIMPLE", "Simple"), ("CONSOLIDADA", "Consolidada")],
                default="SIMPLE",
                max_length=20,
                verbose_name="Tipo de Factura",
            ),
        ),
        migrations.AddIndex(
            model_name="factura",
            index=models.Index(fields=["tipo", "agencia"], name="finance_factura_tipo_idx"),
        ),
    ]
