# Generated by Django 5.2.14 on 2026-07-14 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0050_delete_numberingsequence"),
        ("crm", "0034_remove_whatsappscheduledmessage_is_deleted_and_more"),
        ("finance", "0033_facturaconsolidada_agencia_mixin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Moneda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_iso", models.CharField(max_length=3)),
                ("nombre", models.CharField(max_length=50)),
                ("simbolo", models.CharField(max_length=5)),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionFiscal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iva_por_defecto",
                    models.DecimalField(decimal_places=4, default=16.0, max_digits=15),
                ),
                (
                    "igtf_por_defecto",
                    models.DecimalField(decimal_places=4, default=3.0, max_digits=15),
                ),
                ("es_contribuyente_especial", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Configuración Fiscal",
                "verbose_name_plural": "Configuraciones Fiscales",
            },
        ),
        migrations.AlterModelOptions(
            name="canalrecaudacion",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="comisionventa",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="conciliacionboleto",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="diferenciafinanciera",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="documentoexportacion",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="factura",
            options={
                "ordering": ["-fecha_emision"],
                "verbose_name": "Factura",
                "verbose_name_plural": "Facturas",
            },
        ),
        migrations.AlterModelOptions(
            name="facturafiscal",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="facturaproveedor",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="gastooperativo",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="itemreporte",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="lineareportereconciliacion",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="linkdepago",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="liquidacionagente",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="pago",
            options={
                "ordering": ["-fecha_pago"],
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
            },
        ),
        migrations.AlterModelOptions(
            name="pagobinance",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="propuestatransaccionia",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="reglacomision",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="reporteproveedor",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="reportereconciliacion",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="retencionislr",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="tasacambio",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="taxrefundopportunity",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="tipocambio",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="transaccionpago",
            options={"managed": False},
        ),
        migrations.RemoveIndex(
            model_name="factura",
            name="finance_fac_numero__8f5d18_idx",
        ),
        migrations.RemoveIndex(
            model_name="factura",
            name="finance_fac_numero__5c27f0_idx",
        ),
        migrations.RemoveIndex(
            model_name="factura",
            name="finance_fac_fecha_e_93b651_idx",
        ),
        migrations.RemoveIndex(
            model_name="factura",
            name="finance_fac_tipo_fa_a0840c_idx",
        ),
        migrations.RemoveIndex(
            model_name="factura",
            name="finance_fac_agencia_39b623_idx",
        ),
        migrations.RemoveIndex(
            model_name="factura",
            name="finance_fac_agencia_bb6d18_idx",
        ),
        migrations.RemoveIndex(
            model_name="factura",
            name="idx_factura_soft_delete_saas",
        ),
        migrations.RemoveIndex(
            model_name="factura",
            name="finance_factura_tipo_idx",
        ),
        migrations.RemoveIndex(
            model_name="itemfactura",
            name="idx_itemfact_soft_delete_saas",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="archivo_pdf",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="asiento_contable_factura",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="base_exenta",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="base_imponible",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="cliente_direccion",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="cliente_es_residente",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="cliente_identificacion",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="cliente_nombre",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="cliente_rif",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="cliente_telefono",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="emisor_direccion_fiscal",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="emisor_razon_social",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="emisor_rif",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="es_sujeto_pasivo_especial",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="esta_inscrita_rtn",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="factura_asociada",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="fecha_vencimiento",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="firma_digital",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="id_factura",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="igtf_monto",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="igtf_porcentaje",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="inatur_monto",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="inatur_porcentaje",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="iva_monto",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="iva_porcentaje",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="modalidad_emision",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="moneda",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="moneda_operacion",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="moneda_transaccion",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="monto_igtf",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="monto_igtf_bs",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="monto_impuestos",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="monto_iva_16",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="monto_iva_16_bs",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="monto_iva_adicional",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="monto_total",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="monto_total_bs",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="notas",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="numero_factura",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="saldo_pendiente",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="subtotal",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="subtotal_base_gravada",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="subtotal_base_gravada_bs",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="subtotal_exento",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="subtotal_exento_bs",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="subtotal_exportacion",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="tasa_cambio",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="tasa_cambio_bcv",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="tercero_razon_social",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="tercero_rif",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="tipo",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="tipo_factura",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="tipo_operacion",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="venta_asociada",
        ),
        migrations.RemoveField(
            model_name="itemfactura",
            name="alicuota_iva",
        ),
        migrations.RemoveField(
            model_name="itemfactura",
            name="codigo_aerolinea",
        ),
        migrations.RemoveField(
            model_name="itemfactura",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="itemfactura",
            name="es_gravado",
        ),
        migrations.RemoveField(
            model_name="itemfactura",
            name="id_item_factura",
        ),
        migrations.RemoveField(
            model_name="itemfactura",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="itemfactura",
            name="itinerario",
        ),
        migrations.RemoveField(
            model_name="itemfactura",
            name="nombre_pasajero",
        ),
        migrations.RemoveField(
            model_name="itemfactura",
            name="numero_boleto",
        ),
        migrations.RemoveField(
            model_name="itemfactura",
            name="precio_unitario",
        ),
        migrations.RemoveField(
            model_name="itemfactura",
            name="subtotal_item",
        ),
        migrations.RemoveField(
            model_name="itemfactura",
            name="tipo_impuesto",
        ),
        migrations.RemoveField(
            model_name="itemfactura",
            name="tipo_servicio",
        ),
        migrations.RemoveField(
            model_name="pago",
            name="canal_recaudacion",
        ),
        migrations.RemoveField(
            model_name="pago",
            name="comprobante",
        ),
        migrations.RemoveField(
            model_name="pago",
            name="confirmado",
        ),
        migrations.RemoveField(
            model_name="pago",
            name="creado",
        ),
        migrations.RemoveField(
            model_name="pago",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="pago",
            name="id_pago",
        ),
        migrations.RemoveField(
            model_name="pago",
            name="igtf_aplicado",
        ),
        migrations.RemoveField(
            model_name="pago",
            name="igtf_monto",
        ),
        migrations.RemoveField(
            model_name="pago",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="pago",
            name="moneda",
        ),
        migrations.RemoveField(
            model_name="pago",
            name="monto",
        ),
        migrations.RemoveField(
            model_name="pago",
            name="notas",
        ),
        migrations.RemoveField(
            model_name="pago",
            name="tasa_cambio",
        ),
        migrations.RemoveField(
            model_name="pago",
            name="venta",
        ),
        migrations.RemoveField(
            model_name="tasacambiobcv",
            name="tasa_eur",
        ),
        migrations.RemoveField(
            model_name="tasacambiobcv",
            name="tasa_usd",
        ),
        migrations.RemoveField(
            model_name="tasacambiobcv",
            name="ultima_actualizacion",
        ),
        migrations.AddField(
            model_name="factura",
            name="gran_total_usd",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="factura",
            name="gran_total_ves",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="factura",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="subtotal_usd",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="factura",
            name="subtotal_ves",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="factura",
            name="tasa_bcv_aplicada",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="factura",
            name="total_igtf_usd",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="factura",
            name="total_igtf_ves",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="factura",
            name="total_iva_usd",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="factura",
            name="total_iva_ves",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="itemfactura",
            name="exento",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="itemfactura",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="itemfactura",
            name="precio_unitario_usd",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="itemfactura",
            name="total_linea_usd",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="pago",
            name="factura",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pagos",
                to="finance.factura",
            ),
        ),
        migrations.AddField(
            model_name="pago",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="pago",
            name="metodo_pago",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="pago",
            name="monto_usd",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="pago",
            name="monto_ves",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="tasacambiobcv",
            name="tasa",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="factura",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="crm.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="estado",
            field=models.CharField(
                choices=[
                    ("BORRADOR", "Borrador"),
                    ("EMITIDA", "Emitida"),
                    ("ANULADA", "Anulada"),
                ],
                default="BORRADOR",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="fecha_emision",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="factura",
            name="numero_control",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="itemfactura",
            name="cantidad",
            field=models.DecimalField(decimal_places=4, default=1, max_digits=15),
        ),
        migrations.AlterField(
            model_name="itemfactura",
            name="descripcion",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="itemfactura",
            name="factura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="finance.factura",
            ),
        ),
        migrations.AlterField(
            model_name="pago",
            name="fecha_pago",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="pago",
            name="referencia",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterModelTable(
            name="documentoexportacionconsolidado",
            table=None,
        ),
        migrations.AlterModelTable(
            name="facturaconsolidada",
            table=None,
        ),
        migrations.AlterModelTable(
            name="itemfacturaconsolidada",
            table=None,
        ),
        migrations.AddField(
            model_name="configuracionfiscal",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
    ]
