# Generated by Django 5.2.14 on 2026-07-15 13:30

"""Migración de base de datos para finance.
"""

from django.db import migrations


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("finance", "0034_moneda_configuracionfiscal_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="canalrecaudacion",
            table="finance_canalrecaudacion",
        ),
        migrations.AlterModelTable(
            name="comisionventa",
            table="finance_comisionventa",
        ),
        migrations.AlterModelTable(
            name="conciliacionboleto",
            table="finance_conciliacionboleto",
        ),
        migrations.AlterModelTable(
            name="diferenciafinanciera",
            table="finance_diferenciafinanciera",
        ),
        migrations.AlterModelTable(
            name="documentoexportacion",
            table="finance_documentoexportacion",
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelTable(
                    name="documentoexportacionconsolidado",
                    table="finance_documentoexportacionconsolidado",
                ),
                migrations.AlterModelTable(
                    name="facturaconsolidada",
                    table="finance_facturaconsolidada",
                ),
                migrations.AlterModelTable(
                    name="itemfacturaconsolidada",
                    table="finance_itemfacturaconsolidada",
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterModelTable(
            name="facturafiscal",
            table="finance_facturafiscal",
        ),
        migrations.AlterModelTable(
            name="facturaproveedor",
            table="finance_facturaproveedor",
        ),
        migrations.AlterModelTable(
            name="gastooperativo",
            table="finance_gastooperativo",
        ),
        migrations.AlterModelTable(
            name="itemreporte",
            table="finance_itemreporte",
        ),
        migrations.AlterModelTable(
            name="lineareportereconciliacion",
            table="finance_lineareportereconciliacion",
        ),
        migrations.AlterModelTable(
            name="linkdepago",
            table="finance_linkdepago",
        ),
        migrations.AlterModelTable(
            name="liquidacionagente",
            table="finance_liquidacionagente",
        ),
        migrations.AlterModelTable(
            name="moneda",
            table="finance_moneda",
        ),
        migrations.AlterModelTable(
            name="pagobinance",
            table="finance_pagobinance",
        ),
        migrations.AlterModelTable(
            name="propuestatransaccionia",
            table="finance_propuestatransaccionia",
        ),
        migrations.AlterModelTable(
            name="reglacomision",
            table="finance_reglacomision",
        ),
        migrations.AlterModelTable(
            name="reporteproveedor",
            table="finance_reporteproveedor",
        ),
        migrations.AlterModelTable(
            name="reportereconciliacion",
            table="finance_reportereconciliacion",
        ),
        migrations.AlterModelTable(
            name="retencionislr",
            table="finance_retencionislr",
        ),
        migrations.AlterModelTable(
            name="tasacambio",
            table="finance_tasacambio",
        ),
        migrations.AlterModelTable(
            name="taxrefundopportunity",
            table="finance_taxrefundopportunity",
        ),
        migrations.AlterModelTable(
            name="tipocambio",
            table="finance_tipocambio",
        ),
        migrations.AlterModelTable(
            name="transaccionpago",
            table="finance_transaccionpago",
        ),
    ]
