# Generated by Django 5.2.6 on 2025-09-18 15:47

import django.db.models.deletion
import personas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id_cliente",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID Cliente"
                    ),
                ),
                (
                    "tipo_cliente",
                    models.CharField(
                        choices=[("PAR", "Particular"), ("EMP", "Empresa")],
                        default="PAR",
                        max_length=3,
                        verbose_name="Tipo de Cliente",
                    ),
                ),
                (
                    "nombres",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Nombres"
                    ),
                ),
                (
                    "apellidos",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Apellidos"
                    ),
                ),
                (
                    "nombre_empresa",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Nombre de la Empresa",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="Correo Electrónico",
                    ),
                ),
                (
                    "telefono_principal",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Teléfono Principal",
                    ),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Nacimiento"
                    ),
                ),
                (
                    "numero_pasaporte",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[personas.models.validar_numero_pasaporte],
                        verbose_name="Número de Pasaporte",
                    ),
                ),
                (
                    "fecha_expiracion_pasaporte",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de Expiración del Pasaporte",
                    ),
                ),
                (
                    "direccion",
                    models.TextField(blank=True, null=True, verbose_name="Dirección"),
                ),
                (
                    "puntos_fidelidad",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Puntos de Fidelidad"
                    ),
                ),
                (
                    "es_cliente_frecuente",
                    models.BooleanField(
                        default=False, verbose_name="Es Cliente Frecuente"
                    ),
                ),
                (
                    "ciudad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="personas_clientes",
                        to="core.ciudad",
                        verbose_name="Ciudad",
                    ),
                ),
                (
                    "nacionalidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clientes_nacionales",
                        to="core.pais",
                        verbose_name="Nacionalidad",
                    ),
                ),
                (
                    "pais_emision_pasaporte",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pasaportes_emitidos",
                        to="core.pais",
                        verbose_name="País de Emisión del Pasaporte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["apellidos", "nombres", "nombre_empresa"],
            },
        ),
        migrations.CreateModel(
            name="Pasajero",
            fields=[
                (
                    "id_pasajero",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID Pasajero"
                    ),
                ),
                (
                    "nombres",
                    models.CharField(
                        max_length=150,
                        validators=[personas.models.validar_no_vacio_o_espacios],
                        verbose_name="Nombres",
                    ),
                ),
                (
                    "apellidos",
                    models.CharField(
                        max_length=150,
                        validators=[personas.models.validar_no_vacio_o_espacios],
                        verbose_name="Apellidos",
                    ),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Nacimiento"
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("PASS", "Pasaporte"),
                            ("CI", "Cédula/DNI"),
                            ("OTR", "Otro"),
                        ],
                        default="PASS",
                        max_length=4,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número de Documento"
                    ),
                ),
                (
                    "fecha_expiracion_documento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Expiración"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Correo Electrónico",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "nacionalidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pasajeros_nacionales",
                        to="core.pais",
                        verbose_name="Nacionalidad",
                    ),
                ),
                (
                    "pais_emision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_emitidos",
                        to="core.pais",
                        verbose_name="País de Emisión",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pasajero",
                "verbose_name_plural": "Pasajeros",
                "ordering": ["apellidos", "nombres"],
            },
        ),
    ]
