# Generated by Django 5.2.6 on 2025-09-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="cedula_identidad",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Cédula de Identidad",
            ),
        ),
    ]
