# Generated by Django 5.2.6 on 2025-11-25 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_proveedor_agencia_venta_agencia"),
        ("personas", "0002_cliente_cedula_identidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.agencia",
                verbose_name="Agencia",
            ),
        ),
    ]
