# Generated by Django 5.2.6 on 2026-01-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personas", "0003_cliente_agencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="foto_perfil",
            field=models.ImageField(
                blank=True,
                help_text="Foto extraída del pasaporte o subida manualmente.",
                null=True,
                upload_to="clientes/fotos/",
                verbose_name="Foto de Perfil",
            ),
        ),
    ]
