# Generated by Django 5.2.6 on 2026-01-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personas", "0004_cliente_foto_perfil"),
    ]

    operations = [
        migrations.AddField(
            model_name="pasajero",
            name="preferencias",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Preferencias"
            ),
        ),
    ]
