# Generated by Django 5.2.6 on 2026-01-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personas", "0005_pasajero_preferencias"),
    ]

    operations = [
        migrations.AddField(
            model_name="pasajero",
            name="fecha_emision_documento",
            field=models.DateField(
                blank=True,
                help_text="Fecha de emisión del pasaporte/documento",
                null=True,
                verbose_name="Fecha Emisión Documento",
            ),
        ),
        migrations.AddField(
            model_name="pasajero",
            name="fecha_vacuna_fiebre_amarilla",
            field=models.DateField(
                blank=True,
                help_text="Fecha de aplicación de la vacuna (válida por 10 años)",
                null=True,
                verbose_name="Fecha Vacuna Fiebre Amarilla",
            ),
        ),
        migrations.AddField(
            model_name="pasajero",
            name="tiene_fiebre_amarilla",
            field=models.BooleanField(
                default=False,
                help_text="¿El pasajero tiene la vacuna de fiebre amarilla?",
                verbose_name="Tiene Vacuna Fiebre Amarilla",
            ),
        ),
    ]
