# Generated by Django 5.2.6 on 2026-01-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personas", "0006_pasajero_fecha_emision_documento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="numero_pasaporte_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Hash SHA256 para búsquedas exactas",
                max_length=64,
                null=True,
                verbose_name="Hash Pasaporte",
            ),
        ),
        migrations.AddField(
            model_name="pasajero",
            name="numero_documento_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Hash SHA256 para búsquedas exactas",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Hash Documento",
            ),
        ),
    ]
