# Generated by Django 5.2.6 on 2026-01-26 21:05

import core.fields
import personas.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personas", "0007_cliente_numero_pasaporte_hash_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="numero_pasaporte",
            field=core.fields.EncryptedCharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[personas.models.validar_numero_pasaporte],
                verbose_name="Número de Pasaporte",
            ),
        ),
        migrations.AlterField(
            model_name="pasajero",
            name="numero_documento",
            field=core.fields.EncryptedCharField(
                max_length=50, verbose_name="Número de Documento"
            ),
        ),
    ]
