# Generated by Django 5.2.6 on 2026-05-04 00:17

"""Migración de base de datos para communications.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    initial = True

    dependencies = [
        ("core", "0007_hoteltarifario_agencia_tarifarioproveedor_agencia_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComunicacionProveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remitente", models.CharField(max_length=255)),
                ("asunto", models.CharField(max_length=500)),
                (
                    "fecha_recepcion",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("TICKET", "Boleto / E-Ticket"),
                            ("RESERVATION", "Reserva / PNR"),
                            ("ALERT", "Alerta de Vuelo"),
                            ("CANCELLATION", "Cancelación"),
                            ("OTHER", "Otro"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("contenido_extraido", models.JSONField(blank=True, default=dict)),
                ("cuerpo_completo", models.TextField(blank=True)),
                (
                    "message_id",
                    models.CharField(blank=True, max_length=255, null=True, unique=True),
                ),
                ("procesado", models.BooleanField(default=False)),
                (
                    "agencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="core.agencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comunicación de Proveedor",
                "verbose_name_plural": "Comunicaciones de Proveedores",
                "db_table": "core_comunicacionproveedor",
                "ordering": ["-fecha_recepcion"],
            },
        ),
    ]
