# Generated by Django 5.2.6 on 2026-05-10 19:41
# Edited 2026-06-06: removed AlterModelTable(table=None) so state keeps
# db_table='core_xxx' for the renamed model.

"""Migración de base de datos para communications.
"""

from django.db import migrations


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("communications", "0001_initial"),
    ]

    operations = []
