# Generated by Django 5.2.6 on 2026-05-10 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="comunicacionproveedor",
            table=None,
        ),
    ]
