# Generated by Django 5.2.6 on 2026-05-14 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0002_alter_comunicacionproveedor_table"),
        ("core", "0029_alter_anulacionboleto_agencia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comunicacionproveedor",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
    ]
