# Generated by Django 5.2.14 on 2026-05-30 23:20

"""Migración de base de datos para communications.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("communications", "0004_alter_comunicacionproveedor_agencia"),
        ("core", "0034_alter_anulacionboleto_agencia_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailMonitorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("fecha_ejecucion", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Éxito"),
                            ("ERROR", "Error"),
                            ("WARNING", "Advertencia"),
                        ],
                        default="SUCCESS",
                        max_length=20,
                    ),
                ),
                ("mensaje", models.TextField()),
                ("host_conectado", models.CharField(blank=True, max_length=255, null=True)),
                ("correos_procesados", models.IntegerField(default=0)),
                (
                    "tiempo_ejecucion",
                    models.FloatField(default=0.0, help_text="Tiempo de ejecución en segundos"),
                ),
                (
                    "agencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="core.agencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Monitor de Correo",
                "verbose_name_plural": "Logs de Monitor de Correo",
                "ordering": ["-fecha_ejecucion"],
            },
        ),
    ]
