# Generated by Django 5.2.14 on 2026-06-12 11:17

"""Migración de base de datos para communications.
"""

from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("communications", "0007_alter_comunicacionproveedor_message_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comunicacionproveedor",
            name="message_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="emailmonitorlog",
            name="host_conectado",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
