# Generated by Django 5.2.14 on 2026-07-03 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0008_alter_comunicacionproveedor_message_id_and_more"),
        ("core", "0045_api_keys_webhooks_v2"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(help_text="Evento que disparó la notificación", max_length=50),
                ),
                ("channel", models.CharField(help_text="Canal utilizado", max_length=20)),
                (
                    "recipient",
                    models.CharField(
                        help_text="Destinatario (email, teléfono, etc.)", max_length=255
                    ),
                ),
                (
                    "subject",
                    models.CharField(blank=True, help_text="Asunto (si aplica)", max_length=500),
                ),
                ("body", models.TextField(help_text="Cuerpo del mensaje enviado")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("sent", "Enviada"),
                            ("failed", "Fallida"),
                            ("retrying", "Reintentando"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Mensaje de error si falló"),
                ),
                ("retry_count", models.IntegerField(default=0, help_text="Cantidad de reintentos")),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, help_text="Fecha de envío exitoso", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.CharField(
                        blank=True, help_text="Tipo de objeto (ej: 'venta')", max_length=100
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True, help_text="ID del objeto relacionado", max_length=100
                    ),
                ),
                (
                    "agencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_logs",
                        to="core.agencia",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Notificación",
                "verbose_name_plural": "Logs de Notificaciones",
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="communicati_status_67a417_idx"
                    ),
                    models.Index(
                        fields=["event_type", "created_at"], name="communicati_event_t_28f39a_idx"
                    ),
                    models.Index(
                        fields=["channel", "created_at"], name="communicati_channel_d4a183_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("venta_creada", "Venta Creada"),
                            ("venta_actualizada", "Venta Actualizada"),
                            ("venta_anulada", "Venta Anulada"),
                            ("pago_confirmado", "Pago Confirmado"),
                            ("pago_pendiente", "Pago Pendiente"),
                            ("recordatorio_pago", "Recordatorio de Pago"),
                            ("boleto_importado", "Boleto Importado"),
                            ("boleto_revisado", "Boleto Revisado"),
                            ("cotizacion_enviada", "Cotización Enviada"),
                            ("cotizacion_aprobada", "Cotización Aprobada"),
                            ("factura_generada", "Factura Generada"),
                            ("cliente_creado", "Cliente Creado"),
                        ],
                        help_text="Tipo de evento que dispara la notificación",
                        max_length=50,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                            ("in_app", "In-App"),
                        ],
                        help_text="Canal de notificación preferido",
                        max_length=20,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Si está desactivado, no se enviarán notificaciones para este combo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agencia",
                    models.ForeignKey(
                        blank=True,
                        help_text="Agencia a la que aplican estas preferencias (null = globales)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to="core.agencia",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Usuario propietario de estas preferencias",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Preferencia de Notificación",
                "verbose_name_plural": "Preferencias de Notificación",
                "indexes": [
                    models.Index(
                        fields=["user", "event_type"], name="communicati_user_id_501e1d_idx"
                    ),
                    models.Index(
                        fields=["agencia", "event_type"], name="communicati_agencia_758c36_idx"
                    ),
                ],
                "unique_together": {("user", "agencia", "event_type", "channel")},
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre interno de la plantilla (ej: 'venta_confirmacion')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Tipo de evento asociado (ej: 'venta_creada')", max_length=50
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("whatsapp", "WhatsApp"), ("sms", "SMS")],
                        help_text="Canal para el que está diseñada esta plantilla",
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("es", "Español"), ("en", "English"), ("pt", "Português")],
                        default="es",
                        help_text="Idioma de la plantilla",
                        max_length=2,
                    ),
                ),
                (
                    "subject_template",
                    models.CharField(
                        blank=True,
                        help_text="Asunto (solo Email). Variables: {{variable}}",
                        max_length=200,
                    ),
                ),
                (
                    "body_template",
                    models.TextField(help_text="Cuerpo del mensaje. Variables: {{variable}}"),
                ),
                (
                    "html_template",
                    models.TextField(
                        blank=True, help_text="HTML para emails (opcional). Variables: {{variable}}"
                    ),
                ),
                (
                    "whatsapp_template_id",
                    models.CharField(
                        blank=True,
                        help_text="ID de plantilla en WhatsApp Business API (opcional)",
                        max_length=100,
                    ),
                ),
                (
                    "variables_disponibles",
                    models.TextField(
                        blank=True,
                        help_text="Lista de variables disponibles (documentación interna)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Si es True, se usa como fallback si no hay personalizada",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agencia",
                    models.ForeignKey(
                        blank=True,
                        help_text="Si null, es plantilla global. Si tiene agencia, es personalizada.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_templates",
                        to="core.agencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de Notificación",
                "verbose_name_plural": "Plantillas de Notificación",
                "indexes": [
                    models.Index(
                        fields=["event_type", "channel", "language"],
                        name="communicati_event_t_e35a73_idx",
                    ),
                    models.Index(fields=["name"], name="communicati_name_1d989a_idx"),
                ],
            },
        ),
    ]
