# Generated by Django 5.2.14 on 2026-07-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0011_notificationlog_notificationpreference_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("nombre", models.CharField(blank=True, default="", max_length=150)),
                ("fuente", models.CharField(default="landing_page", max_length=50)),
                ("ip_origen", models.CharField(blank=True, default="", max_length=45)),
                ("guia_descargada", models.BooleanField(default=False)),
                ("email_enviado", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "ordering": ["-created_at"],
            },
        ),
    ]
