# Generated by Django 5.2.14 on 2026-07-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0012_lead_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="_followup_1_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lead",
            name="_followup_2_sent",
            field=models.BooleanField(default=False),
        ),
    ]
