@echo off
echo Iniciando Django y LocalTunnel...
echo.
echo 1. Iniciando Django en puerto 8000...
start cmd /k "cd /d %~dp0 && venv\Scripts\activate && python manage.py runserver"

echo 2. Esperando 5 segundos para que Django inicie...
timeout /t 5 /nobreak > nul

echo 3. Iniciando LocalTunnel...
lt --port 8000

pause