apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-celery-beat
  labels:
    app: {{ .Release.Name }}-celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-celery-beat
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-celery-beat
    spec:
      containers:
        - name: {{ .Chart.Name }}-celery-beat
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ["celery", "-A", "travelhub", "beat", "-l", "INFO", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-secrets
          livenessProbe:
            exec:
              command: ["sh", "-c", "celery -A travelhub inspect ping --destination=celery@$(hostname) --timeout=10 || exit 1"]
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            exec:
              command: ["sh", "-c", "celery -A travelhub inspect ping --destination=celery@$(hostname) --timeout=5 || exit 1"]
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3
