apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-postgres-exporter
  labels:
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres-exporter
  endpoints:
    - port: postgres-exporter
      interval: 30s
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
