apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-node-exporter
  labels:
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-node-exporter
  endpoints:
    - port: node-exporter
      interval: 30s
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
