apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-travelhub
  labels:
    app: {{ .Release.Name }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-celery-worker
  labels:
    app: {{ .Release.Name }}-celery-worker
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-celery-beat
  labels:
    app: {{ .Release.Name }}-celery-beat
