# Generated by Django 5.2.6 on 2026-05-04 02:15

"""Migración de base de datos para common.
"""

import django.db.models.deletion
from django.db import migrations, models

import core.validators


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    initial = True

    dependencies = []

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Aerolinea",
                    fields=[
                        (
                            "id_aerolinea",
                            models.AutoField(
                                primary_key=True, serialize=False, verbose_name="ID Aerolínea"
                            ),
                        ),
                        (
                            "codigo_iata",
                            models.CharField(
                                blank=True,
                                help_text="Código IATA de 2 letras de la aerolínea (ej. AA, AV, LA).",
                                max_length=3,
                                verbose_name="Código IATA",
                            ),
                        ),
                        (
                            "codigo_numerico",
                            models.CharField(
                                blank=True,
                                help_text="Código numérico de 3 dígitos asignado por IATA (ej. 134, 052)",
                                max_length=3,
                                null=True,
                                verbose_name="Código Numérico/Placa",
                            ),
                        ),
                        (
                            "codigo_icao",
                            models.CharField(
                                blank=True,
                                help_text="Código ICAO de 3 letras",
                                max_length=3,
                                verbose_name="Código ICAO",
                            ),
                        ),
                        (
                            "nombre",
                            models.CharField(
                                max_length=150,
                                validators=[core.validators.validar_no_vacio_o_espacios],
                                verbose_name="Nombre de la Aerolínea",
                            ),
                        ),
                        (
                            "orden_prioridad",
                            models.IntegerField(
                                default=100,
                                help_text="Para mostrar al principio en listas.",
                                verbose_name="Orden de Prioridad",
                            ),
                        ),
                        (
                            "pais_origen",
                            models.CharField(
                                blank=True, max_length=100, verbose_name="País de Origen"
                            ),
                        ),
                        (
                            "rif",
                            models.CharField(
                                blank=True,
                                help_text="RIF venezolano o E-99999999-X para internacionales",
                                max_length=20,
                                verbose_name="RIF",
                            ),
                        ),
                        (
                            "activa",
                            models.BooleanField(
                                default=True,
                                help_text="Indica si la aerolínea está actualmente operando.",
                                verbose_name="Activa",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Aerolínea",
                        "verbose_name_plural": "Aerolíneas",
                        "db_table": "core_aerolinea",
                        "ordering": ["nombre"],
                    },
                ),
                migrations.CreateModel(
                    name="Pais",
                    fields=[
                        (
                            "id_pais",
                            models.AutoField(
                                primary_key=True, serialize=False, verbose_name="ID País"
                            ),
                        ),
                        (
                            "codigo_iso_2",
                            models.CharField(
                                help_text="Código ISO 3166-1 alfa-2 del país.",
                                max_length=2,
                                unique=True,
                                verbose_name="Código ISO 2",
                            ),
                        ),
                        (
                            "codigo_iso_3",
                            models.CharField(
                                help_text="Código ISO 3166-1 alfa-3 del país.",
                                max_length=3,
                                unique=True,
                                verbose_name="Código ISO 3",
                            ),
                        ),
                        (
                            "nombre",
                            models.CharField(
                                max_length=100,
                                unique=True,
                                validators=[core.validators.validar_no_vacio_o_espacios],
                                verbose_name="Nombre del País",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "País",
                        "verbose_name_plural": "Países",
                        "db_table": "core_pais",
                        "ordering": ["nombre"],
                    },
                ),
                migrations.CreateModel(
                    name="Ciudad",
                    fields=[
                        (
                            "id_ciudad",
                            models.AutoField(
                                primary_key=True, serialize=False, verbose_name="ID Ciudad"
                            ),
                        ),
                        (
                            "nombre",
                            models.CharField(
                                max_length=100,
                                validators=[core.validators.validar_no_vacio_o_espacios],
                                verbose_name="Nombre de la Ciudad",
                            ),
                        ),
                        (
                            "codigo_iata",
                            models.CharField(
                                blank=True,
                                db_index=True,
                                help_text="Código IATA de 3 letras de la ciudad o aeropuerto.",
                                max_length=3,
                                null=True,
                                verbose_name="Código IATA",
                            ),
                        ),
                        (
                            "region_estado",
                            models.CharField(
                                blank=True,
                                max_length=100,
                                null=True,
                                verbose_name="Región/Estado",
                            ),
                        ),
                        (
                            "pais",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                to="common.pais",
                                verbose_name="País",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Ciudad",
                        "verbose_name_plural": "Ciudades",
                        "db_table": "core_ciudad",
                        "ordering": ["pais__nombre", "nombre"],
                        "unique_together": {("nombre", "pais", "region_estado")},
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
