# Generated by Django 5.2.6 on 2026-05-10 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="aerolinea",
            table=None,
        ),
        migrations.AlterModelTable(
            name="ciudad",
            table=None,
        ),
        migrations.AlterModelTable(
            name="pais",
            table=None,
        ),
    ]
