# Generated by Django 5.2.6 on 2026-06-03 17:22
# Edited 2026-06-06: wrap in SeparateDatabaseAndState because the
# core_moneda table is already created by core.0001_initial.
# Edited 2026-06-07: changed db_table from "finance_moneda" to "core_moneda"
# to match the actual table name. This keeps the state in sync with the DB and
# allows fresh-DB migrations to succeed (later AlterField operations on Moneda
# generate SQL referencing `core_moneda` which is the real table).

"""Migración de base de datos para common.
"""

from django.db import migrations, models

import core.validators


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("common", "0002_alter_aerolinea_table_alter_ciudad_table_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Moneda",
                    fields=[
                        (
                            "id_moneda",
                            models.AutoField(
                                primary_key=True, serialize=False, verbose_name="ID Moneda"
                            ),
                        ),
                        (
                            "codigo_iso",
                            models.CharField(
                                help_text="Código ISO 4217 de la moneda (ej. USD, EUR, VEF).",
                                max_length=3,
                                unique=True,
                                verbose_name="Código ISO",
                            ),
                        ),
                        (
                            "nombre",
                            models.CharField(
                                max_length=50,
                                unique=True,
                                validators=[core.validators.validar_no_vacio_o_espacios],
                                verbose_name="Nombre de la Moneda",
                            ),
                        ),
                        (
                            "simbolo",
                            models.CharField(
                                blank=True, max_length=5, null=True, verbose_name="Símbolo"
                            ),
                        ),
                        (
                            "es_moneda_local",
                            models.BooleanField(
                                default=False,
                                help_text="Marcar si esta es la moneda principal de la agencia.",
                                verbose_name="Es Moneda Local",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Moneda",
                        "verbose_name_plural": "Monedas",
                        "db_table": "core_moneda",
                        "ordering": ["nombre"],
                    },
                ),
            ],
            database_operations=[],
        )
    ]
