# Generated by Django 5.2.14 on 2026-06-06 20:37

"""Migración de base de datos para common.
"""

from django.db import migrations


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    # Edited 2026-06-07: wrap in SeparateDatabaseAndState with
    # database_operations=[] because the tables named in the original
    # AlterModelTable(table=None) operations were already renamed
    # manually (or via pg_dump --schema-only + migrate --fake) in
    # dev/prod. State-only update is safe and idempotent in fresh-DB.

    dependencies = [
        ("common", "0003_moneda"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelTable(
                    name="aerolinea",
                    table=None,
                ),
                migrations.AlterModelTable(
                    name="ciudad",
                    table=None,
                ),
                migrations.AlterModelTable(
                    name="pais",
                    table=None,
                ),
            ],
        ),
    ]
