# Generated by Django 5.2.6 on 2025-10-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detalleasiento",
            name="debe_bsd",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Monto en bolívares para presentación legal",
                max_digits=18,
                verbose_name="Debe BSD",
            ),
        ),
        migrations.AddField(
            model_name="detalleasiento",
            name="haber_bsd",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Monto en bolívares para presentación legal",
                max_digits=18,
                verbose_name="Haber BSD",
            ),
        ),
        migrations.AlterField(
            model_name="detalleasiento",
            name="debe",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="Debe USD"
            ),
        ),
        migrations.AlterField(
            model_name="detalleasiento",
            name="haber",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="Haber USD"
            ),
        ),
        migrations.CreateModel(
            name="TasaCambioBCV",
            fields=[
                (
                    "id_tasa",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID Tasa"
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        db_index=True,
                        help_text="Fecha de vigencia de la tasa",
                        unique=True,
                        verbose_name="Fecha",
                    ),
                ),
                (
                    "tasa_bsd_por_usd",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Bolívares por cada dólar estadounidense",
                        max_digits=12,
                        verbose_name="Tasa BSD/USD",
                    ),
                ),
                (
                    "fuente",
                    models.CharField(
                        default="BCV",
                        help_text="Origen de la tasa (BCV, API, Manual)",
                        max_length=100,
                        verbose_name="Fuente",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "actualizado",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
            ],
            options={
                "verbose_name": "Tasa de Cambio BCV",
                "verbose_name_plural": "Tasas de Cambio BCV",
                "ordering": ["-fecha"],
                "indexes": [
                    models.Index(fields=["-fecha"], name="contabilida_fecha_7481be_idx")
                ],
            },
        ),
    ]
