# Generated by Django 5.2.6 on 2026-05-04 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="NotificacionAgente",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("titulo", models.CharField(max_length=150)),
                        ("mensaje", models.TextField()),
                        ("icono", models.CharField(default="auto_awesome", max_length=50)),
                        (
                            "tipo",
                            models.CharField(
                                choices=[
                                    ("ai_magic", "AI Magic ✨"),
                                    ("success", "Éxito"),
                                    ("warning", "Advertencia"),
                                ],
                                default="ai_magic",
                                max_length=20,
                            ),
                        ),
                        ("leida", models.BooleanField(default=False)),
                        ("creado_en", models.DateTimeField(auto_now_add=True)),
                        (
                            "usuario",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="notificaciones_agente_auto",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Notificación de Agente",
                        "verbose_name_plural": "Notificaciones de Agente",
                        "db_table": "core_notificacionagente",
                        "ordering": ["-creado_en"],
                    },
                ),
                migrations.CreateModel(
                    name="NotificacionInteligente",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "tipo",
                            models.CharField(
                                choices=[
                                    ("ai_magic", "AI Magic ✨"),
                                    ("success", "Éxito"),
                                    ("warning", "Advertencia"),
                                    ("info", "Información"),
                                ],
                                default="info",
                                max_length=20,
                            ),
                        ),
                        ("titulo", models.CharField(max_length=150)),
                        ("mensaje", models.TextField()),
                        (
                            "ahorro_tiempo",
                            models.CharField(
                                blank=True, help_text="Ej: 5 min", max_length=50, null=True
                            ),
                        ),
                        ("leida", models.BooleanField(default=False)),
                        ("creado_en", models.DateTimeField(auto_now_add=True, db_index=True)),
                        (
                            "usuario",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="notificaciones_inteligentes_auto",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Notificación Inteligente",
                        "verbose_name_plural": "Notificaciones Inteligentes",
                        "db_table": "core_notificacioninteligente",
                        "ordering": ["-creado_en"],
                        "indexes": [
                            models.Index(
                                fields=["usuario", "leida"],
                                name="core_notifi_usuario_716d79_idx",
                            )
                        ],
                    },
                ),
            ],
            database_operations=[
            ],
        ),
    ]
