# Generated by Django 5.2.6 on 2026-05-10 19:41
# Edited 2026-06-06: removed AlterModelTable(table=None) operations so
# the state keeps db_table='core_xxx'. Future AlterField migrations need
# this to correctly target the table created by core.0001.

"""Migración de base de datos para automation.
"""

from django.db import migrations


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("automation", "0002_notificacionagente_agencia_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name="notificacioninteligente",
                    new_name="automation__usuario_b9f56b_idx",
                    old_name="core_notifi_usuario_716d79_idx",
                ),
            ],
            database_operations=[],
        )
    ]
