# Generated by Django 5.2.6 on 2026-05-10 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0002_notificacionagente_agencia_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name="notificacioninteligente",
                    new_name="automation__usuario_b9f56b_idx",
                    old_name="core_notifi_usuario_716d79_idx",
                ),
                migrations.AlterModelTable(
                    name="notificacionagente",
                    table=None,
                ),
                migrations.AlterModelTable(
                    name="notificacioninteligente",
                    table=None,
                ),
            ],
            database_operations=[]
        )
    ]
