# Generated by Django 5.2.6 on 2026-05-14 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "automation",
            "0003_rename_core_notifi_usuario_716d79_idx_automation__usuario_b9f56b_idx_and_more",
        ),
        ("core", "0028_alter_agencia_activa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificacionagente",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
        migrations.AlterField(
            model_name="notificacioninteligente",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
    ]
