# Generated by Django 5.2.14 on 2026-06-11 03:43

"""Migración de base de datos para automation.
"""

from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("automation", "0007_add_missing_usuario_columns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificacioninteligente",
            name="ahorro_tiempo",
            field=models.CharField(blank=True, help_text="Ej: 5 min", max_length=50),
        ),
    ]
