http:
  routers:
    travelhub:
      rule: "Host(`travelhub.cc`) || HostRegexp(`{subdomain:[a-z0-9-]+}.travelhub.cc`)"
      entryPoints:
        - websecure
      service: travelhub
      tls:
        certResolver: letsencryptresolver
    travelhub-http:
      rule: "Host(`travelhub.cc`) || HostRegexp(`{subdomain:[a-z0-9-]+}.travelhub.cc`)"
      entryPoints:
        - web
      service: travelhub


  services:
    travelhub:
      loadBalancer:
        servers:
          - url: "http://travelhub_web:8000"
        responseForwarding:
          flushInterval: "100ms"

  middlewares:
    redirect-https:
      redirectScheme:
        scheme: https
        permanent: true
