# Generated by Django 5.2.6 on 2026-02-12 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0073_alter_facturaconsolidada_cliente_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campania",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=255, verbose_name="Nombre de la Campaña"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Inicio"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Fin"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("PROGRAMADA", "Programada"),
                            ("ACTIVA", "Activa"),
                            ("FINALIZADA", "Finalizada"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("publicar_en_instagram", models.BooleanField(default=True)),
                ("publicar_en_facebook", models.BooleanField(default=False)),
                ("publicar_en_whatsapp", models.BooleanField(default=True)),
                (
                    "agencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campanias",
                        to="core.agencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaña",
                "verbose_name_plural": "Campañas",
            },
        ),
        migrations.CreateModel(
            name="ActivoMarketing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("FLYER", "Flyer (Imagen)"),
                            ("STORY", "Story (Instagram)"),
                            ("COPY", "Texto (Copywriting)"),
                            ("VIDEO", "Video/Reel"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Activo",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="marketing/assets/",
                        verbose_name="Archivo",
                    ),
                ),
                (
                    "texto_caption",
                    models.TextField(blank=True, verbose_name="Caption / Texto"),
                ),
                (
                    "prompt_utilizado",
                    models.TextField(blank=True, verbose_name="Prompt Utilizado"),
                ),
                ("generado_por_ia", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "telegram_file_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activos_marketing",
                        to="core.hoteltarifario",
                    ),
                ),
                (
                    "campania",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activos",
                        to="marketing.campania",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activo de Marketing",
                "verbose_name_plural": "Activos de Marketing",
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionMarketing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color_primario", models.CharField(default="#0f172a", max_length=7)),
                ("color_secundario", models.CharField(default="#fbbf24", max_length=7)),
                ("fuente_principal", models.CharField(default="Arial", max_length=100)),
                (
                    "hashtag_default",
                    models.TextField(
                        blank=True,
                        help_text="Separa con espacios",
                        verbose_name="Hashtags por defecto",
                    ),
                ),
                (
                    "agencia",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_marketing",
                        to="core.agencia",
                    ),
                ),
            ],
        ),
    ]
