# Generated by Django 5.2.6 on 2026-05-04 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0008_amenity_comisionoverrideaerolinea_cruceroreserva_and_more"),
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activomarketing",
            name="hotel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activos_marketing",
                to="bookings.hoteltarifario",
            ),
        ),
    ]
