# Generated by Django 5.2.6 on 2026-05-09 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_remove_agencia_bi_insights_and_more"),
        ("marketing", "0002_alter_activomarketing_hotel"),
    ]

    operations = [
        migrations.AddField(
            model_name="activomarketing",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
        migrations.AlterField(
            model_name="campania",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
        migrations.AlterField(
            model_name="configuracionmarketing",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
    ]
