# Generated by Django 5.2.14 on 2026-06-12 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_aeropuerto"),
        ("marketing", "0006_add_missing_agencia_column"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activomarketing",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
    ]
