# Generated by Django 5.2.14 on 2026-06-24 17:56

"""Migración de base de datos para marketing.
"""

from django.db import migrations, models

import core.validators


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("marketing", "0007_alter_activomarketing_agencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activomarketing",
            name="archivo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="marketing/assets/",
                validators=[core.validators.antivirus_hook],
                verbose_name="Archivo",
            ),
        ),
    ]
