# Generated by Django 5.2.14 on 2026-06-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketing", "0008_alter_activomarketing_archivo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activomarketing",
            name="archivo",
            field=models.FileField(
                blank=True, null=True, upload_to="marketing/assets/", verbose_name="Archivo"
            ),
        ),
    ]
