# Generated by Django 5.2.6 on 2026-04-02 00:00

import core.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Eliminado"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Eliminación"
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        db_column="id_cliente", primary_key=True, serialize=False
                    ),
                ),
                ("nombres", models.CharField(max_length=150)),
                ("apellidos", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "nombre_empresa",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "telefono_principal",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "telefono_secundario",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("direccion", models.TextField(blank=True, null=True)),
                (
                    "direccion_linea1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "direccion_linea2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "codigo_postal",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "cedula_identidad",
                    core.fields.EncryptedCharField(
                        blank=True, max_length=255, null=True
                    ),
                ),
                (
                    "numero_pasaporte",
                    core.fields.EncryptedCharField(
                        blank=True, max_length=255, null=True
                    ),
                ),
                (
                    "documento_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("fecha_expiracion_pasaporte", models.DateField(blank=True, null=True)),
                (
                    "fecha_registro",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("tipo_cliente", models.CharField(default="IND", max_length=10)),
                ("es_cliente_frecuente", models.BooleanField(default=False)),
                ("puntos_fidelidad", models.PositiveIntegerField(default=0)),
                ("preferencias_viaje", models.TextField(blank=True, null=True)),
                ("notas_cliente", models.TextField(blank=True, null=True)),
                (
                    "foto_perfil",
                    models.ImageField(
                        blank=True, null=True, upload_to="clientes/fotos/"
                    ),
                ),
                (
                    "agencia_registradora",
                    models.ForeignKey(
                        blank=True,
                        db_column="agencia_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clientes_crm",
                        to="core.agencia",
                    ),
                ),
                (
                    "ciudad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.ciudad",
                    ),
                ),
                (
                    "nacionalidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clientes_nacionalidad",
                        to="core.pais",
                    ),
                ),
                (
                    "pais_emision_pasaporte",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clientes_emision_pasaporte",
                        to="core.pais",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "db_table": "personas_cliente",
            },
        ),
        migrations.CreateModel(
            name="FreelancerProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "comision_fija_por_boleto",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                (
                    "porcentaje_comision",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
                ),
                (
                    "saldo_por_cobrar",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total_historico_pagado",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "agencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="freelancers_asociados",
                        to="core.agencia",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_freelancer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComisionFreelancer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monto_base_venta",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "monto_comision_ganada",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("liquidada", models.BooleanField(default=False)),
                ("fecha_liquidacion", models.DateTimeField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "venta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comision_asignada",
                        to="bookings.venta",
                    ),
                ),
                (
                    "freelancer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comisiones_generadas",
                        to="crm.freelancerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MensajeWhatsApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        choices=[("IN", "Entrante"), ("OUT", "Saliente")], max_length=3
                    ),
                ),
                ("texto", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "agencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.agencia",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes_whatsapp",
                        to="crm.cliente",
                    ),
                ),
            ],
            options={
                "db_table": "crm_whatsapp_mensaje",
            },
        ),
        migrations.CreateModel(
            name="OportunidadViaje",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("origen", models.CharField(blank=True, max_length=100, null=True)),
                ("destino", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "fechas_texto",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("cantidad_pasajeros", models.IntegerField(default=1)),
                (
                    "etapa",
                    models.CharField(
                        choices=[
                            ("NEW", "Nuevo Lead"),
                            ("QUO", "Armando Cotización"),
                            ("PAY", "Esperando Pago"),
                            ("WON", "Ganado (Vendido)"),
                            ("LOS", "Perdido"),
                        ],
                        default="NEW",
                        max_length=3,
                    ),
                ),
                (
                    "presupuesto_estimado",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("notas_ia", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oportunidades",
                        to="crm.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pasajero",
            fields=[
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Eliminado"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Eliminación"
                    ),
                ),
                ("id_pasajero", models.AutoField(primary_key=True, serialize=False)),
                ("nombres", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                (
                    "numero_pasaporte",
                    core.fields.EncryptedCharField(
                        blank=True, max_length=255, null=True
                    ),
                ),
                (
                    "cedula_identidad",
                    core.fields.EncryptedCharField(
                        blank=True, max_length=255, null=True
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("telefono", models.CharField(blank=True, max_length=50, null=True)),
                ("tipo_documento", models.CharField(default="PASS", max_length=4)),
                ("fecha_emision_documento", models.DateField(blank=True, null=True)),
                (
                    "fecha_vencimiento_documento",
                    models.DateField(
                        blank=True, db_column="fecha_expiracion_documento", null=True
                    ),
                ),
                ("preferencias", models.JSONField(blank=True, default=dict)),
                ("notas", models.TextField(blank=True, null=True)),
                (
                    "documento_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("tiene_fiebre_amarilla", models.BooleanField(default=False)),
                (
                    "fecha_vacuna_fiebre_amarilla",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "agencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.agencia",
                    ),
                ),
                (
                    "nacionalidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pasajeros_nacionalidad",
                        to="core.pais",
                    ),
                ),
                (
                    "pais_emision_documento",
                    models.ForeignKey(
                        blank=True,
                        db_column="pais_emision_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.pais",
                    ),
                ),
            ],
            options={
                "db_table": "personas_pasajero",
            },
        ),
        migrations.AddField(
            model_name="cliente",
            name="pasajeros",
            field=models.ManyToManyField(
                blank=True, related_name="clientes_asociados", to="crm.pasajero"
            ),
        ),
    ]
