# Generated by Django 5.2.6 on 2026-02-09 20:19

import core.fields
import core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id_cliente",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID Cliente"
                    ),
                ),
                (
                    "nombres",
                    models.CharField(
                        max_length=100,
                        validators=[core.validators.validar_no_vacio_o_espacios],
                        verbose_name="Nombres",
                    ),
                ),
                (
                    "apellidos",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Apellidos"
                    ),
                ),
                (
                    "nombre_empresa",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Nombre de Empresa",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Correo Electrónico",
                    ),
                ),
                (
                    "telefono_principal",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Teléfono Principal",
                    ),
                ),
                (
                    "telefono_secundario",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Teléfono Secundario",
                    ),
                ),
                (
                    "direccion_linea1",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Dirección Línea 1",
                    ),
                ),
                (
                    "direccion_linea2",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Dirección Línea 2",
                    ),
                ),
                (
                    "codigo_postal",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Código Postal",
                    ),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Nacimiento"
                    ),
                ),
                (
                    "numero_pasaporte",
                    core.fields.EncryptedCharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        validators=[core.validators.validar_numero_pasaporte],
                        verbose_name="Número de Pasaporte",
                    ),
                ),
                (
                    "fecha_expiracion_pasaporte",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha Expiración Pasaporte",
                    ),
                ),
                (
                    "cedula_identidad",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Cédula de Identidad",
                    ),
                ),
                (
                    "direccion",
                    models.TextField(blank=True, null=True, verbose_name="Dirección"),
                ),
                (
                    "foto_perfil",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="clientes/fotos/",
                        verbose_name="Foto de Perfil",
                    ),
                ),
                (
                    "preferencias_viaje",
                    models.TextField(
                        blank=True, null=True, verbose_name="Preferencias de Viaje"
                    ),
                ),
                (
                    "notas_cliente",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notas sobre el Cliente"
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Registro",
                    ),
                ),
                (
                    "tipo_cliente",
                    models.CharField(
                        choices=[
                            ("IND", "Individual"),
                            ("COR", "Corporativo"),
                            ("VIP", "VIP"),
                            ("OTR", "Otro"),
                        ],
                        default="IND",
                        max_length=3,
                        verbose_name="Tipo de Cliente",
                    ),
                ),
                (
                    "puntos_fidelidad",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Puntos acumulados por el cliente.",
                        verbose_name="Puntos de Fidelidad",
                    ),
                ),
                (
                    "es_cliente_frecuente",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        verbose_name="Es Cliente Frecuente",
                    ),
                ),
                (
                    "ciudad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_clientes",
                        to="core.ciudad",
                        verbose_name="Ciudad",
                    ),
                ),
                (
                    "nacionalidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_clientes_nacionalidad",
                        to="core.pais",
                        verbose_name="Nacionalidad",
                    ),
                ),
                (
                    "pais_emision_pasaporte",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_clientes_pasaporte_emitido",
                        to="core.pais",
                        verbose_name="País Emisión Pasaporte",
                    ),
                ),
            ],
            options={
                "managed": True,
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "db_table": "personas_cliente",
                "ordering": ["apellidos", "nombres", "nombre_empresa"],
            },
        ),
        migrations.CreateModel(
            name="Pasajero",
            fields=[
                (
                    "id_pasajero",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID Pasajero"
                    ),
                ),
                (
                    "nombres",
                    models.CharField(
                        max_length=100,
                        validators=[core.validators.validar_no_vacio_o_espacios],
                        verbose_name="Nombres",
                    ),
                ),
                (
                    "apellidos",
                    models.CharField(
                        max_length=100,
                        validators=[core.validators.validar_no_vacio_o_espacios],
                        verbose_name="Apellidos",
                    ),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Nacimiento"
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("PASS", "Pasaporte"),
                            ("CI", "Cédula de Identidad"),
                            ("OTRO", "Otro"),
                        ],
                        default="PASS",
                        max_length=4,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        validators=[core.validators.validar_numero_pasaporte],
                        verbose_name="Número de Documento/Pasaporte",
                    ),
                ),
                (
                    "fecha_emision_documento",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de emisión del pasaporte/documento",
                        null=True,
                        verbose_name="Fecha Emisión Documento",
                    ),
                ),
                (
                    "fecha_vencimiento_documento",
                    models.DateField(
                        blank=True,
                        db_column="fecha_expiracion_documento",
                        null=True,
                        verbose_name="Fecha Vencimiento Documento",
                    ),
                ),
                (
                    "tiene_fiebre_amarilla",
                    models.BooleanField(
                        default=False,
                        help_text="¿El pasajero tiene la vacuna de fiebre amarilla?",
                        verbose_name="Tiene Vacuna Fiebre Amarilla",
                    ),
                ),
                (
                    "fecha_vacuna_fiebre_amarilla",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de aplicación de la vacuna (válida por 10 años)",
                        null=True,
                        verbose_name="Fecha Vacuna Fiebre Amarilla",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Correo Electrónico",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "preferencias",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Preferencias"
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notas sobre el Pasajero"
                    ),
                ),
                (
                    "nacionalidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_pasajeros_nacionalidad",
                        to="core.pais",
                        verbose_name="Nacionalidad",
                    ),
                ),
                (
                    "pais_emision_documento",
                    models.ForeignKey(
                        blank=True,
                        db_column="pais_emision_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.pais",
                        verbose_name="País Emisión Documento",
                    ),
                ),
            ],
            options={
                "managed": True,
                "verbose_name": "Pasajero",
                "verbose_name_plural": "Pasajeros",
                "db_table": "personas_pasajero",
                "ordering": ["apellidos", "nombres"],
            },
        ),
    ]
