# Generated by Django 5.0.2 on 2026-04-02 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookings",
            "0002_actividadservicio_proveedor_actividadservicio_venta_and_more",
        ),
        ("core", "0003_asientocontable_moneda_ciudad_pais_and_more"),
        ("crm", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="comisionfreelancer",
            name="freelancer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comisiones_generadas",
                to="crm.freelancerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="comisionfreelancer",
            name="venta",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comision_asignada",
                to="bookings.venta",
            ),
        ),
        migrations.AlterField(
            model_name="freelancerprofile",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="freelancers_asociados",
                to="core.agencia",
            ),
        ),
        migrations.AlterField(
            model_name="freelancerprofile",
            name="usuario",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perfil_freelancer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="mensajewhatsapp",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mensajes_whatsapp",
                to="crm.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="oportunidadviaje",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="oportunidades",
                to="crm.cliente",
            ),
        ),
    ]
