# Generated by Django 5.2.6 on 2026-02-14 18:45

import core.fields
import core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pasajero",
            name="numero_documento",
            field=core.fields.EncryptedCharField(
                max_length=50,
                unique=True,
                validators=[core.validators.validar_numero_pasaporte],
                verbose_name="Número de Documento/Pasaporte",
            ),
        ),
    ]
