# Generated by Django 5.2.6 on 2026-02-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_alter_pasajero_numero_documento"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="pasajeros",
            field=models.ManyToManyField(
                blank=True,
                related_name="clientes",
                to="crm.pasajero",
                verbose_name="Pasajeros Vinculados",
            ),
        ),
    ]
