# Generated by Django 5.2.6 on 2026-02-19 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0076_facturaconsolidada_agencia"),
        ("crm", "0003_cliente_pasajeros"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="cliente",
                    name="agencia",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.agencia",
                        verbose_name="Agencia",
                    ),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name="pasajero",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.agencia",
                verbose_name="Agencia",
            ),
        ),
    ]
