# Generated by Django 5.2.13 on 2026-04-18 16:20

"""Migración de base de datos para crm.
"""

from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("crm", "0003_remove_cliente_agencia_registradora_cliente_agencia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="tipo_cliente",
            field=models.CharField(
                choices=[
                    ("IND", "Individual / Particular"),
                    ("COR", "Corporativo / B2B"),
                    ("FRE", "Freelance / Aliado"),
                    ("MAY", "Mayorista / Tour Operador"),
                ],
                default="IND",
                max_length=10,
            ),
        ),
    ]
