# Generated by Django 5.2.6 on 2026-02-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0076_facturaconsolidada_agencia"),
        ("crm", "0004_cliente_agencia_pasajero_agencia"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(
                fields=["agencia", "apellidos"], name="personas_cl_agencia_243194_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(
                fields=["agencia", "cedula_identidad"],
                name="personas_cl_agencia_1c0a88_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(
                fields=["agencia", "email"], name="personas_cl_agencia_c03314_idx"
            ),
        ),
    ]
