# Generated by Django 6.0.4 on 2026-04-30 15:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ciudad_codigo_iata_comisionoverrideaerolinea'),
        ('crm', '0004_alter_cliente_tipo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='comisionfreelancer',
            name='agencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='core.agencia'),
        ),
        migrations.AddField(
            model_name='pasajero',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='agencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='core.agencia'),
        ),
    ]
