# Generated by Django 5.2.6 on 2026-05-02 23:21

"""Migración de base de datos para crm.
"""

from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("crm", "0006_comisionfreelancer_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mensajewhatsapp",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fecha de Eliminación"),
        ),
        migrations.AddField(
            model_name="mensajewhatsapp",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Eliminado"),
        ),
    ]
