# Generated by Django 5.2.6 on 2026-05-04 00:17

"""Migración de base de datos para crm.
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("crm", "0007_mensajewhatsapp_deleted_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="PasaporteEscaneado",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("imagen_original", models.ImageField(upload_to="pasaportes/%Y/%m/")),
                        (
                            "imagen_procesada",
                            models.ImageField(
                                blank=True, null=True, upload_to="pasaportes/processed/%Y/%m/"
                            ),
                        ),
                        ("numero_pasaporte", models.CharField(blank=True, max_length=20)),
                        ("nombres", models.CharField(blank=True, max_length=100)),
                        ("apellidos", models.CharField(blank=True, max_length=100)),
                        ("nacionalidad", models.CharField(blank=True, max_length=3)),
                        ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                        ("fecha_vencimiento", models.DateField(blank=True, null=True)),
                        (
                            "sexo",
                            models.CharField(
                                blank=True,
                                choices=[("M", "Masculino"), ("F", "Femenino")],
                                max_length=1,
                            ),
                        ),
                        ("lugar_nacimiento", models.CharField(blank=True, max_length=100)),
                        (
                            "confianza_ocr",
                            models.CharField(
                                choices=[
                                    ("HIGH", "Alta"),
                                    ("MEDIUM", "Media"),
                                    ("LOW", "Baja"),
                                ],
                                default="MEDIUM",
                                max_length=10,
                            ),
                        ),
                        ("datos_ocr_completos", models.JSONField(default=dict)),
                        ("texto_mrz", models.TextField(blank=True)),
                        ("errores_detectados", models.JSONField(default=list)),
                        ("fecha_procesamiento", models.DateTimeField(auto_now_add=True)),
                        ("verificado_manualmente", models.BooleanField(default=False)),
                        (
                            "cliente",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                to="crm.cliente",
                            ),
                        ),
                        (
                            "procesado_por",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Pasaporte Escaneado",
                        "verbose_name_plural": "Pasaportes Escaneados",
                        "db_table": "core_pasaporte_escaneado",
                        "ordering": ["-fecha_procesamiento"],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
