# Generated by Django 5.2.6 on 2026-05-04 13:42

"""Migración de base de datos para crm.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("common", "0001_initial"),
        ("crm", "0008_pasaporteescaneado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="ciudad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.ciudad",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="nacionalidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clientes_nacionalidad",
                to="common.pais",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="pais_emision_pasaporte",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clientes_emision_pasaporte",
                to="common.pais",
            ),
        ),
        migrations.AlterField(
            model_name="pasajero",
            name="nacionalidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pasajeros_nacionalidad",
                to="common.pais",
            ),
        ),
        migrations.AlterField(
            model_name="pasajero",
            name="pais_emision_documento",
            field=models.ForeignKey(
                blank=True,
                db_column="pais_emision_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.pais",
            ),
        ),
    ]
