# Generated by Django 5.2.6 on 2026-05-09 01:29

"""Migración de base de datos para crm.
"""

from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("common", "0001_initial"),
        ("core", "0016_add_critical_indexes"),
        ("crm", "0009_alter_cliente_ciudad_alter_cliente_nacionalidad_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(fields=["agencia", "tipo_cliente"], name="idx_cliente_agencia_tipo"),
        ),
    ]
