# Generated by Django 5.2.6 on 2026-05-09 17:21

"""Migración de base de datos para crm.
"""

from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("crm", "0010_add_critical_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="pasajero",
            name="foto_perfil",
            field=models.ImageField(blank=True, null=True, upload_to="pasajeros/fotos/"),
        ),
    ]
