# Generated by Django 5.2.6 on 2026-05-10 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0012_pasaporteescaneado_agencia_alter_cliente_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="cliente",
            table=None,
        ),
        migrations.AlterModelTable(
            name="mensajewhatsapp",
            table=None,
        ),
        migrations.AlterModelTable(
            name="pasajero",
            table=None,
        ),
        migrations.AlterModelTable(
            name="pasaporteescaneado",
            table=None,
        ),
    ]
