# Generated by Django 5.2.6 on 2026-05-14 18:48

"""Migración de base de datos para crm.
"""

from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("common", "0002_alter_aerolinea_table_alter_ciudad_table_and_more"),
        ("core", "0028_alter_agencia_activa_and_more"),
        ("crm", "0013_alter_cliente_table_alter_mensajewhatsapp_table_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pasajero",
            options={"verbose_name": "Pasajero", "verbose_name_plural": "Pasajeros"},
        ),
        migrations.RemoveIndex(
            model_name="cliente",
            name="idx_cliente_agencia_tipo",
        ),
        migrations.AlterField(
            model_name="cliente",
            name="fecha_expiracion_pasaporte",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="fecha_nacimiento",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="comisionfreelancer",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="freelancerprofile",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="mensajewhatsapp",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="oportunidadviaje",
            name="etapa",
            field=models.CharField(
                choices=[
                    ("NEW", "Nuevo Lead"),
                    ("QUO", "Armando Cotización"),
                    ("PAY", "Esperando Pago"),
                    ("WON", "Ganado (Vendido)"),
                    ("LOS", "Perdido"),
                ],
                db_index=True,
                default="NEW",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="oportunidadviaje",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="pasajero",
            name="fecha_vencimiento_documento",
            field=models.DateField(
                blank=True,
                db_column="fecha_expiracion_documento",
                db_index=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pasajero",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="pasajero",
            name="tipo_documento",
            field=models.CharField(db_index=True, default="PASS", max_length=4),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(
                fields=["agencia_id", "tipo_cliente"], name="idx_cliente_agencia_tipo"
            ),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(
                fields=["is_deleted", "agencia_id"], name="idx_cliente_soft_delete_saas"
            ),
        ),
        migrations.AddIndex(
            model_name="pasajero",
            index=models.Index(
                fields=["is_deleted", "agencia_id"],
                name="idx_pasajero_soft_delete_saas",
            ),
        ),
    ]
