# Generated by Django 5.2.6 on 2026-05-14 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0024_alter_actividadservicio_agencia_and_more"),
        ("core", "0029_alter_anulacionboleto_agencia_and_more"),
        ("crm", "0014_alter_pasajero_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comisionfreelancer",
            options={
                "verbose_name": "Comisión de Freelancer",
                "verbose_name_plural": "Comisiones de Freelancers",
            },
        ),
        migrations.AlterModelOptions(
            name="freelancerprofile",
            options={
                "verbose_name": "Perfil de Freelancer",
                "verbose_name_plural": "Perfiles de Freelancers",
            },
        ),
        migrations.AlterModelOptions(
            name="mensajewhatsapp",
            options={
                "verbose_name": "Mensaje de WhatsApp",
                "verbose_name_plural": "Mensajes de WhatsApp",
            },
        ),
        migrations.AlterModelOptions(
            name="oportunidadviaje",
            options={
                "verbose_name": "Oportunidad de Viaje",
                "verbose_name_plural": "Oportunidades de Viaje",
            },
        ),
        migrations.AlterField(
            model_name="cliente",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
        migrations.AlterField(
            model_name="comisionfreelancer",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
        migrations.AlterField(
            model_name="freelancerprofile",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
        migrations.AlterField(
            model_name="mensajewhatsapp",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
        migrations.AlterField(
            model_name="oportunidadviaje",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
        migrations.AlterField(
            model_name="pasajero",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
        migrations.AlterField(
            model_name="pasaporteescaneado",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
        migrations.AddIndex(
            model_name="comisionfreelancer",
            index=models.Index(
                fields=["is_deleted", "agencia_id"], name="idx_freecom_soft_delete_saas"
            ),
        ),
        migrations.AddIndex(
            model_name="freelancerprofile",
            index=models.Index(
                fields=["is_deleted", "agencia_id"], name="idx_free_soft_delete_saas"
            ),
        ),
        migrations.AddIndex(
            model_name="mensajewhatsapp",
            index=models.Index(
                fields=["is_deleted", "agencia_id"], name="idx_wa_soft_delete_saas"
            ),
        ),
        migrations.AddIndex(
            model_name="oportunidadviaje",
            index=models.Index(
                fields=["is_deleted", "agencia_id"], name="idx_lead_soft_delete_saas"
            ),
        ),
    ]
