# Generated by Django 5.2.6 on 2026-05-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0015_alter_comisionfreelancer_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pasajero",
            name="fecha_vencimiento_pasaporte",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
