# Generated by Django 5.2.6 on 2026-06-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0017_alter_cliente_agencia_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="pasajero",
            name="idx_pasajero_soft_delete_saas",
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefono_principal",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
