# Generated by Django 5.2.6 on 2026-06-02 03:13

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0018_add_missing_indexes"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="cliente",
            managers=[
                ("with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="comisionfreelancer",
            managers=[
                ("with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="freelancerprofile",
            managers=[
                ("with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="mensajewhatsapp",
            managers=[
                ("with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="oportunidadviaje",
            managers=[
                ("with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pasajero",
            managers=[
                ("with_deleted", django.db.models.manager.Manager()),
            ],
        ),
    ]
