# Generated by Django 5.2.6 on 2026-06-03 17:27

"""Migración de base de datos para crm.
"""

from django.db import migrations


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("crm", "0019_add_with_deleted_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="cliente",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="comisionfreelancer",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="freelancerprofile",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="mensajewhatsapp",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="oportunidadviaje",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="pasajero",
            managers=[],
        ),
    ]
