# Generated by Django 5.2.14 on 2026-06-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_alter_aerolinea_table_alter_ciudad_table_and_more"),
        ("crm", "0022_rename_personas_core_tables_to_crm"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pasajero",
            index=models.Index(
                fields=["is_deleted", "agencia_id"],
                name="idx_pasajero_soft_delete_saas",
            ),
        ),
        migrations.AddIndex(
            model_name="pasajero",
            index=models.Index(
                fields=["agencia_id", "numero_pasaporte"],
                name="idx_pasajero_agencia_pasaporte",
            ),
        ),
    ]
