# Generated by Django 5.2.14 on 2026-06-24 17:56

"""Migración de base de datos para crm.
"""

from django.db import migrations, models

import core.validators


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("crm", "0023_pasajero_idx_pasajero_soft_delete_saas_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="foto_perfil",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="clientes/fotos/",
                validators=[core.validators.antivirus_hook],
            ),
        ),
        migrations.AlterField(
            model_name="pasajero",
            name="foto_perfil",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="pasajeros/fotos/",
                validators=[core.validators.antivirus_hook],
            ),
        ),
        migrations.AlterField(
            model_name="pasaporteescaneado",
            name="imagen_original",
            field=models.ImageField(
                upload_to="pasaportes/%Y/%m/", validators=[core.validators.antivirus_hook]
            ),
        ),
        migrations.AlterField(
            model_name="pasaporteescaneado",
            name="imagen_procesada",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="pasaportes/processed/%Y/%m/",
                validators=[core.validators.antivirus_hook],
            ),
        ),
    ]
