# Generated by Django 5.2.14 on 2026-06-24 21:33

"""Migración de base de datos para crm.
"""

from django.db import migrations, models

import core.validators


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("crm", "0024_alter_cliente_foto_perfil_alter_pasajero_foto_perfil_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pasajero",
            name="apellidos_ocr",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="pasajero",
            name="cedula_limpia",
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="pasajero",
            name="fecha_nacimiento_ocr",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pasajero",
            name="foto_id_rostro",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="pasajeros/rostros/",
                validators=[core.validators.antivirus_hook],
            ),
        ),
        migrations.AddField(
            model_name="pasajero",
            name="genero",
            field=models.CharField(
                blank=True,
                choices=[("M", "Masculino"), ("F", "Femenino"), ("X", "Otro")],
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="pasajero",
            name="nombres_ocr",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
