# Generated by Django 5.2.14 on 2026-06-30 14:45

"""Migración de base de datos para crm.
"""

from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("crm", "0026_alter_pasajero_apellidos_ocr_alter_pasajero_nombres_ocr"),
    ]

    operations = [
        migrations.AddField(
            model_name="mensajewhatsapp",
            name="es_bot",
            field=models.BooleanField(
                default=False, help_text="True si el mensaje fue enviado por el bot de IA"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="foto_perfil",
            field=models.ImageField(blank=True, null=True, upload_to="clientes/fotos/"),
        ),
        migrations.AlterField(
            model_name="pasajero",
            name="foto_perfil",
            field=models.ImageField(blank=True, null=True, upload_to="pasajeros/fotos/"),
        ),
        migrations.AlterField(
            model_name="pasaporteescaneado",
            name="imagen_original",
            field=models.ImageField(upload_to="pasaportes/%Y/%m/"),
        ),
        migrations.AlterField(
            model_name="pasaporteescaneado",
            name="imagen_procesada",
            field=models.ImageField(blank=True, null=True, upload_to="pasaportes/processed/%Y/%m/"),
        ),
    ]
