# Generated by Django 5.2.14 on 2026-07-11 22:00

from django.db import migrations


def clean_null_charfields(apps, schema_editor):
    """Replace NULL with empty string in CharField/TextField."""
    # CRM models with null=True on CharField/TextField
    model_fields = {
        "Cliente": [
            "email",
            "telefono",
            "direccion",
            "ciudad",
            "estado",
            "pais",
            "codigo_postal",
            "referencia_comercial",
            "notas",
            "preferencias",
            "origen",
            "fuente_captacion",
            "medio_contacto",
            "vendedor_asignado",
            "tags",
            "metadata",
            "rfc",
            "curp",
            "regimen_fiscal",
            "uso_cfdi",
            "forma_pago",
            "metodo_pago",
            "banco",
            "cuenta_bancaria",
        ],
        "OportunidadViaje": [
            "destino",
            "tipo_viaje",
            "presupuesto_estimado",
            "fecha_inicio",
            "fecha_fin",
            "notas",
            "requisitos_especiales",
        ],
        "FreelancerProfile": [
            "especialidad",
            "bio",
            "telefono",
            "direccion",
            "banco",
            "cuenta",
            "rfc",
            "regimen_fiscal",
        ],
        "ComisionFreelancer": [
            "concepto",
            "observaciones",
        ],
        "MensajeWhatsApp": [
            "mensaje",
            "media_url",
            "respuesta",
        ],
    }

    for model_name, fields in model_fields.items():
        try:
            Modelo = apps.get_model("crm", model_name)
            for obj in Modelo.objects.all():
                changed = False
                for field in fields:
                    value = getattr(obj, field, None)
                    if value is None:
                        setattr(obj, field, "")
                        changed = True
                if changed:
                    obj.save(update_fields=fields)
        except LookupError:
            pass


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0029_remove_cliente_es_proveedor_and_more"),
    ]

    operations = [
        migrations.RunPython(
            clean_null_charfields,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
