# Generated by Django 5.2.14 on 2026-07-14 17:49

"""Migración de base de datos para crm.
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("core", "0050_delete_numberingsequence"),
        ("crm", "0033_cascade_to_set_null"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="whatsappscheduledmessage",
            name="is_deleted",
        ),
        migrations.AlterField(
            model_name="freelancerprofile",
            name="usuario",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="perfil_freelancer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="whatsappscheduledmessage",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappscheduledmessage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
