# Generated by Django 5.2.14 on 2026-08-17 20:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0052_boletoimportado_datos_parseados_actualizado_and_more"),
        ("common", "0005_userprogress"),
        ("core", "0060_webhookdelivery_agencia_and_more"),
        ("crm", "0035_cliente_messaging_preferences"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="telegram_subscribed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora de autoconexión del cliente al bot de Telegram",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="MovimientoSaldoCliente",
            fields=[
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo_movimiento",
                    models.CharField(
                        choices=[
                            ("DEP", "Depósito de Anticipo / Abono"),
                            ("CON", "Consumo en Venta / Deducción"),
                            ("REE", "Reembolso / Devolución"),
                            ("AJU", "Ajuste Contable"),
                        ],
                        default="DEP",
                        max_length=3,
                        verbose_name="Tipo de Movimiento",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monto positivo para depósitos/abonos; positivo para el valor de la deducción.",
                        max_digits=12,
                        verbose_name="Monto",
                    ),
                ),
                (
                    "saldo_resultante",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Saldo a favor del cliente después de aplicar esta transacción.",
                        max_digits=12,
                        verbose_name="Saldo Resultante",
                    ),
                ),
                (
                    "metodo_pago_origen",
                    models.CharField(
                        blank=True,
                        help_text="Ej. Zelle, Transferencia, Efectivo",
                        max_length=50,
                        null=True,
                        verbose_name="Método de Pago Origen",
                    ),
                ),
                (
                    "referencia_bancaria",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Referencia Bancaria"
                    ),
                ),
                (
                    "comprobante",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="clientes/comprobantes_saldo/%Y/%m/",
                        verbose_name="Comprobante",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Descripción / Motivo"
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, verbose_name="Fecha"
                    ),
                ),
                (
                    "agencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="core.agencia",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos_saldo",
                        to="crm.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "moneda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.moneda",
                        verbose_name="Moneda",
                    ),
                ),
                (
                    "pago_venta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimientos_saldo_cliente",
                        to="bookings.pagoventa",
                        verbose_name="Pago de Venta Asociado",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado Por",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consumos_saldo_cliente",
                        to="bookings.venta",
                        verbose_name="Venta Asociada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Saldo de Cliente",
                "verbose_name_plural": "Movimientos de Saldo de Clientes",
                "ordering": ["-creado"],
                "indexes": [
                    models.Index(fields=["cliente", "-creado"], name="idx_mov_saldo_cli_fecha"),
                    models.Index(
                        fields=["agencia_id", "tipo_movimiento"], name="idx_mov_saldo_agencia_tipo"
                    ),
                ],
            },
        ),
    ]
