# Generated by Django 5.2.6 on 2025-09-18 16:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("personas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cotizacion",
            fields=[
                (
                    "id_cotizacion",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID Cotización"
                    ),
                ),
                (
                    "numero_cotizacion",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Número de Cotización",
                    ),
                ),
                (
                    "fecha_emision",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Emisión",
                    ),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Vencimiento"
                    ),
                ),
                (
                    "total_cotizado",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=12,
                        verbose_name="Total Cotizado",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BOR", "Borrador"),
                            ("ENV", "Enviada al Cliente"),
                            ("ACE", "Aceptada"),
                            ("REC", "Rechazada"),
                            ("VEN", "Vencida"),
                        ],
                        default="BOR",
                        max_length=3,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "notas",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="personas.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "moneda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cotizaciones_cotizaciones",
                        to="core.moneda",
                        verbose_name="Moneda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cotización",
                "verbose_name_plural": "Cotizaciones",
                "ordering": ["-fecha_emision"],
            },
        ),
        migrations.CreateModel(
            name="ItemCotizacion",
            fields=[
                (
                    "id_item_cotizacion",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Item Cotización",
                    ),
                ),
                (
                    "descripcion_personalizada",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Descripción Personalizada",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Precio Unitario"
                    ),
                ),
                (
                    "subtotal_item",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=12,
                        verbose_name="Subtotal Item",
                    ),
                ),
                (
                    "cotizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items_cotizacion",
                        to="cotizaciones.cotizacion",
                        verbose_name="Cotización",
                    ),
                ),
                (
                    "producto_servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cotizaciones_items_cotizacion",
                        to="core.productoservicio",
                        verbose_name="Producto/Servicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Cotización",
                "verbose_name_plural": "Items de Cotización",
            },
        ),
    ]
