# Generated by Django 5.2.6 on 2025-09-25 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemcotizacion",
            options={
                "ordering": ["id_item_cotizacion"],
                "verbose_name": "Item de Cotización",
                "verbose_name_plural": "Items de Cotización",
            },
        ),
        migrations.RemoveField(
            model_name="cotizacion",
            name="moneda",
        ),
        migrations.RemoveField(
            model_name="itemcotizacion",
            name="cantidad",
        ),
        migrations.RemoveField(
            model_name="itemcotizacion",
            name="descripcion_personalizada",
        ),
        migrations.RemoveField(
            model_name="itemcotizacion",
            name="precio_unitario",
        ),
        migrations.RemoveField(
            model_name="itemcotizacion",
            name="producto_servicio",
        ),
        migrations.RemoveField(
            model_name="itemcotizacion",
            name="subtotal_item",
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="archivo_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="cotizaciones_pdf/",
                verbose_name="Archivo PDF",
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="consultor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Consultor",
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="destino",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Destino del Viaje"
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="numero_pasajeros",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Número de Pasajeros"
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="terminos_cancelacion",
            field=models.TextField(
                blank=True, null=True, verbose_name="Términos de Cancelación"
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="terminos_pago",
            field=models.TextField(
                blank=True, null=True, verbose_name="Términos de Pago"
            ),
        ),
        migrations.AddField(
            model_name="itemcotizacion",
            name="costo",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Costo Total del Item",
            ),
        ),
        migrations.AddField(
            model_name="itemcotizacion",
            name="descripcion",
            field=models.CharField(
                default="", max_length=255, verbose_name="Descripción Principal"
            ),
        ),
        migrations.AddField(
            model_name="itemcotizacion",
            name="detalles_json",
            field=models.JSONField(
                blank=True,
                help_text="Estructura de datos específica para el tipo de item",
                null=True,
                verbose_name="Detalles (JSON)",
            ),
        ),
        migrations.AddField(
            model_name="itemcotizacion",
            name="tipo_item",
            field=models.CharField(
                choices=[
                    ("VUE", "Vuelo"),
                    ("ALO", "Alojamiento"),
                    ("ACT", "Actividad"),
                    ("SEG", "Seguro de Viaje"),
                    ("OTR", "Otro"),
                ],
                default="OTR",
                max_length=3,
                verbose_name="Tipo de Item",
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="notas",
            field=models.TextField(
                blank=True, null=True, verbose_name="Notas Internas"
            ),
        ),
        migrations.AlterField(
            model_name="itemcotizacion",
            name="cotizacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="cotizaciones.cotizacion",
                verbose_name="Cotización",
            ),
        ),
    ]
