# Generated by Django 5.2.6 on 2025-09-30 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alojamientoreserva_item_venta"),
        ("cotizaciones", "0002_alter_itemcotizacion_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="email_enviado",
            field=models.BooleanField(default=False, verbose_name="Email Enviado"),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="fecha_envio",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Envío"
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="fecha_respuesta",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Respuesta"
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="fecha_vista",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha Vista por Cliente"
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="venta_generada",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.venta",
                verbose_name="Venta Generada",
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("BOR", "Borrador"),
                    ("ENV", "Enviada al Cliente"),
                    ("VIS", "Vista por Cliente"),
                    ("ACE", "Aceptada"),
                    ("REC", "Rechazada"),
                    ("VEN", "Vencida"),
                    ("CON", "Convertida a Venta"),
                ],
                default="BOR",
                max_length=3,
                verbose_name="Estado",
            ),
        ),
    ]
