# Generated by Django 5.2.6 on 2026-02-09 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0072_remove_actividadservicio_proveedor_and_more"),
        (
            "cotizaciones",
            "0003_cotizacion_email_enviado_cotizacion_fecha_envio_and_more",
        ),
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="condiciones_comerciales",
            field=models.TextField(
                blank=True, null=True, verbose_name="Condiciones Comerciales"
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="descripcion_general",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descripción General"
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="fecha_validez",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de Validez"
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="moneda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.moneda",
                verbose_name="Moneda",
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="nombre_cliente_manual",
            field=models.CharField(
                blank=True,
                help_text="Usar si el cliente no está registrado aún.",
                max_length=150,
                null=True,
                verbose_name="Nombre Cliente (Prospecto)",
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="notas_internas",
            field=models.TextField(
                blank=True, null=True, verbose_name="Notas Internas"
            ),
        ),
        migrations.AddField(
            model_name="itemcotizacion",
            name="cantidad",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=10, verbose_name="Cantidad"
            ),
        ),
        migrations.AddField(
            model_name="itemcotizacion",
            name="descripcion_personalizada",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Descripción Personalizada",
            ),
        ),
        migrations.AddField(
            model_name="itemcotizacion",
            name="impuestos_item",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Impuestos"
            ),
        ),
        migrations.AddField(
            model_name="itemcotizacion",
            name="precio_unitario",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Precio Unitario",
            ),
        ),
        migrations.AddField(
            model_name="itemcotizacion",
            name="producto_servicio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.productoservicio",
                verbose_name="Producto/Servicio",
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="crm.cliente",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterModelTable(
            name="cotizacion",
            table="core_cotizacion",
        ),
        migrations.AlterModelTable(
            name="itemcotizacion",
            table="core_itemcotizacion",
        ),
    ]
