# Generated by Django 5.2.6 on 2026-04-02 00:00

import core.storage
import core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActividadServicio",
            fields=[
                (
                    "id_actividad_servicio",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID Actividad"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=150, verbose_name="Nombre Actividad"),
                ),
                (
                    "fecha",
                    models.DateField(blank=True, null=True, verbose_name="Fecha"),
                ),
                (
                    "duracion_horas",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Duración (horas)",
                    ),
                ),
                (
                    "incluye",
                    models.TextField(blank=True, null=True, verbose_name="Incluye"),
                ),
                (
                    "no_incluye",
                    models.TextField(blank=True, null=True, verbose_name="No Incluye"),
                ),
                (
                    "nombre_pasajero",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nombre Pasajero"
                    ),
                ),
                (
                    "localizador_proveedor",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Localizador Proveedor"
                    ),
                ),
                (
                    "notas",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
            ],
            options={
                "verbose_name": "Actividad / Excursión",
                "verbose_name_plural": "Actividades / Excursiones",
                "db_table": "core_actividadservicio",
                "ordering": ["fecha", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="AlojamientoReserva",
            fields=[
                (
                    "id_alojamiento_reserva",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID Alojamiento"
                    ),
                ),
                (
                    "nombre_establecimiento",
                    models.CharField(
                        max_length=150, verbose_name="Nombre Establecimiento"
                    ),
                ),
                (
                    "check_in",
                    models.DateField(blank=True, null=True, verbose_name="Check In"),
                ),
                (
                    "check_out",
                    models.DateField(blank=True, null=True, verbose_name="Check Out"),
                ),
                (
                    "regimen_alimentacion",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Desayuno, Media Pensión, Todo Incluido",
                        max_length=30,
                        null=True,
                        verbose_name="Régimen Alimentación",
                    ),
                ),
                (
                    "habitaciones",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Habitaciones"
                    ),
                ),
                (
                    "nombre_pasajero",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nombre Pasajero"
                    ),
                ),
                (
                    "localizador_proveedor",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Localizador Proveedor"
                    ),
                ),
                (
                    "notas",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
            ],
            options={
                "verbose_name": "Alojamiento (Reserva)",
                "verbose_name_plural": "Alojamientos (Reservas)",
                "db_table": "core_alojamientoreserva",
                "ordering": ["check_in"],
            },
        ),
        migrations.CreateModel(
            name="AlquilerAutoReserva",
            fields=[
                (
                    "id_alquiler_auto",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Alquiler Auto",
                    ),
                ),
                (
                    "fecha_hora_retiro",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha/Hora Retiro"
                    ),
                ),
                (
                    "fecha_hora_devolucion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha/Hora Devolución"
                    ),
                ),
                (
                    "categoria_auto",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Categoría / Clase",
                    ),
                ),
                (
                    "compania_rentadora",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Compañía Rentadora",
                    ),
                ),
                (
                    "numero_confirmacion",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Número Confirmación",
                    ),
                ),
                (
                    "nombre_conductor",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nombre Conductor"
                    ),
                ),
                (
                    "incluye_seguro",
                    models.BooleanField(default=False, verbose_name="Incluye Seguro"),
                ),
                (
                    "notas",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "costo_neto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Costo Neto",
                    ),
                ),
                (
                    "precio_venta",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Precio Venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alquiler de Auto",
                "verbose_name_plural": "Alquileres de Autos",
                "db_table": "core_alquilerautoreserva",
                "ordering": ["fecha_hora_retiro"],
            },
        ),
        migrations.CreateModel(
            name="BoletoImportado",
            fields=[
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Eliminado"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Eliminación"
                    ),
                ),
                (
                    "id_boleto_importado",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Boleto Importado",
                    ),
                ),
                (
                    "archivo_boleto",
                    models.FileField(
                        blank=True,
                        help_text="Suba el archivo del boleto en formato PDF, TXT o EML (máx 5MB).",
                        max_length=255,
                        null=True,
                        storage=core.storage.RawFileStorage,
                        upload_to="boletos_importados/%Y/%m/",
                        validators=[
                            core.validators.validate_file_size,
                            core.validators.validate_file_extension,
                            core.validators.antivirus_hook,
                        ],
                        verbose_name="Archivo del Boleto (.pdf, .txt, .eml)",
                    ),
                ),
                (
                    "fecha_subida",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Subida"
                    ),
                ),
                (
                    "formato_detectado",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PDF_KIU", "PDF (KIU)"),
                            ("PDF_SAB", "PDF (Sabre)"),
                            ("PDF_AMA", "PDF (Amadeus)"),
                            ("TXT_KIU", "TXT (KIU)"),
                            ("TXT_SAB", "TXT (Sabre)"),
                            ("TXT_AMA", "TXT (Amadeus)"),
                            ("EML_KIU", "EML (KIU)"),
                            ("EML_GEN", "EML (General)"),
                            ("OTR", "Otro/Desconocido"),
                            ("ERR", "Error de Formato"),
                        ],
                        default="OTR",
                        max_length=20,
                        verbose_name="Formato Detectado",
                    ),
                ),
                (
                    "datos_parseados",
                    models.JSONField(
                        blank=True,
                        help_text="Información extraída del boleto en formato JSON.",
                        null=True,
                        verbose_name="Datos Parseados",
                    ),
                ),
                (
                    "estado_parseo",
                    models.CharField(
                        choices=[
                            ("PEN", "Pendiente de Parseo"),
                            ("PRO", "En Proceso"),
                            ("COM", "Parseo Completado"),
                            ("REV", "Revisión Requerida"),
                            ("ERR", "Error en Parseo"),
                            ("NAP", "No Aplica Parseo"),
                            ("QUE", "Pendiente (Cola Llena)"),
                        ],
                        default="PEN",
                        max_length=3,
                        verbose_name="Estado del Parseo",
                    ),
                ),
                (
                    "log_parseo",
                    models.TextField(
                        blank=True, null=True, verbose_name="Log del Parseo"
                    ),
                ),
                (
                    "numero_boleto",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Número de Boleto",
                    ),
                ),
                (
                    "nombre_pasajero_completo",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Nombre Completo Pasajero (Original)",
                    ),
                ),
                (
                    "nombre_pasajero_procesado",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Nombre Pasajero (Procesado)",
                    ),
                ),
                (
                    "ruta_vuelo",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Ruta del Vuelo (Itinerario)",
                    ),
                ),
                (
                    "fecha_emision_boleto",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de Emisión del Boleto",
                    ),
                ),
                (
                    "aerolinea_emisora",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Aerolínea Emisora",
                    ),
                ),
                (
                    "direccion_aerolinea",
                    models.TextField(
                        blank=True, null=True, verbose_name="Dirección Aerolínea"
                    ),
                ),
                (
                    "agente_emisor",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Agente Emisor",
                    ),
                ),
                (
                    "foid_pasajero",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="FOID/D.Identidad Pasajero",
                    ),
                ),
                (
                    "localizador_pnr",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Localizador (PNR)",
                    ),
                ),
                (
                    "tarifa_base",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Tarifa Base",
                    ),
                ),
                (
                    "impuestos_descripcion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descripción Impuestos"
                    ),
                ),
                (
                    "impuestos_total_calculado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Total Impuestos (Calculado)",
                    ),
                ),
                (
                    "total_boleto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Total del Boleto",
                    ),
                ),
                (
                    "exchange_monto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monto de exchange o diferencial de cambio asociado al boleto.",
                        max_digits=10,
                        null=True,
                        verbose_name="Exchange",
                    ),
                ),
                (
                    "void_monto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monto asociado a VOID (penalidad / reembolso negativo).",
                        max_digits=10,
                        null=True,
                        verbose_name="Void / Penalidad",
                    ),
                ),
                (
                    "comision_agencia",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Comisión propia de la agencia respecto al boleto.",
                        max_digits=10,
                        null=True,
                        verbose_name="Comisión Agencia",
                    ),
                ),
                (
                    "iva_monto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Monto IVA",
                    ),
                ),
                (
                    "inatur_monto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Monto Inatur (1%)",
                    ),
                ),
                (
                    "otros_impuestos_monto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Otros Impuestos",
                    ),
                ),
                (
                    "fee_servicio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fee cobrado por la agencia por gestión del boleto.",
                        max_digits=10,
                        null=True,
                        verbose_name="Fee de Servicio",
                    ),
                ),
                (
                    "igtf_monto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Impuesto a las Grandes Transacciones Financieras u otras retenciones locales.",
                        max_digits=10,
                        null=True,
                        verbose_name="IGTF",
                    ),
                ),
                (
                    "archivo_pdf_generado",
                    models.FileField(
                        blank=True,
                        help_text="El archivo PDF del boleto unificado, generado automáticamente.",
                        max_length=255,
                        null=True,
                        storage=core.storage.RawFileStorage,
                        upload_to="boletos_generados/%Y/%m/",
                        verbose_name="PDF Unificado Generado",
                    ),
                ),
                (
                    "telegram_file_id",
                    models.CharField(
                        blank=True,
                        help_text="ID del archivo en la nube de Telegram (para almacenamiento gratuito).",
                        max_length=255,
                        null=True,
                        verbose_name="Telegram File ID",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Versión del boleto (1=Original, 2+=Re-emisión)",
                        verbose_name="Versión",
                    ),
                ),
                (
                    "estado_emision",
                    models.CharField(
                        choices=[
                            ("ORI", "Original"),
                            ("REE", "Re-emisión"),
                            ("ANU", "Anulado / Void"),
                            ("REM", "Reembolso"),
                        ],
                        default="ORI",
                        max_length=3,
                        verbose_name="Estado de Emisión",
                    ),
                ),
            ],
            options={
                "verbose_name": "Boleto Importado",
                "verbose_name_plural": "Boletos Importados",
                "db_table": "core_boletoimportado",
                "ordering": ["-fecha_subida"],
            },
        ),
        migrations.CreateModel(
            name="CircuitoDia",
            fields=[
                (
                    "id_circuito_dia",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Circuito Día",
                    ),
                ),
                ("dia_numero", models.PositiveSmallIntegerField(verbose_name="Día #")),
                (
                    "titulo",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Título del Día",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "alojamiento_previsto",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Alojamiento Previsto",
                    ),
                ),
                (
                    "actividades_resumen",
                    models.TextField(
                        blank=True, null=True, verbose_name="Actividades/Resumen"
                    ),
                ),
            ],
            options={
                "verbose_name": "Día de Circuito",
                "verbose_name_plural": "Días de Circuito",
                "db_table": "core_circuitodia",
                "ordering": ["circuito", "dia_numero"],
            },
        ),
        migrations.CreateModel(
            name="CircuitoTuristico",
            fields=[
                (
                    "id_circuito",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID Circuito"
                    ),
                ),
                (
                    "nombre_circuito",
                    models.CharField(max_length=255, verbose_name="Nombre Circuito"),
                ),
                (
                    "dias_total",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Días Totales"
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Inicio"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(blank=True, null=True, verbose_name="Fecha Fin"),
                ),
                (
                    "descripcion_general",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descripción General"
                    ),
                ),
                (
                    "incluye",
                    models.TextField(blank=True, null=True, verbose_name="Incluye"),
                ),
                (
                    "no_incluye",
                    models.TextField(blank=True, null=True, verbose_name="No Incluye"),
                ),
                (
                    "costo_neto_estimado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Costo Neto Estimado",
                    ),
                ),
                (
                    "precio_venta_estimado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Precio Venta Estimado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Circuito Turístico",
                "verbose_name_plural": "Circuitos Turísticos",
                "db_table": "core_circuitoturistico",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="EventoServicio",
            fields=[
                (
                    "id_evento_servicio",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Evento/Servicio",
                    ),
                ),
                (
                    "nombre_evento",
                    models.CharField(max_length=255, verbose_name="Nombre Evento"),
                ),
                (
                    "fecha_evento",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Evento"
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Ubicación"
                    ),
                ),
                (
                    "zona_asiento",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Zona/Asiento",
                    ),
                ),
                (
                    "codigo_boleto_evento",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Código Boleto / Ref",
                    ),
                ),
                (
                    "notas",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "costo_neto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Costo Neto",
                    ),
                ),
                (
                    "precio_venta",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Precio Venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento / Servicio",
                "verbose_name_plural": "Eventos / Servicios",
                "db_table": "core_eventoservicio",
                "ordering": ["fecha_evento"],
            },
        ),
        migrations.CreateModel(
            name="FeeVenta",
            fields=[
                (
                    "id_fee_venta",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID Fee"
                    ),
                ),
                (
                    "tipo_fee",
                    models.CharField(
                        choices=[
                            ("EMI", "Emisión"),
                            ("CAM", "Cambio / Exchange"),
                            ("GST", "Gestión"),
                            ("URG", "Urgente"),
                            ("OTR", "Otro"),
                        ],
                        default="GST",
                        max_length=3,
                        verbose_name="Tipo Fee",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto"
                    ),
                ),
                (
                    "es_comision_agencia",
                    models.BooleanField(
                        default=True, verbose_name="Es Comisión Agencia"
                    ),
                ),
                (
                    "taxable",
                    models.BooleanField(
                        default=False, verbose_name="Sujeto a Impuestos"
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Fee de Venta",
                "verbose_name_plural": "Fees de Venta",
                "db_table": "core_feeventa",
                "ordering": ["-creado"],
            },
        ),
        migrations.CreateModel(
            name="ItemVenta",
            fields=[
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Eliminado"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Eliminación"
                    ),
                ),
                (
                    "id_item_venta",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID Item Venta"
                    ),
                ),
                (
                    "descripcion_personalizada",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Descripción Personalizada",
                    ),
                ),
                (
                    "cantidad",
                    models.PositiveIntegerField(default=1, verbose_name="Cantidad"),
                ),
                (
                    "precio_unitario_venta",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Precio Unitario de Venta",
                    ),
                ),
                (
                    "costo_unitario_referencial",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Costo Unitario Referencial",
                    ),
                ),
                (
                    "impuestos_item_venta",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Impuestos por Item",
                    ),
                ),
                (
                    "subtotal_item_venta",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=12,
                        verbose_name="Subtotal Item",
                    ),
                ),
                (
                    "total_item_venta",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=12,
                        verbose_name="Total Item",
                    ),
                ),
                (
                    "fecha_inicio_servicio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Inicio Servicio"
                    ),
                ),
                (
                    "fecha_fin_servicio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Fin Servicio"
                    ),
                ),
                (
                    "codigo_reserva_proveedor",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Código Reserva Proveedor (PNR, Localizador)",
                    ),
                ),
                (
                    "costo_neto_proveedor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Costo Neto Proveedor",
                    ),
                ),
                (
                    "fee_proveedor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Fee Emisión Proveedor",
                    ),
                ),
                (
                    "comision_agencia_monto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Comisión Agencia (Monto)",
                    ),
                ),
                (
                    "fee_agencia_interno",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Fee Interno Agencia",
                    ),
                ),
                (
                    "estado_item",
                    models.CharField(
                        choices=[
                            ("PCO", "Pendiente Confirmación Proveedor"),
                            ("CNF", "Confirmado por Proveedor"),
                            ("CAP", "Cancelado por Proveedor"),
                            ("CAC", "Cancelado por Cliente"),
                            ("UTI", "Utilizado/Completado"),
                        ],
                        default="PCO",
                        max_length=3,
                        verbose_name="Estado del Item/Servicio",
                    ),
                ),
                (
                    "notas_item",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notas del Item"
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Venta/Reserva",
                "verbose_name_plural": "Items de Venta/Reserva",
                "db_table": "core_itemventa",
            },
        ),
        migrations.CreateModel(
            name="PagoVenta",
            fields=[
                (
                    "id_pago_venta",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID Pago"
                    ),
                ),
                (
                    "fecha_pago",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha Pago"
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto"
                    ),
                ),
                (
                    "metodo",
                    models.CharField(
                        choices=[
                            ("EFE", "Efectivo"),
                            ("TAR", "Tarjeta"),
                            ("TRF", "Transferencia"),
                            ("ZEL", "Zelle"),
                            ("PPL", "PayPal"),
                            ("OTR", "Otro"),
                        ],
                        default="TRF",
                        max_length=3,
                        verbose_name="Método",
                    ),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Referencia"
                    ),
                ),
                (
                    "confirmado",
                    models.BooleanField(default=True, verbose_name="Confirmado"),
                ),
                (
                    "aplica_igtf",
                    models.BooleanField(
                        default=False,
                        help_text="Impuesto a Grandes Transacciones Financieras (Divisas)",
                        verbose_name="Aplica IGTF (3%)",
                    ),
                ),
                (
                    "tasa_igtf",
                    models.DecimalField(
                        decimal_places=2,
                        default=3.0,
                        max_digits=5,
                        verbose_name="Tasa IGTF %",
                    ),
                ),
                (
                    "monto_igtf",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Monto IGTF",
                    ),
                ),
                (
                    "notas",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Pago de Venta",
                "verbose_name_plural": "Pagos de Venta",
                "db_table": "core_pagoventa",
                "ordering": ["-fecha_pago"],
            },
        ),
        migrations.CreateModel(
            name="PaqueteAereo",
            fields=[
                (
                    "id_paquete_aereo",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Paquete Aéreo",
                    ),
                ),
                (
                    "nombre_paquete",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nombre Paquete",
                    ),
                ),
                (
                    "incluye_vuelos",
                    models.BooleanField(default=True, verbose_name="Incluye Vuelos"),
                ),
                (
                    "incluye_hotel",
                    models.BooleanField(default=False, verbose_name="Incluye Hotel"),
                ),
                (
                    "noches",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Noches"
                    ),
                ),
                (
                    "pasajeros",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Pasajeros"
                    ),
                ),
                (
                    "resumen_componentes",
                    models.JSONField(
                        blank=True,
                        help_text="Estructura agregada de vuelos/hoteles/otros.",
                        null=True,
                        verbose_name="Resumen Componentes",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "costo_neto_estimado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Costo Neto Estimado",
                    ),
                ),
                (
                    "precio_venta_estimado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Precio Venta Estimado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paquete Aéreo",
                "verbose_name_plural": "Paquetes Aéreos",
                "db_table": "core_paqueteaereo",
                "ordering": ["-id_paquete_aereo"],
            },
        ),
        migrations.CreateModel(
            name="SegmentoVuelo",
            fields=[
                (
                    "id_segmento_vuelo",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Segmento Vuelo",
                    ),
                ),
                (
                    "aerolinea",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="Aerolínea"
                    ),
                ),
                (
                    "numero_vuelo",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Número de Vuelo",
                    ),
                ),
                (
                    "fecha_salida",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha/Hora Salida"
                    ),
                ),
                (
                    "fecha_llegada",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha/Hora Llegada"
                    ),
                ),
                (
                    "clase_reserva",
                    models.CharField(
                        blank=True, max_length=5, null=True, verbose_name="Clase"
                    ),
                ),
                (
                    "cabina",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Economy, Business, First",
                        max_length=20,
                        null=True,
                        verbose_name="Cabina",
                    ),
                ),
                (
                    "notas",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
            ],
            options={
                "verbose_name": "Segmento de Vuelo",
                "verbose_name_plural": "Segmentos de Vuelo",
                "db_table": "core_segmentovuelo",
                "ordering": ["fecha_salida"],
            },
        ),
        migrations.CreateModel(
            name="ServicioAdicionalDetalle",
            fields=[
                (
                    "id_servicio_adicional",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Servicio Adicional",
                    ),
                ),
                (
                    "tipo_servicio",
                    models.CharField(
                        choices=[
                            ("SEG", "Seguro"),
                            ("SIM", "SIM / E-SIM"),
                            ("AST", "Asistencia"),
                            ("LNG", "Lounge"),
                            ("FST", "Fast Track"),
                            ("OTR", "Otro"),
                        ],
                        default="OTR",
                        max_length=3,
                        verbose_name="Tipo Servicio",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "codigo_referencia",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Código Referencia",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Inicio"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(blank=True, null=True, verbose_name="Fecha Fin"),
                ),
                (
                    "nombre_pasajero",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Nombre Pasajero",
                    ),
                ),
                (
                    "pasaporte_pasajero",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Pasaporte Pasajero",
                    ),
                ),
                (
                    "detalles_cobertura",
                    models.TextField(
                        blank=True, null=True, verbose_name="Detalles Cobertura"
                    ),
                ),
                (
                    "contacto_emergencia",
                    models.TextField(
                        blank=True, null=True, verbose_name="Contacto Emergencia"
                    ),
                ),
                (
                    "participantes",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Participantes",
                    ),
                ),
                (
                    "operado_por",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Operado Por",
                    ),
                ),
                (
                    "hora_lugar_encuentro",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Hora y Lugar de Encuentro",
                    ),
                ),
                (
                    "duracion_estimada",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Duración Estimada",
                    ),
                ),
                (
                    "inclusiones_servicio",
                    models.TextField(
                        blank=True, null=True, verbose_name="Inclusiones Servicio"
                    ),
                ),
                (
                    "recomendaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Recomendaciones"
                    ),
                ),
                (
                    "metadata_json",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Metadata Adicional"
                    ),
                ),
                (
                    "notas",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "costo_neto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Costo Neto",
                    ),
                ),
                (
                    "precio_venta",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Precio Venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Servicio Adicional Detalle",
                "verbose_name_plural": "Servicios Adicionales Detalle",
                "db_table": "core_servicioadicionaldetalle",
                "ordering": ["-id_servicio_adicional"],
            },
        ),
        migrations.CreateModel(
            name="SolicitudAnulacion",
            fields=[
                (
                    "id_anulacion",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID Anulación"
                    ),
                ),
                (
                    "tipo_anulacion",
                    models.CharField(
                        choices=[
                            ("VOL", "Voluntaria"),
                            ("INV", "Involuntaria"),
                            ("CAM", "Cambio de Itinerario"),
                            ("OTR", "Otro"),
                        ],
                        default="VOL",
                        max_length=3,
                        verbose_name="Tipo Anulación",
                    ),
                ),
                ("motivo", models.TextField(verbose_name="Motivo")),
                (
                    "monto_original",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto Original"
                    ),
                ),
                (
                    "penalidad_aerolinea",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Penalidad Aerolínea",
                    ),
                ),
                (
                    "fee_agencia",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Fee Agencia",
                    ),
                ),
                (
                    "monto_reembolso",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Monto a Reembolsar",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PEN", "Pendiente"),
                            ("APR", "Aprobada"),
                            ("REC", "Rechazada"),
                            ("PRO", "Procesada"),
                        ],
                        default="PEN",
                        max_length=3,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_solicitud",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Solicitud"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Anulación",
                "verbose_name_plural": "Solicitudes de Anulación",
                "db_table": "core_solicitudanulacion",
                "ordering": ["-fecha_solicitud"],
            },
        ),
        migrations.CreateModel(
            name="TrasladoServicio",
            fields=[
                (
                    "id_traslado_servicio",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID Traslado"
                    ),
                ),
                (
                    "tipo_traslado",
                    models.CharField(
                        choices=[
                            ("ARR", "Arribo / Llegada"),
                            ("DEP", "Salida"),
                            ("INT", "Interno"),
                        ],
                        default="ARR",
                        max_length=3,
                        verbose_name="Tipo Traslado",
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Origen"
                    ),
                ),
                (
                    "destino",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Destino"
                    ),
                ),
                (
                    "fecha_hora",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha/Hora"
                    ),
                ),
                (
                    "pasajeros",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Pasajeros"
                    ),
                ),
                (
                    "notas",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
            ],
            options={
                "verbose_name": "Traslado",
                "verbose_name_plural": "Traslados",
                "db_table": "core_trasladoservicio",
                "ordering": ["fecha_hora"],
            },
        ),
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Eliminado"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Eliminación"
                    ),
                ),
                (
                    "id_venta",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Venta/Reserva",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        null=True,
                        verbose_name="Token Público",
                    ),
                ),
                (
                    "localizador",
                    models.CharField(
                        blank=True,
                        help_text="Código único de la reserva o localizador.",
                        max_length=20,
                        unique=True,
                        verbose_name="Localizador/PNR",
                    ),
                ),
                (
                    "fecha_venta",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Venta/Reserva",
                    ),
                ),
                (
                    "descripcion_general",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Descripción General de la Venta",
                    ),
                ),
                (
                    "tasa_cambio_bcv",
                    models.DecimalField(
                        decimal_places=4,
                        default=1,
                        help_text="Tasa oficial BCV para la fecha de venta.",
                        max_digits=12,
                        verbose_name="Tasa de Cambio (BCV)",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "impuestos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Impuestos",
                    ),
                ),
                (
                    "total_venta",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=12,
                        verbose_name="Total Venta",
                    ),
                ),
                (
                    "monto_pagado",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Monto Pagado",
                    ),
                ),
                (
                    "saldo_pendiente",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=12,
                        verbose_name="Saldo Pendiente",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PEN", "Pendiente de Pago"),
                            ("PAR", "Pagada Parcialmente"),
                            ("PAG", "Pagada Totalmente"),
                            ("CNF", "Confirmada (Servicios OK)"),
                            ("VIA", "En Proceso/Viaje"),
                            ("COM", "Completada"),
                            ("FAL", "Falla de Sistema (Revertida)"),
                            ("CAN", "Cancelada"),
                        ],
                        default="PEN",
                        max_length=3,
                        verbose_name="Estado de la Venta/Reserva",
                    ),
                ),
                (
                    "tipo_venta",
                    models.CharField(
                        choices=[
                            ("B2C", "B2C (Ocio)"),
                            ("B2B", "B2B (Corporativo)"),
                            ("MICE", "MICE / Eventos"),
                            ("PKG", "Paquete"),
                            ("CIR", "Circuito"),
                            ("TLD", "Viaje a Medida"),
                            ("SEG", "Solo Seguro"),
                            ("OTR", "Otro"),
                        ],
                        db_index=True,
                        default="B2C",
                        max_length=4,
                        verbose_name="Tipo de Venta",
                    ),
                ),
                (
                    "canal_origen",
                    models.CharField(
                        choices=[
                            ("ADM", "Admin"),
                            ("IMP", "Importación"),
                            ("API", "API"),
                            ("WEB", "Formulario Web"),
                            ("MIG", "Migración"),
                            ("OTR", "Otro"),
                        ],
                        db_index=True,
                        default="ADM",
                        max_length=3,
                        verbose_name="Canal de Origen",
                    ),
                ),
                (
                    "margen_estimado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Precio venta - costo neto estimado (informativo).",
                        max_digits=12,
                        null=True,
                        verbose_name="Margen Estimado",
                    ),
                ),
                (
                    "co2_estimado_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimación agregada de la huella de carbono.",
                        max_digits=12,
                        null=True,
                        verbose_name="Emisiones CO₂ Estimadas (kg)",
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notas de la Venta"
                    ),
                ),
                (
                    "puntos_fidelidad_asignados",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        help_text="Evita otorgar puntos duplicados cuando la venta pasa a completada/pagada.",
                        verbose_name="Puntos Fidelidad Asignados",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta/Reserva",
                "verbose_name_plural": "Ventas/Reservas",
                "db_table": "core_venta",
                "ordering": ["-fecha_venta"],
            },
        ),
        migrations.CreateModel(
            name="VentaAuditFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CZS", "Venta con Total 0"),
                            ("MSC", "Costos No Registrados"),
                            ("NMG", "Margen Negativo"),
                            ("GED", "Discrepancia GDS vs ERP"),
                            ("OTH", "Otro Hallazgo"),
                        ],
                        max_length=3,
                        verbose_name="Tipo de Hallazgo",
                    ),
                ),
                ("mensaje", models.TextField(verbose_name="Descripción del Hallazgo")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PEN", "Pendiente"),
                            ("REV", "Revisado"),
                            ("IGN", "Ignorado"),
                            ("SOL", "Solucionado"),
                        ],
                        default="PEN",
                        max_length=3,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_deteccion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Detección"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hallazgo de Auditoría",
                "verbose_name_plural": "Hallazgos de Auditoría",
                "db_table": "bookings_ventaauditfinding",
                "ordering": ["-fecha_deteccion"],
            },
        ),
        migrations.CreateModel(
            name="VentaParseMetadata",
            fields=[
                (
                    "id_metadata",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Metadata Parseo",
                    ),
                ),
                (
                    "fuente",
                    models.CharField(
                        blank=True,
                        help_text="Ej: SABRE, KIU, AMADEUS, IMPORT_MANUAL",
                        max_length=50,
                        null=True,
                        verbose_name="Fuente / Origen",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Moneda"
                    ),
                ),
                (
                    "fare_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Monto Fare",
                    ),
                ),
                (
                    "taxes_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Monto Taxes Detectado",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Monto Total",
                    ),
                ),
                (
                    "amount_consistency",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Consistencia Montos",
                    ),
                ),
                (
                    "amount_difference",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Diferencia Total vs Fare+Taxes",
                    ),
                ),
                (
                    "taxes_amount_expected",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Taxes Esperados (Total - Fare)",
                    ),
                ),
                (
                    "taxes_difference",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Diferencia Taxes Detectado vs Esperado",
                    ),
                ),
                (
                    "segments_json",
                    models.JSONField(
                        blank=True,
                        help_text="Lista de segmentos normalizados.",
                        null=True,
                        verbose_name="Segmentos (JSON)",
                    ),
                ),
                (
                    "raw_normalized_json",
                    models.JSONField(
                        blank=True,
                        help_text="Bloque normalized completo para auditoría.",
                        null=True,
                        verbose_name="Objeto Normalized Completo",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Creado"
                    ),
                ),
            ],
            options={
                "verbose_name": "Metadata de Parseo de Venta",
                "verbose_name_plural": "Metadata de Parseo de Ventas",
                "db_table": "core_ventaparsemetadata",
                "ordering": ["-creado"],
            },
        ),
    ]
