# Generated by Django 5.2.6 on 2026-02-09 20:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0071_aerolinea_codigo_numerico_aerolinea_orden_prioridad"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id_audit_log",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID Audit Log"
                    ),
                ),
                (
                    "modelo",
                    models.CharField(
                        db_index=True, max_length=120, verbose_name="Modelo"
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        db_index=True, max_length=120, verbose_name="Object ID"
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("CREATE", "Creación"),
                            ("UPDATE", "Actualización"),
                            ("DELETE", "Eliminación"),
                            ("STATE", "Cambio de Estado"),
                        ],
                        max_length=10,
                        verbose_name="Acción",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descripción / Resumen"
                    ),
                ),
                (
                    "datos_previos",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Datos Previos"
                    ),
                ),
                (
                    "datos_nuevos",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Datos Nuevos"
                    ),
                ),
                (
                    "metadata_extra",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Metadata Extra"
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Creado"
                    ),
                ),
                (
                    "previous_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                (
                    "record_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoría",
                "verbose_name_plural": "Logs de Auditoría",
                "db_table": "core_auditlog",
                "ordering": ["-creado"],
            },
        ),
        migrations.CreateModel(
            name="CircuitoTuristico",
            fields=[
                (
                    "id_circuito",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID Circuito"
                    ),
                ),
                (
                    "nombre_circuito",
                    models.CharField(max_length=255, verbose_name="Nombre Circuito"),
                ),
                (
                    "dias_total",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Días Totales"
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Inicio"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(blank=True, null=True, verbose_name="Fecha Fin"),
                ),
                (
                    "descripcion_general",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descripción General"
                    ),
                ),
                (
                    "incluye",
                    models.TextField(blank=True, null=True, verbose_name="Incluye"),
                ),
                (
                    "no_incluye",
                    models.TextField(blank=True, null=True, verbose_name="No Incluye"),
                ),
                (
                    "costo_neto_estimado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Costo Neto Estimado",
                    ),
                ),
                (
                    "precio_venta_estimado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Precio Venta Estimado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Circuito Turístico",
                "verbose_name_plural": "Circuitos Turísticos",
                "db_table": "core_circuitoturistico",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="PaqueteAereo",
            fields=[
                (
                    "id_paquete_aereo",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Paquete Aéreo",
                    ),
                ),
                (
                    "nombre_paquete",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nombre Paquete",
                    ),
                ),
                (
                    "incluye_vuelos",
                    models.BooleanField(default=True, verbose_name="Incluye Vuelos"),
                ),
                (
                    "incluye_hotel",
                    models.BooleanField(default=False, verbose_name="Incluye Hotel"),
                ),
                (
                    "noches",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Noches"
                    ),
                ),
                (
                    "pasajeros",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Pasajeros"
                    ),
                ),
                (
                    "resumen_componentes",
                    models.JSONField(
                        blank=True,
                        help_text="Estructura agregada de vuelos/hoteles/otros.",
                        null=True,
                        verbose_name="Resumen Componentes",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "costo_neto_estimado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Costo Neto Estimado",
                    ),
                ),
                (
                    "precio_venta_estimado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Precio Venta Estimado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paquete Aéreo",
                "verbose_name_plural": "Paquetes Aéreos",
                "db_table": "core_paqueteaereo",
                "ordering": ["-id_paquete_aereo"],
            },
        ),
        migrations.CreateModel(
            name="VentaParseMetadata",
            fields=[
                (
                    "id_metadata",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Metadata Parseo",
                    ),
                ),
                (
                    "fuente",
                    models.CharField(
                        blank=True,
                        help_text="Ej: SABRE, KIU, AMADEUS, IMPORT_MANUAL",
                        max_length=50,
                        null=True,
                        verbose_name="Fuente / Origen",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Moneda"
                    ),
                ),
                (
                    "fare_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Monto Fare",
                    ),
                ),
                (
                    "taxes_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Monto Taxes Detectado",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Monto Total",
                    ),
                ),
                (
                    "amount_consistency",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Consistencia Montos",
                    ),
                ),
                (
                    "amount_difference",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Diferencia Total vs Fare+Taxes",
                    ),
                ),
                (
                    "taxes_amount_expected",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Taxes Esperados (Total - Fare)",
                    ),
                ),
                (
                    "taxes_difference",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Diferencia Taxes Detectado vs Esperado",
                    ),
                ),
                (
                    "segments_json",
                    models.JSONField(
                        blank=True,
                        help_text="Lista de segmentos normalizados.",
                        null=True,
                        verbose_name="Segmentos (JSON)",
                    ),
                ),
                (
                    "raw_normalized_json",
                    models.JSONField(
                        blank=True,
                        help_text="Bloque normalized completo para auditoría.",
                        null=True,
                        verbose_name="Objeto Normalized Completo",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Creado"
                    ),
                ),
            ],
            options={
                "verbose_name": "Metadata de Parseo de Venta",
                "verbose_name_plural": "Metadata de Parseo de Ventas",
                "db_table": "core_ventaparsemetadata",
                "ordering": ["-creado"],
            },
        ),
        migrations.CreateModel(
            name="ActividadServicio",
            fields=[
                (
                    "id_actividad_servicio",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID Actividad"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=150, verbose_name="Nombre Actividad"),
                ),
                (
                    "fecha",
                    models.DateField(blank=True, null=True, verbose_name="Fecha"),
                ),
                (
                    "duracion_horas",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Duración (horas)",
                    ),
                ),
                (
                    "incluye",
                    models.TextField(blank=True, null=True, verbose_name="Incluye"),
                ),
                (
                    "no_incluye",
                    models.TextField(blank=True, null=True, verbose_name="No Incluye"),
                ),
                (
                    "nombre_pasajero",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nombre Pasajero"
                    ),
                ),
                (
                    "localizador_proveedor",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Localizador Proveedor"
                    ),
                ),
                (
                    "notas",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.proveedor",
                        verbose_name="Proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad / Excursión",
                "verbose_name_plural": "Actividades / Excursiones",
                "db_table": "core_actividadservicio",
                "ordering": ["fecha", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="AlquilerAutoReserva",
            fields=[
                (
                    "id_alquiler_auto",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Alquiler Auto",
                    ),
                ),
                (
                    "fecha_hora_retiro",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha/Hora Retiro"
                    ),
                ),
                (
                    "fecha_hora_devolucion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha/Hora Devolución"
                    ),
                ),
                (
                    "categoria_auto",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Categoría / Clase",
                    ),
                ),
                (
                    "compania_rentadora",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Compañía Rentadora",
                    ),
                ),
                (
                    "numero_confirmacion",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Número Confirmación",
                    ),
                ),
                (
                    "nombre_conductor",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nombre Conductor"
                    ),
                ),
                (
                    "incluye_seguro",
                    models.BooleanField(default=False, verbose_name="Incluye Seguro"),
                ),
                (
                    "notas",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "costo_neto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Costo Neto",
                    ),
                ),
                (
                    "precio_venta",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Precio Venta",
                    ),
                ),
                (
                    "ciudad_devolucion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings_autos_devolucion",
                        to="core.ciudad",
                        verbose_name="Ciudad Devolución",
                    ),
                ),
                (
                    "ciudad_retiro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings_autos_retiro",
                        to="core.ciudad",
                        verbose_name="Ciudad Retiro",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.proveedor",
                        verbose_name="Proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alquiler de Auto",
                "verbose_name_plural": "Alquileres de Autos",
                "db_table": "core_alquilerautoreserva",
                "ordering": ["fecha_hora_retiro"],
            },
        ),
        migrations.CreateModel(
            name="CircuitoDia",
            fields=[
                (
                    "id_circuito_dia",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Circuito Día",
                    ),
                ),
                ("dia_numero", models.PositiveSmallIntegerField(verbose_name="Día #")),
                (
                    "titulo",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Título del Día",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "alojamiento_previsto",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Alojamiento Previsto",
                    ),
                ),
                (
                    "actividades_resumen",
                    models.TextField(
                        blank=True, null=True, verbose_name="Actividades/Resumen"
                    ),
                ),
                (
                    "ciudad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.ciudad",
                        verbose_name="Ciudad",
                    ),
                ),
                (
                    "circuito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dias",
                        to="bookings.circuitoturistico",
                        verbose_name="Circuito",
                    ),
                ),
            ],
            options={
                "verbose_name": "Día de Circuito",
                "verbose_name_plural": "Días de Circuito",
                "db_table": "core_circuitodia",
                "ordering": ["circuito", "dia_numero"],
            },
        ),
        migrations.CreateModel(
            name="EventoServicio",
            fields=[
                (
                    "id_evento_servicio",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Evento/Servicio",
                    ),
                ),
                (
                    "nombre_evento",
                    models.CharField(max_length=255, verbose_name="Nombre Evento"),
                ),
                (
                    "fecha_evento",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Evento"
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Ubicación"
                    ),
                ),
                (
                    "zona_asiento",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Zona/Asiento",
                    ),
                ),
                (
                    "codigo_boleto_evento",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Código Boleto / Ref",
                    ),
                ),
                (
                    "notas",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "costo_neto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Costo Neto",
                    ),
                ),
                (
                    "precio_venta",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Precio Venta",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.proveedor",
                        verbose_name="Proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento / Servicio",
                "verbose_name_plural": "Eventos / Servicios",
                "db_table": "core_eventoservicio",
                "ordering": ["fecha_evento"],
            },
        ),
        migrations.CreateModel(
            name="FeeVenta",
            fields=[
                (
                    "id_fee_venta",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID Fee"
                    ),
                ),
                (
                    "tipo_fee",
                    models.CharField(
                        choices=[
                            ("EMI", "Emisión"),
                            ("CAM", "Cambio / Exchange"),
                            ("GST", "Gestión"),
                            ("URG", "Urgente"),
                            ("OTR", "Otro"),
                        ],
                        default="GST",
                        max_length=3,
                        verbose_name="Tipo Fee",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto"
                    ),
                ),
                (
                    "es_comision_agencia",
                    models.BooleanField(
                        default=True, verbose_name="Es Comisión Agencia"
                    ),
                ),
                (
                    "taxable",
                    models.BooleanField(
                        default=False, verbose_name="Sujeto a Impuestos"
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "moneda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.moneda",
                        verbose_name="Moneda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fee de Venta",
                "verbose_name_plural": "Fees de Venta",
                "db_table": "core_feeventa",
                "ordering": ["-creado"],
            },
        ),
        migrations.CreateModel(
            name="ItemVenta",
            fields=[
                (
                    "id_item_venta",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID Item Venta"
                    ),
                ),
                (
                    "descripcion_personalizada",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Descripción Personalizada",
                    ),
                ),
                (
                    "cantidad",
                    models.PositiveIntegerField(default=1, verbose_name="Cantidad"),
                ),
                (
                    "precio_unitario_venta",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Precio Unitario de Venta",
                    ),
                ),
                (
                    "costo_unitario_referencial",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Costo Unitario Referencial",
                    ),
                ),
                (
                    "impuestos_item_venta",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Impuestos por Item",
                    ),
                ),
                (
                    "subtotal_item_venta",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=12,
                        verbose_name="Subtotal Item",
                    ),
                ),
                (
                    "total_item_venta",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=12,
                        verbose_name="Total Item",
                    ),
                ),
                (
                    "fecha_inicio_servicio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Inicio Servicio"
                    ),
                ),
                (
                    "fecha_fin_servicio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Fin Servicio"
                    ),
                ),
                (
                    "codigo_reserva_proveedor",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Código Reserva Proveedor (PNR, Localizador)",
                    ),
                ),
                (
                    "costo_neto_proveedor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Costo Neto Proveedor",
                    ),
                ),
                (
                    "fee_proveedor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Fee Emisión Proveedor",
                    ),
                ),
                (
                    "comision_agencia_monto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Comisión Agencia (Monto)",
                    ),
                ),
                (
                    "fee_agencia_interno",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Fee Interno Agencia",
                    ),
                ),
                (
                    "estado_item",
                    models.CharField(
                        choices=[
                            ("PCO", "Pendiente Confirmación Proveedor"),
                            ("CNF", "Confirmado por Proveedor"),
                            ("CAP", "Cancelado por Proveedor"),
                            ("CAC", "Cancelado por Cliente"),
                            ("UTI", "Utilizado/Completado"),
                        ],
                        default="PCO",
                        max_length=3,
                        verbose_name="Estado del Item/Servicio",
                    ),
                ),
                (
                    "notas_item",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notas del Item"
                    ),
                ),
                (
                    "producto_servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.productoservicio",
                        verbose_name="Producto/Servicio",
                    ),
                ),
                (
                    "proveedor_servicio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.proveedor",
                        verbose_name="Proveedor del Servicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Venta/Reserva",
                "verbose_name_plural": "Items de Venta/Reserva",
                "db_table": "core_itemventa",
            },
        ),
        migrations.CreateModel(
            name="AlojamientoReserva",
            fields=[
                (
                    "id_alojamiento_reserva",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID Alojamiento"
                    ),
                ),
                (
                    "nombre_establecimiento",
                    models.CharField(
                        max_length=150, verbose_name="Nombre Establecimiento"
                    ),
                ),
                (
                    "check_in",
                    models.DateField(blank=True, null=True, verbose_name="Check In"),
                ),
                (
                    "check_out",
                    models.DateField(blank=True, null=True, verbose_name="Check Out"),
                ),
                (
                    "regimen_alimentacion",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Desayuno, Media Pensión, Todo Incluido",
                        max_length=30,
                        null=True,
                        verbose_name="Régimen Alimentación",
                    ),
                ),
                (
                    "habitaciones",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Habitaciones"
                    ),
                ),
                (
                    "nombre_pasajero",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nombre Pasajero"
                    ),
                ),
                (
                    "localizador_proveedor",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Localizador Proveedor"
                    ),
                ),
                (
                    "notas",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "ciudad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.ciudad",
                        verbose_name="Ciudad",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.proveedor",
                        verbose_name="Proveedor",
                    ),
                ),
                (
                    "item_venta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alojamientos_reserva",
                        to="bookings.itemventa",
                        verbose_name="Item de Venta Asociado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alojamiento (Reserva)",
                "verbose_name_plural": "Alojamientos (Reservas)",
                "db_table": "core_alojamientoreserva",
                "ordering": ["check_in"],
            },
        ),
        migrations.CreateModel(
            name="PagoVenta",
            fields=[
                (
                    "id_pago_venta",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID Pago"
                    ),
                ),
                (
                    "fecha_pago",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha Pago"
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto"
                    ),
                ),
                (
                    "metodo",
                    models.CharField(
                        choices=[
                            ("EFE", "Efectivo"),
                            ("TAR", "Tarjeta"),
                            ("TRF", "Transferencia"),
                            ("ZEL", "Zelle"),
                            ("PPL", "PayPal"),
                            ("OTR", "Otro"),
                        ],
                        default="TRF",
                        max_length=3,
                        verbose_name="Método",
                    ),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Referencia"
                    ),
                ),
                (
                    "confirmado",
                    models.BooleanField(default=True, verbose_name="Confirmado"),
                ),
                (
                    "aplica_igtf",
                    models.BooleanField(
                        default=False,
                        help_text="Impuesto a Grandes Transacciones Financieras (Divisas)",
                        verbose_name="Aplica IGTF (3%)",
                    ),
                ),
                (
                    "tasa_igtf",
                    models.DecimalField(
                        decimal_places=2,
                        default=3.0,
                        max_digits=5,
                        verbose_name="Tasa IGTF %",
                    ),
                ),
                (
                    "monto_igtf",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Monto IGTF",
                    ),
                ),
                (
                    "notas",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "moneda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.moneda",
                        verbose_name="Moneda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago de Venta",
                "verbose_name_plural": "Pagos de Venta",
                "db_table": "core_pagoventa",
                "ordering": ["-fecha_pago"],
            },
        ),
        migrations.CreateModel(
            name="SegmentoVuelo",
            fields=[
                (
                    "id_segmento_vuelo",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Segmento Vuelo",
                    ),
                ),
                (
                    "aerolinea",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="Aerolínea"
                    ),
                ),
                (
                    "numero_vuelo",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Número de Vuelo",
                    ),
                ),
                (
                    "fecha_salida",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha/Hora Salida"
                    ),
                ),
                (
                    "fecha_llegada",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha/Hora Llegada"
                    ),
                ),
                (
                    "clase_reserva",
                    models.CharField(
                        blank=True, max_length=5, null=True, verbose_name="Clase"
                    ),
                ),
                (
                    "cabina",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Economy, Business, First",
                        max_length=20,
                        null=True,
                        verbose_name="Cabina",
                    ),
                ),
                (
                    "notas",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings_segmentos_llegada",
                        to="core.ciudad",
                        verbose_name="Ciudad Destino",
                    ),
                ),
                (
                    "origen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings_segmentos_salida",
                        to="core.ciudad",
                        verbose_name="Ciudad Origen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Segmento de Vuelo",
                "verbose_name_plural": "Segmentos de Vuelo",
                "db_table": "core_segmentovuelo",
                "ordering": ["fecha_salida"],
            },
        ),
        migrations.CreateModel(
            name="ServicioAdicionalDetalle",
            fields=[
                (
                    "id_servicio_adicional",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Servicio Adicional",
                    ),
                ),
                (
                    "tipo_servicio",
                    models.CharField(
                        choices=[
                            ("SEG", "Seguro"),
                            ("SIM", "SIM / E-SIM"),
                            ("AST", "Asistencia"),
                            ("LNG", "Lounge"),
                            ("FST", "Fast Track"),
                            ("OTR", "Otro"),
                        ],
                        default="OTR",
                        max_length=3,
                        verbose_name="Tipo Servicio",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "codigo_referencia",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Código Referencia",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Inicio"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(blank=True, null=True, verbose_name="Fecha Fin"),
                ),
                (
                    "nombre_pasajero",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Nombre Pasajero",
                    ),
                ),
                (
                    "pasaporte_pasajero",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Pasaporte Pasajero",
                    ),
                ),
                (
                    "detalles_cobertura",
                    models.TextField(
                        blank=True, null=True, verbose_name="Detalles Cobertura"
                    ),
                ),
                (
                    "contacto_emergencia",
                    models.TextField(
                        blank=True, null=True, verbose_name="Contacto Emergencia"
                    ),
                ),
                (
                    "participantes",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Participantes",
                    ),
                ),
                (
                    "operado_por",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Operado Por",
                    ),
                ),
                (
                    "hora_lugar_encuentro",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Hora y Lugar de Encuentro",
                    ),
                ),
                (
                    "duracion_estimada",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Duración Estimada",
                    ),
                ),
                (
                    "inclusiones_servicio",
                    models.TextField(
                        blank=True, null=True, verbose_name="Inclusiones Servicio"
                    ),
                ),
                (
                    "recomendaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Recomendaciones"
                    ),
                ),
                (
                    "metadata_json",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Metadata Adicional"
                    ),
                ),
                (
                    "notas",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "costo_neto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Costo Neto",
                    ),
                ),
                (
                    "precio_venta",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Precio Venta",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.proveedor",
                        verbose_name="Proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Servicio Adicional Detalle",
                "verbose_name_plural": "Servicios Adicionales Detalle",
                "db_table": "core_servicioadicionaldetalle",
                "ordering": ["-id_servicio_adicional"],
            },
        ),
        migrations.CreateModel(
            name="TrasladoServicio",
            fields=[
                (
                    "id_traslado_servicio",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID Traslado"
                    ),
                ),
                (
                    "tipo_traslado",
                    models.CharField(
                        choices=[
                            ("ARR", "Arribo / Llegada"),
                            ("DEP", "Salida"),
                            ("INT", "Interno"),
                        ],
                        default="ARR",
                        max_length=3,
                        verbose_name="Tipo Traslado",
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Origen"
                    ),
                ),
                (
                    "destino",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Destino"
                    ),
                ),
                (
                    "fecha_hora",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha/Hora"
                    ),
                ),
                (
                    "pasajeros",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Pasajeros"
                    ),
                ),
                (
                    "notas",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.proveedor",
                        verbose_name="Proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Traslado",
                "verbose_name_plural": "Traslados",
                "db_table": "core_trasladoservicio",
                "ordering": ["fecha_hora"],
            },
        ),
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id_venta",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Venta/Reserva",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        null=True,
                        verbose_name="Token Público",
                    ),
                ),
                (
                    "localizador",
                    models.CharField(
                        blank=True,
                        help_text="Código único de la reserva o localizador.",
                        max_length=20,
                        unique=True,
                        verbose_name="Localizador/PNR",
                    ),
                ),
                (
                    "fecha_venta",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Venta/Reserva",
                    ),
                ),
                (
                    "descripcion_general",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Descripción General de la Venta",
                    ),
                ),
                (
                    "tasa_cambio_bcv",
                    models.DecimalField(
                        decimal_places=4,
                        default=1,
                        help_text="Tasa oficial BCV para la fecha de venta.",
                        max_digits=12,
                        verbose_name="Tasa de Cambio (BCV)",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "impuestos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Impuestos",
                    ),
                ),
                (
                    "total_venta",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=12,
                        verbose_name="Total Venta",
                    ),
                ),
                (
                    "monto_pagado",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Monto Pagado",
                    ),
                ),
                (
                    "saldo_pendiente",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=12,
                        verbose_name="Saldo Pendiente",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PEN", "Pendiente de Pago"),
                            ("PAR", "Pagada Parcialmente"),
                            ("PAG", "Pagada Totalmente"),
                            ("CNF", "Confirmada (Servicios OK)"),
                            ("VIA", "En Proceso/Viaje"),
                            ("COM", "Completada"),
                            ("CAN", "Cancelada"),
                        ],
                        default="PEN",
                        max_length=3,
                        verbose_name="Estado de la Venta/Reserva",
                    ),
                ),
                (
                    "tipo_venta",
                    models.CharField(
                        choices=[
                            ("B2C", "B2C (Ocio)"),
                            ("B2B", "B2B (Corporativo)"),
                            ("MICE", "MICE / Eventos"),
                            ("PKG", "Paquete"),
                            ("CIR", "Circuito"),
                            ("TLD", "Viaje a Medida"),
                            ("SEG", "Solo Seguro"),
                            ("OTR", "Otro"),
                        ],
                        db_index=True,
                        default="B2C",
                        max_length=4,
                        verbose_name="Tipo de Venta",
                    ),
                ),
                (
                    "canal_origen",
                    models.CharField(
                        choices=[
                            ("ADM", "Admin"),
                            ("IMP", "Importación"),
                            ("API", "API"),
                            ("WEB", "Formulario Web"),
                            ("MIG", "Migración"),
                            ("OTR", "Otro"),
                        ],
                        db_index=True,
                        default="ADM",
                        max_length=3,
                        verbose_name="Canal de Origen",
                    ),
                ),
                (
                    "margen_estimado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Precio venta - costo neto estimado (informativo).",
                        max_digits=12,
                        null=True,
                        verbose_name="Margen Estimado",
                    ),
                ),
                (
                    "co2_estimado_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimación agregada de la huella de carbono.",
                        max_digits=12,
                        null=True,
                        verbose_name="Emisiones CO₂ Estimadas (kg)",
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notas de la Venta"
                    ),
                ),
                (
                    "puntos_fidelidad_asignados",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        help_text="Evita otorgar puntos duplicados cuando la venta pasa a completada/pagada.",
                        verbose_name="Puntos Fidelidad Asignados",
                    ),
                ),
                (
                    "agencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.agencia",
                        verbose_name="Agencia",
                    ),
                ),
                (
                    "asiento_contable_venta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings_ventas_asociadas",
                        to="core.asientocontable",
                        verbose_name="Asiento Contable de Venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta / Reserva",
                "verbose_name_plural": "Ventas / Reservas",
                "db_table": "core_venta",
                "ordering": ["-fecha_venta"],
            },
        ),
    ]
