# Generated by Django 5.2.6 on 2026-02-14 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_initial"),
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venta",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ventas_asociadas",
                to="crm.cliente",
                verbose_name="Cliente (Pagador)",
            ),
        ),
    ]
