# Generated by Django 5.2.6 on 2026-04-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookings",
            "0003_actividadservicio_agencia_alojamientoreserva_agencia_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="contador_vistas_cliente",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Contador de Vistas"
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="ultima_vista_cliente",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Última Vista Cliente"
            ),
        ),
    ]
