# Generated by Django 5.2.6 on 2026-02-16 14:35

import core.storage
import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_alter_venta_cliente"),
        ("core", "0073_alter_facturaconsolidada_cliente_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BoletoImportado",
            fields=[
                (
                    "id_boleto_importado",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Boleto Importado",
                    ),
                ),
                (
                    "archivo_boleto",
                    models.FileField(
                        blank=True,
                        help_text="Suba el archivo del boleto en formato PDF, TXT o EML (máx 5MB).",
                        max_length=255,
                        null=True,
                        storage=core.storage.RawFileStorage,
                        upload_to="boletos_importados/%Y/%m/",
                        validators=[
                            core.validators.validate_file_size,
                            core.validators.validate_file_extension,
                            core.validators.antivirus_hook,
                        ],
                        verbose_name="Archivo del Boleto (.pdf, .txt, .eml)",
                    ),
                ),
                (
                    "fecha_subida",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Subida"
                    ),
                ),
                (
                    "formato_detectado",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PDF_KIU", "PDF (KIU)"),
                            ("PDF_SAB", "PDF (Sabre)"),
                            ("PDF_AMA", "PDF (Amadeus)"),
                            ("TXT_KIU", "TXT (KIU)"),
                            ("TXT_SAB", "TXT (Sabre)"),
                            ("TXT_AMA", "TXT (Amadeus)"),
                            ("EML_KIU", "EML (KIU)"),
                            ("EML_GEN", "EML (General)"),
                            ("OTR", "Otro/Desconocido"),
                            ("ERR", "Error de Formato"),
                        ],
                        default="OTR",
                        max_length=20,
                        verbose_name="Formato Detectado",
                    ),
                ),
                (
                    "datos_parseados",
                    models.JSONField(
                        blank=True,
                        help_text="Información extraída del boleto en formato JSON.",
                        null=True,
                        verbose_name="Datos Parseados",
                    ),
                ),
                (
                    "estado_parseo",
                    models.CharField(
                        choices=[
                            ("PEN", "Pendiente de Parseo"),
                            ("PRO", "En Proceso"),
                            ("COM", "Parseo Completado"),
                            ("REV", "Revisión Requerida"),
                            ("ERR", "Error en Parseo"),
                            ("NAP", "No Aplica Parseo"),
                        ],
                        default="PEN",
                        max_length=3,
                        verbose_name="Estado del Parseo",
                    ),
                ),
                (
                    "log_parseo",
                    models.TextField(
                        blank=True, null=True, verbose_name="Log del Parseo"
                    ),
                ),
                (
                    "numero_boleto",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Número de Boleto",
                    ),
                ),
                (
                    "nombre_pasajero_completo",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Nombre Completo Pasajero (Original)",
                    ),
                ),
                (
                    "nombre_pasajero_procesado",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Nombre Pasajero (Procesado)",
                    ),
                ),
                (
                    "ruta_vuelo",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Ruta del Vuelo (Itinerario)",
                    ),
                ),
                (
                    "fecha_emision_boleto",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de Emisión del Boleto",
                    ),
                ),
                (
                    "aerolinea_emisora",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Aerolínea Emisora",
                    ),
                ),
                (
                    "direccion_aerolinea",
                    models.TextField(
                        blank=True, null=True, verbose_name="Dirección Aerolínea"
                    ),
                ),
                (
                    "agente_emisor",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Agente Emisor",
                    ),
                ),
                (
                    "foid_pasajero",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="FOID/D.Identidad Pasajero",
                    ),
                ),
                (
                    "localizador_pnr",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Localizador (PNR)",
                    ),
                ),
                (
                    "tarifa_base",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Tarifa Base",
                    ),
                ),
                (
                    "impuestos_descripcion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descripción Impuestos"
                    ),
                ),
                (
                    "impuestos_total_calculado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Total Impuestos (Calculado)",
                    ),
                ),
                (
                    "total_boleto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Total del Boleto",
                    ),
                ),
                (
                    "exchange_monto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monto de exchange o diferencial de cambio asociado al boleto.",
                        max_digits=10,
                        null=True,
                        verbose_name="Exchange",
                    ),
                ),
                (
                    "void_monto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monto asociado a VOID (penalidad / reembolso negativo).",
                        max_digits=10,
                        null=True,
                        verbose_name="Void / Penalidad",
                    ),
                ),
                (
                    "comision_agencia",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Comisión propia de la agencia respecto al boleto.",
                        max_digits=10,
                        null=True,
                        verbose_name="Comisión Agencia",
                    ),
                ),
                (
                    "iva_monto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Monto IVA",
                    ),
                ),
                (
                    "inatur_monto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Monto Inatur (1%)",
                    ),
                ),
                (
                    "otros_impuestos_monto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Otros Impuestos",
                    ),
                ),
                (
                    "fee_servicio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fee cobrado por la agencia por gestión del boleto.",
                        max_digits=10,
                        null=True,
                        verbose_name="Fee de Servicio",
                    ),
                ),
                (
                    "igtf_monto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Impuesto a las Grandes Transacciones Financieras u otras retenciones locales.",
                        max_digits=10,
                        null=True,
                        verbose_name="IGTF",
                    ),
                ),
                (
                    "archivo_pdf_generado",
                    models.FileField(
                        blank=True,
                        help_text="El archivo PDF del boleto unificado, generado automáticamente.",
                        max_length=255,
                        null=True,
                        storage=core.storage.RawFileStorage,
                        upload_to="boletos_generados/%Y/%m/",
                        verbose_name="PDF Unificado Generado",
                    ),
                ),
                (
                    "telegram_file_id",
                    models.CharField(
                        blank=True,
                        help_text="ID del archivo en la nube de Telegram (para almacenamiento gratuito).",
                        max_length=255,
                        null=True,
                        verbose_name="Telegram File ID",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Versión del boleto (1=Original, 2+=Re-emisión)",
                        verbose_name="Versión",
                    ),
                ),
                (
                    "estado_emision",
                    models.CharField(
                        choices=[
                            ("ORI", "Original"),
                            ("REE", "Re-emisión"),
                            ("ANU", "Anulado / Void"),
                            ("REM", "Reembolso"),
                        ],
                        default="ORI",
                        max_length=3,
                        verbose_name="Estado de Emisión",
                    ),
                ),
                (
                    "agencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.agencia",
                        verbose_name="Agencia",
                    ),
                ),
                (
                    "boleto_padre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versiones_posteriores",
                        to="bookings.boletoimportado",
                        verbose_name="Boleto Padre (Versión Anterior)",
                    ),
                ),
                (
                    "proveedor_emisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.proveedor",
                        verbose_name="Proveedor Emisor (Consolidador/Aerolínea)",
                    ),
                ),
                (
                    "venta_asociada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="boletos_adjuntos",
                        to="bookings.venta",
                        verbose_name="Venta/Reserva Asociada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Boleto Importado",
                "verbose_name_plural": "Boletos Importados",
                "db_table": "core_boletoimportado",
                "ordering": ["-fecha_subida"],
            },
        ),
        migrations.CreateModel(
            name="SolicitudAnulacion",
            fields=[
                (
                    "id_anulacion",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID Anulación"
                    ),
                ),
                (
                    "tipo_anulacion",
                    models.CharField(
                        choices=[
                            ("VOL", "Voluntaria"),
                            ("INV", "Involuntaria"),
                            ("CAM", "Cambio de Itinerario"),
                            ("OTR", "Otro"),
                        ],
                        default="VOL",
                        max_length=3,
                        verbose_name="Tipo Anulación",
                    ),
                ),
                ("motivo", models.TextField(verbose_name="Motivo")),
                (
                    "monto_original",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto Original"
                    ),
                ),
                (
                    "penalidad_aerolinea",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Penalidad Aerolínea",
                    ),
                ),
                (
                    "fee_agencia",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Fee Agencia",
                    ),
                ),
                (
                    "monto_reembolso",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Monto a Reembolsar",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PEN", "Pendiente"),
                            ("APR", "Aprobada"),
                            ("REC", "Rechazada"),
                            ("PRO", "Procesada"),
                        ],
                        default="PEN",
                        max_length=3,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_solicitud",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Solicitud"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Actualización"
                    ),
                ),
                (
                    "boleto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes_anulacion",
                        to="bookings.boletoimportado",
                        verbose_name="Boleto",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Solicitado Por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Anulación",
                "verbose_name_plural": "Solicitudes de Anulación",
                "db_table": "core_solicitudanulacion",
                "ordering": ["-fecha_solicitud"],
            },
        ),
    ]
