# Generated by Django 5.2.6 on 2026-02-17 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_boletoimportado_solicitudanulacion"),
        ("contabilidad", "0002_add_dualidad_monetaria_ven_nif"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs_creados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="asiento_contable_venta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings_ventas_asociadas",
                to="contabilidad.asientocontable",
                verbose_name="Asiento Contable de Venta",
            ),
        ),
    ]
