# Generated by Django 6.0.4 on 2026-04-28 22:29

"""Migración de base de datos para bookings.
"""

from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("bookings", "0004_venta_contador_vistas_cliente_and_more"),
        ("core", "0003_asientocontable_moneda_ciudad_pais_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="boletoimportado",
            index=models.Index(
                fields=["agencia", "localizador_pnr", "fecha_subida"],
                name="core_boleto_agencia_eea8c0_idx",
            ),
        ),
    ]
