# Generated by Django 5.2.6 on 2026-02-19 20:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_auditlog_user_alter_venta_asiento_contable_venta"),
        ("contabilidad", "0002_add_dualidad_monetaria_ven_nif"),
        ("core", "0076_facturaconsolidada_agencia"),
        ("cotizaciones", "0004_cotizacion_condiciones_comerciales_and_more"),
        ("crm", "0004_cliente_agencia_pasajero_agencia"),
        ("finance", "0005_factura_agencia_reporteproveedor_agencia_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="venta",
            index=models.Index(
                fields=["agencia", "fecha_venta"], name="core_venta_agencia_08a6ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="venta",
            index=models.Index(
                fields=["agencia", "estado"], name="core_venta_agencia_32fb12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="venta",
            index=models.Index(
                fields=["localizador"], name="core_venta_localiz_9d9d61_idx"
            ),
        ),
    ]
