# Generated by Django 5.2.6 on 2026-05-02 23:20

"""Migración de base de datos para bookings.
"""

from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("bookings", "0006_alter_venta_localizador"),
    ]

    operations = [
        migrations.AddField(
            model_name="actividadservicio",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fecha de Eliminación"),
        ),
        migrations.AddField(
            model_name="actividadservicio",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Eliminado"),
        ),
        migrations.AddField(
            model_name="alojamientoreserva",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fecha de Eliminación"),
        ),
        migrations.AddField(
            model_name="alojamientoreserva",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Eliminado"),
        ),
        migrations.AddField(
            model_name="alquilerautoreserva",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fecha de Eliminación"),
        ),
        migrations.AddField(
            model_name="alquilerautoreserva",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Eliminado"),
        ),
        migrations.AddField(
            model_name="eventoservicio",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fecha de Eliminación"),
        ),
        migrations.AddField(
            model_name="eventoservicio",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Eliminado"),
        ),
        migrations.AddField(
            model_name="feeventa",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fecha de Eliminación"),
        ),
        migrations.AddField(
            model_name="feeventa",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Eliminado"),
        ),
        migrations.AddField(
            model_name="segmentovuelo",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fecha de Eliminación"),
        ),
        migrations.AddField(
            model_name="segmentovuelo",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Eliminado"),
        ),
        migrations.AddField(
            model_name="trasladoservicio",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fecha de Eliminación"),
        ),
        migrations.AddField(
            model_name="trasladoservicio",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Eliminado"),
        ),
    ]
