# Generated by Django 5.2.6 on 2026-05-04 00:17

"""Migración de base de datos para bookings.
"""

from decimal import Decimal

from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("bookings", "0007_actividadservicio_deleted_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, unique=True, verbose_name="Nombre"),
                ),
                (
                    "icono_lucide",
                    models.CharField(
                        default="check",
                        help_text="Nombre del icono de Lucide React",
                        max_length=50,
                        verbose_name="Icono Lucide",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComisionOverrideAerolinea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comision_porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Comisión Especial %",
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas Internas")),
            ],
            options={
                "verbose_name": "Comisión Especial por Aerolínea",
                "verbose_name_plural": "Comisiones Especiales (Overrides)",
            },
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="CruceroReserva",
                    fields=[
                        (
                            "id_crucero",
                            models.AutoField(
                                primary_key=True, serialize=False, verbose_name="ID Crucero"
                            ),
                        ),
                        (
                            "nombre_crucero",
                            models.CharField(max_length=200, verbose_name="Nombre del Crucero"),
                        ),
                        (
                            "naviera",
                            models.CharField(max_length=150, verbose_name="Naviera/Compañía"),
                        ),
                        (
                            "nombre_barco",
                            models.CharField(
                                blank=True, max_length=150, verbose_name="Nombre del Barco"
                            ),
                        ),
                        ("fecha_embarque", models.DateField(verbose_name="Fecha de Embarque")),
                        (
                            "fecha_desembarque",
                            models.DateField(verbose_name="Fecha de Desembarque"),
                        ),
                        ("noches", models.PositiveSmallIntegerField(verbose_name="Noches")),
                        (
                            "puerto_embarque",
                            models.CharField(max_length=150, verbose_name="Puerto de Embarque"),
                        ),
                        (
                            "puerto_desembarque",
                            models.CharField(max_length=150, verbose_name="Puerto de Desembarque"),
                        ),
                        (
                            "puertos_escala",
                            models.JSONField(
                                blank=True, null=True, verbose_name="Puertos de Escala"
                            ),
                        ),
                        (
                            "dias_navegacion",
                            models.PositiveSmallIntegerField(
                                default=0, verbose_name="Días de Navegación"
                            ),
                        ),
                        (
                            "tipo_cabina",
                            models.CharField(
                                choices=[
                                    ("INT", "Interior (sin ventana)"),
                                    ("VEN", "Vista al Mar (con ventana)"),
                                    ("BAL", "Balcón Privado"),
                                    ("SUI", "Suite"),
                                    ("SUP", "Suite Premium"),
                                ],
                                default="BAL",
                                max_length=3,
                                verbose_name="Tipo de Cabina",
                            ),
                        ),
                        (
                            "numero_cabina",
                            models.CharField(
                                blank=True, max_length=20, verbose_name="Número de Cabina"
                            ),
                        ),
                        (
                            "ubicacion_cabina",
                            models.CharField(
                                blank=True, max_length=100, verbose_name="Ubicación en el Barco"
                            ),
                        ),
                        (
                            "clase_cabina",
                            models.CharField(
                                blank=True, max_length=50, verbose_name="Clase de Cabina"
                            ),
                        ),
                        (
                            "numero_pasajeros",
                            models.PositiveSmallIntegerField(
                                default=2, verbose_name="Número de Pasajeros"
                            ),
                        ),
                        (
                            "nombres_pasajeros",
                            models.TextField(verbose_name="Nombres de Pasajeros"),
                        ),
                        (
                            "paquete_bebidas",
                            models.BooleanField(default=False, verbose_name="Paquete de Bebidas"),
                        ),
                        (
                            "paquete_restaurantes",
                            models.BooleanField(
                                default=False, verbose_name="Paquete Restaurantes Especialidad"
                            ),
                        ),
                        (
                            "paquete_spa",
                            models.BooleanField(
                                default=False, verbose_name="Paquete Spa y Bienestar"
                            ),
                        ),
                        (
                            "paquete_wifi",
                            models.BooleanField(default=False, verbose_name="Paquete Wi-Fi"),
                        ),
                        (
                            "excursiones_tierra",
                            models.JSONField(
                                blank=True, null=True, verbose_name="Excursiones en Tierra"
                            ),
                        ),
                        (
                            "pension_completa",
                            models.BooleanField(
                                default=True, verbose_name="Pensión Completa Incluida"
                            ),
                        ),
                        (
                            "servicios_incluidos",
                            models.TextField(blank=True, verbose_name="Servicios Incluidos"),
                        ),
                        (
                            "servicios_no_incluidos",
                            models.TextField(blank=True, verbose_name="Servicios NO Incluidos"),
                        ),
                        (
                            "localizador_proveedor",
                            models.CharField(
                                blank=True, max_length=100, verbose_name="Localizador Proveedor"
                            ),
                        ),
                        (
                            "tarifa_base_cabina",
                            models.DecimalField(
                                blank=True,
                                decimal_places=2,
                                max_digits=12,
                                null=True,
                                verbose_name="Tarifa Base Cabina",
                            ),
                        ),
                        (
                            "es_comisionable",
                            models.BooleanField(default=True, verbose_name="Es Comisionable"),
                        ),
                        (
                            "porcentaje_comision",
                            models.DecimalField(
                                blank=True,
                                decimal_places=2,
                                max_digits=5,
                                null=True,
                                verbose_name="% Comisión",
                            ),
                        ),
                        (
                            "monto_comision",
                            models.DecimalField(
                                blank=True,
                                decimal_places=2,
                                editable=False,
                                max_digits=12,
                                null=True,
                                verbose_name="Monto Comisión",
                            ),
                        ),
                        (
                            "fee_servicio_agencia",
                            models.DecimalField(
                                blank=True,
                                decimal_places=2,
                                max_digits=12,
                                null=True,
                                verbose_name="Fee Servicio Agencia",
                            ),
                        ),
                        (
                            "costo_total_proveedor",
                            models.DecimalField(
                                blank=True,
                                decimal_places=2,
                                max_digits=12,
                                null=True,
                                verbose_name="Costo Total Proveedor",
                            ),
                        ),
                        (
                            "precio_venta_cliente",
                            models.DecimalField(
                                blank=True,
                                decimal_places=2,
                                max_digits=12,
                                null=True,
                                verbose_name="Precio Venta Cliente",
                            ),
                        ),
                        (
                            "observaciones",
                            models.TextField(blank=True, verbose_name="Observaciones"),
                        ),
                        (
                            "recomendaciones_cliente",
                            models.TextField(blank=True, verbose_name="Recomendaciones al Cliente"),
                        ),
                    ],
                    options={
                        "verbose_name": "Crucero",
                        "verbose_name_plural": "Cruceros",
                        "db_table": "core_cruceroreserva",
                        "ordering": ["fecha_embarque"],
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.CreateModel(
            name="HotelTarifario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Nombre del Hotel"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, help_text="URL amigable", max_length=250, null=True
                    ),
                ),
                ("destino", models.CharField(max_length=100, verbose_name="Destino")),
                (
                    "direccion",
                    models.TextField(blank=True, verbose_name="Dirección Completa"),
                ),
                (
                    "coordenadas_mapa",
                    models.CharField(
                        blank=True,
                        help_text="Lat,Long para Google Maps",
                        max_length=100,
                    ),
                ),
                (
                    "descripcion_corta",
                    models.TextField(
                        blank=True,
                        help_text="Para listados",
                        verbose_name="Descripción Corta",
                    ),
                ),
                (
                    "descripcion_larga",
                    models.TextField(blank=True, verbose_name="Descripción Completa (IA)"),
                ),
                (
                    "imagen_principal",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="hoteles/portadas/",
                        verbose_name="Imagen Portada",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="hoteles/logos/",
                        verbose_name="Logo del Hotel",
                    ),
                ),
                (
                    "video_promocional",
                    models.FileField(
                        blank=True,
                        help_text="Video corto para la ficha del hotel",
                        null=True,
                        upload_to="hoteles/videos/",
                        verbose_name="Video Promocional",
                    ),
                ),
                (
                    "categoria",
                    models.IntegerField(
                        choices=[
                            (1, "Eco / Posada"),
                            (2, "Estandar"),
                            (3, "Confort"),
                            (4, "Lujo"),
                            (5, "Gran Lujo / Premium"),
                        ],
                        default=3,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "regimen_default",
                    models.CharField(
                        choices=[
                            ("SO", "Solo Alojamiento"),
                            ("SD", "Solo Desayuno"),
                            ("MP", "Media Pensión"),
                            ("PC", "Pensión Completa"),
                            ("TI", "Todo Incluido"),
                        ],
                        default="SD",
                        max_length=2,
                        verbose_name="Régimen Principal",
                    ),
                ),
                (
                    "comision",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        max_digits=5,
                        verbose_name="Comisión %",
                    ),
                ),
                ("politicas", models.TextField(blank=True, verbose_name="Políticas")),
                (
                    "check_in",
                    models.TimeField(default="15:00", verbose_name="Check-in"),
                ),
                (
                    "check_out",
                    models.TimeField(default="12:00", verbose_name="Check-out"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "destacado",
                    models.BooleanField(default=False, verbose_name="Destacado (Home)"),
                ),
            ],
            options={
                "verbose_name": "Hotel",
                "verbose_name_plural": "Hoteles",
                "ordering": ["destino", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="ImagenHotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagen", models.ImageField(upload_to="hoteles/galeria/")),
                ("titulo", models.CharField(blank=True, max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General"),
                            ("HABITACION", "Habitación"),
                            ("COMIDA", "Restaurante/Comida"),
                            ("PLAYA", "Playa/Piscina"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                ("es_portada", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ProductoTerrestre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_servicio",
                    models.CharField(
                        choices=[
                            ("HOTEL", "Hotel / Alojamiento"),
                            ("TOUR", "Tour / Excursión"),
                            ("TRANS", "Traslado"),
                            ("PACK", "Paquete Dinámico"),
                            ("INS", "Seguro de Viaje"),
                        ],
                        default="HOTEL",
                        max_length=10,
                        verbose_name="Tipo de Servicio",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=255, verbose_name="Nombre Comercial"),
                ),
                (
                    "destino",
                    models.CharField(
                        help_text="Ej. Madrid, España",
                        max_length=255,
                        verbose_name="Destino / Ubicación",
                    ),
                ),
                (
                    "descripcion_publica",
                    models.TextField(
                        blank=True,
                        help_text="Lo que verá el cliente en la cotización",
                        null=True,
                        verbose_name="Descripción (Pública)",
                    ),
                ),
                (
                    "costo_neto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Costo Neto (Proveedor)",
                    ),
                ),
                (
                    "markup_porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20.00"),
                        max_digits=5,
                        verbose_name="Markup (Ganancia %)",
                    ),
                ),
                (
                    "precio_venta_calculado",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=12,
                        verbose_name="Precio Venta",
                    ),
                ),
                (
                    "imagen_principal",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="productos_terrestres/%Y/%m/",
                        verbose_name="Foto Principal",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Producto Terrestre",
                "verbose_name_plural": "Productos Terrestres",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="TarifaHabitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha Inicio")),
                ("fecha_fin", models.DateField(verbose_name="Fecha Fin")),
                (
                    "nombre_temporada",
                    models.CharField(blank=True, max_length=100, verbose_name="Temporada"),
                ),
                (
                    "moneda",
                    models.CharField(
                        choices=[("USD", "$ Dólares"), ("EUR", "€ Euros")],
                        default="USD",
                        max_length=3,
                        verbose_name="Moneda",
                    ),
                ),
                (
                    "tipo_tarifa",
                    models.CharField(
                        choices=[
                            ("POR_PERSONA", "Por Persona por Noche"),
                            ("POR_HABITACION", "Por Habitación por Noche"),
                        ],
                        default="POR_PERSONA",
                        max_length=20,
                        verbose_name="Tipo de Tarifa",
                    ),
                ),
                (
                    "tarifa_sgl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="SGL (Simple)",
                    ),
                ),
                (
                    "tarifa_dbl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="DBL (Doble)",
                    ),
                ),
                (
                    "tarifa_tpl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="TPL (Triple)",
                    ),
                ),
                (
                    "tarifa_cpl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="CPL (Cuadruple)",
                    ),
                ),
                (
                    "tarifa_nino",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Tarifa Niño",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarifa de Habitación",
                "verbose_name_plural": "Tarifas de Habitaciones",
                "ordering": ["tipo_habitacion", "fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="TarifarioProveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "archivo_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="tarifarios/%Y/%m/",
                        verbose_name="Archivo PDF",
                    ),
                ),
                (
                    "fecha_vigencia_inicio",
                    models.DateField(verbose_name="Vigencia Inicio"),
                ),
                ("fecha_vigencia_fin", models.DateField(verbose_name="Vigencia Fin")),
                (
                    "comision_estandar",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("15.00"),
                        max_digits=5,
                        verbose_name="Comisión Estándar %",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "fecha_carga",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de Carga"),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
            ],
            options={
                "verbose_name": "Tarifario de Proveedor",
                "verbose_name_plural": "Tarifarios de Proveedores",
                "ordering": ["-fecha_carga"],
            },
        ),
        migrations.CreateModel(
            name="TipoHabitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Tipo de Habitación"),
                ),
                (
                    "capacidad_adultos",
                    models.IntegerField(default=2, verbose_name="Max Adultos"),
                ),
                (
                    "capacidad_ninos",
                    models.IntegerField(default=1, verbose_name="Max Niños"),
                ),
                (
                    "capacidad_total",
                    models.IntegerField(default=3, verbose_name="Max Total"),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "foto_referencial",
                    models.ImageField(blank=True, null=True, upload_to="hoteles/habitaciones/"),
                ),
            ],
            options={
                "verbose_name": "Tipo de Habitación",
                "verbose_name_plural": "Tipos de Habitación",
                "ordering": ["hotel", "nombre"],
            },
        ),
        migrations.AlterModelOptions(
            name="servicioadicionaldetalle",
            options={
                "verbose_name": "Servicio Adicional Detalle",
                "verbose_name_plural": "Servicios Adicionales Detalle",
            },
        ),
        migrations.RemoveIndex(
            model_name="servicioadicionaldetalle",
            name="core_servic_tipo_se_1f3d42_idx",
        ),
        migrations.RemoveField(
            model_name="servicioadicionaldetalle",
            name="contacto_emergencia",
        ),
        migrations.RemoveField(
            model_name="servicioadicionaldetalle",
            name="detalles_cobertura",
        ),
        migrations.RemoveField(
            model_name="servicioadicionaldetalle",
            name="duracion_estimada",
        ),
        migrations.RemoveField(
            model_name="servicioadicionaldetalle",
            name="hora_lugar_encuentro",
        ),
        migrations.RemoveField(
            model_name="servicioadicionaldetalle",
            name="inclusiones_servicio",
        ),
        migrations.RemoveField(
            model_name="servicioadicionaldetalle",
            name="metadata_json",
        ),
        migrations.RemoveField(
            model_name="servicioadicionaldetalle",
            name="operado_por",
        ),
        migrations.RemoveField(
            model_name="servicioadicionaldetalle",
            name="participantes",
        ),
        migrations.RemoveField(
            model_name="servicioadicionaldetalle",
            name="pasaporte_pasajero",
        ),
        migrations.RemoveField(
            model_name="servicioadicionaldetalle",
            name="recomendaciones",
        ),
        migrations.AlterField(
            model_name="pagoventa",
            name="aplica_igtf",
            field=models.BooleanField(default=False, verbose_name="Aplica IGTF (3%)"),
        ),
    ]
