# Generated by Django 5.2.6 on 2026-05-04 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0008_amenity_comisionoverrideaerolinea_cruceroreserva_and_more"),
        ("core", "0008_remove_hoteltarifario_amenidades_and_more"),
        ("finance", "0003_alter_factura_asiento_contable_factura_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venta",
            name="factura_consolidada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings_ventas_facturadas",
                to="finance.facturaconsolidada",
                verbose_name="Factura Consolidada",
            ),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="comisionoverrideaerolinea",
                    name="aerolinea",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.aerolinea",
                        verbose_name="Aerolínea",
                    ),
                ),
                migrations.AddField(
                    model_name="cruceroreserva",
                    name="moneda",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.moneda",
                        verbose_name="Moneda",
                    ),
                ),
                migrations.AddField(
                    model_name="cruceroreserva",
                    name="proveedor",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.proveedor",
                        verbose_name="Proveedor/Consolidador",
                    ),
                ),
                migrations.AddField(
                    model_name="cruceroreserva",
                    name="venta",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cruceros",
                        to="bookings.venta",
                        verbose_name="Venta",
                    ),
                ),
                migrations.AddField(
                    model_name="hoteltarifario",
                    name="agencia",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="core.agencia",
                    ),
                ),
                migrations.AddField(
                    model_name="hoteltarifario",
                    name="amenidades",
                    field=models.ManyToManyField(
                        blank=True, related_name="hoteles", to="bookings.amenity"
                    ),
                ),
                migrations.AddField(
                    model_name="imagenhotel",
                    name="hotel",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes",
                        to="bookings.hoteltarifario",
                    ),
                ),
                migrations.AddField(
                    model_name="productoterrestre",
                    name="agencia",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos_terrestres",
                        to="core.agencia",
                    ),
                ),
                migrations.AddField(
                    model_name="tarifarioproveedor",
                    name="agencia",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="core.agencia",
                    ),
                ),
                migrations.AddField(
                    model_name="tarifarioproveedor",
                    name="proveedor",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifarios",
                        to="core.proveedor",
                    ),
                ),
                migrations.AddField(
                    model_name="hoteltarifario",
                    name="tarifario",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hoteles",
                        to="bookings.tarifarioproveedor",
                    ),
                ),
                migrations.AddField(
                    model_name="comisionoverrideaerolinea",
                    name="tarifario",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides_aerolinea",
                        to="bookings.tarifarioproveedor",
                    ),
                ),
                migrations.AddField(
                    model_name="tipohabitacion",
                    name="hotel",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tipos_habitacion",
                        to="bookings.hoteltarifario",
                    ),
                ),
                migrations.AddField(
                    model_name="tarifahabitacion",
                    name="tipo_habitacion",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifas",
                        to="bookings.tipohabitacion",
                    ),
                ),
                migrations.AlterUniqueTogether(
                    name="hoteltarifario",
                    unique_together={("agencia", "slug")},
                ),
                migrations.AlterUniqueTogether(
                    name="comisionoverrideaerolinea",
                    unique_together={("tarifario", "aerolinea")},
                ),
                migrations.AlterUniqueTogether(
                    name="tipohabitacion",
                    unique_together={("hotel", "nombre")},
                ),
            ],
            database_operations=[],
        ),
    ]
