# Generated by Django 5.2.6 on 2026-05-04 13:42

"""Migración de base de datos para bookings.
"""

import django.db.models.deletion
from django.db import migrations, models

import core.validators


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("bookings", "0009_alter_venta_factura_consolidada_and_more"),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="ComisionProveedorServicio",
                    fields=[
                        (
                            "is_deleted",
                            models.BooleanField(
                                db_index=True, default=False, verbose_name="Eliminado"
                            ),
                        ),
                        (
                            "deleted_at",
                            models.DateTimeField(
                                blank=True, null=True, verbose_name="Fecha de Eliminación"
                            ),
                        ),
                        (
                            "id_comision",
                            models.AutoField(
                                primary_key=True, serialize=False, verbose_name="ID Comisión"
                            ),
                        ),
                        (
                            "tipo_servicio",
                            models.CharField(
                                choices=[
                                    ("AIR", "Boleto Aéreo"),
                                    ("HTL", "Alojamiento (Hotel)"),
                                    ("PKG", "Paquete Turístico"),
                                    ("TOU", "Tour o Actividad"),
                                    ("TRF", "Traslado"),
                                    ("INS", "Seguro de Viaje"),
                                    ("CRU", "Crucero"),
                                    ("CAR", "Alquiler de Auto"),
                                    ("SVC", "Servicio Adicional"),
                                    ("OTR", "Otro"),
                                ],
                                max_length=3,
                                verbose_name="Tipo de Servicio",
                            ),
                        ),
                        (
                            "comision_porcentaje",
                            models.DecimalField(
                                blank=True,
                                decimal_places=2,
                                max_digits=5,
                                null=True,
                                verbose_name="Comisión (%)",
                            ),
                        ),
                        (
                            "comision_monto_fijo",
                            models.DecimalField(
                                blank=True,
                                decimal_places=2,
                                max_digits=10,
                                null=True,
                                verbose_name="Comisión Monto Fijo",
                            ),
                        ),
                        ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                    ],
                    options={
                        "verbose_name": "Comisión de Proveedor por Servicio",
                        "verbose_name_plural": "Comisiones de Proveedores por Servicios",
                        "db_table": "core_comisionproveedorservicio",
                    },
                ),
                migrations.CreateModel(
                    name="ProductoServicio",
                    fields=[
                        (
                            "is_deleted",
                            models.BooleanField(
                                db_index=True, default=False, verbose_name="Eliminado"
                            ),
                        ),
                        (
                            "deleted_at",
                            models.DateTimeField(
                                blank=True, null=True, verbose_name="Fecha de Eliminación"
                            ),
                        ),
                        (
                            "id_producto_servicio",
                            models.AutoField(
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID Producto/Servicio",
                            ),
                        ),
                        (
                            "codigo_interno",
                            models.CharField(
                                blank=True,
                                max_length=50,
                                null=True,
                                unique=True,
                                verbose_name="Código Interno",
                            ),
                        ),
                        (
                            "nombre",
                            models.CharField(
                                max_length=255,
                                validators=[core.validators.validar_no_vacio_o_espacios],
                                verbose_name="Nombre del Producto/Servicio",
                            ),
                        ),
                        (
                            "descripcion",
                            models.TextField(blank=True, null=True, verbose_name="Descripción"),
                        ),
                        (
                            "tipo_producto",
                            models.CharField(
                                choices=[
                                    ("AIR", "Boleto Aéreo"),
                                    ("HTL", "Alojamiento (Hotel)"),
                                    ("PKG", "Paquete Turístico"),
                                    ("TOU", "Tour o Actividad"),
                                    ("TRF", "Traslado"),
                                    ("INS", "Seguro de Viaje"),
                                    ("CRU", "Crucero"),
                                    ("CAR", "Alquiler de Auto"),
                                    ("SVC", "Servicio Adicional"),
                                    ("OTR", "Otro"),
                                ],
                                default="OTR",
                                max_length=3,
                                verbose_name="Tipo de Producto/Servicio",
                            ),
                        ),
                        (
                            "costo_estandar_referencial",
                            models.DecimalField(
                                blank=True,
                                decimal_places=2,
                                max_digits=12,
                                null=True,
                                verbose_name="Costo Estándar Referencial",
                            ),
                        ),
                        (
                            "precio_venta_sugerido",
                            models.DecimalField(
                                blank=True,
                                decimal_places=2,
                                max_digits=12,
                                null=True,
                                verbose_name="Precio de Venta Sugerido",
                            ),
                        ),
                        ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                    ],
                    options={
                        "verbose_name": "Producto o Servicio",
                        "verbose_name_plural": "Productos y Servicios",
                        "db_table": "core_productoservicio",
                        "ordering": ["nombre"],
                    },
                ),
                migrations.CreateModel(
                    name="Proveedor",
                    fields=[
                        (
                            "is_deleted",
                            models.BooleanField(
                                db_index=True, default=False, verbose_name="Eliminado"
                            ),
                        ),
                        (
                            "deleted_at",
                            models.DateTimeField(
                                blank=True, null=True, verbose_name="Fecha de Eliminación"
                            ),
                        ),
                        (
                            "id_proveedor",
                            models.AutoField(
                                primary_key=True, serialize=False, verbose_name="ID Proveedor"
                            ),
                        ),
                        (
                            "nombre",
                            models.CharField(
                                max_length=150,
                                unique=True,
                                validators=[core.validators.validar_no_vacio_o_espacios],
                                verbose_name="Nombre del Proveedor",
                            ),
                        ),
                        (
                            "alias",
                            models.CharField(
                                blank=True,
                                help_text="Nombre con el que es conocido en el mercado",
                                max_length=150,
                                null=True,
                                verbose_name="Alias/Nombre Comercial",
                            ),
                        ),
                        (
                            "rif",
                            models.CharField(
                                blank=True,
                                help_text="Registro de Información Fiscal",
                                max_length=20,
                                null=True,
                                verbose_name="RIF",
                            ),
                        ),
                        (
                            "tipo_proveedor",
                            models.CharField(
                                choices=[
                                    ("AER", "Aerolínea"),
                                    ("HTL", "Hotel"),
                                    ("OPT", "Operador Turístico"),
                                    ("CON", "Consolidador"),
                                    ("MAY", "Mayorista"),
                                    ("SEG", "Seguros"),
                                    ("TRN", "Transporte Terrestre"),
                                    ("GDS", "Sistema de Distribución Global (GDS)"),
                                    ("OTR", "Otro"),
                                ],
                                default="OTR",
                                max_length=3,
                                verbose_name="Tipo de Proveedor",
                            ),
                        ),
                        (
                            "nivel_proveedor",
                            models.CharField(
                                choices=[
                                    ("DIR", "Directo"),
                                    ("CON", "Consolidador"),
                                    ("MAY", "Mayorista"),
                                    ("TER", "Otro (Tercero)"),
                                ],
                                default="DIR",
                                help_text="Nivel de intermediación del proveedor.",
                                max_length=3,
                                verbose_name="Nivel del Proveedor",
                            ),
                        ),
                        (
                            "contacto_nombre",
                            models.CharField(
                                blank=True,
                                max_length=100,
                                null=True,
                                verbose_name="Nombre de Contacto",
                            ),
                        ),
                        (
                            "contacto_email",
                            models.EmailField(
                                blank=True,
                                max_length=255,
                                null=True,
                                verbose_name="Email de Contacto",
                            ),
                        ),
                        (
                            "contacto_telefono",
                            models.CharField(
                                blank=True,
                                max_length=30,
                                null=True,
                                verbose_name="Teléfono de Contacto",
                            ),
                        ),
                        (
                            "direccion",
                            models.CharField(
                                blank=True, max_length=255, null=True, verbose_name="Dirección"
                            ),
                        ),
                        (
                            "notas",
                            models.TextField(
                                blank=True, null=True, verbose_name="Notas sobre el Proveedor"
                            ),
                        ),
                        (
                            "numero_cuenta_agencia",
                            models.CharField(
                                blank=True,
                                max_length=50,
                                null=True,
                                verbose_name="Número de Cuenta/IATA con el Proveedor",
                            ),
                        ),
                        (
                            "condiciones_pago",
                            models.CharField(
                                blank=True,
                                max_length=100,
                                null=True,
                                verbose_name="Condiciones de Pago",
                            ),
                        ),
                        (
                            "datos_bancarios",
                            models.TextField(
                                blank=True,
                                null=True,
                                verbose_name="Datos Bancarios del Proveedor",
                            ),
                        ),
                        (
                            "fee_nacional",
                            models.DecimalField(
                                blank=True,
                                decimal_places=2,
                                help_text="Fee por servicios nacionales",
                                max_digits=10,
                                null=True,
                                verbose_name="Fee Nacional",
                            ),
                        ),
                        (
                            "fee_internacional",
                            models.DecimalField(
                                blank=True,
                                decimal_places=2,
                                help_text="Fee por servicios internacionales",
                                max_digits=10,
                                null=True,
                                verbose_name="Fee Internacional",
                            ),
                        ),
                        ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                        (
                            "identificadores_gds",
                            models.JSONField(
                                blank=True,
                                default=dict,
                                null=True,
                                verbose_name="Identificadores GDS (IATA/OfficeID)",
                            ),
                        ),
                        (
                            "iata",
                            models.CharField(
                                blank=True, max_length=10, null=True, verbose_name="IATA"
                            ),
                        ),
                        (
                            "seudo_sabre",
                            models.CharField(
                                blank=True, max_length=4, null=True, verbose_name="Seudo SABRE"
                            ),
                        ),
                        (
                            "office_id_kiu",
                            models.CharField(
                                blank=True,
                                max_length=8,
                                null=True,
                                verbose_name="Office ID KIU",
                            ),
                        ),
                        (
                            "office_id_amadeus",
                            models.CharField(
                                blank=True,
                                max_length=10,
                                null=True,
                                verbose_name="Office ID AMADEUS",
                            ),
                        ),
                        (
                            "office_id_travelport",
                            models.CharField(
                                blank=True,
                                max_length=10,
                                null=True,
                                verbose_name="Office ID TRAVELPORT",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Proveedor",
                        "verbose_name_plural": "Proveedores",
                        "db_table": "core_proveedor",
                        "ordering": ["nombre"],
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name="actividadservicio",
            name="item_venta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actividades_reserva",
                to="bookings.itemventa",
                verbose_name="Item de Venta Asociado",
            ),
        ),
        migrations.AddField(
            model_name="alquilerautoreserva",
            name="item_venta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alquileres_reserva",
                to="bookings.itemventa",
                verbose_name="Item de Venta Asociado",
            ),
        ),
        migrations.AddField(
            model_name="circuitoturistico",
            name="item_venta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="circuitos_reserva",
                to="bookings.itemventa",
                verbose_name="Item de Venta Asociado",
            ),
        ),
        migrations.AddField(
            model_name="cruceroreserva",
            name="item_venta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cruceros_reserva",
                to="bookings.itemventa",
                verbose_name="Item de Venta Asociado",
            ),
        ),
        migrations.AddField(
            model_name="eventoservicio",
            name="item_venta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventos_reserva",
                to="bookings.itemventa",
                verbose_name="Item de Venta Asociado",
            ),
        ),
        migrations.AddField(
            model_name="itemventa",
            name="detalles_json",
            field=models.JSONField(
                blank=True,
                help_text="Metadatos adicionales del producto (Hotel, Auto, etc.)",
                null=True,
                verbose_name="Detalles Específicos (JSON)",
            ),
        ),
        migrations.AddField(
            model_name="itemventa",
            name="tipo_item",
            field=models.CharField(
                choices=[
                    ("AIR", "Boleto Aéreo"),
                    ("HTL", "Alojamiento (Hotel)"),
                    ("PKG", "Paquete Turístico"),
                    ("TOU", "Tour o Actividad"),
                    ("TRF", "Traslado"),
                    ("INS", "Seguro de Viaje"),
                    ("CRU", "Crucero"),
                    ("CAR", "Alquiler de Auto"),
                    ("SVC", "Servicio Adicional"),
                    ("OTR", "Otro"),
                ],
                default="OTR",
                max_length=3,
                verbose_name="Tipo de Item",
            ),
        ),
        migrations.AddField(
            model_name="paqueteaereo",
            name="item_venta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paquetes_reserva",
                to="bookings.itemventa",
                verbose_name="Item de Venta Asociado",
            ),
        ),
        migrations.AddField(
            model_name="segmentovuelo",
            name="item_venta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="segmentos_reserva",
                to="bookings.itemventa",
                verbose_name="Item de Venta Asociado",
            ),
        ),
        migrations.AddField(
            model_name="servicioadicionaldetalle",
            name="item_venta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles_adicionales",
                to="bookings.itemventa",
                verbose_name="Item de Venta Asociado",
            ),
        ),
        migrations.AddField(
            model_name="trasladoservicio",
            name="item_venta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="traslados_reserva",
                to="bookings.itemventa",
                verbose_name="Item de Venta Asociado",
            ),
        ),
        migrations.AlterField(
            model_name="alojamientoreserva",
            name="ciudad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="common.ciudad",
                verbose_name="Ciudad",
            ),
        ),
        migrations.AlterField(
            model_name="alquilerautoreserva",
            name="ciudad_devolucion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings_autos_devolucion",
                to="common.ciudad",
                verbose_name="Ciudad Devolución",
            ),
        ),
        migrations.AlterField(
            model_name="alquilerautoreserva",
            name="ciudad_retiro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings_autos_retiro",
                to="common.ciudad",
                verbose_name="Ciudad Retiro",
            ),
        ),
        migrations.AlterField(
            model_name="circuitodia",
            name="ciudad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.ciudad",
                verbose_name="Ciudad",
            ),
        ),
        migrations.AlterField(
            model_name="comisionoverrideaerolinea",
            name="aerolinea",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="common.aerolinea",
                verbose_name="Aerolínea",
            ),
        ),
    ]
