# Generated by Django 5.2.6 on 2026-05-04 14:14

"""Migración de base de datos para bookings.
"""

from django.db import migrations


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("bookings", "0011_alter_cruceroreserva_moneda_alter_feeventa_moneda_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelTable(
                    name="productoterrestre",
                    table="core_productoterrestre",
                ),
            ],
            database_operations=[],
        ),
    ]
