# Generated by Django 5.2.6 on 2026-05-04 14:18

"""Migración de base de datos para bookings.
"""

from django.db import migrations


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("bookings", "0012_alter_productoterrestre_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={
                "verbose_name": "Servicio/Amenidad",
                "verbose_name_plural": "Servicios/Amenidades",
            },
        ),
        migrations.AlterModelOptions(
            name="imagenhotel",
            options={
                "verbose_name": "Imagen de Hotel",
                "verbose_name_plural": "Imágenes de Hoteles",
            },
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelTable(
                    name="amenity",
                    table="core_amenity",
                ),
                migrations.AlterModelTable(
                    name="comisionoverrideaerolinea",
                    table="core_comisionoverrideaerolinea",
                ),
                migrations.AlterModelTable(
                    name="hoteltarifario",
                    table="core_hoteltarifario",
                ),
                migrations.AlterModelTable(
                    name="imagenhotel",
                    table="core_imagenhotel",
                ),
                migrations.AlterModelTable(
                    name="tarifahabitacion",
                    table="core_tarifahabitacion",
                ),
                migrations.AlterModelTable(
                    name="tarifarioproveedor",
                    table="core_tarifarioproveedor",
                ),
                migrations.AlterModelTable(
                    name="tipohabitacion",
                    table="core_tipohabitacion",
                ),
            ],
            database_operations=[],
        ),
    ]
