# Generated by Django 5.2.6 on 2026-05-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0013_alter_amenity_options_alter_imagenhotel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proveedor",
            name="office_id_expedia",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Office ID EXPEDIA"
            ),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="office_id_hotelbeds",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Office ID HOTEL BEDS",
            ),
        ),
    ]
