# Generated by Django 5.2.6 on 2026-05-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0014_proveedor_office_id_expedia_and_more"),
        ("core", "0015_agencia_configuracion_contable"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="boletoimportado",
            index=models.Index(
                fields=["agencia", "fecha_emision_boleto"],
                name="core_boleto_agencia_b730c5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="boletoimportado",
            index=models.Index(
                fields=["agencia", "aerolinea_emisora"],
                name="core_boleto_agencia_1c7a57_idx",
            ),
        ),
    ]
