# Generated by Django 5.2.6 on 2026-05-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0015_boletoimportado_core_boleto_agencia_b730c5_idx_and_more"),
        ("core", "0015_agencia_configuracion_contable"),
        ("finance", "0004_moneda_alter_reporteproveedor_proveedor_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="boletoimportado",
            index=models.Index(fields=["estado_parseo"], name="idx_boleto_estado_parseo"),
        ),
        migrations.AddIndex(
            model_name="boletoimportado",
            index=models.Index(
                fields=["venta_asociada", "estado_emision"],
                name="idx_boleto_venta_estado",
            ),
        ),
        migrations.AddIndex(
            model_name="pagoventa",
            index=models.Index(fields=["agencia", "venta"], name="idx_pago_agencia_venta"),
        ),
        migrations.AddIndex(
            model_name="pagoventa",
            index=models.Index(fields=["agencia", "fecha_pago"], name="idx_pago_agencia_fecha"),
        ),
        migrations.AddIndex(
            model_name="pagoventa",
            index=models.Index(fields=["metodo"], name="idx_pago_metodo"),
        ),
    ]
