# Generated by Django 5.2.6 on 2026-05-10 00:12

"""Migración de base de datos para bookings.
"""

import django.contrib.postgres.indexes
from django.db import migrations


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("bookings", "0017_circuitodia_agencia_cruceroreserva_agencia_and_more"),
        ("core", "0022_remove_agencia_bi_insights_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="boletoimportado",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["datos_parseados"], name="idx_boleto_json_gin"
            ),
        ),
    ]
