# Generated by Django 5.2.6 on 2026-05-10 19:41
# Edited 2026-06-06: removed AlterModelTable(table=None) operations so
# the state keeps db_table='core_xxx' for the renamed models.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "bookings",
            "0019_rename_core_alquil_fecha_h_9424c1_idx_bookings_al_fecha_h_2d2f55_idx_and_more",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[],
            database_operations=[],
        ),
    ]
