# Generated by Django 5.2.6 on 2026-05-10 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookings",
            "0019_rename_core_alquil_fecha_h_9424c1_idx_bookings_al_fecha_h_2d2f55_idx_and_more",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelTable(
                    name="amenity",
                    table=None,
                ),
                migrations.AlterModelTable(
                    name="comisionoverrideaerolinea",
                    table=None,
                ),
                migrations.AlterModelTable(
                    name="feeventa",
                    table=None,
                ),
                migrations.AlterModelTable(
                    name="hoteltarifario",
                    table=None,
                ),
                migrations.AlterModelTable(
                    name="imagenhotel",
                    table=None,
                ),
                migrations.AlterModelTable(
                    name="pagoventa",
                    table=None,
                ),
                migrations.AlterModelTable(
                    name="tarifahabitacion",
                    table=None,
                ),
                migrations.AlterModelTable(
                    name="tarifarioproveedor",
                    table=None,
                ),
                migrations.AlterModelTable(
                    name="tipohabitacion",
                    table=None,
                ),
            ],
            database_operations=[],
        ),
    ]
