# Generated by Django 5.2.6 on 2026-05-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0020_alter_amenity_table_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="boletoimportado",
            new_name="bookings_bo_agencia_1abd71_idx",
            old_name="core_boleto_agencia_5b10f1_idx",
        ),
        migrations.RenameIndex(
            model_name="boletoimportado",
            new_name="bookings_bo_agencia_80f1fb_idx",
            old_name="core_boleto_agencia_5ac087_idx",
        ),
        migrations.RenameIndex(
            model_name="boletoimportado",
            new_name="bookings_bo_agencia_4aebbe_idx",
            old_name="core_boleto_agencia_f24a5d_idx",
        ),
        migrations.RenameIndex(
            model_name="venta",
            new_name="bookings_ve_agencia_f375ba_idx",
            old_name="core_venta_agencia_3252dc_idx",
        ),
        migrations.AddField(
            model_name="boletoimportado",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de Actualización"
            ),
        ),
    ]
