# Generated by Django 5.2.6 on 2026-05-14 18:48

"""Migración de base de datos para bookings.
"""

from django.conf import settings
from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("bookings", "0022_add_updated_at_boletoimportado"),
        ("common", "0002_alter_aerolinea_table_alter_ciudad_table_and_more"),
        (
            "contabilidad",
            "0005_asientocontable_agencia_detalleasiento_agencia_and_more",
        ),
        ("core", "0027_seed_feature_flags"),
        ("cotizaciones", "0004_alter_cotizacion_table_alter_itemcotizacion_table"),
        ("crm", "0013_alter_cliente_table_alter_mensajewhatsapp_table_and_more"),
        (
            "finance",
            "0006_rename_core_factur_numero__4980ce_idx_finance_fac_numero__8f5d18_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="boletoimportado",
            name="bookings_bo_agencia_1abd71_idx",
        ),
        migrations.RemoveIndex(
            model_name="boletoimportado",
            name="bookings_bo_agencia_80f1fb_idx",
        ),
        migrations.RemoveIndex(
            model_name="boletoimportado",
            name="bookings_bo_agencia_4aebbe_idx",
        ),
        migrations.RemoveIndex(
            model_name="boletoimportado",
            name="bookings_bo_agencia_920b0f_idx",
        ),
        migrations.RemoveIndex(
            model_name="boletoimportado",
            name="bookings_bo_agencia_908484_idx",
        ),
        migrations.RemoveIndex(
            model_name="boletoimportado",
            name="bookings_bo_agencia_5c0e82_idx",
        ),
        migrations.RemoveIndex(
            model_name="venta",
            name="bookings_ve_agencia_897c27_idx",
        ),
        migrations.RemoveIndex(
            model_name="venta",
            name="bookings_ve_agencia_f375ba_idx",
        ),
        migrations.RemoveIndex(
            model_name="venta",
            name="bookings_ve_agencia_1b4e31_idx",
        ),
        migrations.AlterField(
            model_name="actividadservicio",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="alojamientoreserva",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="alquilerautoreserva",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="boletoimportado",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="comisionproveedorservicio",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="eventoservicio",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="feeventa",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="itemventa",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="productoservicio",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="productoterrestre",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="segmentovuelo",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="trasladoservicio",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="venta",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="actividadservicio",
            index=models.Index(
                fields=["is_deleted", "agencia_id"],
                name="idx_actividad_soft_delete_saas",
            ),
        ),
        migrations.AddIndex(
            model_name="alojamientoreserva",
            index=models.Index(
                fields=["is_deleted", "agencia_id"], name="idx_alojam_soft_delete_saas"
            ),
        ),
        migrations.AddIndex(
            model_name="alquilerautoreserva",
            index=models.Index(
                fields=["is_deleted", "agencia_id"], name="idx_auto_soft_delete_saas"
            ),
        ),
        migrations.AddIndex(
            model_name="boletoimportado",
            index=models.Index(
                fields=["agencia_id", "numero_boleto"],
                name="bookings_bo_agencia_1abd71_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="boletoimportado",
            index=models.Index(
                fields=["agencia_id", "localizador_pnr"],
                name="bookings_bo_agencia_80f1fb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="boletoimportado",
            index=models.Index(
                fields=["agencia_id", "fecha_subida"],
                name="bookings_bo_agencia_4aebbe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="boletoimportado",
            index=models.Index(
                fields=["agencia_id", "fecha_emision_boleto"],
                name="bookings_bo_agencia_908484_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="boletoimportado",
            index=models.Index(
                fields=["agencia_id", "aerolinea_emisora"],
                name="bookings_bo_agencia_5c0e82_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="boletoimportado",
            index=models.Index(
                fields=["agencia_id", "localizador_pnr", "fecha_subida"],
                name="bookings_bo_agencia_920b0f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="boletoimportado",
            index=models.Index(
                fields=["is_deleted", "agencia_id"], name="idx_boleto_soft_delete_saas"
            ),
        ),
        migrations.AddIndex(
            model_name="eventoservicio",
            index=models.Index(
                fields=["is_deleted", "agencia_id"], name="idx_evento_soft_delete_saas"
            ),
        ),
        migrations.AddIndex(
            model_name="itemventa",
            index=models.Index(
                fields=["is_deleted", "agencia_id"],
                name="idx_itemventa_soft_delete_saas",
            ),
        ),
        migrations.AddIndex(
            model_name="segmentovuelo",
            index=models.Index(
                fields=["is_deleted", "agencia_id"],
                name="idx_segmento_soft_delete_saas",
            ),
        ),
        migrations.AddIndex(
            model_name="trasladoservicio",
            index=models.Index(
                fields=["is_deleted", "agencia_id"],
                name="idx_traslado_soft_delete_saas",
            ),
        ),
        migrations.AddIndex(
            model_name="venta",
            index=models.Index(
                fields=["agencia_id", "fecha_venta"],
                name="bookings_ve_agencia_897c27_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="venta",
            index=models.Index(
                fields=["agencia_id", "localizador"],
                name="bookings_ve_agencia_f375ba_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="venta",
            index=models.Index(
                fields=["agencia_id", "estado"], name="bookings_ve_agencia_1b4e31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="venta",
            index=models.Index(
                fields=["is_deleted", "agencia_id"], name="idx_venta_soft_delete_saas"
            ),
        ),
    ]
