# Generated by Django 5.2.6 on 2026-05-16 16:57

"""Migración de base de datos para bookings.
"""

from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("bookings", "0024_alter_actividadservicio_agencia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="boletoimportado",
            name="raw_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Hash SHA-256 para evitar duplicados.",
                max_length=64,
                null=True,
                verbose_name="Hash del Contenido",
            ),
        ),
    ]
