# Generated by Django 5.2.6 on 2026-05-18 15:41

"""Migración de base de datos para bookings.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("bookings", "0025_boletoimportado_raw_hash"),
        ("finance", "0011_alter_retencionislr_factura"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venta",
            name="factura_consolidada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings_ventas_facturadas",
                to="finance.factura",
                verbose_name="Factura Consolidada",
            ),
        ),
    ]
