# Generated by Django 5.2.6 on 2026-05-19 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0026_alter_venta_factura_consolidada"),
        ("core", "0031_agenciaconfiguracion_evolution_api_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoletoImportadoTransito",
            fields=[
                (
                    "id_transito",
                    models.AutoField(primary_key=True, serialize=False, verbose_name="ID Tránsito"),
                ),
                (
                    "ticket_index",
                    models.PositiveIntegerField(default=0, verbose_name="Índice de Ticket"),
                ),
                (
                    "nombre_pasajero",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Nombre Pasajero",
                    ),
                ),
                (
                    "numero_boleto",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Número de Boleto",
                    ),
                ),
                (
                    "datos_json",
                    models.JSONField(
                        help_text="Datos de ticket normalizados staged en tránsito.",
                        verbose_name="Datos Normalizados",
                    ),
                ),
                (
                    "procesado",
                    models.BooleanField(default=False, verbose_name="Procesado"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de Creación"),
                ),
                (
                    "agencia",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="core.agencia",
                    ),
                ),
                (
                    "boleto_origen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="splits_transito",
                        to="bookings.boletoimportado",
                        verbose_name="Boleto Origen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Boleto Importado en Tránsito",
                "verbose_name_plural": "Boletos Importados en Tránsito",
                "ordering": ["id_transito"],
                "indexes": [
                    models.Index(
                        fields=["agencia_id", "procesado"],
                        name="bookings_bo_agencia_58d9d4_idx",
                    ),
                    models.Index(
                        fields=["boleto_origen_id", "procesado"],
                        name="bookings_bo_boleto__e1c6ab_idx",
                    ),
                ],
            },
        ),
    ]
