# Generated by Django 5.2.6 on 2026-05-22 12:53

"""Migración de base de datos para bookings.
"""

from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("bookings", "0027_boletoimportadotransito"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="alerta_tl_disparada",
            field=models.BooleanField(
                default=False,
                help_text="Evita duplicidad de notificaciones del Time Limit.",
                verbose_name="Alerta de TL Disparada",
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="tiempo_limite_emision",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Fecha y hora límite de emisión dada por la aerolínea/consolidador.",
                null=True,
                verbose_name="Tiempo Límite de Emisión (TL)",
            ),
        ),
    ]
