# Generated by Django 5.2.6 on 2026-05-23 02:32

"""Migración de base de datos para bookings.
"""

from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("bookings", "0028_venta_alerta_tl_disparada_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="monto_neto_proveedor",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Lo que cobra el GDS/Consolidador.",
                max_digits=12,
                verbose_name="Monto Neto Proveedor",
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="monto_venta_cliente",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Lo que paga el cliente final.",
                max_digits=12,
                verbose_name="Monto Venta Cliente",
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="porcentaje_comision_agente",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Porcentaje Comisión Agente",
            ),
        ),
    ]
