# Generated by Django 5.2.6 on 2026-06-02 02:59

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0031_alter_actividadservicio_agencia_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="actividadservicio",
            managers=[
                ("with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="alojamientoreserva",
            managers=[
                ("with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="alquilerautoreserva",
            managers=[
                ("with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="boletoimportado",
            managers=[
                ("with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="comisionproveedorservicio",
            managers=[
                ("with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="eventoservicio",
            managers=[
                ("with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="feeventa",
            managers=[
                ("with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="itemventa",
            managers=[
                ("with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="productoservicio",
            managers=[
                ("with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="productoterrestre",
            managers=[
                ("with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="proveedor",
            managers=[
                ("with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="segmentovuelo",
            managers=[
                ("with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="trasladoservicio",
            managers=[
                ("with_deleted", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="venta",
            managers=[
                ("with_deleted", django.db.models.manager.Manager()),
            ],
        ),
    ]
