# Generated by Django 5.2.14 on 2026-06-08 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0034_alter_actividadservicio_table_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feeventa",
            name="venta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fees_venta",
                to="bookings.venta",
                verbose_name="Venta",
            ),
        ),
        migrations.AlterField(
            model_name="pagoventa",
            name="venta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pagos_venta",
                to="bookings.venta",
                verbose_name="Venta",
            ),
        ),
    ]
