# Generated by Django 5.2.14 on 2026-06-11 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0040_add_missing_indexes"),
        ("core", "0037_rename_remaining_core_tables"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="productoservicio",
                    name="requiere_datos_pasajero_especificos",
                    field=models.BooleanField(
                        default=False,
                        help_text="Ej. para boletos aéreos, seguros.",
                        verbose_name="Requiere Datos Específicos del Pasajero",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="actividadservicio",
            name="incluye",
            field=models.TextField(blank=True, verbose_name="Incluye"),
        ),
        migrations.AlterField(
            model_name="actividadservicio",
            name="no_incluye",
            field=models.TextField(blank=True, verbose_name="No Incluye"),
        ),
        migrations.AlterField(
            model_name="actividadservicio",
            name="notas",
            field=models.TextField(blank=True, verbose_name="Notas"),
        ),
        migrations.AlterField(
            model_name="alojamientoreserva",
            name="notas",
            field=models.TextField(blank=True, verbose_name="Notas"),
        ),
        migrations.AlterField(
            model_name="alojamientoreserva",
            name="regimen_alimentacion",
            field=models.CharField(
                blank=True,
                help_text="Ej: Desayuno, Media Pensión, Todo Incluido",
                max_length=30,
                verbose_name="Régimen Alimentación",
            ),
        ),
        migrations.AlterField(
            model_name="alquilerautoreserva",
            name="categoria_auto",
            field=models.CharField(blank=True, max_length=50, verbose_name="Categoría / Clase"),
        ),
        migrations.AlterField(
            model_name="alquilerautoreserva",
            name="compania_rentadora",
            field=models.CharField(blank=True, max_length=100, verbose_name="Compañía Rentadora"),
        ),
        migrations.AlterField(
            model_name="alquilerautoreserva",
            name="notas",
            field=models.TextField(blank=True, verbose_name="Notas"),
        ),
        migrations.AlterField(
            model_name="alquilerautoreserva",
            name="numero_confirmacion",
            field=models.CharField(blank=True, max_length=100, verbose_name="Número Confirmación"),
        ),
        migrations.AlterField(
            model_name="boletoimportado",
            name="aerolinea_emisora",
            field=models.CharField(blank=True, max_length=200, verbose_name="Aerolínea Emisora"),
        ),
        migrations.AlterField(
            model_name="boletoimportado",
            name="agente_emisor",
            field=models.CharField(blank=True, max_length=200, verbose_name="Agente Emisor"),
        ),
        migrations.AlterField(
            model_name="boletoimportado",
            name="direccion_aerolinea",
            field=models.TextField(blank=True, verbose_name="Dirección Aerolínea"),
        ),
        migrations.AlterField(
            model_name="boletoimportado",
            name="foid_pasajero",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="FOID/D.Identidad Pasajero"
            ),
        ),
        migrations.AlterField(
            model_name="boletoimportado",
            name="impuestos_descripcion",
            field=models.TextField(blank=True, verbose_name="Descripción Impuestos"),
        ),
        migrations.AlterField(
            model_name="boletoimportado",
            name="localizador_pnr",
            field=models.CharField(blank=True, max_length=20, verbose_name="Localizador (PNR)"),
        ),
        migrations.AlterField(
            model_name="boletoimportado",
            name="log_parseo",
            field=models.TextField(blank=True, verbose_name="Log del Parseo"),
        ),
        migrations.AlterField(
            model_name="boletoimportado",
            name="nombre_pasajero_completo",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Nombre Completo Pasajero (Original)"
            ),
        ),
        migrations.AlterField(
            model_name="boletoimportado",
            name="nombre_pasajero_procesado",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Nombre Pasajero (Procesado)"
            ),
        ),
        migrations.AlterField(
            model_name="boletoimportado",
            name="numero_boleto",
            field=models.CharField(blank=True, max_length=50, verbose_name="Número de Boleto"),
        ),
        migrations.AlterField(
            model_name="boletoimportado",
            name="raw_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Hash SHA-256 para evitar duplicados.",
                max_length=64,
                verbose_name="Hash del Contenido",
            ),
        ),
        migrations.AlterField(
            model_name="boletoimportado",
            name="ruta_vuelo",
            field=models.TextField(blank=True, verbose_name="Ruta del Vuelo (Itinerario)"),
        ),
        migrations.AlterField(
            model_name="boletoimportado",
            name="telegram_file_id",
            field=models.CharField(
                blank=True,
                help_text="ID del archivo en la nube de Telegram (para almacenamiento gratuito).",
                max_length=255,
                verbose_name="Telegram File ID",
            ),
        ),
        migrations.AlterField(
            model_name="boletoimportadotransito",
            name="nombre_pasajero",
            field=models.CharField(blank=True, max_length=150, verbose_name="Nombre Pasajero"),
        ),
        migrations.AlterField(
            model_name="boletoimportadotransito",
            name="numero_boleto",
            field=models.CharField(blank=True, max_length=50, verbose_name="Número de Boleto"),
        ),
        migrations.AlterField(
            model_name="circuitodia",
            name="actividades_resumen",
            field=models.TextField(blank=True, verbose_name="Actividades/Resumen"),
        ),
        migrations.AlterField(
            model_name="circuitodia",
            name="alojamiento_previsto",
            field=models.CharField(blank=True, max_length=255, verbose_name="Alojamiento Previsto"),
        ),
        migrations.AlterField(
            model_name="circuitodia",
            name="descripcion",
            field=models.TextField(blank=True, verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="circuitodia",
            name="titulo",
            field=models.CharField(blank=True, max_length=255, verbose_name="Título del Día"),
        ),
        migrations.AlterField(
            model_name="circuitoturistico",
            name="descripcion_general",
            field=models.TextField(blank=True, verbose_name="Descripción General"),
        ),
        migrations.AlterField(
            model_name="circuitoturistico",
            name="incluye",
            field=models.TextField(blank=True, verbose_name="Incluye"),
        ),
        migrations.AlterField(
            model_name="circuitoturistico",
            name="no_incluye",
            field=models.TextField(blank=True, verbose_name="No Incluye"),
        ),
        migrations.AlterField(
            model_name="eventoservicio",
            name="codigo_boleto_evento",
            field=models.CharField(blank=True, max_length=100, verbose_name="Código Boleto / Ref"),
        ),
        migrations.AlterField(
            model_name="eventoservicio",
            name="notas",
            field=models.TextField(blank=True, verbose_name="Notas"),
        ),
        migrations.AlterField(
            model_name="eventoservicio",
            name="ubicacion",
            field=models.CharField(blank=True, max_length=255, verbose_name="Ubicación"),
        ),
        migrations.AlterField(
            model_name="eventoservicio",
            name="zona_asiento",
            field=models.CharField(blank=True, max_length=100, verbose_name="Zona/Asiento"),
        ),
        migrations.AlterField(
            model_name="feeventa",
            name="descripcion",
            field=models.CharField(blank=True, max_length=200, verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="hoteltarifario",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
        migrations.AlterField(
            model_name="itemventa",
            name="codigo_reserva_proveedor",
            field=models.CharField(
                blank=True,
                max_length=50,
                verbose_name="Código Reserva Proveedor (PNR, Localizador)",
            ),
        ),
        migrations.AlterField(
            model_name="itemventa",
            name="descripcion_personalizada",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Descripción Personalizada"
            ),
        ),
        migrations.AlterField(
            model_name="itemventa",
            name="notas_item",
            field=models.TextField(blank=True, verbose_name="Notas del Item"),
        ),
        migrations.AlterField(
            model_name="pagoventa",
            name="notas",
            field=models.TextField(blank=True, verbose_name="Notas"),
        ),
        migrations.AlterField(
            model_name="pagoventa",
            name="referencia",
            field=models.CharField(blank=True, max_length=100, verbose_name="Referencia"),
        ),
        migrations.AlterField(
            model_name="paqueteaereo",
            name="nombre_paquete",
            field=models.CharField(blank=True, max_length=255, verbose_name="Nombre Paquete"),
        ),
        migrations.AlterField(
            model_name="paqueteaereo",
            name="observaciones",
            field=models.TextField(blank=True, verbose_name="Observaciones"),
        ),
        migrations.AlterField(
            model_name="productoservicio",
            name="codigo_interno",
            field=models.CharField(
                blank=True, max_length=50, unique=True, verbose_name="Código Interno"
            ),
        ),
        migrations.AlterField(
            model_name="productoservicio",
            name="descripcion",
            field=models.TextField(blank=True, verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="productoterrestre",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productos_terrestres",
                to="core.agencia",
            ),
        ),
        migrations.AlterField(
            model_name="productoterrestre",
            name="descripcion_publica",
            field=models.TextField(blank=True, verbose_name="Descripción (Pública)"),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="alias",
            field=models.CharField(
                blank=True,
                help_text="Nombre con el que es conocido en el mercado",
                max_length=150,
                verbose_name="Alias/Nombre Comercial",
            ),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="condiciones_pago",
            field=models.CharField(blank=True, max_length=100, verbose_name="Condiciones de Pago"),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="contacto_nombre",
            field=models.CharField(blank=True, max_length=100, verbose_name="Nombre de Contacto"),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="contacto_telefono",
            field=models.CharField(blank=True, max_length=30, verbose_name="Teléfono de Contacto"),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="datos_bancarios",
            field=models.TextField(blank=True, verbose_name="Datos Bancarios del Proveedor"),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="direccion",
            field=models.CharField(blank=True, max_length=255, verbose_name="Dirección"),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="iata",
            field=models.CharField(blank=True, max_length=10, verbose_name="IATA"),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="notas",
            field=models.TextField(blank=True, verbose_name="Notas sobre el Proveedor"),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="numero_cuenta_agencia",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Número de Cuenta/IATA con el Proveedor"
            ),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="office_id_amadeus",
            field=models.CharField(blank=True, max_length=10, verbose_name="Office ID AMADEUS"),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="office_id_expedia",
            field=models.CharField(blank=True, max_length=10, verbose_name="Office ID EXPEDIA"),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="office_id_hotelbeds",
            field=models.CharField(blank=True, max_length=10, verbose_name="Office ID HOTEL BEDS"),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="office_id_kiu",
            field=models.CharField(blank=True, max_length=8, verbose_name="Office ID KIU"),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="office_id_travelport",
            field=models.CharField(blank=True, max_length=10, verbose_name="Office ID TRAVELPORT"),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="rif",
            field=models.CharField(
                blank=True,
                help_text="Registro de Información Fiscal",
                max_length=20,
                verbose_name="RIF",
            ),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="seudo_sabre",
            field=models.CharField(blank=True, max_length=4, verbose_name="Seudo SABRE"),
        ),
        migrations.AlterField(
            model_name="segmentovuelo",
            name="aerolinea",
            field=models.CharField(blank=True, max_length=80, verbose_name="Aerolínea"),
        ),
        migrations.AlterField(
            model_name="segmentovuelo",
            name="cabina",
            field=models.CharField(
                blank=True,
                help_text="Ej: Economy, Business, First",
                max_length=20,
                verbose_name="Cabina",
            ),
        ),
        migrations.AlterField(
            model_name="segmentovuelo",
            name="clase_reserva",
            field=models.CharField(blank=True, max_length=5, verbose_name="Clase"),
        ),
        migrations.AlterField(
            model_name="segmentovuelo",
            name="notas",
            field=models.TextField(blank=True, verbose_name="Notas"),
        ),
        migrations.AlterField(
            model_name="segmentovuelo",
            name="numero_vuelo",
            field=models.CharField(blank=True, max_length=20, verbose_name="Número de Vuelo"),
        ),
        migrations.AlterField(
            model_name="servicioadicionaldetalle",
            name="codigo_referencia",
            field=models.CharField(blank=True, max_length=100, verbose_name="Código Referencia"),
        ),
        migrations.AlterField(
            model_name="servicioadicionaldetalle",
            name="descripcion",
            field=models.CharField(blank=True, max_length=255, verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="servicioadicionaldetalle",
            name="nombre_pasajero",
            field=models.CharField(blank=True, max_length=150, verbose_name="Nombre Pasajero"),
        ),
        migrations.AlterField(
            model_name="servicioadicionaldetalle",
            name="notas",
            field=models.TextField(blank=True, verbose_name="Notas"),
        ),
        migrations.AlterField(
            model_name="tarifarioproveedor",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
        migrations.AlterField(
            model_name="tipohabitacion",
            name="hotel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tipos_habitacion",
                to="bookings.hoteltarifario",
            ),
        ),
        migrations.AlterField(
            model_name="trasladoservicio",
            name="destino",
            field=models.CharField(blank=True, max_length=150, verbose_name="Destino"),
        ),
        migrations.AlterField(
            model_name="trasladoservicio",
            name="notas",
            field=models.TextField(blank=True, verbose_name="Notas"),
        ),
        migrations.AlterField(
            model_name="trasladoservicio",
            name="origen",
            field=models.CharField(blank=True, max_length=150, verbose_name="Origen"),
        ),
        migrations.AlterField(
            model_name="venta",
            name="descripcion_general",
            field=models.TextField(blank=True, verbose_name="Descripción General de la Venta"),
        ),
        migrations.AlterField(
            model_name="venta",
            name="notas",
            field=models.TextField(blank=True, verbose_name="Notas de la Venta"),
        ),
        migrations.AlterField(
            model_name="ventaauditfinding",
            name="nota_resolucion",
            field=models.TextField(blank=True, verbose_name="Nota de Resolución"),
        ),
        migrations.AlterField(
            model_name="ventaparsemetadata",
            name="amount_consistency",
            field=models.CharField(blank=True, max_length=15, verbose_name="Consistencia Montos"),
        ),
        migrations.AlterField(
            model_name="ventaparsemetadata",
            name="currency",
            field=models.CharField(blank=True, max_length=10, verbose_name="Moneda"),
        ),
        migrations.AlterField(
            model_name="ventaparsemetadata",
            name="fuente",
            field=models.CharField(
                blank=True,
                help_text="Ej: SABRE, KIU, AMADEUS, IMPORT_MANUAL",
                max_length=50,
                verbose_name="Fuente / Origen",
            ),
        ),
        migrations.AlterModelTable(
            name="ventaauditfinding",
            table=None,
        ),
    ]
