# Generated by Django 5.2.14 on 2026-06-24 17:56

"""Migración de base de datos para bookings.
"""

from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("bookings", "0042_alter_actividadservicio_incluye_and_more"),
        ("common", "0004_alter_aerolinea_table_alter_ciudad_table_and_more"),
        ("core", "0043_alter_usuarioagencia_agencia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boletoimportado",
            name="raw_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Hash SHA-256 para evitar duplicados.",
                max_length=64,
                null=True,
                verbose_name="Hash del Contenido",
            ),
        ),
        migrations.AlterField(
            model_name="boletoimportado",
            name="telegram_file_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ID del archivo en la nube de Telegram (para almacenamiento gratuito).",
                max_length=255,
                null=True,
                verbose_name="Telegram File ID",
            ),
        ),
        migrations.AlterField(
            model_name="itemventa",
            name="codigo_reserva_proveedor",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                null=True,
                verbose_name="Código Reserva Proveedor (PNR, Localizador)",
            ),
        ),
        migrations.AlterField(
            model_name="itemventa",
            name="descripcion_personalizada",
            field=models.CharField(
                blank=True,
                default="",
                max_length=500,
                null=True,
                verbose_name="Descripción Personalizada",
            ),
        ),
        migrations.AlterField(
            model_name="itemventa",
            name="notas_item",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Notas del Item"
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="notas",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Notas de la Venta"
            ),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="pagoventa",
                    index=models.Index(fields=["creado"], name="idx_pagoventa_creado"),
                ),
            ],
            database_operations=[],
        ),
    ]
