# Generated by Django 5.2.14 on 2026-06-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0044_boletoimportado_email_message_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ventaparsemetadata",
            options={
                "ordering": ["-creado"],
                "verbose_name": "Metadatos de Parseo (Venta)",
                "verbose_name_plural": "Metadatos de Parseo (Ventas)",
            },
        ),
        migrations.RemoveConstraint(
            model_name="boletoimportado",
            name="uq_boleto_agencia_message_id",
        ),
        migrations.RemoveField(
            model_name="boletoimportado",
            name="email_message_id",
        ),
        migrations.AlterField(
            model_name="boletoimportado",
            name="formato_detectado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PDF_KIU", "PDF (KIU)"),
                    ("PDF_SAB", "PDF (Sabre)"),
                    ("PDF_AMA", "PDF (Amadeus)"),
                    ("TXT_KIU", "TXT (KIU)"),
                    ("TXT_SAB", "TXT (Sabre)"),
                    ("TXT_AMA", "TXT (Amadeus)"),
                    ("EML_KIU", "EML (KIU)"),
                    ("EML_GEN", "EML (General)"),
                    ("EMA_AUTO", "Email (Auto-detectado)"),
                    ("PDF_AUTO", "PDF (Auto-detectado)"),
                    ("OTR", "Otro/Desconocido"),
                    ("ERR", "Error de Formato"),
                ],
                default="OTR",
                max_length=20,
                verbose_name="Formato Detectado",
            ),
        ),
        migrations.AlterModelTable(
            name="ventaparsemetadata",
            table="core_ventaparsemetadata",
        ),
    ]
