# Generated by Django 5.2.14 on 2026-07-09 13:07

"""Migración de base de datos para bookings.
"""

from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("bookings", "0045_alter_ventaparsemetadata_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ventaparsemetadata",
            options={
                "ordering": ["-creado"],
                "verbose_name": "Metadata de Parseo de Venta",
                "verbose_name_plural": "Metadata de Parseo de Ventas",
            },
        ),
        migrations.AlterField(
            model_name="boletoimportado",
            name="formato_detectado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PDF_KIU", "PDF (KIU)"),
                    ("PDF_SAB", "PDF (Sabre)"),
                    ("PDF_AMA", "PDF (Amadeus)"),
                    ("TXT_KIU", "TXT (KIU)"),
                    ("TXT_SAB", "TXT (Sabre)"),
                    ("TXT_AMA", "TXT (Amadeus)"),
                    ("EML_KIU", "EML (KIU)"),
                    ("EML_GEN", "EML (General)"),
                    ("OTR", "Otro/Desconocido"),
                    ("ERR", "Error de Formato"),
                ],
                default="OTR",
                max_length=20,
                verbose_name="Formato Detectado",
            ),
        ),
        migrations.AlterModelTable(
            name="ventaparsemetadata",
            table=None,
        ),
    ]
