# Generated by Django 5.2.14 on 2026-07-15 13:30

"""Migración de base de datos para bookings.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("bookings", "0047_componentes_cascade_to_set_null"),
        ("core", "0053_ssoprovider"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecuenciaVentaDiaria",
            fields=[
                ("id_secuencia", models.AutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateField(db_index=True, verbose_name="Fecha")),
                (
                    "contador",
                    models.PositiveIntegerField(default=0, verbose_name="Contador"),
                ),
                (
                    "agencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="core.agencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Secuencia de Venta Diaria",
                "verbose_name_plural": "Secuencias de Ventas Diarias",
                "db_table": "bookings_secuencia_venta_diaria",
                "unique_together": {("agencia", "fecha")},
            },
        ),
    ]
