# Generated by Django 5.2.14 on 2026-08-17 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0051_ventamensaje_mensajeadjunto"),
        ("core", "0060_webhookdelivery_agencia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="boletoimportado",
            name="datos_parseados_actualizado",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha de última actualización de los datos parseados",
                null=True,
                verbose_name="Datos Parseados Actualizado",
            ),
        ),
        migrations.AddField(
            model_name="boletoimportado",
            name="datos_parseados_version",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Versión de los datos parseados (incrementa en cada re-parseo)",
                verbose_name="Versión Datos Parseados",
            ),
        ),
        migrations.AddField(
            model_name="comisionproveedorservicio",
            name="notas",
            field=models.TextField(blank=True, default="", verbose_name="Notas"),
        ),
        migrations.AlterField(
            model_name="pagoventa",
            name="metodo",
            field=models.CharField(
                choices=[
                    ("EFE", "Efectivo"),
                    ("TAR", "Tarjeta"),
                    ("TRF", "Transferencia"),
                    ("ZEL", "Zelle"),
                    ("PPL", "PayPal"),
                    ("SAF", "Saldo a Favor / Billetera"),
                    ("OTR", "Otro"),
                ],
                default="TRF",
                max_length=3,
                verbose_name="Método",
            ),
        ),
        migrations.AlterField(
            model_name="productoterrestre",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
        migrations.AlterField(
            model_name="tarifahabitacion",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
    ]
