# Generated by Django 5.0.2 on 2026-04-02 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Articulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255, verbose_name="Título")),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "resumen",
                    models.TextField(blank=True, null=True, verbose_name="Resumen"),
                ),
                ("contenido", models.TextField(verbose_name="Contenido (Markdown)")),
                (
                    "destino",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Destino Relacionado"
                    ),
                ),
                ("generado_por_ia", models.BooleanField(default=False)),
                ("prompt_ia", models.TextField(blank=True, null=True)),
                ("meta_titulo", models.CharField(blank=True, max_length=255)),
                ("meta_descripcion", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BOR", "Borrador"),
                            ("PUB", "Publicado"),
                            ("ARC", "Archivado"),
                        ],
                        default="BOR",
                        max_length=3,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_publicacion", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Artículo",
                "verbose_name_plural": "Artículos",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="GuiaDestino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre del Destino"),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción General")),
                (
                    "mejor_epoca",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Mejor época para viajar",
                    ),
                ),
                (
                    "requisitos_visa",
                    models.TextField(blank=True, verbose_name="Requisitos de Visa"),
                ),
                ("idioma", models.CharField(default="Español", max_length=50)),
                ("moneda_local", models.CharField(blank=True, max_length=50)),
                ("imagen_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Guía de Destino",
                "verbose_name_plural": "Guías de Destino",
            },
        ),
        migrations.CreateModel(
            name="PostRedesSociales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plataforma",
                    models.CharField(
                        choices=[
                            ("INS", "Instagram"),
                            ("FAC", "Facebook"),
                            ("TEL", "Telegram"),
                            ("LIN", "LinkedIn"),
                            ("TWI", "Twitter/X"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "contenido",
                    models.TextField(verbose_name="Contenido del Post (Caption)"),
                ),
                ("hashtags", models.CharField(blank=True, max_length=255)),
                ("fecha_programada", models.DateTimeField(blank=True, null=True)),
                ("publicado", models.BooleanField(default=False)),
                (
                    "articulo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts_redes",
                        to="cms.articulo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post en Red Social",
                "verbose_name_plural": "Posts en Redes Sociales",
            },
        ),
    ]
