# Generated by Django 5.2.6 on 2026-05-28 10:15

"""Migración de base de datos para cms.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration:
    """Clase Migration. Uso: según contexto de la aplicación.
    """
    dependencies = [
        ("cms", "0003_alter_articulo_agencia_alter_guiadestino_agencia_and_more"),
        ("core", "0034_alter_anulacionboleto_agencia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articulo",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
        migrations.AlterField(
            model_name="guiadestino",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
        migrations.AlterField(
            model_name="postredessociales",
            name="agencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="core.agencia",
            ),
        ),
    ]
